### ISSUE TITLE
Add screen_name to user type when OAuth is done via Twitter

### ISSUE THREAD

**Issue by jay-dee7** [auth0/auth0-spa-js#1014]
### Describe the problem you'd like to have solved

I can clearly see `screen_name` as a field in raw JSON tab when a user logs in via Auth0 + Twitter OAuth2.0. However, this field is absent from the `User` type we have here https://github.com/auth0/auth0-spa-js/blob/master/src/global.ts#L604

![SCR-20221006-pqf](https://user-images.githubusercontent.com/10788442/194319674-81e75557-d4eb-4a0a-87fa-6ab1b9b75c16.png)

### Describe the ideal solution

Add an optional field of `screen_name` to `User` type populate this field when the authentication provider is Twitter.

## Alternatives and current work-arounds
Current workaround we have had to do is create an API especially for fetching the Twitter user handle. It would be amazing if the `getUser` could just return this value since this value is clearly present in the response

**Comment by frederikprijck** [comment]
Hey,

The user object should support any arbitrary properties. Even more so, you can use

```
class MyUser extends User {
  screen_name: string;
}

client.getUser<MyUser>();
```

But even without that, `User` supports any additional claims. Does it exist on the user if you use:
```
const user = await client.getUser();
console.log(user.screen_name);
```
If not, there is probably something else at play. Regardless, our SDK should not be limiting you to default properties on the user.

**Comment by frederikprijck** [comment]
Closing, feel free to reply and can open if needed.

**Comment by jay-dee7** [comment]
Hey @frederikprijck I did try extending the user the way you described but it didn't work for me. `screen_name` came out as `undefined`. 
When I do the request with or without the extended type, it only has the following fields:

```json
{
  "name": "Jasdeep Singh"
  "nickname": "Jasdeep Singh"
  "picture": "<img_url>"
  "sub": "twitter|<user_id>"
  "updated_at": "2022-10-12T08:28:20.924Z"
}
```

I am using `openid profile` as scopes.

**Comment by frederikprijck** [comment]
I believe this is not an issue with our SDK. If `screen_name` isn't present in the token, our SDK will not be able to read it.

What you want to achieve is ensure your Id token gets populated with the neccesary additional claims through the use of a Rule or Action. Once the claims exist in the token, our SDK will pick it up.

Using Actions: https://auth0.com/blog/adding-custom-claims-to-id-token-with-auth0-actions/

This seems somewhat related, even tho I believe it's the other way around. Regardless I wanted to share this in case it would be of any use: https://auth0.com/docs/authenticate/identity-providers/pass-parameters-to-idps#example-twitter.
