### ISSUE TITLE
Error parsing redirect: Error: Invalid state

### ISSUE THREAD

**Issue by jerryzhao0423** [auth0/auth0-spa-js#1015]
### Describe the problem
My app is built with Angular and having this error when doing `handleRedirectCallback()`,
```
Error parsing redirect: Error: Invalid state
    at e.<anonymous> (auth0-spa-js.production.esm.js:15:84048)
    at auth0-spa-js.production.esm.js:15:2236
    at Object.next (auth0-spa-js.production.esm.js:15:1552)
    at auth0-spa-js.production.esm.js:15:1278
    at new ZoneAwarePromise (zone.js:1351:1)
    at o (auth0-spa-js.production.esm.js:15:1023)
    at e.handleRedirectCallback (auth0-spa-js.production.esm.js:15:83485)
```
I read through about this issue #245 and I think the issue is coming back after version upgrades.
I tried with `1.2.4` and `1.3.2` and this error didn't happen but it happens with the latest version `1.22.4`.
Can you help check about it and fix it?

### What was the expected behavior?
After handleRedirect the user can successful login.

### Reproduction
1. Automatically call `loginWithRedirect` when landing on the page
2. Continue with Google
3. Upon return to the application, the error occurs in the console.

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

### Environment

- **Version of `auth0-spa-js` used: 1.22.4**
- **Which browsers have you tested in? Chrome & Firefox(Windows)**
- **Which framework are you using, if applicable (Angular, React, etc): Angular**
- **Other modules/plugins/libraries that might be involved: n/a**

**Comment by frederikprijck** [comment]
Hello,

Can you please provide a reproduction for this? This shouldnt happen unless something weird is going on. But nothing in the steps you mention would indicate that behavior.

Thanks.

**Comment by jerryzhao0423** [comment]
@frederikprijck Thanks for the replying. I was able to find and fix the issue while I prepared a sample code.

**Comment by RosarioAleCali** [comment]
> @frederikprijck Thanks for the reply. I was able to find and fix the issue while I prepared a sample code.

Would you be able to share what was the fix? I might be experiencing the same problem right now.

**Comment by jerryzhao0423** [comment]
@RosarioAleCali I can't really remember the exact fix now. But I can provide my current working code below:
````
async getAuth0Token(options,type,redirected){
  const auth0 = await createAuth0Client(options);
  const isAuthenticated = await auth0.isAuthenticated();
  if (type === 'loginWithRedirect'){
    if (redirected){
       try{
          localStorage.removeItem('loggedIn);
          await auth0.handleRedirectCallback();
          window.history.replaceState({}, document.title, window.location.pathname);
          const newToken = await auth0.getIdTokenClaims();
          return newToken.__raw;
       }catch(err){}
    }else if (isAuthenticated){
      const newToken = await auth0.getIdTokenClaims();
      return newToken.__raw;
    } else {
       try {
          localstorage.setItem('redirectStart', '1');
          await auth0.loginWithRedirect();
          return;
       }catch(err){}
    }   
  } else {
     try {
       await auth0.getTokenSilently();
     }catch(err){
       return 'login failed'
     }
     const claims = await auth0.getIdTokenClaims();
     return cliams.__raw;
  }
}
````
