### ISSUE TITLE
Verifying the idToken isn't processed for getTokenUsingRefreshToken anymore

### ISSUE THREAD

**Issue by dandob74** [auth0/auth0-spa-js#1041]
Hey, 
I am struggling with the "validation" of the idToken by using refresh tokens.

In Release 1.22.5 the idToken was verified within the Auth0Client.ts in method _getTokenUsingRefreshToken (via this._verifyIdToken).
In Release 2.0.0 the idToken isn't verified anymore. At least not in the _getTokenUsingRefreshToken method.

I have the following issues now in Release 2.0.0:
- Calling isAuthenticated() returns true even if the idToken has been expired.
- Calling getTokenSilently() won't return a new idToken even if the idToken has been expired.

Did I get something wrong here?

Thanks for your help
Daniel

**Comment by frederikprijck** [comment]
Thanks for reaching out.

An Id token is used to initially tell the application who the user is. Its expiration doesn't impact the authentication state of the user in a Single Page Application.

For our SDK, a user is considered authenticated if we have an Id token, even if it's expired. However, as soon as we no longer have a valid access token, and we are unable to retrieve a new one from Auth0, we will remove the Id token and consider the user not authenticated anymore.

> Calling getTokenSilently() won't return a new idToken even if the idToken has been expired.

This should mean the expiration of the id token is lower than the expiration of the access token. As soon as the access token is expired, we should also fetch a new id token. If that's not happening, that would be a bug we need to investigate. Can you verify the expiration of the id token is indeed lower than the access token's expiration?

**Comment by dandob74** [comment]
Hey,
thanks for getting back to me. 
Yep, you are right, in my case the accessToken lives indeed longer than the idToken.

But, I am 99.99% sure that we will get a new accessToken when the expiration of the idToken is expired, even if the access Token is still valid for V 1.22.X. This behavior is gone in V2.

I had a short look into the code. Could the changed cache handling leads to this "new" behavior?

In V1.22 the exp value of the idToken is taken into consideration in the [wrapCacheEntry](https://github.com/auth0/auth0-spa-js/blob/v1.22.5/src/cache/cache-manager.ts#L119) in the CacheManager:

```
const expirySeconds = Math.min(
  expiresInTime,
  entry.decodedToken.claims.exp // <= expiration of the ID Token
);
```

In V2 the expiration value of the **idToken** isn't used anymore here.


Thanks again for your help,
Daniel

**Comment by frederikprijck** [comment]
> But, I am 99.99% sure that we will get a new accessToken when the expiration of the idToken is expired, even if the access Token is still valid for V 1.22.X. This behavior is gone in V2.

That's correct. We should not refresh the Access Token when the ID Token is expired, as the ID Token has no influence on the expiration and validity of the Access Token. 

We removed this as part of https://github.com/auth0/auth0-spa-js/pull/967, as you can see it's called out explicitly in the PR to remove that check explicitly. 

What's the use case for using id token's with an expiration that's lower than the access token?

**Comment by dandob74** [comment]
Thanks for the quick response! 
You're totally right, it makes no sense to automatically refresh a valid accessToken, when only the idToken has been expired.
To be honest, I wasn't aware of #967, which describes the changes in depth. 
I used this "automatic" refreshing to get updated idToken-data of the current user, as we use short living idTokens in our app. 
I will change my code as needed, and I am totally fine how the SDK behaves in 2.0. 
Thanks a lot for your time and detailed explanations. 
Sorry for any inconveniences,
Daniel
