### ISSUE TITLE
Cannot handle login required error when refresh token expires

### ISSUE THREAD

**Issue by chriskuech** [auth0/auth0-spa-js#1042]
### Describe the problem you'd like to have solved

We are getting bugs from users complaining that the app fails if they keep their browser tab open for 12+ hours because the refresh token expires under the hood.  I want to handle this error and execute some code (logging out the user from the app).

### Describe the ideal solution

Ideally, auth0 exposes the `MissingRefreshTokenError` error for us to handle in our code, though it appears internally you handle by checking error structure with an unexposed constant.

## Alternatives and current work-arounds

Alternative solution could be proactively checking the refresh token (#813)

We currently have no workarounds, so any would be appreciated.

**Comment by frederikprijck** [comment]
Thanks for reaching out, can you elaborate on what it means for the application for fail?

Typically our SDK should be able to handle when the refresh token expired. What happens in that case is, when you call `getTokenSIlently`, it will try get a new token. If it can't it will throw a `login_required`, `invalid_grant` or any error returned by Auth0 indicating we were unable to retrieve a new pair of tokens.

That error should typically allow you to react accordingly and log the user in again. Our SDK should already log the user out internally in the SDK when these errors occur.

**Comment by frederikprijck** [comment]
Exported it in https://github.com/auth0/auth0-spa-js/pull/1043, thanks for reporting that!

**Comment by chriskuech** [comment]
@frederikprijck thank you for the diligent solution!
