### ISSUE TITLE
`isAuthenticated()` returns false even though the token is still valid

### ISSUE THREAD

**Issue by schester44** [auth0/auth0-spa-js#1053]
Having trouble tracking this one down so figured i'd reach out to see if anyone has any idea what is going on here.

A small subset of our users are having their token removed from localStorage even though the token's exp value is a month out.

A few details of our integration:

- We're using localStorage for our cacheLocation.
- We're using Resource Owner Password Flow and calling `auth0client.cacheManager.set(token)` for setting the token.
- isAuthenticated initially returns true but at some point the token is removed
  - logging the token value when this occurs, we're able to see that the token doesn't expire anytime soon.

We're obviously somewhat hacking things together by calling cacheManager.set(token)` and using a token that is returned from our server so i'm wondering if there is a better way to go about using this lib with resource owner password flow or if anyone has any tips for figuring out why the localStorage token is being removed.

For the small subset of users that this affects, we're finding that the token stays in localStorage for some time (10 mins or so) before being removed. No consistent patterns in browsers. We're seeing chrome/windows and safar/osx being affected.

**Comment by frederikprijck** [comment]
Thanks for reaching out. This SDK does not support the Resource Owner flow and there are currently no plans to support this.

We recommend still using this SDK, but rely on it using the Authorization Code flow. 

We definetly do not encourage using the cacheManager like that, neither is this a situation we can realy support. Our SDK is mainly used to retrieve the tokens using the Authorization Code flow internally, if you do not want to use that you shouldnt try and rely on our SDK only to handle the state. Our SDK also has built in logic to try and refresh the token, which might also behave weird as well.

Even thought I still encourage looking into using this SDK properly, if you do need to use the Resource Owner Grant, you can have a look at https://github.com/auth0/auth0.js.
