### ISSUE TITLE
Module '"@auth0/auth0-spa-js"' has no exported member 'createAuth0Client'

### ISSUE THREAD

**Issue by PhentomPT** [auth0/auth0-spa-js#1054]
### Describe the problem

`Module '"@auth0/auth0-spa-js"' has no exported member 'createAuth0Client'. Did you mean to use 'import createAuth0Client from "@auth0/auth0-spa-js"' instead?ts(2614)`

### What was the expected behavior?

Be able to import createAuth0Client from @auth0/auth0-spa-js

### Environment
auth0-spa-js version 2.0.0
Vue version 3.2.45 with TS

**Comment by frederikprijck** [comment]
Thanks for reaching out.

Did you take a look at the [Migration Guide](https://github.com/auth0/auth0-spa-js/blob/master/MIGRATION_GUIDE.md), more specifically, the section that covers the fact that we [dropped the default export](https://github.com/auth0/auth0-spa-js/blob/master/MIGRATION_GUIDE.md#no-more-default-export)?

You'll want to use:

```ts
import { createAuth0Client } from "@auth0/auth0-spa-js";
```

Would that help?

**Comment by PhentomPT** [comment]
> 

i have also used `import { createAuth0Client } from "@auth0/auth0-spa-js";` that i saw on the README but it give an error that it is not being exported

**Comment by PhentomPT** [comment]
After a second look at it, it seems like the import comes true when i use it in a .ts file but not in a .vue file (inside script setup lang="ts")

**Comment by frederikprijck** [comment]
I tried reproducing this but was unable. I tried the following:

- npm init vue@latest
- npm i @auth0/auth0-spa-js

Then update App.vue:

```
<script setup lang="ts">
import { RouterLink, RouterView } from "vue-router";
import HelloWorld from "./components/HelloWorld.vue";
import { createAuth0Client } from "@auth0/auth0-spa-js";

async function init() {
  console.log(await createAuth0Client({ clientId: "", domain: "" }));
}

init();
</script>
```
And the console logs the created instance as expected:
![image](https://user-images.githubusercontent.com/2146903/205018672-41b9c893-e587-489f-9bc7-63fee97f0e5c.png)


Everything seems to work as expected, would there be anything on your end that could be causing this?

**Comment by PhentomPT** [comment]
> I tried reproducing this but was unable. I tried the following:
> 
> * npm init vue@latest
> * npm i @auth0/auth0-spa-js
> 
> Then update App.vue:
> 
> ```
> <script setup lang="ts">
> import { RouterLink, RouterView } from "vue-router";
> import HelloWorld from "./components/HelloWorld.vue";
> import { createAuth0Client } from "@auth0/auth0-spa-js";
> 
> async function init() {
>   console.log(await createAuth0Client({ clientId: "myClientId", domain: "myDomain" }));
> }
> 
> init();
> </script>
> ```
> 
> And the console logs the created instance as expected: ![image](https://user-images.githubusercontent.com/2146903/205018672-41b9c893-e587-489f-9bc7-63fee97f0e5c.png)
> 
> Everything seems to work as expected, would there be anything on your end that could be causing this?

Also tried a new project and works well 👍
Something must be wrong on the other project, thank you for the clearing things up!

**Comment by JulienCorb** [comment]
Having the same issue : `import { createAuth0Client } from "@auth0/auth0-spa-js"` in a `.ts` file, 

`Attempted import error: 'createAuth0Client' is not exported from '@auth0/auth0-spa-js' (imported as 'createAuth0Client').` when building.
