### ISSUE TITLE
Invalid State error with Nuxt, custom callback page and url-encoded characters

### ISSUE THREAD

**Issue by johannes-wtfoxtrot** [auth0/auth0-spa-js#1060]
### Describe the problem

I tried to implement a custom callback URL to allow for adjusted error handling in a Nuxt.js SPA.
Long story short: Nuxt.js seams to normalize the URL and to replace `%3D` by `=` in `location.href`.

Using the Vue.js integration works when using `createAuth0` as `handleRedirectCallback` is called _before_ that normalization.
When calling `handleRedirectCallback` from inside a Vue.js component that normalization has happened and the replacement causes the state from the transaction to not match that from the URL.

I believe this to be an error in auth0-spa-js due to the way it reads the URL.
The `Invalid State` error should happen whenever `=` characters are encoded in the state and those characters are replaced by anything before `handleRedirectCallback` is called.

**What I found out about the auth0 implementation:**

The `Invalid State` error is thrown in https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L513.
Key and Value of the URL are parsed by using `.split('=')` in https://github.com/auth0/auth0-spa-js/blob/master/src/utils.ts#L24.

💡 Reading the value by `new URL(location.href).searchParams.get('state')` gives the full value including trailing `'=='`.

`=` chars in the value should be very common, as the values are just base64 encoded random strings ( https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L293 ).

### What was the expected behavior?

The auth0 SDK should not fail if any middleware replaces query parameters by their URL-Decoded representation. This replacement might be done for human readability.

### Reproduction

- Try to Login via the Auth0 SDK
- Replace `%3D` with `=` in the URL before calling `handleRedirectCallback`
- call `handleRedirectCallback`

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

### Environment

- **Version of `auth0-spa-js` used:** 1.22.5 (but behaviour shouldn't be changed as the respective code stayed the same) 
- **Which browsers have you tested in?**  Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** Vue.js with Nuxt 3
- **Other modules/plugins/libraries that might be involved:** @auth0/auth0-vue

**Comment by frederikprijck** [comment]
Thanks for reaching out. I will need to look into this, but I believe it makes sense to see if we can improve the way we read the query string, especially now that we have dropped support for IE in v2, we should be able to solve this in v2.

Auth0-Vue v2, which uses Auth0-SPA-JS v2, has been released in beta, and should be GA somewhere in January 2023. If we would patch this in Auth0-SPA-JS v2, it would also be picked up by Auth0-Vue v2 (beta).

**Comment by frederikprijck** [comment]
After taken a quick look, I do want to mention that by replacing `=` with `%3D` in the URL when calling `handleRedirectCallback`, I am not getting the `Invalid State` error, instead I get a different error.

Can you elaborate on what you are exactly doing that gives you this error? Idealy, a reproduction would be helpful, making it easier for us to see if it works with Nuxt. Even though we have no official Nuxt support, I am more than happy to try and see what we can do to make it work.

**Comment by frederikprijck** [comment]
I opened a [PR](https://github.com/auth0/auth0-spa-js/pull/1061) to address this, any chance you can give this a try to see if it works for you?

**Comment by johannes-wtfoxtrot** [comment]
Hi @frederikprijck.

I will not be able to test the code until the end of the year, but the code looks good to me and should fix the issue.

I would suggest du add two assertions to ensure it works independent of encoding
```
      expect(
        parseAuthenticationResult('code=test&state=another-test==')
      ).toMatchObject({
        code: 'test',
        state: 'another-test=='
      });
    });

      expect(
        parseAuthenticationResult('code=test&state=another-test%3D%3D')
      ).toMatchObject({
        code: 'test',
        state: 'another-test=='
      });
    });
```

or

```
      expect(
        parseAuthenticationResult('code=test&state=another-test==')
      ).toEqual(
        parseAuthenticationResult('code=test&state=another-test%3D%3D')
      );
    });
```
