### ISSUE TITLE
Legacy SameSite cookie is not cleared on logout

### ISSUE THREAD

**Issue by ZdravkoDonev-gtmhub** [auth0/auth0-spa-js#1070]
### Describe the problem

When using the auth0-spa-js library, I set the cookieDomain option, which is propagated to the `CookieStorageWithLegacySameSite` class. When the library sets the `isAuthenticatedCookieName` during login, it sets the `cookieDomain` for the cookie for new browsers. But for legacy browsers it sets the cookie for the same domain where the login happened. There is no issue with this particularly.

The problem comes when I issue a logout through the library. Then the new cookie is cleared properly, but the legacy cookie is not cleared.

Then, during the next login, when the library calls `checkSession` it finds the legacy cookie and sees that the customer is authenticated for tha Auth0 application.

### What was the expected behavior?

The correct behavior is to clear both the new and the legacy cookie.

### Reproduction

To consistently reproduce the issue:

- Create the Auth0Client client with `cookieDomain: "mycompany.com"`
- Login at customerdomain.mycompany.com
- Check in the cookies that the new cookie is set with domain `mycompany.com` and the legacy cookie is set with domain `customerdomain.mycompany.com`
- Logout
- Check in the cookies that the new cookie is removed, but the legacy cookie is not.

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

When logged in:
![image](https://user-images.githubusercontent.com/81867642/216617653-533ba887-d964-4dfd-9053-c8c46f6d8a82.png)

When logged out:
![image](https://user-images.githubusercontent.com/81867642/216617751-15d44e88-f51d-4dff-bb6b-8b7e8d65d926.png)

### Environment

- **Version of `auth0-spa-js` used:** 1.22.4
- **Which browsers have you tested in?** Google Chrome Version 109.0.5414.119 (Official Build) (x86_64)
- **Which framework are you using, if applicable (Angular, React, etc):** AngularJS
- **Other modules/plugins/libraries that might be involved:** No.

**Comment by frederikprijck** [comment]
Thanks, I can see what could be causing that. Will look into this and provide a fix!

**Comment by frederikprijck** [comment]
I opened a PR that should solve this. Feel free to give it a try to see if it works as expected in your case as well.

**Comment by ZdravkoDonev-gtmhub** [comment]
Hi, @frederikprijck , Looking at the fix, I think this is exactly the problem as well. I also narrowed it down to that place. So I think it's OK.

Will this result in a new version of the library and if yes, when will it be available?

**Comment by frederikprijck** [comment]
As soon as https://github.com/auth0/auth0-spa-js/pull/1073 is approved, it will be released and available.

**Comment by ZdravkoDonev-gtmhub** [comment]
@frederikprijck Ok, thanks. And is this fix going to be applied for the v1 of the library or only for v2? As we haven't migrated yet to v2 and there are breaking changes.

**Comment by frederikprijck** [comment]
We will patch V1 somewhere next week. What's holding you back from migrating to V2?

If you experience any difficulties, feel free to reach out as we encourage moving to V2. Even though there are a couple of breaking changes in terms of public API, we expect these to be minimal.

**Comment by ZdravkoDonev-gtmhub** [comment]
Thanks, that's great.

Well nothing is stopping us, I actually saw that there's a V2 of the library this week.

We'll most probably migrate to it this quarter. I saw also migration documentation, so I guess there wouldn't be issues.
