### ISSUE TITLE
Is it possible to accept a valid refresh token to update the token cache?

### ISSUE THREAD

**Issue by wanqian2223** [auth0/auth0-spa-js#1077]
### Describe the problem you'd like to have solved

Currently, the refresh token exchange is fully managed by SPA SDK, which is really convenient. But I am wondering is it possible to support to accept an Auth0 issued refresh token which is probably generated by backed using Resource Owner Password flow or calling WebAuth.login directly by passing pwd/username to update token cache in SPA SDK, then we could use that refresh token going forward, with the "getTokenSilently" method and "useRefreshTokens" enabled.

More context: 
Our UI fully rely on the auth0 Universal Login to manage authentication and refresh token rotation (https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation). More specific, we use npm library @auth0/auth0-react(https://auth0.github.io/auth0-react/) which uses auth0-spa-js under the hood (API reference) to request new tokens and refresh tokens.

Recently, we plan to implement a new feature: make our users auto-login once they verify their emails.it's a little tricky as it's not under Universal Login Page, so we could not refresh token like we did in Universal Login Page.

However, we probably could get the refresh token in different way and want to provide this Auth0 issued refresh token to the browser storage the SDK was using, then we could use SPA SDK to help us maintain refresh token exchange.

**Comment by frederikprijck** [comment]
Thanks for reaching out. 

Using the resource owner flow isn't something we support in this SDK, and neither do we plan to add any support by the means of using it externally and injecting refresh tokens.

Our SDK is solely to use the PKCE flow and should be used as such.

If you would like for a way for users to be auto-logged in in a. way that is currently not supported in Auth0, I would recommend providing [product feedback](https://auth0.com/feedback).

Closing, as this isn't something we can accomodate.
