### ISSUE TITLE
How to integrate this into NextJs app?

### ISSUE THREAD

**Issue by zhouhao27** [auth0/auth0-spa-js#108]
I followed **QuickStart** to integrate this into my NextJs application. But got this error message:

> ReferenceError: window is not defined

In my index.js:

```
import React, { Component } from "react";
import Home from './home'
import { Auth0Provider } from "../services/auth0";
import config from "../services/auth_config.json";

// A function that routes the user to the right place
// after login
const onRedirectCallback = appState => {
  window.history.replaceState(
    {},
    document.title,
    appState && appState.targetUrl
      ? appState.targetUrl
      : window.location.pathname
  );
};

class Index extends Component {

  render() {
    return (
      <Auth0Provider
        domain={config.domain}
        client_id={config.clientId}
        redirect_uri={window.location.origin}
        onRedirectCallback={onRedirectCallback}
      >
        <Home/>
      </Auth0Provider>
    );
  }
}

export default Index;
```

Any idea? Thanks.

**Comment by thangbn** [comment]
use should use withRouter to access router data

**Comment by luisrudge** [comment]
If you want to use this SDK, you have to make sure that this only runs in the client, which means giving up on server side rendering and extracting your application to a static app.

If you still want to keep using SSR, then you'd have to use server side authentication and not this SDK. We have amazing content written about Next.js with all the guidance you need:

https://auth0.com/blog/next-js-authentication-tutorial/
https://auth0.com/blog/next-js-practical-introduction-for-react-developers-part-1/
https://auth0.com/blog/next-js-practical-introduction-for-react-developers-part-2/
https://auth0.com/blog/next-js-practical-introduction-for-react-developers-part-3/
