### ISSUE TITLE
scope not present in request arguments when grant_type = refresh_token contrary to API documentation

### ISSUE THREAD

**Issue by aaronctmr** [auth0/auth0-spa-js#1083]
### Problem

When calling getAccessTokenSilently from auth0-react with refreshToken: true and scope with the same value as the Auth0Client config, the value of scope does not make it in to the body of the request sent to the Auth0 Authorisation API.

i.e. When grant_type = refresh_token, scope is not present in the form body of the request, even when specified as an argument in `authorizationParams`.

### Expected behaviour?

When `getAccessTokenSilently()` is called (and subsequently `getTokenSilently()`), I expect the request to the Auth0 API to also include the scope values next to `grant_type`, `client_id` etc. I have this expectation because the Auth0 API allows for scope in the request as per the documentation: https://auth0.com/docs/api/authentication#refresh-token

### Reproduction

Basic configuration for Auth0Client
```
const auth0ClientConfig = {
  domain: config.domain,
  clientId: config.clientId,

  onRedirectCallback,
  cacheLocation: 'localstorage',

  useRefreshTokens: true,

  authorizationParams: {
    audience: config.audience,
    scope: customScope,
    screen_hint: 'login',
    redirect_uri: 'http://localhost:3001/callback',
  }
}
```

```
  const accessToken = await getAccessTokenSilently({
    cacheMode: 'off',
    authorizationParams: {
      scope: customScope,
    }
  });
```

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

This behaviour can not be reproduced in the playground in its current state, there seems to be a bug regarding the use of refresh tokens in the playground. 

*However*, I used the above config in the **Auth0 React SDK Sample Application** with version 2.0 and 2.01 of the Auth0 React SDK and was able to reproduce the problem.

#### Steps to reproduce:
1. Configure the App code per the config above, ensure that when get[Access]TokenSilently is called, there is a non-empty string for scope.
2. Configure the API in Auth0 dashboard with *allow offline access*
3. Authenticate as a user 
4. Open the network tab in the browser
5. Trigger getAccessTokenSilently() or getTokenSilently()
6. Inspect the POST request to the /oauth/token end-point
7. Note the absence of the scope value in the payload attributes

### Environment

- **Version of `auth0-spa-js` used:** 2.03
- **Version of `auth0-react` used:** 2.0
- **Which browsers have you tested in?** Brave
- **Which framework are you using, if applicable (Angular, React, etc):** Auth0 React SDK Sample Application
- **Other modules/plugins/libraries that might be involved:** Only those in the above SDK

**Comment by frederikprijck** [comment]
Thank you for reaching out.

The reasons this works as-is is explained in https://github.com/auth0/auth0-spa-js/issues/896.

Can you elaborate why you want to send the scope parameter with the refresh_token grant?

**Comment by aaronctmr** [comment]
Hi @frederikprijck, Thanks for your quick response! 
We have actions in place which rely on the scope to populate custom claims in the ID token. We're actually considering the alternative variable option mentioned in #896 but there are unknown security concerns around allowing the logic tied to scopes being decoupled from the Auth0 controls. 

e.g. During authentication, requesting scopes which aren't allowed will cause a failure and prevent abuse, however, decoupling in to a new variable will mean the logic in Auth0 which deals with scopes - no longer applies to the values in the new variable. 

It seems like a potential vector to us and may require more scrutiny in our actions where we'd rather just rely on what's already in place.

We do also have a future requirement for descoping, but it's a few months off.

Thanks,
Aaron

**Comment by frederikprijck** [comment]
> e.g. During authentication, requesting scopes which aren't allowed will cause a failure and prevent abuse, however, decoupling in to a new variable will mean the logic in Auth0 which deals with scopes - no longer applies to the values in the new variable.

If we would pass along scopes with refresh tokens, the following will also work:

- User logs in and gets a token for Scope A and B
- User calls refresh_token grant sending Scope A, B and C
- Auth0 will ignore C, and send a new token for A and B.

So even tho Auth0 doesn't use ScopeC, your custom logic will need to ensure it does not handle Scope C in this case.
So I believe the issue isn't very different with using custom parameters on this end. 

> We do also have a future requirement for descoping, but it's a few months off.

We do appreciate feedback around this feature, and would love to hear your exact need for this.

**Comment by aaronctmr** [comment]
@frederikprijck Thanks for clarifying the scope functionality, looks like we will have to do some work. 

Future descoping will likely involve temporary step-up by leveraging an additional auth factor (add scope), then a drop down (descope) after a short period of time. The requirement is for a temporary higher level of authentication for more sensitive activities.
