### ISSUE TITLE
Why Auth0 keeps redirecting to non-secure http URL instead of https?

### ISSUE THREAD

**Issue by priyasonar31** [auth0/auth0-spa-js#1085]
### Describe the problem
I am using cdn <script src="https://cdn.auth0.com/js/auth0-spa-js/2.0/auth0-spa-js.production.js"> 
all the code base is similar to example here https://github.com/auth0/auth0-spa-js#logging-in
  but after this await auth0.loginWithRedirect();
  callback is redirecting to http URL instead of https.
  and we have rechecked all our code, we have provide https in redirect uri

### What was the expected behavior?

it should redirect to https

### Reproduction

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

### Environment

- **Version of `auth0-spa-js` used:** 2.0
- **Which browsers have you tested in?** edge, chrome
- **Which framework are you using, if applicable (Angular, React, etc):** plain JS
- **Other modules/plugins/libraries that might be involved:** no

**Comment by stevehobbsdev** [comment]
👋🏻 Can you please share the relevant code from your app that initializes the SDK and calls `loginWithRedirect`?

**Comment by priyasonar31** [comment]
```
let auth0Client = null;
const configureClient = async () => {
  auth0Client = await auth0.createAuth0Client({
    domain: '',
    clientId: '',
    authorizationParams: {
      redirect_uri : '' // redirecting to this file location again
    }
  });
};

const login = async () => {
  try {
    console.log("> Logging in...");
	const options = {};
    await auth0Client.loginWithRedirect(options);
  } catch (err) {
    console.log(" failed...", err);
  }
};

window.onload = async () => {
 const query = window.location.search;
  await configureClient();
  const isAuthenticated = await auth0Client.isAuthenticated();
  if (isAuthenticated) {
    console.log("User is authenticated...");
    return;
  }
  console.log("User not authenticated...");
  const shouldParse = query.includes("code=") && query.includes("state=");
  if (shouldParse) {
    console.log("Callback parsing redirect...");
    try {
      const result = await auth0Client.handleRedirectCallback();
      console.log("Logged in!!!");
    } catch (err) {
      console.log(" Error", err);
    }
  } else {
    console.log(" Proceed to login...");
    login();
  }
}
```

**Comment by priyasonar31** [comment]
> 👋🏻 Can you please share the relevant code from your app that initializes the SDK and calls `loginWithRedirect`?
```
let auth0Client = null;
const configureClient = async () => {
  auth0Client = await auth0.createAuth0Client({
    domain: '',
    clientId: '',
    authorizationParams: {
      redirect_uri : '' // redirecting to this file location again
    }
  });
};

const login = async () => {
  try {
    console.log("> Logging in...");
	const options = {};
    await auth0Client.loginWithRedirect(options);
  } catch (err) {
    console.log(" failed...", err);
  }
};

window.onload = async () => {
 const query = window.location.search;
  await configureClient();
  const isAuthenticated = await auth0Client.isAuthenticated();
  if (isAuthenticated) {
    console.log("User is authenticated...");
    return;
  }
  console.log("User not authenticated...");
  const shouldParse = query.includes("code=") && query.includes("state=");
  if (shouldParse) {
    console.log("Callback parsing redirect...");
    try {
      const result = await auth0Client.handleRedirectCallback();
      console.log("Logged in!!!");
    } catch (err) {
      console.log(" Error", err);
    }
  } else {
    console.log(" Proceed to login...");
    login();
  }
}
```
https://user-images.githubusercontent.com/115352135/224102101-8b76e432-a888-4ebb-b202-9156f76d45a4.png

**Comment by stevehobbsdev** [comment]
Normally we would set `redirect_uri` to `window.location.origin` and the browser would end up back on the app - can you try that? Right now it looks like you're setting a blank value, but not sure if that's just been omitted from the issue.

```js
auth0Client = await auth0.createAuth0Client({
    domain: '',
    clientId: '',
    authorizationParams: {
      redirect_uri : window.location.origin
    }
  });
```

**Comment by priyasonar31** [comment]
> Normally we would set `redirect_uri` to `window.location.origin` and the browser would end up back on the app - can you try that? Right now it looks like you're setting a blank value, but not sure if that's just been omitted from the issue.
> 
> ```js
> auth0Client = await auth0.createAuth0Client({
>     domain: '',
>     clientId: '',
>     authorizationParams: {
>       redirect_uri : window.location.origin
>     }
>   });
> ```
had omitted that purposely. But thanks for checking, my Issue got resolved by adding trailing slash in redirect_uri/ auth0 callback.
we can close the bug.

**Comment by priyasonar31** [comment]
my issue is resolved. it was not related to library
