### ISSUE TITLE
Since v2 getTokenSilently returns expired tokens

### ISSUE THREAD

**Issue by xixixao** [auth0/auth0-spa-js#1089]
### Describe the problem

`getTokenSilently` should only return a token if it hasn't expired, but we're seeing expired tokens being returned. This breaks clients when tokens expire.

### Reproduction

Configure a short expiration in Auth0 settings, like 10 seconds in ID Token Expiration.

Log in to a client (we use React):

```

function LoginButton() {
  const { loginWithRedirect } = useAuth0()
  return (
    <button
      onClick={() => {
        loginWithRedirect()
      }}
    >
      Log in
    </button>
  )
}

<Auth0Provider domain="..." clientId="...."
  authorizationParams={{
          redirect_uri:
            global.window !== undefined
              ? global.window.location.origin
              : (null as any),
        }}
        cacheLocation="localstorage"
        ><LoginButton /></Auth0Provider>
```

Then after 10 seconds run (say from a button click):

```
getAccessTokenSilently({ detailedResponse: true }).then(console.log)
```

You will see that you get the same token, no matter how long you wait, despite the fact that the token expired.

I think this is bug in V2, and was not the case before.

We cannot use `cacheMode: "off",` because that breaks browsers with "Prevent Cross-site Tracking".

- Step 1..
- Step 2..
- ...
-->

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?** Not sure

### Environment

- **Version of `auth0-spa-js` used:** 2.0.4
- **Which browsers have you tested in?** MacOS Chrome, iOS Safari
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** auth0-react

**Comment by frederikprijck** [comment]
Thanks for reaching out. The token being returned is the Access Token whose expiration is not affected by the ID Token expiration.

In v2, we indeed removed the ID Token expiration to impact the Access Token expiration. Instead, the Access Token expiration is now defined by the Access Token expiration alone, as it should be. This was different in v1, but it was incorrect.

The ID token expiration should only be used initially to accept the ID Token, it's not used to determine any session duration or anything.

**Comment by xixixao** [comment]
@frederikprijck thanks for the detailed answer.

> I do understand you say you can't, however if you can't, how would you expect our SDK to retrieve a new token in the first place, as we use the same mechanism when the Access Token is expired

Actually we can set it to `cacheMode: off`. There are two problems:

1. We (unlike the Auth0 client) cannot tell whether the ID token has expired or not (we don't know when it was fetched, so can't calculate using its lifetime when it should be expired). So we have to wait for a validation server to reply with an error (yes we're passing the ID token down to a server which we understand is not recommended), if we want to do this only when necessary.
2. Other auth providers like Clerk have no trouble refetching tokens on mobile Safari with Prevent Cross-site Tracking turned on. My (perhaps incorrect) understanding is that Auth0 uses cookies when the `cacheLocation` is set to "memory", while Clerk uses an actually in-memory store, so doesn't run into a cookie issue.

`cacheMode: off` on mobile Safari with Auth0 always logs the user out. (perhaps this a separate issue worth investigating)

**Comment by frederikprijck** [comment]
That's explained in our [FAQ]( https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md). Yes we rely on cookies, as we should.

I am not familiar with clerk or how they implement it, but yes we believe we should rely on cookies if you don't use refresh tokens.

You can use [custom domains](https://auth0.com/docs/customize/custom-domains), which will make cookies work with iframes in browsers like safari.

**Comment by frederikprijck** [comment]
Also want to mention that this behavior has changed intentionally. We believe the behavior in V1 is wrong, but understand people relied on it so we didnt want to break people by removing that behavior in V1, hence why we introduced that change in V2.

**Comment by xixixao** [comment]
Confirmed that Refresh Tokens do prevent the logout in mobile safari. This required `useRefreshTokens={true}` on `Auth0Provider` while using `cacheMode: off`.

I couldn't find docs specifically for the combo of spa/react and Refresh Tokens, so that might be worth adding (perhaps the FAQ callout should be mentioned in docs for spa/react).


Thanks again @frederikprijck for the awesome customer support!
