### ISSUE TITLE
Verify Id Token fails when client clock is out of sync

### ISSUE THREAD

**Issue by aveiros** [auth0/auth0-spa-js#1093]
### Describe the problem

Verify Id Token fails when client clock is out of sync

I'm currently getting this error with this library
```
Error: Expiration Time (exp) claim error in the ID token; 
current time (Thu Apr 27 2023 21:15:19 GMT+0100) is 
after expiration time (Thu Apr 27 2023 20:31:20 GMT+0100)
```

Currently happening when calling getTokenSilently and the library makes a call to the authorization server token endpoint and `verifyIdToken` happens to execute, the following code executes:
```
  const leeway = options.leeway || 60;
  const now = new Date(options.now || Date.now());
  const expDate = new Date(0);

  expDate.setUTCSeconds(decoded.claims.exp + leeway);

  if (now > expDate) {
    throw new Error(
      `Expiration Time (exp) claim error in the ID token; current time (${now}) is after expiration time (${expDate})`
    );
  }
```

If my computer clock is later than the id token expires claim we run into this issue.

Maybe we could probably use `TokenEndpointResponse` `expires_in` property, and compute expDate as `expDate.setUTCSeconds(Math.floor(now / 1000) + expires_in + leeway);` or maybe follow the `nowProvider` approach and allow a parameterized `expiresCompute(now, expires, expires_in, leeway)` -- just some thoughts

Furthermore, I did not check if it affects other expiration checks (i.e. when token is cached for example).

Thanks for the awesome work on this library ;) 

### What was the expected behavior?

Verify Id Token to work regardless of the client clock being in sync or not.

### Reproduction

- Step 1: Make sure you set your computer clock to a date/hour after the token expiration (use case: users that dont have automatic date/time server sync selected).
- Step 2: Make sure you delete the "cached" token so a new one is requested.

### Environment

- **Version of `auth0-spa-js` used:** 2.0.4
- **Which browsers have you tested in?** chrome

**Comment by frederikprijck** [comment]
> If my computer clock is later than the id token expires claim we run into this issue.

This looks to be expected, as we should not accept an ID token after it's considered expired. Messing / incorrectly configured times have an impact on this. Can you elaborate on why your clock is out of sync and why you believe a library should accomodate for that ?

**Comment by aveiros** [comment]
Hey @frederikprijck 
I don't have a nowProvider configured. How could i configure a nowProvider to fix this issue?

**Comment by frederikprijck** [comment]
nowProvider is a function that returns a date that reflects what 'now' means on the current system.

If your clock is 2 hours behind, you would set the now to Date.now + 2 hours. Or vica versa.
Ideally you would introduce a time server to solve this, e.g.:

```ts
async function getCurrentTime() {
  const response = await fetch('URL_HERE');
  const data = await response.json();
  return data.now;
}
const client = new Auth0Client({
  nowProvider: () => getCurrentTime()
});
```

**Comment by aveiros** [comment]
Ok, but in that case it implies a further network call for every user. When the application has millions of users -- this can be costly. Would the following not be a better solution?

```
  const leeway = options.leeway || 60;
  const nowInMillis = options.now || Date.now();
  const now = new Date(nowInMillis);
  const expDate = new Date(0);

  if(options.expires_in) {
    // options.expires_in is populated from TokenEndpointResponse expires_in property.
    expDate.setUTCSeconds(Math.floor(nowInMillis / 1000) + options.expires_in + leeway);
  } else {
    expDate.setUTCSeconds(decoded.claims.exp + leeway);
  }

  if (now > expDate) {
    throw new Error(
      `Expiration Time (exp) claim error in the ID token; current time (${now}) is after expiration time (${expDate})`
    );
  }
```

where `expires_in` and configure via Auth0ClientOptions

```
export interface JWTVerifyOptions {
  iss: string;
  aud: string;
  id_token: string;
  expires_in?: number;
  nonce?: string;
  leeway?: number;
  max_age?: number;
  organizationId?: string;
  now?: number;
}```

**Comment by frederikprijck** [comment]
expires_in is a value that's coming from Auth0 and should not be configurable. The issue here is the clock being incorrect, meaning the value of "now". To fix that, we have nowProvider.

You do not need to integrate an API call if u do not want that. You can just as well use any value (e.g. whatever value you are planning to configure the proposed `expires_in` with) and use that to add/subtract from datetime.now.

**Comment by aveiros** [comment]
Sorry, not sure I'm totally following. Can you please check this potential scenario?

The Auth Server issues the following token:
```
expires_in: 900 seconds
id_token_expires: 28th April 1pm
```
The end user clock is on
```
29 April 3pm (1 day and something ahead).
```

The master implementation of verifyIdToken checks the token is invalid (the error above).

With the proposal above, verifyIdToken checks the token is valid and also when using `cache: 'localstorage'` the local storage entry `@@auth0spajs@@::xxxxxx::default::openid profile email offline_access` `expiresAt` property is set for tomorrow (end user clock + expires_in).

I'm not sure I can solve this issue with just the nowProvider.

**Comment by frederikprijck** [comment]
If you would update the expiresAt property in localstorage based on the users incorrectly configured date, you'll end up with other issues. 

Imagine the additional scenario, where the user has an entry in local storage with expiresAt set to tomorrow (end user clock + expired), and after that they rectify their clock. We now have an expiresAt in local storage that is based on the previous clock settings of the user, not the current.

> I'm not sure I can solve this issue with just the nowProvider without introducing a time server / network call.

Let's say we would implement your proposal, what would you pass to the `expires_in` property and how would u calculate its value?

**Comment by aveiros** [comment]
Here's my attempt (I'm still doing some testing and there are probably more elegant ways to do it):

`src/global.ts`

```
export interface JWTVerifyOptions {
  iss: string;
  aud: string;
  id_token: string;
  expires_in: number;
  useExpiresCheckFallback: boolean;
  nonce?: string;
  leeway?: number;
  max_age?: number;
  organizationId?: string;
  now?: number;
}
```

`src/Auth0Client.ts`
```
 const decodedToken = await this._verifyIdToken(
      authResult.id_token,
      authResult.expires_in,
      nonceIn,
      organizationId
    );


  private async _verifyIdToken(
    id_token: string,
    expires_in: number,
    nonce?: string,
    organizationId?: string
  ) {
    const now = await this.nowProvider();

    return verifyIdToken({
      iss: this.tokenIssuer,
      aud: this.options.clientId,
      id_token,
      expires_in: expires_in,
      useExpiresCheckFallback: !!this.options.useIdTokenExpiresCheckFallback,
      nonce,
      organizationId,
      leeway: this.options.leeway,
      max_age: parseNumber(this.options.authorizationParams.max_age),
      now
    });
  }
```

`src/jwt.ts`
```
  const leeway = options.leeway || 60;
  const nowInMillis = options.now || Date.now();
  const now = new Date(nowInMillis);
  const expDate = new Date(0);

  expDate.setUTCSeconds(decoded.claims.exp + leeway);

  if (now > expDate) {
    if(!options.useExpiresCheckFallback) {
      throw new Error(
          `Expiration Time (exp) claim error in the ID token; current time (${now}) is after expiration time (${expDate})`
      );
    }

    expDate.setUTCSeconds(Math.floor(nowInMillis / 1000) + options.expires_in + leeway);

    if (now > expDate) {
      throw new Error(
          `Expiration Time (exp) claim error in the ID token; current time (${now}) is after expiration time (${expDate})`
      );
    }
  }
```

This gets around the problem for those users that have a clock in the future, allowing them to still use the application.

**Comment by frederikprijck** [comment]
I don't believe we should be messing with the expires value only to accomodate for an incorrectly configured.

Please integrate a time server, that's a practice used specifically for this situation. The overhead should be limited as you can implement it in such a way that you only call it once:

- call time server, it retrieves the current time
- calculate the difference between now locally and now on the timeserver
- use that difference to configure the nowProvider to add or subtract from the local current time.

Any call to nowProvider will not require an http call.

That should work for your usecase with the current version of the SDK.

**Comment by aveiros** [comment]
@frederikprijck thanks for the reply -- we are now considering using a get server time call.
