### ISSUE TITLE
Login popup dimensions should be configurable

### ISSUE THREAD

**Issue by srmagura** [auth0/auth0-spa-js#1095]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The initial dimensions of the login popup are not big enough to fit the whole content, so there are horizontal and vertical scrollbars. (This might be because we have custom styles on our login page, not sure.)

![image](https://user-images.githubusercontent.com/801549/236828660-7f5f54e0-a3ca-4147-ae3b-91d5b6fc1254.png)

There's currently no good way to fix this, since the popup window size is hardcoded here:

https://github.com/auth0/auth0-spa-js/blob/79720c5fe345f194151259a8b05cfe452734c6b5/src/utils.ts#L86-L97

### Describe the ideal solution

`loginWithPopup` should accept `popupWidth, popupHeight` options for setting the initial dimensions of the popup. Or something similar to that.

**Comment by frederikprijck** [comment]
Thanks for reaching out, `loginWithPopup` accepts a `popup` property (see: https://auth0.github.io/auth0-spa-js/interfaces/PopupConfigOptions.html#popup) that allows you to provide the entire popup instance yourself. This should allow to apply any customization as needed.

**Comment by srmagura** [comment]
Thanks, I can use that.

I had seen the `popup` property and read the comment on it, but it wasn't clear to me that this is how you would set the dimensions of the popup window. I wonder if the documentation could be improved, or if `popupWidth` and `popupHeight` options could be added since that is (presumably) a common use case that would be easy to support.

**Comment by frederikprijck** [comment]
We considered making width and height configurable, but it opens up for adding all kind of additional configuration while you can configure all of those through providing your own `popup`.

> but it wasn't clear to me that this is how you would set the dimensions of the popup window

You use popup when u want to use a popup that is different from the one we create for you.

Closing as I think this should solve it, let me know if not.
