### ISSUE TITLE
Distinguish between Missing State and Invalid State

### ISSUE THREAD

**Issue by aveiros** [auth0/auth0-spa-js#1097]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Often users hit the back button and land on the callback url with callback parameters (code + state) and we have no way to know (?) when an "Invalid state" error was caused by [missing state](https://github.com/auth0/auth0-spa-js/blob/ccc53a571b4b312b9d124efb2132b5bbfde94b7f/src/Auth0Client.ts#L496) or [invalid state](https://github.com/auth0/auth0-spa-js/blob/ccc53a571b4b312b9d124efb2132b5bbfde94b7f/src/Auth0Client.ts#L515) (state mismatch).

We would like to take different routes depending on each of the scenarios above.

### Describe the ideal solution

Maybe use `GenericError` with a different error property in order to distinguish these two scenarios.

### Alternatives and current workarounds

None (? i believe).

**Comment by frederikprijck** [comment]
Thanks for reaching out, I believe that's a fair request and opened a PR to accommodate for this.
