### ISSUE TITLE
How should my API verify this?

### ISSUE THREAD

**Issue by dannytatom** [auth0/auth0-spa-js#110]
I can't find it now, but the original doc/guide I was using (from Auth0) said to use `node-jsonwebtoken` to verify the access token in the auth header. But the token isn't JWT, so I'm not really sure how to verify a user when they hit the API or how to associate that user with a DB record.

I got the login working on the fronted, but yea, I'm stuck on where to go from there. Sorry if dumb question, just a bit confused.

**Comment by luisrudge** [comment]
If your access_token is not a JWT, it means that you're not using a custom audience. Please check our guidance for [calling an api here](https://auth0.com/docs/quickstart/spa/vanillajs/02-calling-an-api#create-an-api).

**Comment by luisrudge** [comment]
Also, if you don't want to use a custom API, you can send the access_token and then use https://github.com/auth0/node-auth0 to get the user information using the [`getProfile` method](http://auth0.github.io/node-auth0/module-auth.AuthenticationClient.html#getProfile).

**Comment by dannytatom** [comment]
Created a new API, still get malformed error when supplying that API as the audience.

```typescript
// AUTH0_AUDIENCE is the custom API I just created

const client = jwksClient({
  jwksUri: `https://${process.env.AUTH0_DOMAIN}/.well-known/jwks.json`
});

const getKey = (header: any, callback: any) => {
  client.getSigningKey(header.kid, (_err: Error, key: jwksClient.SigningKey) => {
    const signingKey = (key as jwksClient.CertSigningKey).publicKey || (key as jwksClient.RsaSigningKey).rsaPublicKey
    callback(null, signingKey)
  })
}

const options = {
  audience: `${process.env.AUTH0_AUDIENCE}`,
  issuer: `https://${process.env.AUTH0_DOMAIN}/`,
  algorithms: ['RS256']
};

const apollo = new ApolloServer({
  modules: [graphQLRoot],

  context: (context: any) => {
    let token = context.req.headers.authorization;
    token = token ? token.replace('Bearer ', '') : null
    
    if (token) {
      const user = new Promise((resolve, reject) => {
        jwt.verify(token, getKey, options, (_err, decoded) => {
          console.log('err', _err)
          console.log('decoded', decoded)

          resolve(decoded);
        });
      });
  
      return {
        currentUser: user
      }
    } else {
      return {
        currentUser: undefined
      }
    }
  }
}
```

**Comment by dannytatom** [comment]
I feel like the app on auth0 should know the API exists, but I don't see anywhere to tell it that?

**Comment by mcblum** [comment]
I was wondering the exact same thing -- does my API have to have some kind of `/token` endpoint or something? I thought Auth0 handled all of that? Here's our flow:

1. Angular app creates Auth0 client which, after login, does somewhere make a call to `{domain}.auth0.com/oauth/token` in which I see the token and id_token, but we can't actually get to it.
2. If I call the API with the `token`, I get a JWT malformed error.
3. If I call the API with the `id_token`, the audience is wrong.

What am I missing here?

**Comment by luisrudge** [comment]
If you're not receiving a JWT as an `access_token`, then you're probably missing the step where you declare your custom audience: https://auth0.com/docs/quickstart/spa/angular2/02-calling-an-api#modify-the-authservice-class

**Comment by luisrudge** [comment]
In order to get a JWT as the `access_token`, your request should have something in the `audience` param. So, the first request to `/authorize` will be something like `https://yourtenant.auth0.com/authorize?client_id=YOUR_CLIENT&audience=YOUR_API....` (not necessarily in that order).

**Comment by mcblum** [comment]
@luisrudge also saw your other comment -- here's what I have for my service:
```
private config = {
    domain: AUTH0_AUTH_ISSUER,
    client_id: AUTH0_CLIENT_IDS.GLOBAL,
    redirect_uri: `${window.location.origin}/${AUTH0_REDIRECT_URI}`
  };
```
