### ISSUE TITLE
Missed Invalid state errors with Generic Error

### ISSUE THREAD

**Issue by aveiros** [auth0/auth0-spa-js#1101]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

On the [MR](https://github.com/auth0/auth0-spa-js/pull/1099) to distinguish missing state from state mismatch we missed some errors (the ones i noticed): [here](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L382) and [here](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L901)

Not sure if the `auth0-spa-js.development_old.js` should also be updated.

Thanks for your contributions 👏 

### Reproduction

n/a

### auth0-spa-js version

latest

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Thanks for reporting, it appears that I have missed those two, opened a PR to fix that.

> Not sure if the auth0-spa-js.development_old.js should also be updated.

No, that's an old version of v1 of the SDK.
