### ISSUE TITLE
TransactionManager not using cookieDomain option passed to the library. Instead if uses the current domain.

### ISSUE THREAD

**Issue by ZdravkoDonev-gtmhub** [auth0/auth0-spa-js#1104]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi,

We're using the auth0-spa-js library option `Auth0ClientOptions.cookieDomain`. My expectation is that whatever cookies the library wants to use (especially transaction cookies) it should use the passed cookieDomain. Instead, the library uses this cookieDomain for some of it's flows and for others it does not.

For example, we initiate a login flow from `app.gtmhub.com` and after a successful login on the Auth0 side we redirect the user to his vanity domain `<vanity_prefix>.gtmhub.com`. In that case, the TransactionManger storage is lost, because it will set the expected state on the domain `app.gtmhub.com` instead of the passed `cookieDomain: "gtmhub.com"`. 

I will raise a Pull Request with my expectations.

### Reproduction

1. Initiate a login flow from app.gtmhub.com by passing Auth0ClientOptions with options `{cookieDomain: "gtmhub.com", authorizationParams: {redirect_uri: client123.gtmhub.com}}`.
2. Login successfully on the Auth0 Universal login flow
3. Get redirected back to client123.gtmhub.com
4. TransactionManager throws an error for "Invalid state".

### auth0-spa-js version

2.0.5

### Which framework are you using (React, Angular, Vue...)?

Angular

### Framework version

14

### Which browsers have you tested in?

Chrome

**Comment by ZdravkoDonev-gtmhub** [comment]
This is my proposal for fix - https://github.com/auth0/auth0-spa-js/pull/1105

**Comment by frederikprijck** [comment]
Thanks 👍
