### ISSUE TITLE
`amr` property on IdToken is of type `string`

### ISSUE THREAD

**Issue by bellascalzi1** [auth0/auth0-spa-js#1110]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, I'm writing some custom logic based on the `amr` values in the ID token (specifically checking for the presence of the string 'mfa' as detailed in [this docs page on step-up authentication](https://auth0.com/docs/secure/multi-factor-authentication/step-up-authentication/configure-step-up-authentication-for-web-apps). In the documentation it says:

> When a user logs in, you get an [ID token](https://auth0.com/docs/secure/tokens/id-tokens/get-id-tokens) that contains information relevant to the user's session in the form of claims. The relevant claim is amr (authentication methods reference) which is a **JSON array of strings** that indicates the authentication method used during login. It must be present in the ID token's payload and must contain the value mfa.

This suggests to me that the type should be `Array<string>` or `string[]` instead of `string`. 

At runtime the `amr` value does seem to be an array of strings, as seen in this screenshot (this is using the Angular SDK)

![screenshot](https://github.com/auth0/auth0-spa-js/assets/16617321/c14e8e42-abf3-4039-8cf1-61ef1f2a4c0f)

Right now this isn't blocking me as I am using the `includes()` function to check for the presence of the 'mfa' string, which is also a method on strings but it would still be nice to get this fixed.

If the fix for this is as simple as changing this line I would be more than happy to submit a PR https://github.com/auth0/auth0-spa-js/blob/66e0dfbe8ed9dc35406d0281cd60cd14f705e9e7/src/global.ts#L591

### Reproduction

1. Retrieve an ID Token after authenticating with MFA
2. Print the contents of the token to the console, and observe that `amr` is an array rather than a string.

### auth0-spa-js version

2.0.8

### Which framework are you using (React, Angular, Vue...)?

Angular

### Framework version

15.1.0

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Thanks for reporting this. It looks like this should indeed be an array of strings.

Feel free to open a PR to update the type and we are happy to review this.
