### ISSUE TITLE
Getting error on Authorisation using sample react application - Cannot read property 'split' of undefined     at auth0-spa-js.production.js:685

### ISSUE THREAD

**Issue by mkmuduli** [auth0/auth0-spa-js#112]
![image](https://user-images.githubusercontent.com/16792091/61880305-47c6e500-af12-11e9-8330-dfa491d9b4ef.png)

Getting the same issue. Trying to login using gmail. Login is succesful but on Approving access to the application, the page redirects to http://localhost:3000/?code=YpqazoJ6B_RazjFx&state=Mm05b19LSlZSekxaTGpnZGR1aHhBNnF%2BSkhiczZneHI3dm91anI3NEF5RA%3D%3D and gives the error in console. Check attached screeenshot

Kindly help resolve.

**Comment by luisrudge** [comment]
duplicate of https://github.com/auth0/auth0-spa-js/issues/70. I'm closing this issue, but let's continue our conversation in #70. If we find a bug, we can open another issue with the full repro steps.
