### ISSUE TITLE
"Misconfiguration in the system or a service outage" error in Auth0

### ISSUE THREAD

**Issue by HanBC0704** [auth0/auth0-spa-js#1121]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Now I’ve integrated the auth0 using the auth0-spa-js/2.1/auth0-spa-js.production.js
In normal case, it works well.
But after logout, certain period later, I tried to login in again. In this case I got the misconfiguration error.

[Error Case Reference Video Here](https://api.media.atlassian.com/file/5202534e-0d85-4b68-b106-cafab3f44ae5/artifact/video_1280.mp4/binary?client=b1fe7f8d-551f-480d-b85e-621c5af1c363&collection=&max-age=2592000&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJiMWZlN2Y4ZC01NTFmLTQ4MGQtYjg1ZS02MjFjNWFmMWMzNjMiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOmVkZDU3ZjU1LWY4MTUtNDk4Ny04ZGQyLWE4ZmRkMjJjOGZlNyI6WyJyZWFkIl0sInVybjpmaWxlc3RvcmU6ZmlsZTpkMTk1ZGE1NS1jNGVhLTQxOTItODcwYS0yZmI3MTcyOTU1NGYiOlsicmVhZCJdLCJ1cm46ZmlsZXN0b3JlOmZpbGU6ZjJhMmE5NjktZmI2OC00NmE5LTk4M2YtNWQwYjY1NTRjMzkwIjpbInJlYWQiXSwidXJuOmZpbGVzdG9yZTpmaWxlOmM3MTIzNWU2LWI5ZGYtNDcyNC04N2FkLTNmMzY5MWMxZWQ5OCI6WyJyZWFkIl0sInVybjpmaWxlc3RvcmU6ZmlsZTplYWY0OTNlYS0zNzIzLTRlOWEtYTk2OS1jOGJhY2U1Yjk5MDciOlsicmVhZCJdLCJ1cm46ZmlsZXN0b3JlOmZpbGU6ZDI5YjhiZjgtZTRiMi00Nzc3LTk5MjYtNzg5YzViNjZmZDJmIjpbInJlYWQiXSwidXJuOmZpbGVzdG9yZTpmaWxlOjUyMDI1MzRlLTBkODUtNGI2OC1iMTA2LWNhZmFiM2Y0NGFlNSI6WyJyZWFkIl0sInVybjpmaWxlc3RvcmU6ZmlsZTo4ZWM4YjgzYS00NTU2LTQwNmQtYjhiMy00MTFjODhiYWJiODIiOlsicmVhZCJdfSwiZXhwIjoxNjg5ODYzMjI4LCJuYmYiOjE2ODk4NjIzMjh9.914ygaxe1aDoa-P4orMmzspLnmzdbUCDz1e1Vb6VLB0)

I already added allowed callback urls, login urls, logout urls in the auth0 dashboard config. but not sure Why I got this error.
Please help. Thank you.

PS： here is a tracking when error occurred. 93681c1f0d5d9661154b, 75c6fc801fc031d745d7
And already posted this in the Auth0 community: [https://community.auth0.com/t/misconfiguration-in-the-system-or-a-service-outage-error-in-auth0/111693/1]

### Reproduction

case1: 
1. step1: open one browser, and hit https://stg.comportal.tsh.care/, then will open auth0 login page. here using account: "tsh.qateam07@gmail.com" pwd: "abcd@123", login. 
2. step2: after login success, passed 15 minutes you will be logout. in this case, don't close the browser, after one day, login again. Then the misconfiguration error will be occurred. 

case2:
1. step1: open one browser, and hit https://stg.comportal.tsh.care/, then will open auth0 login page. here using account: "tsh.qateam07@gmail.com" pwd: "abcd@123", login. 
2. step2: open another 5 tabs, and repeat step1, so open 5 tabs with the same url. 
3. after auto logout, passed 1 or 2 hour, login in again one by one. then one of the opened 5 tabs will be reproduced. 

### auth0-spa-js version

2.1

### Which framework are you using (React, Angular, Vue...)?

Vue

### Framework version

2.6.14

### Which browsers have you tested in?

Chrome, Safari

**Comment by HanBC0704** [comment]
Just one question for this. 
When does the state of the Auth0 change in the Auth0 engine?

**Comment by adamjmcgrath** [comment]
Hi @HanBC0704 - thanks for raising this and apologies for the delay getting back to you.

Could you share a HAR file that demonstrates the issue and I'd be happy to investigate for you.

> When does the state of the Auth0 change in the Auth0 engine?

Sorry, I'm not sure what you mean by "state of the Auth0"

**Comment by lohiyalavarthi1** [comment]
hi @HanBC0704 is the issue resolved?
