### ISSUE TITLE
prompt in authorizationParams is not getting override. It is coming none even if it is set to other value like login.

### ISSUE THREAD

**Issue by dhairyafaria-uniphore** [auth0/auth0-spa-js#1125]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

'prompt' in authorizationParams is not getting overridden. It is coming as 'none' even if it is set to another value like 'login'.

And thus authorize API call is not redirecting to the login page. This issue is for Nuxt2. In nuxt3 issue is not there as there is a different package used.

### Reproduction

This is my plugin file

import Vue from 'vue';
import { Auth0Client } from '@auth0/auth0-spa-js';

export default async ({ app, $config: { domain, clientId, audience, redirectUri } }, inject) => {
    const organization = new URLSearchParams(window.location.search).get("orgId");
    const authorizationParams = {
        prompt: "login",
        audience,
        redirect_uri: redirectUri,
    };
    
    if (organization) {
        Object.assign(authorizationParams, {
          organization,
        });
    }

    const auth = new Auth0Client({
        domain,
        clientId,
        authorizationParams,
    });

    inject('auth', auth);
    app.$auth = auth;
}

### auth0-spa-js version

latest

### Which framework are you using (React, Angular, Vue...)?

vue

### Framework version

2

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Thanks for reaching out. Can you please elaborate a bit more on what you are experiencing and what you are expecting, idealy can you please provide a reproduction sample so we can see this happening?

Additionally, what calls are you talking about? If this is about the iframe call, we will always set it to none as you can see here: https://github.com/auth0/auth0-spa-js/blob/eec419f3028fee80826403d12e8f0383f7823eab/src/Auth0Client.ts#L862

**Comment by dhairyafaria-uniphore** [comment]
When user is logged out getting this error "Error: Login required" after authorize API call this is because of the prompt property. 
I want it to redirect to login page. 

<img width="574" alt="image" src="https://github.com/auth0/auth0-spa-js/assets/123978818/b01bcea8-d805-41ae-96c7-3f460db50f0e">

I tried to pass the prompt value to login but still it is not accepting and sticking to none. And thus not getting this login page.

**Comment by frederikprijck** [comment]
Auth0-vue is using auth0-spa-js. So if it works with auth0-vue, it works with Auth0-spa-js.

Our SDK doesnt set prompt to none apart for iframe.

If you provide a reproduction sample, i can help troubleshoot for you.

**Comment by dhairyafaria-uniphore** [comment]
@frederikprijck  Is this snapshot?
<img width="688" alt="image" src="https://github.com/auth0/auth0-spa-js/assets/123978818/3d3d6afd-6781-4106-96f3-05eed7b0e541">

**Comment by frederikprijck** [comment]
That does look like the iframe. But please provide an actual sample for us to run and investigate.

**Comment by frederikprijck** [comment]
Closing as I don't see how this is an issue with our SDK and there hasn't been any response. Happy to reopen if needed, just give me a ping.
