### ISSUE TITLE
Sophos Cyber Security Endpoint detects ransomware in the package

### ISSUE THREAD

**Issue by R3BLcreative** [auth0/auth0-spa-js#1129]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

My company uses the Sophos Cyber Security Service to protect company laptops. I recently added the auth0-spa-js (v2.1.2) to a NextJS app I am working on in my local dev environment on my machine (MacBook Pro M1 running Ventura 13.5.1).

I spent the last week removing every Node related file and node_modules folders from my machine and slowly added each one back and running the Sophos scanner in order to hunt down what was causing the threat detection and finally found that it was the auth0-spa-js package.

When running the app on http://localhost:3000, Sophos flags a ransomware threat on my machine. The notification does not give much detail except that "Node" has been flagged as ransomware. Hence my process above of needing to hunt down the package.

My guess is that this has nothing to do with ransomware. I am thinking that behind the scenes a file is being encrypted on my machine as part of the expected functionality and causing a false positive with Sohpos. If this is the case, I would appreciate a confirmation that the repo is not compromised and a short explanation of what's getting encrypted on my machine so I can submit it to our IT department. Thank you in advance.

### Reproduction

1.  npm install auth0-spa-js
2. npm run dev
3. Run an authentication process

### auth0-spa-js version

2.1.2

### Which framework are you using (React, Angular, Vue...)?

NextJS

### Framework version

13.4.19

### Which browsers have you tested in?

Chrome, Safari, Firefox

**Comment by ewanharris** [comment]
Hey @R3BLcreative thanks for the issue.

It’s most likely that what’s being flagged is the usage of the crypto APIs in this library ([here](https://github.com/auth0/auth0-spa-js/blob/e8e4f2c1a0f453ab8c6ed34b2e877881305141dd/src/utils.ts#L144-L153) and [here](https://github.com/auth0/auth0-spa-js/blob/e8e4f2c1a0f453ab8c6ed34b2e877881305141dd/src/utils.ts#L171-L176)). This usage is required to ensure we generate secure values for the `state`, `nonce`, `code_verifier`, and `code_challenge` values in the authorization flow.

**Comment by R3BLcreative** [comment]
Thank you for your response! This should satisfy my IT departments reqs.

**Comment by R3BLcreative** [comment]
Marking this closed
