### ISSUE TITLE
How to get a management api access token?

### ISSUE THREAD

**Issue by PapaMufflon** [auth0/auth0-spa-js#115]
I'm trying to get an access token to be able to change some user metadata. This is what I have so far:
```` typescript
async getAuth0Client(): Promise<Auth0Client> {
  if (!this.auth0Client) {
    this.auth0Client = await createAuth0Client(this.config);

    // Provide the current value of isAuthenticated
    this.isAuthenticated.next(await this.auth0Client.isAuthenticated());

    // Whenever isAuthenticated changes, provide the current value of `getUser`
    this.isAuthenticated.subscribe(async isAuthenticated => {
      if (isAuthenticated) {
        this.profile.next(await this.auth0Client.getUser());
        this.backendToken.next(await this.auth0Client.getTokenWithPopup());
        this.managementToken.next(await this.auth0Client.getTokenWithPopup({
          audience: 'https://{project}.{region}.auth0.com/api/v2/',
          scope: 'update:users update:users_app_metadata'
        }));

        return;
      }

      this.profile.next(null);
    });
  }

  return this.auth0Client;
}
````
However, my `managementToken` only contains the usual scopes `openid email profile`, not the ones I explicitly stated.
The `profile` contains the user metadata I set via the auth0-website, but I cannot update it via `this.http.patch(`http://{project}.{region}.auth0.com/api/v2/users/${this.profile.sub}`, this.profile)`.
I also tried to create a second `auth0Client` for the management api, but this mixes up the state when authenticating. Any idea what I'm doing wrong?

**Comment by luisrudge** [comment]
```
this.backendToken.next(await this.auth0Client.getTokenWithPopup());
this.managementToken.next(await this.auth0Client.getTokenWithPopup({
  audience: 'https://{project}.{region}.auth0.com/api/v2/',
  scope: 'update:users update:users_app_metadata'
}));
```

I'm not that well versed with Angular, but I assume both calls will happen at the same time, right?

That particular code won't work for a couple of reasons:

- Your popup will likely be blocked because you can only open a popup when executing code inside a user initiated event handler (like a button click, for example). Your code is trying to open a popup whenever `isAuthenticated` changes to true, so that will fail
- You can't open two popups at the same time

Your best bet is to ask for those tokens once the user clicks on a button or something (example: Click here to do admin action).

**Comment by PapaMufflon** [comment]
In my opinion this has nothing to do with Angular. This uses async/await and rxjs.

Because of the `await` the calls will not happen at the same time. When I use the code with `.getTokenSilently` I get the same result. I get two tokens (one at a time, you can see it in the 'network tab'), but both contain only the standard scopes, not the extra ones I've set. In fact, when I just query the `managementToken` and comment out the code to get the `backendToken` I get also the same result (so no race condition issue).

When I inspect the `managementToken` with `jwt.io`, I see that the audience is set correctly to
````
"aud": [
    "https://jetcalc.eu.auth0.com/api/v2/",
    "https://jetcalc.eu.auth0.com/userinfo"
  ]
````
but the scopes
````
update:users
update:users_app_metadata
````
are missing. Do I have to configure something on the auth0-website to successfully get the scopes back?

**Comment by luisrudge** [comment]
Ah, sorry. I didn’t pay attention to the scopes at first. You can’t ask those scopes from a public SPA (client). This scopes are available only for confidential clients.

**Comment by PapaMufflon** [comment]
Oh, that's a pity. Any reasons why the user shouldn't be able to change
their own metadata on a public SPA?

The alternative is to go through the backend I suppose?

Thanks for the help and the very quick responses!

**Comment by luisrudge** [comment]
https://auth0.com/docs/users/concepts/overview-user-metadata There’s two metadata fields. An authenticated user can modify data in the `user_metadata`, but not in the `app_metadata`.
