### ISSUE TITLE
Angular SSR window.crypto

### ISSUE THREAD

**Issue by oshri** [auth0/auth0-spa-js#1173]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When trying to angular SSR prerender, i get this error
 For security reasons, `window.crypto` is required to run `auth0-spa-js`.

### Reproduction

0. install "@auth0/auth0-angular": "^2.2.1"
1. create empty angular 16 with ssr and add AuthModule
2. run prerender

### auth0-spa-js version

2.0.1

### Which framework are you using (React, Angular, Vue...)?

Angular

### Framework version

16

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Thanks for reaching out, see https://github.com/auth0/auth0-angular/issues/305#issuecomment-1118261182 for a solution.

Long story short is that, as per the angular docs, you want to ensure you avoid using our SDK on the server side and use some kind of mock. And only use our actual SDK in the client.

Closing, if you need any further assistance, please open an issue on auth0-angular.
