### ISSUE TITLE
Import module from browser

### ISSUE THREAD

**Issue by Enelar** [auth0/auth0-spa-js#120]
```
    const clientClass = await import("https://cdn.auth0.com/js/auth0-spa-js/1.0/auth0-spa-js.production.js");
    const client = new clientClass({
        domain: ac.domain,
        client_id: ac.clientId,
        redirect_uri: location.href
      });
```

```
clientClass: Module {Symbol(Symbol.toStringTag): "Module"}
client: undefined
```

`Chrome 75`

tried `clientClass.createAuth0Client()`, `clientClass.client`, `clientClass()`, noting.

I think it's just broken.

**Comment by luisrudge** [comment]
That file is a umd build. You should use the ESM build: `https://cdn.auth0.com/js/auth0-spa-js/1.1/auth0-spa-js.production.esm.js`.

Just as a heads up, I just checked this and our CDN is not sending the necessary CORS headers and mime type for ESM files. I'll investigate this with them, but you can load it via unpkg for now:

```
window.addEventListener('load', async () => {
  const {default: createAuth0Client} = await import("https://unpkg.com/@auth0/auth0-spa-js@1.1.0/dist/auth0-spa-js.production.esm.js");
  
  console.log(createAuth0Client);
});
```
