### ISSUE TITLE
Passing login_hint to loginWithRedirect does not populate email address

### ISSUE THREAD

**Issue by brianagriffith** [auth0/auth0-spa-js#121]
Per the documentation [here](https://auth0.github.io/auth0-spa-js/interfaces/redirectloginoptions.html#login_hint), passing the email address in the login_hint parameter should populate the email address on the login page but that doesn't appear to be working. Below is example code:
```typescript
login(emailAddress: string, redirectPath: string = '/') {
    const opts = {
      redirect_uri: `${window.location.origin}/callback`,
      appState: { target: redirectPath },
      login_hint: emailAddress
    };
    this.auth0Client.subscribe((client: Auth0Client) => {
      client.loginWithRedirect(opts);
    });
  }
```
This code results in a redirect without the email address being passed forward. Am I misunderstanding how this parameter works?

**Comment by luisrudge** [comment]
You'll have to customize the Login Page and use the Lock default template, which does this automatically:

![image](https://user-images.githubusercontent.com/941075/62137173-e1e4af80-b2bb-11e9-9027-1e835e81acdc.png)

The new Universal Login Page experience still doesn't prefill the email field based on `login_hint`.

**Comment by brianagriffith** [comment]
Something is still misbehaving. We are using the classic login page with the Lock default template and the prefill doesn't work. 
If I customize the Lock default template and change the prefill to only include the email address the prefill works.
```json
prefill: loginHint ? { email: loginHint } : null
```

**Comment by luisrudge** [comment]
do you see the login_hint parameter being sent in your chrome dev tools?

**Comment by luisrudge** [comment]
In your universal login page, open your dev tools and type this into the console:

![image](https://user-images.githubusercontent.com/941075/62388984-0b5c4000-b535-11e9-9b18-45df82962a3b.png)

**Comment by brianagriffith** [comment]
We're using the classic login page, not the universal login page. When I look at the network activity, I see the login_hint being sent as a query parameter.

**Comment by luisrudge** [comment]
Then you likely have a misconfiguration in the customization of the ULP. I'd suggest you to reset to the default customization because the default template works correctly

**Comment by aounleonardo** [comment]
@luisrudge  I am using the ULP with the default customization and login_hint is not working for me.

Any idea how can I debug this? if I type config in the devtools of ULP I get undefined :/
