### ISSUE TITLE
Use '.well-known/openid-configuration' to configure Auth0Provider (Auth0Client) calls

### ISSUE THREAD

**Issue by johnny-the-coder** [auth0/auth0-spa-js#1219]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like that Auth0Provider (Auth0Client) would use the configuration specified in {domain}/.well-known/openid-configuration to make calls to auth0 endpoints.

Currently configuring custom endpoints for 'authorize' or 'oauth/token' is impossible. Only the domain is configurable.
https://auth0.github.io/auth0-react/functions/Auth0Provider.html
'.well-known/openid-configuration' is not taken into account.

In my case 'authorize' endpoint is 'oauth2/authorize' and 'oauth/token' is 'ouath2/token'.

### Describe the ideal solution

The ideal solution would be that Auth0Provider could be configured with '.well-known/openid-configuration', e.g:

```
<Auth0Provider
  domain={domain}
  wellKnown={".well-known/openid-configuration"}    <--- this would be new configuration parameter
  clientId={clientId}
  authorizationParams={{ redirect_uri: window.location.origin }}}>
  <MyApp />
</Auth0Provider>
```

Than calls to authorize and token endpoints (and other enpoints as well) would use urls defined in the well-known file:
- authorization_endpoint
- token_endpoint
- other

**Comment by frederikprijck** [comment]
Thanks for reaching out.

> In my case 'authorize' endpoint is 'oauth2/authorize' and 'oauth/token' is 'ouath2/token'.

Are you using Auth0 or some other Identity Provider?

**Comment by johnny-the-coder** [comment]
Hi Frederik,

I guess we can both agree that the library would be much more versatile and useful when it would consider ./well-known/openid-configuration.

I searched in the web and there are people struggling with the exact same problem, e.g.:
https://stackoverflow.com/questions/68187471/why-does-google-use-oauth2-auth-and-auth0-spec-uses-oauth2-authorize

I think it would not make a huge effort to implement the necessary changes.
So why not make a much more powerful open-source library?

**Comment by jan-malkiewicz** [comment]
ok, thanks for the explanation, I will search for other library then.

**Comment by frederikprijck** [comment]
https://github.com/panva/oauth4webapi is probably a good one if u look for an OIDC compliant SDK.

**Comment by johnny-the-coder** [comment]
ok, thanks for the information, I will search for another library then.

**Comment by johnny-the-coder** [comment]
closing for now
