### ISSUE TITLE
Library not returning the scopes granted to user

### ISSUE THREAD

**Issue by raanam** [auth0/auth0-spa-js#122]
I am implementing Authorization in SPA using technique described in - https://auth0.com/docs/architecture-scenarios/spa-api/part-2
But I found that there is no way to retrieve value of "scope" present in the "/token" response. getTokenSilently method is returning access_token only.
Any suggesting to work around this issue.

**Comment by luisrudge** [comment]
There's no scopes returned in the `oauth/token` http call:
![image](https://user-images.githubusercontent.com/941075/62136674-012f0d00-b2bb-11e9-8160-8d0e09abe34c.png)

We had discussion on how to expose the permissions of a token in https://github.com/auth0/auth0-spa-js/issues/48#issuecomment-508181381 and https://github.com/auth0/auth0-spa-js/issues/23#issuecomment-507794605. Let me know if this helps.

**Comment by raanam** [comment]
Hi

If you look at - https://auth0.com/docs/architecture-scenarios/spa-api/part-3 [Section - https://auth0.com/docs/architecture-scenarios/spa-api/part-3], It mentions that authResult.scope will contain the scope granted to user. I have followed the stems mentioned in this article and I get scope value in the response of /token call.

**Comment by luisrudge** [comment]
That tutorial uses https://github.com/auth0/auth0.js. The scope comes back in the authentication result, not in the /token call. Auth0.js doesn't use the /token endpoint at all.

**Comment by luisrudge** [comment]
if the issued scope is equal to the one requested then `oauth/token` is not required to send the scope parameter, but if the scope changes (we can do that through rules) the response must contain the scope parameter.
https://tools.ietf.org/html/rfc6749#section-5.1

We'll add a way to get those scopes

**Comment by saradotramli** [comment]
> 
> 
> if the issued scope is equal to the one requested then `oauth/token` is not required to send the scope parameter, but if the scope changes (we can do that through rules) the response must contain the scope parameter.
> https://tools.ietf.org/html/rfc6749#section-5.1
> 
> We'll add a way to get those scopes

Is there an ETA for this?
