### ISSUE TITLE
Clarify limits for checkSession method

### ISSUE THREAD

**Issue by zfeed** [auth0/auth0-spa-js#1224]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

[auth0.js docs ](https://auth0.com/docs/libraries/auth0js#polling-with-checksession-) describes the polling technique with `checkSession` method. It mentions a 15-minute interval to avoid getting rate limits.

auth0-spa-js has a similar `checkSession` method that doesn't mention this interval.

Both of the methods seem to be using the same API internally, so limits should be the same.

### Describe the ideal solution

It would be nice to clarify this interval recommendation for `checkSession` method.
Also, as it uses `getTokenSilently` internally, clarify limits for  `getTokenSilently` method as well

**Comment by frederikprijck** [comment]
Thanks for reaching out. Can you elaborate what issues you encounter that made you look for this limitation?

`checkSession` works differently in Auth0-SPA-JS to how Auth0.JS works, more specifically we have internal mechanisms to not hit Auth0 when not needed, which are not part of Auth0.js. Therefore, we have no such limitation defined for checkSession in Auth0-SPA-JS, same goes for `getTokenSilently`. 

However, we are ofcourse interested to learn from your use-case that made you look for these limitations.

**Comment by zfeed** [comment]
@frederikprijck thanks for your response!

We want to set a 5-minute inactivity timeout for  [Auth0 session](https://auth0.com/docs/manage-users/sessions/configure-session-lifetime-settings). We use auth0-react (which uses auth0-spa-js internally) in our application.
To keep the session active while the app is open we were looking for methods that can keep the activity of the session. 
We found these two methods `getTokenSilently` and `checkSession` in auth0-spa-js, but also encountered that the auth0.js docs mentioned 15-minutes rate limits.
As auth0-spa-js has a similar method `checkSession`, that uses `getTokenSilently` internally, we got confused about the limits

**Comment by frederikprijck** [comment]
As mentioned, both work differently. With Auth0-SPA-JS having its own cache, and doing less calls to auth0, it makes less sense to consider the same limitations.

Closing, feel free to open another issue if you need further assistance.

**Comment by zfeed** [comment]
Limits do not apply even if I call `getTokenSilently` in auth0-spa-js with `{ cacheMode: off }` options?

**Comment by frederikprijck** [comment]
They do, but limits may vary depending whether or not you use refresh tokens.

However, cacheMode of is something you should need so often it would hit limits. Can you expand on your use case if you think it will hit the limits?

**Comment by zfeed** [comment]
@frederikprijck We have an inactivity session limit for the auth0 session of 5 mins. 
When an SPA application tab is open, we would like to keep the session active. For this purpose, we need to request auth API at least every 5 minutes, so the session remains active. We found only one method to do that, using `getTokenSilently` method. 

But we fear that we can encounter the 15 mins limit (as I said we want to call it each 5 mins). 

*We don't use refresh tokens, we use authentication through an iframe

**Comment by frederikprijck** [comment]
Yeah, if you have an inactivity session limit set to 5 mins, and you want to be able to extend that session, I can see why you want to use `cacheMode: off` every 5 minutes. 

In that case, you would hit the same limit as you'd with Auth0.js, yes. 

To be honest, I am not sure where the 15min limit is coming from on the Auth0.js page you shared, but it most likely also depends on the tier you are using etc. If it would cause issues, I think you want to consider increasing the session time (but that's ofcourse not something I have any say in, just want to mention it)
