### ISSUE TITLE
React Quickstart causing error upon clicking the login button

### ISSUE THREAD

**Issue by charlesanthonyalfonso** [auth0/auth0-spa-js#1243]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I followed the React Quickstart instruction.
Upon reaching in `Add Login to Your Application` section, I can see the button.
however when i click the login button it does not do anything.
and i see a console error

![image](https://github.com/auth0/auth0-spa-js/assets/5631311/e5351b76-1c1c-44d0-a6ae-52e29327fdc3)

### Reproduction

1. follow react quickstart instruction
2. when you already added a login button, try to click that button and the error message appears

### auth0-spa-js version

2.2.4

### Which framework are you using (React, Angular, Vue...)?

Vite with React

### Framework version

Vite@5.0.8 and React@18.2.0

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Can you show your Auth0Provider, including the values passed to it?

From the error, it looks like the domain isnt set correctly.

**Comment by charlesanthonyalfonso** [comment]
Hi @frederikprijck 

This can be closed now, it was my fault i had provided a wrong domain and clientId in the Auth0Provider.
Thank you.
