### ISSUE TITLE
organization option of Auth0Client.getTokenSilently function is unexpectedly reuse previous value

### ISSUE THREAD

**Issue by sndyuk** [auth0/auth0-spa-js#1245]
### Checklist

- [X] The issue can be reproduced in the [auth0-spa-js sample app](https://github.com/auth0-samples/auth0-javascript-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

organization option of Auth0Client.getTokenSilently function is unexpectedly reuse previous value when we specify null to the option.

### Reproduction

1. Specify orgId first

  ```
  client.getTokenSilently({
    cacheMode: 'off'
    authorizationParams: {
      organization: 'org-foobar1' // Please replace the value with actual one
    }
  })
  ```

2. Specify null to the organization option. It calls authorize endpoint with previous orgId `org-foobar1`
  ```
  client.getTokenSilently({
    cacheMode: 'off'
    authorizationParams: {
      organization: null // Any of these value can reproduce the issue: null | undefined | false | ''
    }
  })
  ```

3. When we specify other org, it requests with this new org `org-foobar2`

  ```
  client.getTokenSilently({
    cacheMode: 'off'
    authorizationParams: {
      organization: 'org-foobar2' // Please replace the value with actual one
    }
  })
  ```

### auth0-spa-js version

2.1.3

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
This is intentional, please see our examples at https://github.com/auth0/auth0-spa-js/blob/main/EXAMPLES.md on "Switching organization"

**Comment by frederikprijck** [comment]
`getTokenSilently` accepts any arbitrary arguments, including `organization`. This is because you can send any custom parameter you like to your own Auth0 Actions, so we can not block sending unknown parameters. However, we do not have first-class support for organization at that level, see:

- https://auth0.github.io/auth0-spa-js/interfaces/GetTokenSilentlyOptions.html

While we do have first-class support for organization on loginWith* level, see:

- https://auth0.github.io/auth0-spa-js/interfaces/RedirectLoginOptions.html
