### ISSUE TITLE
Make getTokenSilently Generic

### ISSUE THREAD

**Issue by JANA-itsaishvili** [auth0/auth0-spa-js#1252]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-spa-js#readme), [Examples](https://github.com/auth0/auth0-spa-js/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.com/docs/libraries/auth0-single-page-app-sdk) and [API documentation](https://auth0.github.io/auth0-spa-js/), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-spa-js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am in the middle of implementing the spa-js in our react app, and I'm having a very hard time implementing the overloaded `getTokenSilently` function smoothly. Ideally the callbacks passed down via React Context will match the method signatures on Auth0Client, but I cannot implement this with the overload.

Moreover, auth0-react package doesn't even leverage the verbose option of the auth0-spa-js since it only cares about the token.`

### Describe the ideal solution

Convert getTokenSilently to be a generic function so you can infer the options argument based on the presence of `detailedResponse` .

Alternatively, make `detailedResponse` a part of the `GetTokenSilentlyOptions` and make the return conditional.

 I should be able to pass `getTokenSilently` to React Provider value that references `Auth0Client['getTokenSilently']`. It works for all other methods.

### Alternatives and current workarounds

I have to manually declare this type now, so it's not reactive with package updates.

**Comment by frederikprijck** [comment]
Thanks for reaching out. I am a bit confused about the problem you are having.

> Moreover, auth0-react package doesn't even leverage the verbose option of the auth0-spa-js since it only cares about the token.`

As you can see [here](https://github.com/auth0/auth0-react/blob/main/src/auth0-context.tsx#L54-L62), our react SDK does have the ability to get the verbose option. 

I added auth0-react to a react application and this is what it looks like for me:

![image](https://github.com/auth0/auth0-spa-js/assets/2146903/3464d0d4-e69a-42e2-ab10-4f85f2b1db0e)

![image](https://github.com/auth0/auth0-spa-js/assets/2146903/7a7c62d5-0b00-4637-8a29-65e7b302571f)

This looks as expected, so not sure I understand what issue you are facing.

**Comment by frederikprijck** [comment]
Closing, feel free to provide more information and we can reopen as needed.
