### ISSUE TITLE
auth0-spa-js for multipage app?

### ISSUE THREAD

**Issue by Macok** [auth0/auth0-spa-js#1255]
I want to create an multipage (serverside rendered) app in Python+Flask with auth0 authentication.
There's a Python SDK for such cases, but I believe I still need a javascript on the client side for things like storing and refreshing the auth0 token.
In the official Python SDK example they use HTTP sessions to store the tokens, but I want to avoid HTTP sessions because they don't scale well.

Is there any problem with using auth0 Python SDK in the backend and auth0-spa-js in the frontend, even though my app is not SPA?

**Comment by frederikprijck** [comment]
> In the official Python SDK example they use HTTP sessions to store the tokens, but I want to avoid HTTP sessions because they don't scale well.

I think it's a better solution to rely on cookies and/or sessions when u can, and solve the scaling issue.

> Is there any problem with using auth0 Python SDK in the backend and auth0-spa-js in the frontend, even though my app is not SPA?

When it comes to adding login / logout, It's either one or the other. You can not combine them. 
If you use SPA-JS in the client, you want to validate the tokens on the backend, but there is no need to add an SDK for login/logout.

Long story short, I think you want to use AuthLib, and not our Python or SPA-JS SDK. See our guidance for securing Python Web Apps here: https://auth0.com/docs/quickstart/webapp/python/01-login

**Comment by Macok** [comment]
@frederikprijck 
Thanks for the answer!
I've seen your guide for securing Python Web Apps, but it's relying on HTTP sessions, which I don't want (I want my backend to be stateless).

> If you use SPA-JS in the client, you want to validate the tokens on the backend, but there is no need to add an SDK for login/logout on the server side in that case..

I understand that. The idea is to use SPA-JS in the client for login/logout/registration/token refreshing, and then Python SDK in the backend for token validation. Is this not a valid approach?

I don't understand why you are recommending AuthLib. AuthLib is a Python library, so maybe I could use it for validating tokens in the backend, but I don't think it will help me with the client-side tasks?

Thanks!

**Comment by frederikprijck** [comment]
> I've seen your guide for securing Python Web Apps, but it's relying on HTTP sessions, which I don't want (I want my backend to be stateless).

There may be ways to implement it stateless. I am not familiar with Python, but I know other server side technologies allow you to go stateful or stateless when it comes to authentication.

> I understand that. The idea is to use SPA-JS in the client for login/logout/registration/token refreshing, and then Python SDK in the backend for token validation. Is this not a valid approach?

That is a perfectly valid approach, but it was not clear from your initial comment, sorry about that. In that case, you want https://auth0.com/docs/quickstart/backend/python, which is still using Authlib.

> I don't understand why you are recommending AuthLib. AuthLib is a Python library, so maybe I could use it for validating tokens in the backend, but I don't think it will help me with the client-side tasks?

Correct, it wont help you in the client side, but it does allow you to either do the authentication on the server, or validate tokens on the server while managing the tokens on the client using Auth0-SPA-JS.
