### ISSUE TITLE
Best practice for multiple API calls in app

### ISSUE THREAD

**Issue by gnarj** [auth0/auth0-spa-js#127]
Is it best practice to call the getTokenSliently method every time the app needs to make a call to a private endpoint or does it make more sense to call it once when the user is authenticated and call it again whenever the token expires? I apologize in advance if this has been answered.

**Comment by luisrudge** [comment]
We recommend calling `getTokenSliently` since we manage the lifecycle of the token for you. You don't need to worry if the token is expired or not.

**Comment by kershnerd** [comment]
Sorry to hijack this thread, but is the same true if we are calling an API every second?  

I thought getTokenSilently() would just reuse the access_token it already has as it is still valid, but it appears to always connect to Auth0 and get a new access_token.

**Comment by stevehobbsdev** [comment]
@kershnerd It should indeed use the token it already has from it's in-memory cache:

https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L301

* Does your audience or scope change between calls to the API?
* Are you able to refresh the page and still be logged in?
