### ISSUE TITLE
Default popup login state

### ISSUE THREAD

**Issue by Enngage** [auth0/auth0-spa-js#131]
Hey,

is it possible to set the context of popup to be either **login** or **signup**?  Currently it always defaults to login which means that if have a register button and expect users to create new accounts they first need to click on the "Sign up" button at the bottom.

**Comment by luisrudge** [comment]
If you use the classic Universal Login experience, you can customize the template to have this behavior (explained here: https://community.auth0.com/t/how-to-open-login-signup-on-the-universal-login-hosted-page/12642/7).

If you use the new Universal Login experience, then this is not available right now. We're evaluating adding this feature as well, but there's no ETA.
