### ISSUE TITLE
Typescript error returning Auth0Context.Provider while following getting started guide

### ISSUE THREAD

**Issue by fandy** [auth0/auth0-spa-js#135]
While following the [Auth0 docs](https://auth0.com/docs/quickstart/spa/react/01-login?download=true#install-the-auth0-react-wrapper) on getting started for our Next.js SPA, I converting it to TypeScript and got this error:

```
    return (<exports.Auth0Context.Provider value={{
            ^

SyntaxError: Unexpected token <
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Module.m._compile (/Users/fang/choice-kittens/node_modules/ts-node/src/index.ts:414:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.require.extensions.(anonymous function) [as .tsx] (/Users/fang/choice-kittens/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

## [auth0.tsx Gist](https://gist.github.com/fandy/b938eef02def1f83d374c0c1aa4af744)

Things I've tried:
* [I looked through issues and couldn't find a working TypeScript example](https://github.com/auth0/auth0-spa-js/issues/36)
* [Seems unrelated to the other default import TypeScript issue, since I do have `    "esModuleInterop": true`](https://github.com/auth0/auth0-spa-js/issues/60)

@luisrudge would you have any idea what's happening here? 🙏

**Comment by luisrudge** [comment]
wow, that's very weird! I have no idea why you're getting that error. In fact, I have a version of that wrapper in typescript if you want to take a look at. Maybe nextjs is messing up with the compilation? I'd try with create-react-app first just to see if it works as expected.

Here's my ts version of the wrapper (non official, still wip): https://gist.github.com/luisrudge/28e591869dcdee10afdfd878bf20b006

**Comment by fandy** [comment]
Hi @luisrudge, I think I've isolated the problem to `tsconfig.json`. Do you mind posting your config so I can compare and see?

**Comment by luisrudge** [comment]
I think it's the default created by `create-react-app --typescript`

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src"
  ]
}
```

**Comment by fandy** [comment]
Ah, turns out I placed the file in another directory that was SSR, which had different `tsconfig` rules.
