### ISSUE TITLE
Logout and multiple instances of an application

### ISSUE THREAD

**Issue by tomgranerod** [auth0/auth0-spa-js#136]
If I'm running an application in multiple tabs, then logout from one of them, it seems I'm still able to retrieve a non-expired access_token through getTokenSilently in another tab.

Should there be a check in getTokenSilently that checks if the "auth0.is.authenticated" stored in cookies is still truthy before returning the access_token? I guess that would solve my problem, as this property seems to be removed from cookies when logging out.

**Comment by luisrudge** [comment]
That might work, yes. We could sync between tabs as well (that's a good improvement), but it's not fault proof, right? None of this would work if you have the sdk running in multiple browsers or even running in normal and incognito mode. I still think syncing between tabs is still a good improvement. I'll add this to our internal backlog so we can tackle this in the near future.

**Comment by tomgranerod** [comment]
Thanks for the quick reply. No, it's definitely not fault proof, but as you say, it would be an improvement if it could be synced across tabs at least. Guess one option still, is to use the ignoreCache option, but then again I don't really want to request a new token for every request that we do.

**Comment by sayanthk-perfagents** [comment]
Is there any update on this ? I am also facing the same issue.

**Comment by andreasvirkus** [comment]
Also showing interest in this 🙏
