### ISSUE TITLE
loginWithRedirect not using redirect_uri from Auth0Client

### ISSUE THREAD

**Issue by whynotavailable** [auth0/auth0-spa-js#143]
Is there a reason that loginWithRedirect does not simply use the redirect_uri value from the client?

Can the value be optional for loginWithRedirect, using the client version if not given in the method?

**Comment by luisrudge** [comment]
`redirect_url` is optional in the `loginWithRedirect`. If you send `redirect_url` in the `createAuth0CLient`call and nowhere else, that will work as well.
