### ISSUE TITLE
Issues with iOS 10.3.3

### ISSUE THREAD

**Issue by sardah** [auth0/auth0-spa-js#144]
Hi,

I've got a working implementation using promises.  Paid account and custom domain.

Works fine on desktop and iOS 11 & 12.

loginWithRedirect is failing for me on iOS 10.3.3

loginWithPopup brings up a blank popup.

Has anybody confirmed this works on iOS 10.3

Thanks.

**Comment by luisrudge** [comment]
What's the error?

**Comment by sardah** [comment]
No error message - it just fails to bring up the auth0 login interface using loginWithRedirect on iOS 10.3.3

I also tried loginWithPopup and this just brings up a blank page.

CreateAuth0Client is returning a valid object.  Just can't get the auth0 login interface to appear using loginWithRedirect or loginWithPopup on iOS 10.3.3

Same code is working fine on iOS 11 & 12 and desktop.

Any ideas?

**Comment by luisrudge** [comment]
@sardah are you using the classic Universal Login Experience or the new one?

**Comment by sardah** [comment]
I've tried both - same experience.

**Comment by luisrudge** [comment]
when you use the loginWithRedirect, are you at least redirected to your tenant's page?

**Comment by sardah** [comment]
No - not on iOS 10.3.3.

No action at all.  Works fine on later iOS versions.

Have you successfully tested on iOS 10.3.3 ?

**Comment by luisrudge** [comment]
ahhhhh! ahahah. Sorry! I misread the version all the times. You're talking about 10.3, not 13 😝 Sorry!
I think the issue with 10.3 is that it doesn't support `crypto.subtle`. Can you test adding a polyfill for that and see if it works? https://github.com/vibornoff/webcrypto-shim

**Comment by sardah** [comment]
Worked great!

Thanks for your help Luis.
