### ISSUE TITLE
Method for raw ID token

### ISSUE THREAD

**Issue by emsearcy** [auth0/auth0-spa-js#145]
We have code migrating to the PKCE flow for which we would need to pass/leverage the raw ID Token (JWT).

Is there a way to get -- or could a method be added to get -- the user's raw id_token JWT, as returned by the oauth/token endpoint?

**Comment by luisrudge** [comment]
duplicate of https://github.com/auth0/auth0-spa-js/pull/54#issuecomment-509956271

Would you mind sharing your use case so we can add it to our internal discussion? If you don't to share it publicly, send me an email luis.rudge@auth0.com

Thanks!

**Comment by emsearcy** [comment]
I agree with your best practices rationale — I just didn't search closed tickets before I opened this.
