### ISSUE TITLE
Can you set a scope to getUser ?

### ISSUE THREAD

**Issue by vouill** [auth0/auth0-spa-js#147]
Hello!
Nice work on the package, really cool to work with.

I manage to getUser correctly and so on yet i would like to get its meta data.

In order to do that i try to update the scope of the user request yet i do not seem to change it from it's default value.

How would i update the scope of the user info request?

Cheers

**Comment by luisrudge** [comment]
Here's everything you need to know about how to add custom claims to your token: https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims. If you need to send a custom scope, you can add the scope in the `createAuth0Client` call.

```
createAuth0Client({
  domain: '',
  client_id: '',
  scope: 'read:todos' //example
})
```

**Comment by vouill** [comment]
Thanks for the response!

I am trying to implement it yet trying it i  feel like it may not work as intented.

```js
const auth0 = await createAuth0Client({
            domain: 'xxxx.auth0.com',
            client_id: x',xxx
            audience: 'http://localhost:1337',
            redirect_uri: window.location.origin,
            scope: 'email',
        });
```

Even with this after doing `auth0.getUser()` i get this info:

```
{
aud: "xxx"
email: "xxx@gmail.com"
email_verified: false
exp: 1565399459
iat: 1565363459
iss: "https://xxx.auth0.com/"
name: "xxx@gmail.com"
nickname: "xxxd"
nonce: "xxxx"
picture: "https://s.gravatar.com/avatar/xxxx?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fvo.png"
sub: "auth0|xxx"
updated_at: "2019-08-09T15:10:58.913Z"
}
```

By setting the scope to email shouldn't i just get email related informations ?

**Comment by luisrudge** [comment]
but you're getting the email back.. what's the issue?

**Comment by vouill** [comment]
Alright i'll try to be clearer here :)

As i you know i want to get app_metadata from the user i am calling `getUser()` on.

Thanks to your recommendations i actually tried to do this:

```
const auth0 = await createAuth0Client({
            domain: 'xx',
            client_id: 'xxx',
            audience: 'http://localhost:1337',
            redirect_uri: window.location.origin,
            scope: 'http://localhost:3000/app_metadata',
        });
```

I felt like i maybe wasn't using setting the custom claim correctly. 
I then tried to use a standard claim in order to make sure i understood correctly using `email` like such.

```js
const auth0 = await createAuth0Client({
            domain: 'xxxx.auth0.com',
            client_id: x',xxx
            audience: 'http://localhost:1337',
            redirect_uri: window.location.origin,
            scope: 'email',
        });
```

Yet i still had the same answer in every case, this one: 

 
```json
{
aud: "xxx"
email: "xxx@gmail.com"
email_verified: false
exp: 1565399459
iat: 1565363459
iss: "https://xxx.auth0.com/"
name: "xxx@gmail.com"
nickname: "xxxd"
nonce: "xxxx"
picture: "https://s.gravatar.com/avatar/xxxx?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fvo.png"
sub: "auth0|xxx"
updated_at: "2019-08-09T15:10:58.913Z"
}
```

Hence my question as i felt as even when using a standard claim in the scope the response was still the same. I was wondering if it was expected?

Thanks for your help!

**Comment by luisrudge** [comment]
You have to add a custom rule, add the properties you want back in the token and it will get returned in the `getUser` method. It's all explained in the doc I sent you: https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims See how it loads data from `user_medata`. You'll do the same thing, but using `app_metadata` instead

**Comment by vouill** [comment]
Ohhhhh alright now i got it thanks a lot!

Sorry for the inconvenience have a nice day!
