### ISSUE TITLE
id_token was issued in the future (invalid iat)

### ISSUE THREAD

**Issue by izzmeifter** [auth0/auth0-spa-js#153]
We're seeing an increasing number of the above error since switching to this library.

The error is sent from Auth0Client._verifyIdToken.

Does anyone have any insight into troubleshooting this? I don't think this is a configuration issue on our end as for the most part, it's random issue, generally on win7 and win8 machines.

Kind regards,

**Comment by izzmeifter** [comment]
Looking into this more, I'm guessing this could happen simply from a system time being set incorrectly.  Is there a recommended way to tell clients to set their clocks to sync with the token generating server?

Thanks.

**Comment by luisrudge** [comment]
There's no way to know that unless you do it yourself by getting the current client time + your server time and doing a comparison. We have a 60s leeway to prevent small differences, but you can increase that value if you want: https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#leeway - anything up to 5min should be fine.

**Comment by redixhumayun** [comment]
Just commenting in to add that adding a leeway fixed my issue as well with a clients Windows 7 desktop. 

Out of curiosity, what causes the system time to differ from the token generation server time? The time zone on the desktop computer was also set to IST +05:30, however I did notice that the time on this particular system was off by a minute.

**Comment by giocodes** [comment]
In case someone in the future finds it useful:
I was getting the error:
`RPError: id_token issued in the future`

The fix came form using the `clockTolerance` option of `initAuth0`
https://github.com/auth0/nextjs-auth0#runtime-configuration
