### ISSUE TITLE
Export Auth0Client typing

### ISSUE THREAD

**Issue by jcmoore0** [auth0/auth0-spa-js#157]
Hi Auth Team - I would like to be able to import the Auth0Client like this (standard practice)
```
import createAuth0Client, { Auth0Client } from '@auth0/auth0-spa-js';
```
Would you please add to src/index.d.ts?
```
export { Auth0Client} 
```
Auth0Client is imported but not exported in src/index.d.ts.
Thanks for the help.

**Comment by luisrudge** [comment]
closing for this reason: https://github.com/auth0/auth0-spa-js/pull/159#issuecomment-522601580
