### ISSUE TITLE
window.location.assign vs window.location.replace

### ISSUE THREAD

**Issue by malliapi** [auth0/auth0-spa-js#158]
I see that there is no option to allow for the user to replace the location rather than assign it. This creates issues with the browser back button and relogin. Would a replace option be possible?

**Comment by luisrudge** [comment]
What issue?

**Comment by malliapi** [comment]
pressing the browser back button will obviously take you back to the hosted login page, which is now unable to login again and takes you to a generic error page. Do you have any ideas on how to tackle this?

**Comment by malliapi** [comment]
We have tried doing a check session on the login page but would ideally like to skip it entirely.

**Comment by luisrudge** [comment]
So, you're talking about the redirect from the Universal Login Page to your app, right? Not the redirect **to** the Login Page. We don't control what the ULP does, so we can't change that behavior. We do have a new option in the dashboard that fixes some of the problems encountered when users go directly to the ULP. See if this helps: https://auth0.com/docs/universal-login/default-login-url
