### ISSUE TITLE
Support for auto_login

### ISSUE THREAD

**Issue by benlester** [auth0/auth0-spa-js#169]
Is there any support for `auto_login` as outlined here: https://auth0.com/rules/email-verified

We have an SPA where users can register - we enforce email verification so after registration we don't want automatic sign in to be enabled.

**Comment by luisrudge** [comment]
You can send any parameters you want to the Universal Login Page. If you send `auto_login`, you can customize the ULP to use the `loginAfterSignup` param if you're using Lock. This won't work with the new ULP though.

**Comment by benlester** [comment]
I'm afraid I'm still a bit confused - how would you pass auto_login to ULP? A simple MWE would be greatly appreciated. Thanks.

**Comment by luisrudge** [comment]
Sorry! My bad for not providing an example.

Any parameter you use in the login methods will be forwarded to the ULP, so you can do:

```
auth0.loginWithRedirect({
  auto_login: true
})
```

And then, in the Classic ULP, you can customize the template to use the `loginAfterSignup` option:

```
var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
  // other options
  loginAfterSignup: config.auto_login
});
```

**Comment by benlester** [comment]
I see! I didn't know you could pass ULP arguments into `loginWithRedirect` - perhaps I've overlooked it in the documentation - but if not it should be added I'm sure it would help many.

**Comment by benlester** [comment]
Interestingly - I pass `auto_login` false to the `loginWithRedirect` (it appears in the URL) it doesn't seem to function as expected. After signing up it proceeds to attempt to log the user in.

**Comment by luisrudge** [comment]
did you customize the ULP template?
