### ISSUE TITLE
Add support for redirect with window.replace instead of window.assign

### ISSUE THREAD

**Issue by cxcorp** [auth0/auth0-spa-js#183]
We're dealing with protected routes in the classic way of having an auth check in a custom Route component (using e.g. react-router). When a visitor who's not logged in attempts to access such a page, `loginWithRedirect` is called and he gets redirected to Auth0's login screen.

However, if the visitor is not a user but only peeking at the site, he will at this point attempt to click Back to return to the previous content. This will take him back to the route which is, in fact, protected, and as such, he gets redirected straight back to Auth0. So, going back from the login screen is more difficult than it should be, and the visitor will probably close the site and bounce.

We played with the idea of having the links themselves do the auth check so that the user doesn't get into an endless loop of `loginWithRedirect`, but I feel that it would be more pragmatic to be able to pass a parameter to the function which would use `window.location.replace` instead of `window.location.assign`. This way, the protected page isn't in the user's history and as such he will go Back to the content he was viewing as expected.

https://github.com/auth0/auth0-spa-js/blob/acf6c8e002f9cd50003e8070a8f1db4e946ee7ce/src/Auth0Client.ts#L220

I think this feature could be as simple as:

```diff
diff --git a/src/Auth0Client.ts b/src/Auth0Client.ts
index b21dd25..32e8959 100644
--- a/src/Auth0Client.ts
+++ b/src/Auth0Client.ts
@@ -196,7 +196,12 @@ export default class Auth0Client {
    * @param options
    */
   public async loginWithRedirect(options: RedirectLoginOptions = {}) {
-    const { redirect_uri, appState, ...authorizeOptions } = options;
+    const {
+      redirect_uri,
+      appState,
+      redirectMethod,
+      ...authorizeOptions
+    } = options;
     const stateIn = encodeState(createRandomString());
     const nonceIn = createRandomString();
     const code_verifier = createRandomString();
@@ -217,7 +222,7 @@ export default class Auth0Client {
       scope: params.scope,
       audience: params.audience || 'default'
     });
-    window.location.assign(url);
+    window.location[redirectMethod || 'assign'](url);
   }
 
   /**
diff --git a/src/global.ts b/src/global.ts
index 6360ac0..ca5ce9c 100644
--- a/src/global.ts
+++ b/src/global.ts
@@ -113,6 +113,8 @@ interface RedirectLoginOptions extends BaseLoginOptions {
    * Used to store state before doing the redirect
    */
   appState?: any;
+
+  redirectMethod?: 'replace' | 'assign';
 }
 
 interface RedirectLoginResult {
```

**Comment by stevehobbsdev** [comment]
Hi @cxcorp, this looks like a good addition. I think as long as it continues to default to `.assign` so as not to introduce a breaking change, we could bring this in. 

Would you mind raising a PR with the changes where we can discuss the implementation further? We would also need some unit tests around this and documentation added.

**Comment by cxcorp** [comment]
Hey @stevehobbsdev, thanks for the green light! Unfortunately, I do not have the time to work on this right now, as I've moved to working on a different project which does not utilize Auth0's technologies.

**Comment by stevehobbsdev** [comment]
@cxcorp No worries! Will close for now but if this functionality is useful for anyone else, feel free to raise a PR.

**Comment by slaywell** [comment]
FYI I have submitted a PR for this here:

https://github.com/auth0/auth0-spa-js/pull/717
