### ISSUE TITLE
getTokenSilently()  using fetch() instead of iframes?

### ISSUE THREAD

**Issue by joberdick** [auth0/auth0-spa-js#187]
I am aware that the latest version of Safari does not support cross-domain cookies for iframes. Per your docs here: https://auth0.com/docs/api-auth/token-renewal-in-safari

Is there a reason that silent tokens can not be used via fetch() with the credentials: 'include' option?

Ref: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Sending_a_request_with_credentials_included

I believe this will solve the iframe issue and potentially remove the need for iframes all together. I could be missing something though.

**Comment by luisrudge** [comment]
Not right now, because we use the [`response mode web message`](https://tools.ietf.org/html/draft-sakimura-oauth-wmrm-00) spec to get the token. We're doing some internal work to add support for refresh tokens in SPAs. When our server supports it, we'll move to a traditional fetch.
