### ISSUE TITLE
'Invalid algorithm' when signing up/logging in with a Google account

### ISSUE THREAD

**Issue by phyreman** [auth0/auth0-spa-js#198]
When attempting to sign up a test user using a Google account via auth0.loginWithPopup() I get the following error:

jwt.ts:65 Uncaught (in promise) Error: Invalid algorithm
    at ee (jwt.ts:65)
    at oe._verifyIdToken (Auth0Client.ts:76)
    at oe.<anonymous> (Auth0Client.ts:131)
    at Generator.next (<anonymous>)
    at a (tslib.es6.js:68)
ee @ jwt.ts:65
_verifyIdToken @ Auth0Client.ts:76
(anonymous) @ Auth0Client.ts:131
a @ tslib.es6.js:68
async function (async)
login @ (index):274

which the login function mentioned is the following call:

`auth0 = await createAuth0Client({...});`

**Comment by phyreman** [comment]
After a while in the debugger, I figured out that the JWT from Google uses the HS256 header.alg instead of the expected RS256.

**Comment by phyreman** [comment]
The problem was on my end. Apologies for not checking the FAQ sooner, as it had the fix I needed.

**Comment by luisrudge** [comment]
@phyreman sorry! I saw your issue and forgot to answer! I'm glad you found our FAQ though! 🎉
