### ISSUE TITLE
Login problems on refresh

### ISSUE THREAD

**Issue by rajarameshvarma** [auth0/auth0-spa-js#202]
I am trying to setup auth for my react app using auth0-spa-js. I am following the [quickstart](https://auth0.com/docs/quickstart/spa/react) and everything see to be working except if I refresh the browser.

If I refresh the browser, the process it stuck in the initAuth0 (refer to the wrapper class in the quickstart). 

`    const initAuth0 = async () => {
      console.log("creating client");
      const auth0FromHook = await createAuth0Client(initOptions);
      console.log("Done creating client");
      setAuth0(auth0FromHook);
`

Process is stuck between those two console statements for almost a minute and after that it sets the state to unauthenticated.

**Comment by stevehobbsdev** [comment]
Hi @rajarameshvarma,

See the [Why does the Auth0Client object take a long time to initialize?](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-does-the-auth0client-object-take-a-long-time-to-initialize) FAQ item. When refreshing the browser, the *Allowed Web Origins* setting in your Auth0 app is particularly relevant. Have you set this to an appropriate value for your app?

**Comment by rajarameshvarma** [comment]
@stevehobbsdev This helped. Now the refresh is quick but it does not recognize that the user is already logged in. I see this on stackoverflow with no answer https://stackoverflow.com/questions/54572846/why-is-auth0-failing-with-a-failed-silent-auth

**Comment by stevehobbsdev** [comment]
@rajarameshvarma Can you have a look at [this comment on a different issue](https://github.com/auth0/auth0-spa-js/issues/189#issuecomment-528283531) and see if it helps? Also, do you have multi-factor authentication turned on?

**Comment by rajarameshvarma** [comment]
Thank you, it is working
