### ISSUE TITLE
Invalid State on GetTokenSilently

### ISSUE THREAD

**Issue by CHAZTATS** [auth0/auth0-spa-js#203]
Hey all.
Working on an Angular app implementing the new library. version 1.2.3.
Using the exact same auth service file from the samples.
I have an interceptor calling getTokenSilently.
My early http call is to get my users permission from the server.
However this intermittently will throw an "Invalid State" error.
It happens after login more often than not.
Assuming this is a race condition, but wondered if anyone has seen anything similar or knows a fix.

Thanks

**Comment by taylorbryant** [comment]
@CHAZTATS, how'd you fix this issue?
