### ISSUE TITLE
IE 11 Cookie issue?

### ISSUE THREAD

**Issue by ed-sparkes** [auth0/auth0-spa-js#205]
Hi, 

I have followed the quickstart and have the spa flow working well in Chrome etc. however i am experiencing ongoing issues with IE11, the polyfills have allowed the code to run but it appears there is an issue with auth0 cookies. 
If i look at the network traffic in Chrome the call to /authorize in chrome appears to have an auth0 cookie and responsds with an auth0 cookie, this helps to keep the session alive between page refreshes. In IE, this cookie doesnt appear to exists and the only cookie being sent is one called `did`

Appreciate this might not be an issue with the library but any thougths welcome

**Comment by ed-sparkes** [comment]
ahh crap, had protected mode on in IE

**Comment by ed-sparkes** [comment]
ahh crap, had protected mode on in IE

**Comment by stevehobbsdev** [comment]
@ed-sparkes Glad you got it sorted!
