### ISSUE TITLE
getTokenSilently fails with login_required on refresh in Safari

### ISSUE THREAD

**Issue by bijoutrouvaille** [auth0/auth0-spa-js#207]
`getTokenSilently` fails on both desktop and mobile Safari with this error after page refresh with user/password or Google social login:

`[Log] {error: "login_required", error_description: "Login required", state: "..."}`

Settings enabled:
1. The "New" Universal login.
2. Real Google provider keys (as described here https://auth0.com/docs/connections/social/google)
3. scope='openid'

Steps:
1. Login using `loginWithRedirect` and either user/pass or Google
2. Refresh the page.

Expected: `getTokenSilently` obtains the token.
Actual: `login_required` error is generated.

Chrome and Firefox do not experience this issue.

**Comment by bijoutrouvaille** [comment]
Signing in again, skips the Auth0 login screen and redirects immediately to the authenticated app, where `getTokenSilently` retrieves the token without errors.

**Comment by bijoutrouvaille** [comment]
The same issue with the Brave browser.

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. More likely, your app is being targeted by Safari's ITP and whatever Brave uses to block 3rd party cookies as well. Are you using custom domains? We have a nice write up about this issue here: https://auth0.com/docs/api-auth/token-renewal-in-safari

**Comment by bijoutrouvaille** [comment]
May I ask why your library doesn't save it in localStorage? Is it impossible or is there a security implication?

**Comment by stevehobbsdev** [comment]
@bijoutrouvaille It's not impossible, it's just against security guidance. Local storage is susceptible to XSS attacks, which makes not an ideal place to store tokens.

[Here's a short Community thread](https://community.auth0.com/t/why-is-storing-tokens-in-memory-recommended/17742) which explains the reasoning.

**Comment by dg92** [comment]
@bijoutrouvaille i am facing the same issues are yours, did you get it fixed?

**Comment by bijoutrouvaille** [comment]
@dg92 the replies to my comments didn’t leave much wiggle room. Disabling third party cookie blocking in client’s browser worked.

**Comment by dg92** [comment]
@dg92 how did you disable 3rd party cookie on user safari?

**Comment by bijoutrouvaille** [comment]
@dg92 don’t remember anymore. It’s in the settings somewhere.
