### ISSUE TITLE
Unable to refresh page with active Auth0 session

### ISSUE THREAD

**Issue by Greenbones** [auth0/auth0-spa-js#209]
I am using the SDK in an Angular application (having followed the tutorial on the Auth0 website). I have the following code that runs on load:

```
return this.authService.isAuthenticated$.pipe(
  tap(loggedIn => {
    if (!loggedIn) {
      this.authService.login(state.url);
    }
  })
);
```
Basically calls isAuthenticated on the client and if there is no active session locally call login.

This works fine locally against localhost. The first time I navigate to the site, I get the log in dialog. After signing in, I can log out and back in successfully. If I reload the page, I get redirected to Auth0 to refresh my session, but I do not see a login dialog. I end up back at my callback handler and the local session is initialized successfully.

I am working on getting my app working in production now and I am finding that I hit errors. When I initially navigate to the page, everything is fine. I get a login dialog, log in and am redirected back to my app's callback handler. I can log out and back in without issues.

However when I reload the page, the code above detects that there is no local session and calls login. This results in a call to /authorize in Auth0 and this call fails with a 400 error. The logs in Auth0 indicate that the request failed because my redirect_uri origin is not registered. It clearly is registered though, since I was able to log in in the first place with the same redirect_uri. In either case, I have specifically confirmed that the redirect uri from the authorize request is in my registered origins.

Once I am in this bad state, calling logout has no effect and I cannot use the app again until I clear my cookies and reload it. I then get a login dialog again and can access the app, until I reload it.

One additional note, my app does an auto refresh of its data periodically and if I just let it sit after the failed /authorize call, it will eventually attempt an HTTP call against my backend, which triggers a call to getTokenSilently. This works, returns a token and I am then able to retrieve data from my backend.

The only material difference between running locally and in prod is that I am using localhost:4200 locally and an https subdomain (https://subdomain.site.com/route/callback) in prod. It seems like the Auth0 backend still knows I'm logged in because the eventual getTokenSilently call succeeds, but I am at a loss as to why calling /authorize is failing.

I appreciate that this may not be an issue in the SDK, but it is resulting from its calls and I'm not really sure where else to ask. 

Thanks,
Jeff

**Comment by consolenaut** [comment]
Just ran into exactly the same issue

**Comment by Greenbones** [comment]
So it turns out this was actually an issue with my Allowed Web Origins in my SPA config. In my case, it was because I had a trailing slash on the origin for my production app. This isn't allowed. 

Figured it out with help from Auth0 support, I'm not sure I ever would have gotten there from the error message though.

**Comment by stevehobbsdev** [comment]
Glad you got it sorted, @Greenbones!
