### ISSUE TITLE
Using with Custom Domains

### ISSUE THREAD

**Issue by BrianSHenderson** [auth0/auth0-spa-js#211]
Has anyone managed to get the component to work with custom domains?  The documentation doesn't seem very clear here.  Does anyone have examples?

Thanks

**Comment by luisrudge** [comment]
You can use your custom domain here: https://github.com/auth0/auth0-spa-js#creating-the-client

```
const auth0 = await createAuth0Client({
  domain: 'auth.myapp.com',
  client_id: '<AUTH0_CLIENT_ID>',
  redirect_uri: '<MY_CALLBACK_URL>'
});
```
