### ISSUE TITLE
Support for IdP-Initiated Single Sign-On

### ISSUE THREAD

**Issue by iacoshoria** [auth0/auth0-spa-js#213]
As per the official documentation [here](https://auth0.com/docs/protocols/saml/idp-initiated-sso), is there any support for the IDP initiated SSO?

Or is this already supported within the constructor?

> If you are using Auth0.js, you have to update the webAuth.parseHash of the library and set the flag __enableIdPInitiatedLogin to true.
> ```javascript
> var data = webAuth.parseHash(
>   {
>     ...
>     __enableIdPInitiatedLogin: true
>     ...
>   }
> ```
> If you're using Lock, you can include the flag using the options parameter sent to the constructor.
> ```javascript
> const options = {
>     _enableIdPInitiatedLogin: true
> };
> const lock = new Auth0Lock(clientID, domain, options)
> ```
> Note that the enableIdPInitiatedLogin flag is preceded by one underscore when used with Lock and two underscores when used with the auth0.js library.

**Comment by luisrudge** [comment]
Because of the [risks](https://auth0.com/docs/protocols/saml/idp-initiated-sso#risks-of-using-an-idp-initiated-sso-flow), there's no plan to add support to IdP initiated SSO yet. We might revisit in the future, though. For now, I added this into our internal backlog to give some more thought.

**Comment by x3haloed** [comment]
I would like to add a factor to the discussion here. The way this is showing up as an issue for me is that we have SAML SSO customers with Okta who want to be able to access our software (SP) directly from their dashboard (idP). So unless I'm missing something, we don't really have any options right now except to tell our customers that dashboard access is not available due to the security risks. Is that correct? Do you have any other suggestions, @luisrudge?

**Comment by amiluttwak** [comment]
This is a major gap for us, our customers expect us to support IdP initiated flow, I would urge you to reconsider and hopefully provide a timeline for a fix.

**Comment by oneillsp96** [comment]
We also need to support this feature, at least short term. Has there been any movement on this?

**Comment by andrewrmiller** [comment]
I just worked with Auth0 support to get this working.  It looks something like this:

1. Enable IdP initiated in your enterprise connection (Accept Requests on the IdP Initiated tab)
2. In the Query String parameter on the same tab, use `https://YOUR_CALLBACK_URL?connection=YOUR_CONNECTION_NAME`.
3. In your callback page where you  normally call auth0-spa-js's `handleRedirectCallback`, check for a `state` parameter.  If it is *not* present, you are dealing with IdP initiated.  Grab the `connection` value from the query string and feed it to `loginWithRedirect`.

Seems to be working for me...

**Comment by oneillsp96** [comment]
@andrewrmiller that makes sense except the last step. How do you feed the connection to loginWithRedirect, I don’t think loginWithRedirect takes “connection” as a parameter?

Are you sure this actually works, and it’s not just that your user already has an auth0 session+tokens when the idp launcher sends you to the app? For example does it still work if you clear cookies and localstorage and then launch your app from idp-initiated?

**Comment by andrewrmiller** [comment]
```
            // If there is no state param, this is an IdP initiated log in.  Redirect
            // to Auth0 to get the token.
            this.auth0.loginWithRedirect({
              redirect_uri: this.redirectUri,
              connection: params.connection as string
            });
```

**Comment by andrewrmiller** [comment]
> 

Looking for missing state is as per Auth0 tech support.  Guess you could probably look for `connection` in the qs as well.
