### ISSUE TITLE
Use with custom self-hosted login form

### ISSUE THREAD

**Issue by daanporon** [auth0/auth0-spa-js#214]
Is it possible to use the 'Authorization Code Flow with PKCE' using a custom self-hosted login form where i just call a login function with the username and password (just as in the Auth0.js SDK)? As far as i can see this only works with Universal Login, but maybe i'm missing something. 

Right now i integrated the regular 'Authorization Code Flow' in this way using the Auth0.js SDK but there is no option to pass in a code_challenge when logging in.

Any help?

Thanks,
Daan

**Comment by luisrudge** [comment]
You can still use Lock or Auth0.js to authenticate users by using the implicit flow. Support for Embedded login with PKCE is on our roadmap, but there's no ETAs yet.

**Comment by nicbavetta** [comment]
> You can still use Lock or Auth0.js to authenticate users by using the implicit flow. Support for Embedded login with PKCE is on our roadmap, but there's no ETAs yet.

Can you point us towards some documentation or examples for using auth0-js and auth0-spa-js side by side in the same solution? We'd like to implement custom login/signup pages in our application but are having issues doing so with both libraries in the same project. We'd still like to leverage auth0-spa-js for token management if possible.

**Comment by osdiab** [comment]
I am interested in switching over to `auth0-spa-js` because `auth0-js`'s bundle size is enormous, but we use Embedded Login so it seems we wouldn't be able to.

@luisrudge any chance this has been added to a roadmap internally to `auth0`?

**Comment by stevehobbsdev** [comment]
@osdiab I'm afraid to say we do not have any plans to add embedded login support to this SDK as yet.

@nicbavetta Unfortunately we don't have such a sample to hand but we could do with creating one. I'd be interested to hear what sort of issues you've had, might help us to concentrate on showing the right things in the sample.
