### ISSUE TITLE
code_challenge is empty

### ISSUE THREAD

**Issue by rgunczer** [auth0/auth0-spa-js#216]
During Login Redirect the generated url contains a code_challange query parameter with empty value.

https://auth.brucke.club/login?state=g6Fo2SBGaHVTN196OGlVdFltNDVLQTZZRzFHT1Q1RTF1elBZZKN0aWTZIDVFbmJadWxiOHBNdDhCSkRxOHlCT2RLSGk5MWRDdTlzo2NpZNkgd0xTSVA0N3dNMzl3S2REbU9qNlpiNWVTRXczSlZoVnA&client=wLSIP47wM39wKdDmOj6Zb5eSEw3JVhVp&protocol=oauth2&scope=openid%20profile%20email&response_type=code&response_mode=query&nonce=.FS1wxtuxKVMDZ0S8f3~aZN3Hka48tP3V0qjoKYJjU3&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&code_challenge=&code_challenge_method=S256&auth0Client=eyJuYW1lIjoiYXV0aDAtc3BhLWpzIiwidmVyc2lvbiI6IjEuMi4zIn0%3D

File: Auth0Client.ts
Line: 207

const code_challenge = bufferToBase64UrlEncoded(code_challengeBuffer);

After looking a bit closer. This line https://github.com/auth0/auth0-spa-js/blob/32690bb10dc08497467d54eefe78c0be23d1259d/src/Auth0Client.ts#L203
const code_challengeBuffer = await sha256(code_verifier);
Fills the code_challengeBuffer however that value is lost in the next line:
const code_challenge = bufferToBase64UrlEncoded(code_challengeBuffer);

Going into bufferToBase64UrlEncoded function in this line https://github.com/auth0/auth0-spa-js/blob/32690bb10dc08497467d54eefe78c0be23d1259d/src/utils.ts#L134
the content is lost.

Hope this helps.

**Comment by benprime** [comment]
Having the same problem.

**Comment by benprime** [comment]
@rgunczer I was able to get it to send the code challenge by rolling the library version back to 1.0.1
`npm install --save @auth0/auth0-spa-js@1.0.1`

**Comment by rgunczer** [comment]
@benprime  Thanks, it woks with the older version and waiting for your fix to be merged.
