### ISSUE TITLE
Issue with IE11 and id_token expired error immediately after login

### ISSUE THREAD

**Issue by adbutterfield** [auth0/auth0-spa-js#223]
Hi!
We released an application using Auth0 a few days ago. Looks like we failed to qa IE11, and now we have a bit of an incident. 

Directly after login in the console it says: `Unhandled promise rejection Error: id_token expired`. I tracked down where the error is being thrown at least, and it's line 82 in `src/jwt.js`.

I've exhausted crawling the internet, and the Auth0 Support Center, so I thought I'd see if I can get an assistance here. 

Let me know if you need any additional details from me. It's a React app, and I followed the React tutorial to get everything set up.

**Comment by luisrudge** [comment]
@adbutterfield Hi there! Thanks for reaching out. Do you have a repro we can test? Can you replicate this if you download our sample app from the quick start page and just run it in IE11? Are you using popup or redirect for authentication? Sorry about all the questions, we're adding our issue template soon!

**Comment by adbutterfield** [comment]
Hi @luisrudge! Thanks for getting back to me. 

I'm using the redirect for authentication.

I just tried with the quick start repo (https://github.com/auth0-samples/auth0-react-samples), and I get the same behavior for IE11. 

Also note, to get auth0-spa-js to work on IE11, you need to add the IE11 polyfill: (https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill)

**Comment by adbutterfield** [comment]
Oh, so I was just looking through the FAQ, and I saw this one: https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-error-invalid-state-in-firefox-when-refreshing-the-page-immediately-after-a-login

I think it might be the same problem. IE11 also gets stuck at https://my-domain?code=blabla&state=blabla

**Comment by adbutterfield** [comment]
So after digging into it more, I've found that it goes into the if statement [HERE](https://github.com/auth0-samples/auth0-react-samples/blob/6fc8552489c541eb8290ef5771a0f28138682b21/01-Login/src/react-auth0-spa.js#L26) and then fails at `const { appState } = await auth0FromHook.handleRedirectCallback();`

**Comment by adbutterfield** [comment]
After digging a bit into the package and putting some logs I get:
<img width="469" alt="Screen Shot 2019-09-26 at 13 01 26" src="https://user-images.githubusercontent.com/4752047/65657328-ec25ee80-e05d-11e9-87d5-6c47762a287c.png">
I put my log statements right after [THIS LINE](https://github.com/auth0/auth0-spa-js/blob/fafcb62671c7651d74fa3832a25805982ebe4600/src/jwt.ts#L78)

**Comment by adbutterfield** [comment]
So never mind. The issue was because I was using a Windows virtual machine on my Macbook. The times for the expiration of the id_token were always made in the past because of the timezone of the virtual machine.

**Comment by luisrudge** [comment]
@adbutterfield thank you so much for sharing your issue and solution with us. It might help other users in the future! Also, thanks for the IE11 feedback about the quickstart. I'll add that info in the quickstart itself because it's super important!
