### ISSUE TITLE
Is there a reason for getUser being async?

### ISSUE THREAD

**Issue by halfzebra** [auth0/auth0-spa-js#224]
Hello friends!

Thanks for building this library 👍 

As far as I can see, [getUser](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L162) method is not performing any asynchronous computations.
Is there a reason for it to be async?

**Comment by stevehobbsdev** [comment]
@halfzebra Mainly for futureproofing and consistency with the rest of the API surface. You're right in that it doesn't do anything async right now, but it may do in the future.

**Comment by halfzebra** [comment]
Thanks for the reply, makes sense!
