### ISSUE TITLE
Angular router, useHash - results in: There are no query params available at window.location.search.

### ISSUE THREAD

**Issue by hidegh** [auth0/auth0-spa-js#225]
NOTE: currently using the "@auth0/auth0-spa-js": "^1.2.3" will produce the following error after a successful login, if the angular routes do have useHash: true (so use a # in the route).

Error at callback:
There are no query params available at window.location.search.

Bypass:
**Avoid useHash: true in the router**
```
@NgModule({
  imports: [RouterModule.forRoot(routes, { useHash: false }) ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

**Comment by luisrudge** [comment]
@hidegh thanks for reporting this. What is the end result of your url? Something like `http://myapp.com/#/callback?code=123`?

**Comment by hidegh** [comment]
@luisrudge exactly

**Comment by CloudEntity57** [comment]
I have this problem with auth0-spa-ts as well, but adding usehash:false to router does not fix it.

**Comment by stevehobbsdev** [comment]
@CloudEntity57 Which version are you testing with?

**Comment by nicowernli** [comment]
Same as @CloudEntity57 but it only happens with stupid Safari. The app works fine in Chrome.
