### ISSUE TITLE
Reducing the amout of requests to Auth0 (Injectable cache instance)

### ISSUE THREAD

**Issue by halfzebra** [auth0/auth0-spa-js#226]
Hello friends!

I'm not a specialist in OAuth 2.0 by any means, so maybe this issue and the stuff I'm doing is completely wrong.
My goal is to reduce the number of requests to Auth0, when the client is instantiated, as I'm planning on using Auth0 client on a webpage that has a lot of traffic.

For this, I would like to have a client store the token in Session Storage or Local Storage, so I can call `.getUser` during the time when the token is valid without sending requests to Auth0.

For this, I would propose the option to skip the initial call to [`.getTokenSilently`](https://github.com/auth0/auth0-spa-js/blob/fafcb62671c7651d74fa3832a25805982ebe4600/src/index.ts#L37) either by exposing `Auth0Client` class for the advanced usage or by introducing an option for this.

Another proposed change would include an option to control the cache somehow. The path to introduce this without the breaking changes would be to export `Auth0Client` class and make the [`cache`](https://github.com/auth0/auth0-spa-js/blob/fafcb62671c7651d74fa3832a25805982ebe4600/src/Auth0Client.ts#L33) injectable, so users could implement their own caching layer.

Please let me know whether this makes sense? 🤞 
I'm pretty much interested in working on a PR if this is something you would consider adding.

**Comment by stevehobbsdev** [comment]
@halfzebra Can you elaborate a bit more on your requirement to reduce traffic to Auth0?

The Auth0 client will already cache the credentials while the tokens are valid. When they expire, they will be automatically renewed for you at the appropriate time. Unless I'm missing something (hence the ask for more info), moving these tokens into local storage won't gain you very much as they are still restricted to one browser client. Besides, [storing tokens in local storage is not something we endorse](https://auth0.com/docs/security/store-tokens#don-t-store-tokens-in-local-storage) thanks to the issues around XSS and injected JavaScript being able to read them.

> Another proposed change would include an option to control the cache somehow. 

Probably the best thing to do here is raise your PR where we can discuss the implementation and use case - it sounds like an interesting idea!

**Comment by luisrudge** [comment]
After some consideration, we decided that we'll keep managing the lifecycle of the tokens in the same way we're doing it right now. Introducing an API that allows you to provide a previously acquired token might bring more confusion than benefits and will also incentivize customers to store tokens in localStorage, which is something we don't recommend right now. This is something that we might reconsider in the future, but I wanted to be transparent regarding our current decision. Thanks for the feedback!

**Comment by halfzebra** [comment]
@stevehobbsdev @luisrudge Thanks for your reply! 👍 

After researching this, I don't have any arguments for justifying having an easy way to store the token in local storage.
