### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by javierGnz** [auth0/auth0-spa-js#235]
Hi, so i implement auth0 in my react app, but happen this 

![image](https://user-images.githubusercontent.com/25081104/66340136-f1ffb780-e91a-11e9-9c3d-c88c9bc0030d.png)

i not sure what is the problem, i have the configuration right and copied almost equals the tutorial and if i create a new proyect and implement this in the proyect work, but in the proyect that i need dosent work, any idea ? someone else that happen this ?

**Comment by luisrudge** [comment]
From the stacktrace in your error, this comes from the `react-auth0-spa.js` file, which we mention in our quickstart. It's not an issue with this SDK. Please take a look at our quickstart repo. You can clone it and compare with yours to figure it out where it's going wrong. https://github.com/auth0-samples/auth0-react-samples/
