### ISSUE TITLE
Unable to get hooks from wrapper js file

### ISSUE THREAD

**Issue by samayo** [auth0/auth0-spa-js#236]
### Description

Calling `loading`, `isAuthenticated`, `loginWithRedirect` from `react-auth0-wrapper.js` (example at https://auth0.com/docs/quickstart/spa/react/01-login#install-the-auth0-react-wrapper) throws an error like this: 

```
router.tsx?9eeb:48 Uncaught TypeError: Cannot read property 'loading' of undefined
    at RouterConfig (router.tsx?9eeb:48)
```

### Reproduction

This is tested on a simple create-react-app

- react router is installed
- auth0 installed ex: `npm install @auth/auth0-spa-js --save`

Demo: 
```js
// router.tsx
import React from 'react'
...
import { useAuth0 } from './utils/auth0-hooks'

const check = () => {
  const { loading, isAuthenticated, loginWithRedirect } = useAuth0()
}

// function defineRoutes () {...}
// export default defineRoutes
```
No matter where I put `const {..} = useAuth0()` I always get the error I mentioned above.
 
### Environment
- **Version of this library used:**
   `"@auth0/auth0-spa-js": "^1.2.4"`

- **Version of the platform or framework used, if applicable:**
   Ubuntu 19.04
   NPM 6.10.3
   Node v12.10.0
 
- **Other relevant versions (language, server software, OS, browser):**
   Google Chrome Version 77.0.3865.90
- **Other modules/plugins/libraries that might be involved:**
    "dva": "2.4.1"

**Comment by luisrudge** [comment]
Hi there 👋 Thanks for trying out our quickstart! Did you follow all the steps, including the one that integrates with the SDK itself? https://auth0.com/docs/quickstart/spa/react/01-login#integrate-the-sdk Without this step, you'll see the error you have right now.

If you still have any questions, please clone our quickstart repo and compare with your project to see where it went wrong: https://github.com/auth0-samples/auth0-react-samples

Also, please let us know which part went wrong so we can see if there's any improvement we can do to prevent other users from going through the same issue. Thanks! 🎉
