### ISSUE TITLE
handleRedirectCallback does not handle authorization error responses

### ISSUE THREAD

**Issue by nyobe** [auth0/auth0-spa-js#24]
It would be nice if `handleRedirectCallback` would extract error responses to the callback. I'm envisioning it throwing an error with with the `error` and `error_description` params for instance.

**Comment by davidpatrick** [comment]
Thanks for reporting this @nyobe.  We will include this in our next release.

**Comment by luisrudge** [comment]
released in @auth0/auth0-spa-js@1.0.0-beta.3 🎉
