### ISSUE TITLE
Invalid state still in react with 1.3.2 with Firefox 69.0.2

### ISSUE THREAD

**Issue by gcuadrad** [auth0/auth0-spa-js#250]
### Description

Hello, first of all I wanted to thank you for your work and apologize for my level of English. I wanted to ask for help because the error "Invalid state" still appears in firefox, I reviewed post like this (https://github.com/auth0/auth0-spa-js/issues/245) but unfortunately it still does not work for me.  

It works correctly in Chrome, but in Firefox when I log in with a Google account (I also tried github) then refresh the site the invalid state error appears again.

### Reproduction

I followed the following guide step by step:
https://auth0.com/docs/quickstart/spa/react#post-passwordless-start
Then I log in with a google account, when I return to the site and refresh the browser launches the error "Invalid state".
I uploaded to a repository a copy of what I did. (I only deleted the credentials) :
https://github.com/gcuadrad/auth0-test

Pic of the error:
https://i.postimg.cc/43H7YHJn/Screenshot-from-2019-10-22-16-00-06.png

### Environment

- **Version of this library used:** auth0-spa-js v1.3.2, react-dom v16.10.2
- **Version of the platform or framework used, if applicable:** react v16.10.2
- **Other relevant versions (language, server software, OS, browser):**  Ubuntu v19.04, Firefox v69.0.2
- **Other modules/plugins/libraries that might be involved:** Node v10.16.3

Thank you very much and I'm sorry for the inconvenience.

**Comment by luisrudge** [comment]
Hi there 👋 Firefox has a known issue documented here: https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-error-invalid-state-in-firefox-when-refreshing-the-page-immediately-after-a-login

Basically, when you refresh the page after a callback, you get a invalid_state error. Check the FAQ to see if it helps. If you still see the issue after than, let us know so we can further investigate it.

**Comment by stav** [comment]
_Lesson learned: use `localhost` for testing, not `<hostname>`._

I'm running `1.8.1` on Firefox 68.8.0 for a [tutorial](https://hasura.io/learn/graphql/react/introduction/) and when I run `yarn start` it says:

	Compiled successfully!
	You can now view react-apollo-todo in the browser.
	  http://varan:3000/

And when I login to my app on host `varan` using Firefox the spinner just keeps spinning and in the console I see:

	Error: Invalid state
	auth0-spa-js.production.esm.js:2894

​So then I used the Brave browser and in the cosole I see:

	Uncaught (in promise) Error: auth0-spa-js must run on a secure origin. 
	See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.
	auth0-spa-js.production.esm.js:2743

Then I change to `localhost:3000` and everything works fine.
