### ISSUE TITLE
Using a Custom Domain instead of auth0.com domain gives "You should not be hitting this endpoint" error message

### ISSUE THREAD

**Issue by philvarner** [auth0/auth0-spa-js#255]
### Description

Using a custom domain gives error message "You should not be hitting this endpoint. Make sure to use the code snippets shown in the tutorial or contact support@auth0.com for help" upon login attempt.

### Reproduction

With the code below, Auth0 Universal Login (redirect-based) works correctly when the domain is set to our auth0.com domain (e.g., foo.auth0.com). However, it fails if we have it set to our custom domain (represented by login.mydomain.net) with the message "You should not be hitting this endpoint. Make sure to use the code snippets shown in the tutorial or contact support@auth0.com for help".   I have validated via the management console that the custom domain gets a "success" message when clicking Verify.  All of the documentation (including a closed issue here in GitHub) seems to indicate all that needs to be done is to change the `domain` field to the custom domain.

Code
```
const AUTH0_CREDENTIALS = {
  domain: 'login.mydomain.net',
  client_id: '...',
  audience: 'https://server.mydomain.net'
}

const catalogClient: ClientWrapper = {
  client: null,
  token: null,
  permissions: null,
  authenticated: false,
  config: {
    ...AUTH0_CREDENTIALS,
    redirect_uri: `${redirectDomain}`
  }
}

  catalogClient.client = await createAuth0Client(catalogClient.config)
```

Then login is initiated with:
```
 await (catalogClient.client as Auth0Client).loginWithRedirect({
      redirect_uri: `${redirectDomain}`
    }
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.3.2
- **Version of the platform or framework used, if applicable:** ?
- **Other relevant versions (language, server software, OS, browser):** MacOS Firefox and Chrome
- **Other modules/plugins/libraries that might be involved:** None

**Comment by joshcanhelp** [comment]
@philvarner - Sorry for the trouble here! This typically occurs when you have a customized universal login page. There is a configuration change that needs to be made:

https://auth0.com/docs/custom-domains/additional-configuration#universal-login

Please let me know if that does not solve your problem!

**Comment by philvarner** [comment]
Thanks @joshcanhelp I'll check that out. Will that still allow us to use either the auth0.com domain or the custom domain, or will we only be allowed to use the custom domain?

**Comment by philvarner** [comment]
It appears that fixed the issue and still allows us to use our auth0.com subdomain.  The documentation you link to, and which I'd already seen, is pretty clear that I needed to make the change to the custom login page -- where I got confused was that I wasn't the person who created our custom login page, and didn't realize that it was using Lock, so I just assumed that neither the Lock or auth.js required changes applied to my case.
