### ISSUE TITLE
TypeScript problem with 1.4.0.

### ISSUE THREAD

**Issue by nirvdrum** [auth0/auth0-spa-js#259]
### Description

After upgrading from 1.3.2 to 1.4.0, my app fails to build with TypeScript. I'm using the React SPA Quick Start code, [ported to TypeScript](https://github.com/auth0/auth0-spa-js/issues/39#issuecomment-505901626). I don't think port to TypeScript matters so much, but I mention it because it means my quick start file is being passed through the TypeScript compiler. The TypeScript failure comes for an import statement that also appears in the original quick start code:

```
TypeScript error in /home/nirvdrum/dev/workspaces/cloudtruth/ctweb/src/reactAuth0Spa.tsx(2,31):
Could not find a declaration file for module '@auth0/auth0-spa-js'. '/home/myuser/dev/workspaces/myproject/node_modules/@auth0/auth0-spa-js/dist/lib/auth0-spa-js.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/auth0__auth0-spa-js` if it exists or add a new declaration (.d.ts) file containing `declare module '@auth0/auth0-spa-js';`  TS7016

    1 | import React, { useState, useEffect, useContext } from 'react'
  > 2 | import createAuth0Client from '@auth0/auth0-spa-js'
      |                               ^
    3 | import Auth0Client from '@auth0/auth0-spa-js/dist/typings/Auth0Client'
    4 | 
    5 | interface Auth0Context {

```

If roll back to @auth/auth0-spa-js 1.3.2, the problem goes away.

### Reproduction

Pass the Auth0 React SPA Quick Start code through the TypeScript compiler or use the [TypeScript port](https://github.com/auth0/auth0-spa-js/issues/39) of the Quick Start code.

### Environment

@auth0/auth0-spa-js: 1.4.0
typescript: 3.6.4

**Comment by nirvdrum** [comment]
It looks like merging #234 might fix the problem.

**Comment by stevehobbsdev** [comment]
@nirvdrum Ah good, I came in to ask if #234 would solve your issue. We're just waiting on the author to fix some things up.

**Comment by nirvdrum** [comment]
I haven't verified that branch, FYI. Just looking at it, it looks like it could be helpful. I'll have to clone, rebase, and use the package locally. In the meanwhile, I'll stick with 1.3.2.

**Comment by nirvdrum** [comment]
I spent some more time looking into this. The issue is pretty straightforward. The type definitions used to be in `dist/typings` and now there's an extra directory in between, making it `dist/typings/src`. However, this library's package.json still points to the old index.d.ts location. That part needs to be fixed in the library. With that change in place I encounter another error, but that's due to the import statement taken from the TypeScript port of the Quick Start code now pointing at an invalid location.

I can work up a PR for the immediate problem, but should this change even have been made? It looks like putting type definitions directly in `typings/` is the common practice.

**Comment by stevehobbsdev** [comment]
@nirvdrum 1.4.1 has now been released, if you'd like to give that a try and see if it fixes your issue.

**Comment by stevehobbsdev** [comment]
@nirvdrum @ttrevorr We've had to backtrack on this slightly, as we realised it would break existing apps that reference the types directly by path. Instead of amending the path to the typings in `package.json`, we simply moved the files back where they were. We released this in 1.4.2, so you should upgrade to that to get the latest behaviour.

**Comment by nirvdrum** [comment]
@stevehobbsdev Confirmed working. Thanks for the quick turnaround.

**Comment by ggascoigne** [comment]
I don't understand why types such as Auth0Client aren't just exported from the index.d.ts file in the first place.

```ts
import Auth0Client from '@auth0/auth0-spa-js/dist/typings/Auth0Client'
```

just gives me: 

```
Module not found: Can't resolve '@auth0/auth0-spa-js/dist/typings/Auth0Client' in '/Users/ggp/dev/git/acnw2/packages/ui/src/components/Acnw/Auth'
```

from my CRA app.

**Comment by ggascoigne** [comment]
ah, just found https://github.com/auth0/auth0-spa-js/pull/310, looks like there's a likely fix on it's way.  Sweet.

**Comment by stevehobbsdev** [comment]
@ggascoigne Yes we have a fix being rolled into the 1.7 beta, I'm just waiting on a couple more PRs going through review before release. Hopefully not long.

**Comment by l222p** [comment]
Any update?
I'm still having this issue on version 1.6.4 and typescript 3.8.3

**Comment by stevehobbsdev** [comment]
@l222p Yes the fix is deployed into the beta if you'd like to try it. There should be no breaking changes there so you should be able to start using it without any changes.

`@auth0/auth0-spa-js@beta`

Would love to hear some feedback on the TypeScript typings if you get a change to try it.
