### ISSUE TITLE
Configurable Authorization endpoint

### ISSUE THREAD

**Issue by ayamani** [auth0/auth0-spa-js#267]
The authorization server I'm using has its auth end-point set as /auth instead of /authorize.

I am not able to configure the auth end point as it's hard-coded in _authorizeUrl() [Auth0Client.ts]

I don't believe OAuth 2.0 specification mandates a specific path for the auth end-point, so it would be good if I could configure it accordingly.

**Comment by stevehobbsdev** [comment]
Hi @ayamani, thanks for your patience. We've been discussing this internally and while it could be a useful feature, the library is primarily designed to work with Auth0's endpoints and spending effort to support other authorization servers in a generic way is not a priority for this library at this time.

**Comment by MaxIbanez** [comment]
Hi, everyone.

what happend with this issue? any solution or nothing?
