### ISSUE TITLE
Having issues to make it working in Nuxt.js

### ISSUE THREAD

**Issue by mkralik** [auth0/auth0-spa-js#269]
### Description

I have a Nuxt.js application and trying to make this plugin working there, but after two days of troubleshooting I could not figure it out. Not sure if it is not compatible with nuxt and I should look for different solution or I am just doing it wrong (I have rather limited knowledge of Vue/Nuxt). 

**// plugins/auth0_spa.js**
`import Vue from "vue";`
`import createAuth0Client from "@auth0/auth0-spa-js";`

`export default async (ctx, inject) => {`
`    const $auth = await createAuth0Client({`
`        domain: 'MY_DOMAIN',`
`        client_id: 'MY_CLIENT_KEY',`
`        audience: 'MY_AUDIENCE'`
`      });`

`    inject('auth0', $auth)`
`    ctx.$auth0 = $auth`
`}`
**ERROR**: Property or method "$auth" is not defined on the instance but referenced during render

I tried also the following: 
`const useAuth0 = async () => await createAuth0Client({`
`    domain: 'MY_DOMAIN',`
`    client_id: 'MY_CLIENT_KEY',`
`    audience: 'MY_AUDIENCE'`
`});`

`Vue.prototype.$auth = useAuth0;`

**ERROR**: this.$auth.loginWithRedirect is not a function.

**// nuxt.config.js**
`plugins: [`
`    { src: '~/plugins/auth0_spa.js', mode: 'client' }`
`  ],`

**// Page**
`login() {`
`    this.$auth.loginWithRedirect();`
`}`

### Environment
- "@auth0/auth0-spa-js": "^1.5.0"
- "nuxt": "^2.0.0"

**Comment by ItayKatzCC** [comment]
Any updates?

**Comment by thibaultvanluchene** [comment]
+1
