### ISSUE TITLE
restore auth state doesn't work in chrome but works in IE and firefox 

### ISSUE THREAD

**Issue by wang305305** [auth0/auth0-spa-js#271]
### Description

> In my angular project, when the user is logged in, after refreshing the page, it should automatically restore the login status. it works fine in IE and firefox, but in chrome the user has to click login button to be logged in, although username/password is not required.

### Reproduction

the code for reproduction cannot be shared. But har files are provided.

[bnv_har.zip](https://github.com/auth0/auth0-spa-js/files/3805127/bnv_har.zip)

### Environment

- Version of this library used: "@auth0/auth0-spa-js": "^1.2.4"
- Version of the platform or framework used, if applicable: node v10.16.3; angular 7.2.8
- Other relevant versions (language, server software, OS, browser): chrome Version 76.0.3809.132 (Official Build);  firefox 68.0.2

**Comment by stevehobbsdev** [comment]
@wang305305 Thanks for sending the HAR file over. `auth0-spa-js` is currently at version 1.5 - could you please upgrade and see if that fixes your issue first, before we go into debugging?

**Comment by stevehobbsdev** [comment]
@wang305305 I've checked the HAR files out and they show that the right calls are being made. The important one is the `/authorize` call where a `prompt=none` param is being sent through the querystring. These are returning a 200 status.

Next thing to try is bringing the library up to date if possible, then we can take it from there.

**Comment by wang305305** [comment]
Hi I just updated auth0-spa-js to version 1.5 and the behavior is still the
same.

Steve Hobbs <notifications@github.com> 于2019年11月6日周三 上午8:02写道：

**Comment by stevehobbsdev** [comment]
@wang305305 Hmm. The network trace looks good from the auth server point of view.

I know you can't share the code but is there anything you can tell me about how you're using the SDK? Also:

* Are you seeing the same issue with our [Angular sample](https://github.com/auth0-samples/auth0-angular-samples)?
* Are you getting any errors in the console or the Auth0 log dashboard that could help us pinpoint the issue?

**Comment by wang305305** [comment]
Hi,
The angular sample has the same behavior.


this is what I get in the log. What I did is:
            firstly I login, and then I refresh the page, thenI click the
login button.


TypeDescriptionDate↓ConnectionApplication
Success Exchange
<https://manage.auth0.com/dashboard/us/dev-j2kin68i/logs/90020191107155415213000326140176286513883192790096019586>Authorization
Code for Access Tokena minute agoN/AMy App
Failed Silent Auth
<https://manage.auth0.com/dashboard/us/dev-j2kin68i/logs/90020191107155414130005938788060109303949494058253025394>Login
requireda minute agoN/AMy App
Success Login
<https://manage.auth0.com/dashboard/us/dev-j2kin68i/logs/90020191107155412614000542696461633232038180385158332514>Successful
logina minute agoN/AMy App
Failed Silent Auth
<https://manage.auth0.com/dashboard/us/dev-j2kin68i/logs/90020191107155405813000326129998340038547629081049956482>Login
requireda minute agoN/AMy App
Success Exchange
<https://manage.auth0.com/dashboard/us/dev-j2kin68i/logs/90020191107155306613000100020126923057808380712869429330>Authorization
Code for Access Token2 minutes agoN/AMy App
Success Login
<https://manage.auth0.com/dashboard/us/dev-j2kin68i/logs/90020191107155301413000542609709116416492385860440817762>Successful
login2 minutes agoUsername-Password-AuthenticationMy App

The following is the content of the error:
{
  "date": "2019-11-07T15:54:01.227Z",
  "type": "fsa",
  "description": "Login required",
  "client_id": "23YfYSZt1p0735LLXvUQUaANbV9cAPeb",
  "client_name": "My App",
  "ip": "204.40.130.136",
  "user_agent": "Chrome 76.0.3809 / Windows 10.0.0",
  "details": {
    "body": {},
    "qs": {
      "client_id": "23YfYSZt1p0735LLXvUQUaANbV9cAPeb",
      "redirect_uri": "http://localhost:4020/callback",
      "audience": "
https://ws.dev.gwy.apic.sus.ebc.gov.on.ca/ods/public/bd/bnv/v1/bn9",
      "scope": "openid profile email",
      "response_type": "code",
      "response_mode": "web_message",
      "state":
"eEt0Lk8wQTVIUnY4QURjWWVaVE1xTTdkSVIyWElOcUdyVWtSWlNIbDhVNg==",
      "nonce": "ekpHTU9AHnV3Ldgqd9jLqUhL0JBtJqPg7rx35sGU7wS",
      "code_challenge": "2s603Z5S8P9EOSXdJWG2oWpYpjQZKAxKYWk1IMeFiNk",
      "code_challenge_method": "S256",
      "prompt": "none",
      "auth0Client":
"eyJuYW1lIjoiYXV0aDAtc3BhLWpzIiwidmVyc2lvbiI6IjEuNS4wIn0="
    },
    "connection": null,
    "error": {
      "message": "Login required",
      "oauthError": "login_required",
      "type": "oauth-authorization"
    }
  },
  "hostname": "dev-j2kin68i.auth0.com",
  "audience": "
https://ws.dev.gwy.apic.sus.ebc.gov.on.ca/ods/public/bd/bnv/v1/bn9",
  "scope": [
    "openid",
    "profile",
    "email"
  ],
  "auth0_client": {
    "name": "auth0-spa-js",
    "version": "1.5.0"
  },
  "log_id": "90020191107155405813000326129998340038547629081049956482",
  "_id": "90020191107155405813000326129998340038547629081049956482",
  "isMobile": false
}

Thanks,
Wayne


Steve Hobbs <notifications@github.com> 于2019年11月7日周四 上午10:46写道：

**Comment by stevehobbsdev** [comment]
@wang305305 Can you confirm that you've entered a value into your **Allowed Web Origins** configuration setting for the Auth0 app you're using?

**Comment by wang305305** [comment]
Yes, if it's not set in Allowed Web Origin, it wouldn't work in firefox
either. BTW, here's the log for a successful silent auth in firefox:

{
  "date": "2019-11-07T16:02:25.694Z",
  "type": "ssa",
  "client_id": "23YfYSZt1p0735LLXvUQUaANbV9cAPeb",
  "client_name": "My App",
  "ip": "204.40.194.134",
  "user_agent": "Firefox 68.0.0 / Windows 10.0.0",
  "details": {
    "prompts": [],
    "completedAt": 1573142545693,
    "elapsedTime": null,
    "session_id": "ADUHS1ymh8AvPmh_uaODLTaH73hPk4DR",
    "device_id": "v0:6a245910-fa77-11e9-b0a7-ff5f475ccd60"
  },
  "hostname": "dev-j2kin68i.auth0.com",
  "session_connection": "Username-Password-Authentication",
  "user_id": "auth0|5d93784b0d878b0c504275f0",
  "user_name": "a@b.com",
  "auth0_client": {
    "name": "auth0-spa-js",
    "version": "1.5.0"
  },
  "log_id": "90020191107160226613000101187179179058445683177654583378",
  "_id": "90020191107160226613000101187179179058445683177654583378",
  "isMobile": false,
  "description": "Successful silent authentication"
}
thanks,
Wayne

Steve Hobbs <notifications@github.com> 于2019年11月7日周四 上午11:20写道：

**Comment by stevehobbsdev** [comment]
@wang305305 Thanks for the info.

Ok so you're getting a `login_required` error on refresh. This basically means that the Auth0 cookie that's tied to `dev-j2kin68i.auth0.com` is not being sent, so the authorization server thinks you don't have a session.

When you refresh the page, the SDK internally calls `getTokenSilently` on initialization to try and refresh your user session. It's this call that's failing and is causing you to appear logged out on refresh. As to why the cookie is not being sent, it is usually down to some sort of 3rd-party tracking prevention blocking the sending of that cookie. You'll probably see the same thing happen if you try to do this in Safari (with its ITP technology) or Brave (with its protection sheilds up). And you can see this in your network logs; the HAR file for Firefox shows that the `auth0` cookie is sent with the request to `/authorize` after the refresh, whereas in Chrome it is not.

I've tried to reproduce this in vanilla Chrome 48 without any extensions and it works as expected. In your case, do you have any extensions running or any other software which could be blocking the transmission of the cookie?

I'll leave the issue open for now but so far I don't believe this is an issue with the SDK.

**Comment by stevehobbsdev** [comment]
@wang305305 Closing this for now but if you feel there's still an issue, please continue the conversation.
