### ISSUE TITLE
web app does not work after page refresh

### ISSUE THREAD

**Issue by ShaneZhengNZ** [auth0/auth0-spa-js#272]
### Description

I know this has been reported a few times (#64, #209), but with the lastest auth0-spa.js (v1.5.0), my sample app still does not work after reload. Although I am still authenticated, the page stucks at 'loading...' for a long time before showing the correct home page.

### Reproduction

To replicate the issue:

1. Create a new React application by using create-react-app
2. Follow the 'Quick Start' documentation for React up to 'Read the User Profile'.
3. So far so good, I can login, logout, click Home, click Profile. etc.
4. Try to reload the page (click on **F5** or **ctrl + R**)

Expected Result - after the page is reloaded, I still see the home, profile and logout link, because I am still authenticated.
Actual Result - the page stucks at 'loading...' for a long time before the correct home page is shown.

I attach the network tab result here (after I did step 4):
![image](https://user-images.githubusercontent.com/2180397/68267291-d07b2280-00b6-11ea-83c5-417e1609a0a8.png)

Those 3 items worried me. It is clear that I am authenticated, why do I get 400 error? Why does the websocket call take 1 min to complete?

### Environment

> Please provide the following:

- **Version of this library used: 1.5.0
- **Version of the platform or framework used, if applicable: React v16.11.0
- **Other relevant versions (language, server software, OS, browser): Windows 10, Chrome/Firefox/Edge
- **Other modules/plugins/libraries that might be involved: none.

**Comment by stevehobbsdev** [comment]
Hi @ShaneZhengNZ, we do recognise that the error reporting around this needs to be improved and I can assure you it's on our backlog. Having said that, what you're seeing is usually down to a configuration issue with the **Allowed Web Origins** setting in your Auth0 app dashboard.

Can you have a read of [this item in the FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-does-the-auth0client-object-take-a-long-time-to-initialize) and confirm whether or not it solves your problem?

**Comment by ShaneZhengNZ** [comment]
Hi @stevehobbsdev, you are right, **Allowed Web Origins** should be set to https://localhost:3000 in this case. I missed it.

I would suggest making those fields mandatory, just so that they are not missed. When the user is new to the Auth0 platform, it is too easier to make mistakes as I did, then wasted a few hours to find out whether they are bugs in our code or not.

**Comment by stevehobbsdev** [comment]
Thanks for the suggestion @ShaneZhengNZ. Unfortuantely we can't make them mandatory as they're not needed in all cases. We try to outline these common problems in the FAQ though, and will continue to do so as these things come up.
