### ISSUE TITLE
Return auth URL for usage with manual browser redirects

### ISSUE THREAD

**Issue by austin43** [auth0/auth0-spa-js#273]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here. 

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). 

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

My app runs ionic/react with capacitor and the auth0-spa-js sdk.  I am attempting to use the capacitor "Browser" plugin to open the auth0 universal login, because utilizing loginWithRedirect() causes the app to open safari externally.  The problem is, I cannot find how to retrieve the constructed URL loginWithRedirect uses.  It would be nice to have the auth0-spa-js library return the URL that loginWithRedirect generates so we can utilize custom plugins for redirect.  Am I going about this the wrong way?

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

Run auth0-spa-js sdk with ionic/react quickstart and call loginWithRedirect().  Observe redirection outside of app instead of in SafariViewController.

### Environment

> Please provide the following:

- **Version of this library used:** 1.5.0
- **Version of the platform or framework used, if applicable:** @ionic/react@4
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by austin43** [comment]
@stevehobbsdev Is there some correspondence I can read about ionic/react with auth0? I've been having a hard time finding documentation as it's a very new platform.  I appreciate this being marked as a feature, but I am wondering if there's something simpler here that I'm missing where auth0-spa-js is supposed to work out of the box with ionic/react.

**Comment by stevehobbsdev** [comment]
@austin43 We do have a [quickstart for Ionic 4](https://auth0.com/docs/quickstart/native/ionic4) but it uses our previous SDK, [Auth0.js](https://github.com/auth0/auth0.js), rather than this one. It's not that Auth0.js is deprecated, but is a bit more involved to get things up and running.

If it helps, the [React quickstart](https://auth0.com/docs/quickstart/spa/react) also defines a React wrapper that makes working with auth0-spa-js + React a bit easier.

To answer your question, we don't currently have a way to access the generated authorize URL so you can do redirection yourself, but if the above literature doesn't help you then I think you have a pretty good use-case for it. We recently had #249 which initially implemented exactly what you want, but we accepted a different approach in the end.

**Comment by austin43** [comment]
@stevehobbsdev Thanks for clarifying.  Does this mean that even though auth0-spa-js uses PKCE, it's not necessarily a choice for hybrid web/native apps?  I think I assumed it was possible from my deep dives into other forums on the topic, but perhaps that was an incorrect assumption.

I am currently using the react quickstart with auth0-spa-js, and it has worked great for web, and it feels like this library is 99% of the way to working with native apps, but just needs slightly more flexibility to work with ionic/capacitor.  At this point I'm pretty much willing to try anything, as it's the only blocker for getting our app running natively.  Sounds like a rewrite in auth0.js might be my next stop.

If my use case validates a separate approach, would you anticipate LOE being rather low? It seems like a relatively simple change on the surface, but that could just be my noob status on this library speaking.

**Comment by stevehobbsdev** [comment]
@austin43 PKCE is definitely the preferred method for hybrid/native apps. I don't think adding something to allow you to get the URL as opposed to redirecting out on your behalf is out of the question and it'll be fairly simple to implement. If you'd like to have a crack at it, we'd welcome a PR. Otherwise, I can do this myself but unfortunately it's not a priority issue and will be prioritised as such.

We also have [auth0-cordova](https://github.com/auth0/auth0-cordova/) - does this look like it might get you moving in the meantime?

**Comment by austin43** [comment]
@stevehobbsdev 

i would be glad to take a shot at a PR. I’ll let you know where I end up with that.

**Comment by austin43** [comment]
@stevehobbsdev whoops, I meant this library not pkce. Is this library supposed to be used with ionic native apps at all, or is that not an intended use case?

I would be happy to take a shot at a PR. I’ll let you know where I end up with it. 

As far as auth0-Cordova I may be able to swing that, but it’s not 1:1 since I’m using capacitor. I’ll look into it after I attempt a PR.

**Comment by stevehobbsdev** [comment]
@austin43 This has now been released in [v1.6.0](https://github.com/auth0/auth0-spa-js/releases/tag/v1.6.0) - thanks for your contribution!

**Comment by evansaa1** [comment]
@austin43 I'm in the same situation trying to use Ionic + Capacitor + React + auth0-spa-js. Once you have the URL how are you handling the redirect? I'm currently using Capacitor Browser plugin which navigates to the Auth0 login page fine but fails to navigate back to localhost. There are a number of unanswered questions on community.auth0.com surrounding this so any advice would be much appreciated!

**Comment by stevehobbsdev** [comment]
@austin43 It would be great to hear if the PR we merged enabled you to continue with your app. I wonder - did you have to make use of the [customurlscheme plugin](https://www.npmjs.com/package/cordova-plugin-customurlscheme) to get the callback to work? I believe it should be compatible with Ionic apps.

**Comment by austin43** [comment]
@evansaa1 @stevehobbsdev It’s been a while, but I ended up switching to Firebase auth and using separate handler code for native and web. I can share my code once I get to my PC today. 

The issue I ran into was related to android. Android doesn’t let you programmatically close in app browsers, so this seemed like a bad user experience on native. With Firebase sdk’s and phone auth, there’s no browser component so it simplified our flow.

**Comment by evansaa1** [comment]
@austin43 thanks for your feedback, I'm willing to refactor my apps to use Firebase if it's been working well for you. If you could share your handler code for both native and web it would be much appreciated!

**Comment by mogusbi-motech** [comment]
I've pretty much hit the same roadblock, I can launch the log in window but I can't get back to my app after. I'm using Capacitor + Ionic React

```
import { Plugins } from '@capacitor/core';

...

const { buildAuthorizeUrl } = useAuth();

const { Browser } = Plugins;

const login = async () => {
  const url = await buildAuthorizeUrl({
    appState: {
      targetUrl: '/dashboard',
    },
  });

  await Browser.open({
    presentationStyle: 'popover',
    url,
  });
};
```

**Comment by mogusbi-motech** [comment]
Just to follow on, I have been able to get the log in flow to work with the following

```typescript
import { Capacitor, Plugins } from '@capacitor/core';
import history from '../history';

const { App, Browser } = Plugins;

App.addListener('appUrlOpen', async ({ url }) => {
  if (url) {
    await Browser.close();

    const { pathname, search } = new URL(url);

    history.push(pathname + search);
  }
});

...

const { buildAuthorizeUrl } = useAuth();

const login = async () => {
  const params = {
    appState: {
      targetUrl: '/dashboard',
    },
  };

  const url = await buildAuthorizeUrl(params);

  await Browser.open({
    presentationStyle: 'popover',
    url,
  });
};
```

The problem I'm now having is to do with logging out. I think a `buildLogoutUrl` method might be of use and would be easy enough to implement. What would be your thoughts on that @stevehobbsdev?

**Comment by benhunterandrewrobertson** [comment]
> Just to follow on, I have been able to get the log in flow to work with the following
> 
> ```ts
> import { Plugins } from '@capacitor/core';
> import history from '../history';
> 
> const { App, Browser } = Plugins;
> 
> App.addListener('appUrlOpen', async ({ url }) => {
>   if (url) {
>     await Browser.close();
> 
>     const { pathname, search } = new URL(url);
> 
>     history.push(pathname + search);
>   }
> });
> 
> ...
> 
> const { buildAuthorizeUrl } = useAuth();
> 
> const login = async () => {
>   const params = {
>     appState: {
>       targetUrl: '/dashboard',
>     },
>   };
> 
>   const url = await buildAuthorizeUrl(params);
> 
>   await Browser.open({
>     presentationStyle: 'popover',
>     url,
>   });
> };
> ```
> 
> The problem I'm now having is to do with logging out as it fires me out of the app and into Safari, which then presents an alert to go back to the app. I think a `buildLogoutUrl` method might be of use and would be easy enough to implement. What would be your thoughts on that @stevehobbsdev?

@mogusbi-motech How did you go about configuring `appUrlOpen` to fire on Android? It fires no worries on iOS.
