### ISSUE TITLE
Problem with Firefox failing silent auth on refresh in Sapper (Svelte)

### ISSUE THREAD

**Issue by kevmodrome** [auth0/auth0-spa-js#284]
### Description

I'm currently trying to implement this package with Svelte and Sapper and it's mostly working fine except in Firefox. I'm using Version 70 so the issue with replaceState should be resolved (I tested with the proposed solution as well).

After directing to the login screen and redirecting back to the site in question it works and I'm authenticated but if **I refresh the page it fails to do the silent auth**. Looking at the network tab and HAR files and comparing between Chrome and Firefox it looks like Firefox is only sending one cookie while Chrome is sending two. Specifically it's missing the auth0 but sending the "did" cookie.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:

In the _layout.svelte file in the basic [Sapper template](https://github.com/sveltejs/sapper-template) put the following code:

Script tag:
```javascript
<script>
  import createAuth0Client from "@auth0/auth0-spa-js";
  import { user } from "../stores/auth.js";
  let auth0;

  if (typeof window !== "undefined") {
    generateClient();
  }

  const onRedirectCallback = appState => {
    window.history.replaceState(
      {},
      document.title,
      appState && appState.targetUrl
        ? appState.targetUrl
        : window.location.pathname
    );
  };

  async function generateClient() {
    auth0 = await createAuth0Client({
      domain: "nomadmeals.eu.auth0.com",
      client_id: "QnyQ7Ktjruji_PEGi_qsEXcEd1L12an2"
    });
    if (window.location.search.includes("code=")) {
      const { appState } = await auth0.handleRedirectCallback();

      console.log("App State: ", appState);
      onRedirectCallback(appState);
    }
  }

  async function handleLogin() {
    try {
      await auth0.loginWithRedirect({
        redirect_uri: window.location.origin
      });
    } catch (error) {
      console.error(error);
    }
  }
  async function handleGetUser() {
    try {
      const fetchedUserData = await auth0.getUser();
      user.set(fetchedUserData);
      console.log("User: ", $user);
    } catch (error) {
      console.error(error);
    }
  }
  async function handleGetTokenSilently() {
    try {
      const token = await auth0.getTokenSilently();
      console.log("Token: ", token);
    } catch (error) {
      console.error(error);
    }
  }
</script>
```

And the HTML (only for testing):
```html
<button on:click|preventDefault={handleLogin}>Log in!</button>
<button on:click|preventDefault={handleGetUser}>Get user!</button>
<button on:click|preventDefault={handleGetTokenSilently}>Get token!</button>
```
### Environment

- Version of this library used: 1.5.0
- Version of the platform or framework used, if applicable: Sapper 0.27, Svelte 3.0.0
- Other relevant versions (language, server software, OS, browser): Mac, English

**Comment by stevehobbsdev** [comment]
Hey @kevmodrome, this usually occurs when the `auth0` cookie is being blocked, usually by software that intends to block third-party tracking cookies. You might find that if you try your scenario in Safari, it would be blocked there too thanks to their ITP2 feature.

Can you confirm if you have any addons or other software running that may be blocking this cookie?

As for a fix, we are working on an alternative to allow silent auth to work, but I don't have anything more specific to share yet, unfortunately.

**Comment by kevmodrome** [comment]
Hi,

Yeah, I've tried all kinds of different things, nothing seems to help. Very odd!

That's great to hear, any idea when we can expect it?

**Comment by june07** [comment]
@kevmodrome Are you using auth0 dev keys for your connection?  I was having a similar issue and noticed that when I switched to using my own keys (google social connection in this case), and NOT the auth0 dev keys, the silent auth started working!

**Comment by stevehobbsdev** [comment]
@june07 This would affect all browsers though, @kevmodrome reports that it works in some browsers and not others.

**Comment by kevmodrome** [comment]
Yes, I'm not even using the social connection parts of Auth0 at the moment so that can't be the problem.

**Comment by stevehobbsdev** [comment]
Closing this for now as this is most likely a browser extension/software issue blocking the transmission of the `auth0` cookie. If it can be shown that's not the case, let's discuss it.
