### ISSUE TITLE
Determine whether user signed up or logged in

### ISSUE THREAD

**Issue by brendanator** [auth0/auth0-spa-js#289]
### Describe the problem you'd like to have solved

Determine whether use signed up or logged in

### Describe the ideal solution

```js
    const { appState, authenticationType } = await auth0Client.handleRedirectCallback()
```

Where authenticationType in `login` or `signup`

## Alternatives and current work-arounds

No known workaround

**Comment by stevehobbsdev** [comment]
There might be a way you can do this using [Auth0 Rules](https://auth0.com/docs/rules) but I'm not entirely sure. Let me ask internally.

**Comment by stevehobbsdev** [comment]
So it looks like you could do this using a custom rule. Inside the rule code, the user profile has a property on it called `loginCount` which indicates whether the user signed up or logged in. You could put this value into your ID token as a claim and read it on the client.

Hope that helps! Feel free to continue the conversation if you need to clarify this further.
