### ISSUE TITLE
User APP Meta is sometimes missing when calling getUser

### ISSUE THREAD

**Issue by sixfootsixdesigns** [auth0/auth0-spa-js#290]
### Description

We have a react app that is using the auth0-spa-js and when we call `getUser()` it sometimes does not return the app_metadata for the user that is defined for a user in the auth0 dashboard. I have attached a screen shot of the data we have for a user.
<img width="1127" alt="Screen Shot 2019-11-27 at 12 42 37 PM" src="https://user-images.githubusercontent.com/2627303/69754558-6aad1400-1113-11ea-8ca0-a88910bd6c28.png">

We are able replicate this problem using the https://auth0.com/docs/quickstart/spa/react/01-login code.
React 16.12
@auth0/auth0-spa-js 1.6.0.
Browser Chrome 73.0.3683.103 on mac
Auth0 config: Application type: Single page application

To reproduce, you need to login and refresh the app a few times. Sometimes the user will have all the data and sometimes the user will be missing the app_metadata data but have the user_metadata.

I've tried clearing all cookies to see if that was the issue with no avail.

Let me know if you need any other information.

-James

**Comment by sixfootsixdesigns** [comment]
Closing this as it might be an issue with the rules we are using. I'll re-open if that's not it

**Comment by tomboolean** [comment]
Can someone give their example with a Rule or Action? I'm lost.

**Comment by 5310** [comment]
@tomboolean In case you're still lookin for this. This [other answer](https://github.com/auth0/auth0-spa-js/issues/286#issuecomment-557126960) pointed me to the kind of Rule I needed to add to see `app_metadata` (or whatever I name it) on my user-facing `getUser()`
