### ISSUE TITLE
Uncaught exception related to client clock settings

### ISSUE THREAD

**Issue by daviseford** [auth0/auth0-spa-js#296]
### Description

When a client with an incorrectly configured Windows time attempts to login using the latest version of this library, they receive this error in console:

```
Uncaught (in promise) Error: Issued At (iat) claim error in the ID token; current time (Fri Nov 29 2019 01:02:30 GMT-0800 (Pacific Standard Time)) is before issued at time (Fri Nov 29 2019 01:03:37 GMT-0800 (Pacific Standard Time))
    at auth0-spa-js.production.js:1843
    at t._verifyIdToken (auth0-spa-js.production.js:1890)
    at t.<anonymous> (auth0-spa-js.production.js:2019)
    at auth0-spa-js.production.js:152
    at Object.next (auth0-spa-js.production.js:100)
    at a (auth0-spa-js.production.js:52)
```

Unfortunately, because this is an uncaught error, it affects the application downstream and leaves the app in a state of waiting for the user object.

This concern was first raised by a user here: https://github.com/daviseford/aos-reminders/issues/768

### Reproduction

The user's PC clock was out of sync, and the Windows Time service (w32tm) was not running. 

The user restarted the service, re-synced their clock, and is now able to log in.

### Environment

> Please provide the following:

- **Version of this library used:** 1.6.0
- **Other relevant versions (language, server software, OS, browser):** Chrome, Windows

**Comment by stevehobbsdev** [comment]
This looks to be uncaught by the application using `auth0-spa-js`, as we generate that error as part of our ID token validation logic. I'm not sure what else we can do here; what action do you feel should be taken?

**Comment by daviseford** [comment]
You’re right, I read this trace badly. My bad! I will catch the error on my end
