### ISSUE TITLE
logout is cancelled by browser before it hits /v2/logout

### ISSUE THREAD

**Issue by tommedema** [auth0/auth0-spa-js#297]
### Description

I've implemented auth0-spa-js with react as per your quickstart. When I call the `logout()` function however, the browser is never logged out before the HTTP request to `/v2/logout` is cancelled:

![Screen Shot 2019-12-01 at 10 17 08 AM](https://user-images.githubusercontent.com/331833/69918230-83277200-1424-11ea-8fe1-0940c21b9d9d.png)

https://github.com/tommedema/startup-boilerplate/blob/login-redirect/packages/react-app/src/components/EmojiView.tsx#L21

### Reproduction

1. `git clone git@github.com:tommedema/startup-boilerplate.git`
2. `git checkout login-redirect`
3. `yarn install`
4. `yarn build`
5. `cd packages/react-app`
6. `cp .env.example .env`, you can use my temporary dev client ID (will regenerate after you fixed this):

```
AUTH0_DOMAIN=dev-startup-boilerplate.auth0.com
AUTH0_CLIENT_ID=YZQ2d98L8Un34aBxEANq2wzynERPgm6V
```

7. `yarn dev`
8. attempt to logout and check your network log

### Environment

- **Version of this library used:** 1.6.0
- **Version of the platform or framework used, if applicable:** react 16.12.0
- **Other relevant versions (language, server software, OS, browser):** https://whatsmybrowser.org/b/2YSC7JF
- **Other modules/plugins/libraries that might be involved:** none

**Comment by tommedema** [comment]
When I comment out the `history.push` call in the `onRedirectCallback` function, I see the following error message in my console on logout:

![Screen Shot 2019-12-01 at 10 44 45 AM](https://user-images.githubusercontent.com/331833/69918507-9be55700-1427-11ea-8011-71064235561a.png)

However I cannot understand _why_ the state would be invalid as my implementation seems identical to the quickstart

**Comment by tommedema** [comment]
The cancellation can be prevented by using `e.preventDefault()` inside the event handler, see also https://github.com/auth0/auth0-spa-js/issues/295#issuecomment-560352949

**Comment by andela-mallan** [comment]
In my case, I was calling `loginWithRedirect` right after the `logout` function which cause that request to be canceled.

**Comment by allan-vera** [comment]
> In my case, I was calling `loginWithRedirect` right after the `logout` function which cause that request to be canceled.

also am curious
