### ISSUE TITLE
how can I get the access_token

### ISSUE THREAD

**Issue by asotoglez** [auth0/auth0-spa-js#301]
I need to get the access token but I can't find how to get it, someone can help me.

**Comment by stevehobbsdev** [comment]
Hi @asotoglez, you can retrieve the access token by calling `getTokenSilently`. Hope that helps!

**Comment by asotoglez** [comment]
Usé getTokenSilently pero me retorna un token sin formato JWT
Por ejemplo este : 5-IwUwnVMgbifhI2RkN8AXSlMiHyUEHH
Necesito el token de tipo Bearer

**Comment by stevehobbsdev** [comment]
That is the access token you're seeing.

If you expect it to be a JWT, you need to ensure you're setting an `audience` value when creating the Auth0 client. This should be set to the Auth0 API Identifier that you want an access token for. Does that help?

**Comment by petrogad** [comment]
I'm hitting a similar path; My audience is set as such:
```
<Auth0Provider
	domain={'MY DOMAIN'}
	client_id={'MY AUDIENCE'}
	redirect_uri={window.location.origin}
	onRedirectCallback={onRedirectCallback}
>
```

I don't think I'm quite following if something additional needs to be set. I see that if I get the token claims it resides in the .raw bundle; however uncertain if that's really the best way to go about getting at that token.

Will keep digging here, if I come to the solution i'll make sure to follow back up.

**Comment by petrogad** [comment]
resolved here:
https://auth0.com/docs/quickstart/spa/react/02-calling-an-api

Thank you!
