### ISSUE TITLE
Unable to fetch user after auth without setinterval ($auth.user populats after 4 seconds)

### ISSUE THREAD

**Issue by edmonAvetisyan555** [auth0/auth0-spa-js#304]
Hello . Using VueJs SDK . Problem is the following .
My redirect url is example.com/callback , inside routes I have callback component which suppose to send user data to backend and check if user exists and log user in otherwise create new user and get back jwt from our backend application .
Problem is following , inside created/mounted cycle I can not reach auth0Client and so user properties .
this.$auth.auth0Client.
I have to do this hack

```
const interval = setInterval(async () => {
     count++;
     if (this.$auth.auth0Client) {
         clearInterval(interval);
         let loggedUser = await this.$auth.auth0Client.getUser();
         if(loggedUser){
             const email = loggedUser.email;
             const name = loggedUser.name;
             try{
                //backend logic
             }catch (e) {
                 console.log(e)
             }
         }
     } else {
         if (count > 80) {
             clearInterval(interval);
         }
     }
 }, 100)
```

My problem /question is how to handle this better as it seems not very logical and nice .
I want to send authenticated user data to our backend and do the rest there ,
Thanks

**Comment by stevehobbsdev** [comment]
In general after using `createAuth0Client` you must wait until the promise that is returned to you is resolved before you can access methods like `getUser`. It could be that by the time this code is executed, the promise hasn't resolved.

It might help to see some of the surrounding code. At what point do you call `createAuth0Client`?

Or, are you using the [wrapper from our Vue quickstart](https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/auth/authWrapper.js)? If so, you can also check the `loading` property on that and take action when it is `false`.

**Comment by edmonAvetisyan555** [comment]
I  was able to solve the issue by using bus system 
right after creation (promise)
`this.auth0Client = await createAuth0Client({
        domain: options.domain,
        client_id: options.clientId,
        audience: options.audience,
        redirect_uri: redirectUri,
        responseType: 'token'
      });
      this.$eventBus.$emit('auth0Client',this.auth0Client)`
I emit event which is handled in callback component 
Thanks for reply
