### ISSUE TITLE
logoutWithPopup

### ISSUE THREAD

**Issue by franciscolourenco** [auth0/auth0-spa-js#306]
**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved
I would like to logout with a popup, for the same reasons you would want to login with a popup.

### Describe the ideal solution

Popup appears, user is logged out, session is cleared, callback is executed.

### Additional context
The motivation is not to loose application context, even when the user is logged out.

**Comment by stevehobbsdev** [comment]
Would #308 not help with this or is there another motivation for using a popup? Otherwise, we could close this and push the iframe version.

**Comment by franciscolourenco** [comment]
Popup would not require third-party cookie support correct?

**Comment by stevehobbsdev** [comment]
Good point, I don't think it would. What's the primary motivator here (and I'm including your other issues in this) - is it to get around third-party cookie support, or to retain application state?

**Comment by franciscolourenco** [comment]
Retain application state. Third-party cookie support seems to be a concern raised in Auth0 documentation in a few places.

**Comment by adamjmcgrath** [comment]
Hi @franciscolourenco - for a similar reason to #308 we've decided not to support this feature. 

There's nothing stopping you implementing this yourself, but it's out of scope for the library.
