### ISSUE TITLE
Support for Hybrid flow

### ISSUE THREAD

**Issue by PeterGFernandez** [auth0/auth0-spa-js#314]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Support for Hybrid flow (i.e. `response_type='code id_token'`)

### Describe the ideal solution

> A clear and concise description of what you want to happen.

Hybrid flow supported where an `id_token` will provided as a URL parameter as part of the callback, in addition to the authorization `code`

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

Currently no alternatives seem to be available

### Additional context

> Add any other context or screenshots about the feature request here.

Can offer performance improvement in a number of situations, and will still conform to best practice (as discussed here: https://auth0.com/blog/oauth2-implicit-grant-and-spa/)

**Comment by stevehobbsdev** [comment]
Hybrid support is not planned for this library as it was built specifically to make use of the [Auth Code + PKCE flow](https://auth0.com/docs/flows/concepts/auth-code-pkce). However, an alternative is to use [Auth0.js](https://github.com/auth0/auth0.js) which does use the hybrid flow.

It's an older SDK which requires more work from the developer, but is more flexible and will support the hybrid flow.
