### ISSUE TITLE
'utf8' TextDecoder Error from 'fast-text-encoding' dependency on Edge

### ISSUE THREAD

**Issue by chris-freightweb** [auth0/auth0-spa-js#316]
### Description

During the authentication flow of our React app, we are getting a very strange error but only on Edge. The page throws the error
`RangeError: Failed to construct 'TextDecoder': The encoding label provided ('utf8') is invalid.`
I did quite a bit of research which lead me to [this](https://github.com/samthor/fast-text-encoding/issues/4) issue on fast-text-encoding which is a dependency of this package. Basically, it's checking for 'utf-8' explicitly, but 'utf8' should also be supported. I'm really surprised more people aren't hitting this and I'm wondering if that means we're doing something weird but I think our interaction with auth0 is pretty standard. Additionally, that package had a PR opened in March that fixes that bug but it doesn't appear it is being actively maintained. 

### Reproduction

We are using a custom auth hook on a PrivateRoute WrapperComponent. The hook uses the following code to setup the Auth Provider
```
export const Auth0Provider = ({
  children,
  onRedirectCallback = DEFAULT_REDIRECT_CALLBACK,
  logout_redirect_uri,
  ...initOptions
}) => {
  const [isAuthenticated, setIsAuthenticated] = useState();
  const [user, setUser] = useState();
  const [auth0Client, setAuth0] = useState();
  const [loading, setLoading] = useState(true);
  const [popupOpen, setPopupOpen] = useState(false);

  useEffect(() => {
    const initAuth0 = async () => {
      const auth0FromHook = await createAuth0Client(initOptions);
      setAuth0(auth0FromHook);

      if (window.location.search.includes('code=')) {
        const { appState } = await auth0FromHook.handleRedirectCallback();
        onRedirectCallback(appState);
      }

      const isAuthenticated = await auth0FromHook.isAuthenticated();

      setIsAuthenticated(isAuthenticated);

      if (isAuthenticated) {
        const user = await auth0FromHook.getUser();
        setUser(user);
      }

      // Respond to token requests
      _auth0Client = auth0FromHook;
      pendingRequests.forEach(({ resolve, reject }) =>
        isAuthenticated
          ? getTokenSilently()
              .then(resolve)
              .catch(reject)
          : resolve(),
      );
      pendingRequests = [];

      setLoading(false);
    };
    initAuth0();
    // eslint-disable-next-line
  }, []);

  const loginWithPopup = async (params = {}) => {
    setPopupOpen(true);
    try {
      await auth0Client.loginWithPopup(params);
    } catch (error) {
      console.error(error);
    } finally {
      setPopupOpen(false);
    }
    const user = await auth0Client.getUser();
    setUser(user);
    setIsAuthenticated(true);
  };

  const handleRedirectCallback = async () => {
    setLoading(true);
    await auth0Client.handleRedirectCallback();
    const user = await auth0Client.getUser();
    setLoading(false);
    setIsAuthenticated(true);
    setUser(user);
  };
  return (
    <Auth0Context.Provider
      value={{
        isAuthenticated,
        user,
        loading,
        popupOpen,
        loginWithPopup,
        handleRedirectCallback,
        getIdTokenClaims: (...p) => auth0Client.getIdTokenClaims(...p),
        loginWithRedirect: (...p) => auth0Client.loginWithRedirect(...p),
        getTokenSilently: (...p) => auth0Client.getTokenSilently(...p),
        getTokenWithPopup: (...p) => auth0Client.getTokenWithPopup(...p),
        logout: (...p) =>
          auth0Client.logout({ returnTo: logout_redirect_uri, ...p }),
        logoutRaw: (...p) => auth0Client.logout(...p),
      }}
    >
      {children}
    </Auth0Context.Provider>
  );
};
```
Navigating to any route with PrivateRoute triggers the error,
`RangeError: Failed to construct 'TextDecoder': The encoding label provided ('utf8') is invalid.`

The issue was not reproducible on any browser except Edge and IE

### Environment

- **Version of this library used:** 1.6.0
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** Edge on Windows (Beta version of Edge for Mac does NOT reproduce)
- **Other modules/plugins/libraries that might be involved:** fast-text-encoding

**Comment by stevehobbsdev** [comment]
Let me evaluate this and get back to you.

**Comment by chris-freightweb** [comment]
After playing with this a bit, the issue appears to go away when I revert auth0-spa-js to 1.0.0. I'm not sure at what point this broke as I didn't try all the versions, but I do see it on 1.6.0 and 1.5.0

**Comment by chris-freightweb** [comment]
Oh.. nvm. Reverting to 1.0.0 only 'fixed' the issue because TextEncoder isn't actually polyfilled in that version so other functionality doesn't work on Edge for that. Back to square one :( 
It still feels like something is funky in our project because this was explicitly fixed and others would've certainly have experienced this before now. I'm wondering if there's a weird interaction between other dependencies within our project that are causing the TextEncoder polyfill to be called with 'utf8' instead of 'utf-8' but I don't know enough about how polyfill, react, and yarn packages interact

**Comment by chris-freightweb** [comment]
I was able to find a workaround by doing the polyfill for TextEncoder that accepts the correct encodings (utf-8 and utf8) before importing auth0-spa-js so that the erroneous polyfill from fast-text-encoding never executes

**Comment by stevehobbsdev** [comment]
Thanks for reporting back!

**Comment by fcandi** [comment]
> I was able to find a workaround by doing the polyfill for TextEncoder that accepts the correct encodings (utf-8 and utf8) before importing auth0-spa-js so that the erroneous polyfill from fast-text-encoding never executes

Hi @chris-freightweb I have the same problem. Can you explain to me what you exactly mean with "doing the polyfill for TextEncode"?

Thx,

Andreas

**Comment by fcandi** [comment]
I just tried the last versions and for me the latest version that works is 1.0.1. Beginning of 1.0.2, the above error occurs.

Andreas

**Comment by chris-freightweb** [comment]
Hey Andreas. I just checked and it looks like the author of fast-text-encoding actually fixed the issue last night. So @stevehobbsdev if you guys update auth0-spa-js to use fast-text-encoding 1.0.1 instead of 1.0.0, this issue would be resolved without any workarounds (https://www.npmjs.com/package/fast-text-encoding)

**Comment by chris-freightweb** [comment]
But if you don't want to wait for that, you could import fast-text-encoding 1.0.1 in your project and simply import that before you import auth0-spa-js. Then the polyfill will work properly... I _think_...
e.g.
```
import 'fast-text-encoding';
import createAuth0Client from '@auth0/auth0-spa-js';
```

**Comment by fcandi** [comment]
@chris-freightweb thx a lot, you saved my day. Its working just fine now!!

Have a nice day,

Andreas

**Comment by stevehobbsdev** [comment]
Thanks for the heads up @chris-freightweb , raised #371 to fix this.
