### ISSUE TITLE
Custom query parameters with getTokenSilently

### ISSUE THREAD

**Issue by nkete** [auth0/auth0-spa-js#317]
### Description

Custom query parameters are not appended to the `/authorize` url when used with `getTokenSilently` like they are when used with `loginWithRedirect`.

`loginWithRedirect({ foo: 'bar' });` will produce `/authorize?scope&audience...&foo=bar`
`getTokenSilently({scope, audience, foo: 'bar'});` will produce `/authorize?scope&audience`.

Looking at [GetTokenSilentlyOptions](https://github.com/auth0/auth0-spa-js/blob/902062723784d29b1bbeac9ba634071a51e38c4b/src/global.ts#L166) it support [key:value](https://github.com/auth0/auth0-spa-js/blob/902062723784d29b1bbeac9ba634071a51e38c4b/src/global.ts#L187) pairs.

[Pull request](https://github.com/auth0/auth0-spa-js/pull/318)

### Reproduction

Add a custom query parameter to `getTokenSilently` like so (`scope` and `audience` are required in this case) and inspect the url in the network tab.
```js
auth0.getTokenSilently({
    scope,
    audience,
    foo: 'bar',
});
```

### Environment

- **Version of this library used:** 1.6.0

**Comment by stevehobbsdev** [comment]
Thanks for raising this. We'd welcome a PR to help push this through, if that's something you'd be interested in doing.

**Comment by stevehobbsdev** [comment]
PR has been merged and awaiting release - thanks again
