### ISSUE TITLE
Logging message is misleading when iat is before browser clock time

### ISSUE THREAD

**Issue by spinfooser** [auth0/auth0-spa-js#322]
### Description

When a failure occurs in validating the iat in a recently verified jwt, the error messages include leeway time in them. This is misleading, and can make developers who use this tool think that the leeway feature isn't working properly.

Log message: `Issued At (iat) claim error in the ID token; current time (${now}) is before issued at time (${iatDateWithLeewaySubtracted})`

[Relevant line of code which is logging the wrong timestamp.](https://github.com/auth0/auth0-spa-js/blob/2ace866d33cefc8140dceae7437e2a9e61469564/src/jwt.ts#L180)

### Reproduction

1. Get a valid token
2. Change computer time to be 2 minutes behind the current time.
3. Try to verify the old token you have
4. You will see the error message showing a ~1 minute time difference due to the leeway being added to the 2nd message. Expected: It should be 2 minutes difference since that is how far your clock is behind.

### Environment

- **Version of this library used:** 1.6.0
- **Version of the platform or framework used, if applicable:** React 16.9
- **Other relevant versions (language, server software, OS, browser):** All browsers should be effected.

**Comment by lbalmaceda** [comment]
AFAIK this was intentional. We need to include the leeway in either the "current clock" value or the "claim's date" value. In the end, what we compare (and you see on the message) are 2 different date-times that one is before/after the other.

**Comment by spinfooser** [comment]
The issue isn't the way this code does the math, its the way it logs the result.

> <now_time> is before issued at time <timestamp>

This log message is misleading because the original "issued at time" in the jwt is actually 1 minute different from the value logged. This value isn't the issued_at time, its the issued_at time with leeway subtracted from it. 

You could put that in the error message if you want, but it's not accurate to label this as issued_at.

**Comment by lbalmaceda** [comment]
I understand. My point is we need to include the leeway on the message as well because it's being taken into consideration for the time check. If we just print the base clock and the base claim value, you may also think the leeway is not being considered. Unfortunately, if we want to keep the message short, we either do that base+leeway addition for the "clock" value or the "claim" value (current behavior).

**Comment by spinfooser** [comment]
Yeah, both perspectives are important. I do agree with that. Well maybe just changing the text label would be enough? You could do something like:

`Issued At (iat) claim error in the ID token; current time (${now}) is outside of the allowed issued at range (${iat} minus ${leewaySeconds})`

**Comment by lbalmaceda** [comment]
@spinfooser Let me raise this internally for discussion and see what the outcome is. I will come back to you next week.

**Comment by stevehobbsdev** [comment]
@spinfooser After discussing this internally, we've taken the decision to remove the `iat` value check altogether, which should make this a non-issue. We will still be checking for presence and type, but will not be comparing the issued-at time.

Please keep your eyes peeled for a PR coming in the very near future.
