### ISSUE TITLE
Cannot get user scope in access token (GitHub API)

### ISSUE THREAD

**Issue by taniarascia** [auth0/auth0-spa-js#323]
### Description

I expect to be able to call the GitHub API and have access to the scopes and permissions the user granted the application. Instead I get a 401.

### Reproduction

```js
  const getRepos = () => {
    const fn = async () => {
      const accessToken = await getTokenSilently()

      try {
        const response = await axios.get('https://api.github.com/user/repos', {
          headers: {
            Authorization: 'token ' + accessToken,
          },
        })

        console.log(response)
      } catch (error) {
        console.log(error)
      }
    }

    fn()
  }
```

Response:

```
message: "Bad credentials"
documentation_url: "https://developer.github.com/v3"
```

I've tried adding audience and adding scope (`repo`) to `getTokenSilently()`, to `createAuth0Client({})`, but to no avail.

I can see when I do that, the `/authorize` endpoint has the scope:

```
https://,e.auth0.com/authorize?client_id=xxx
&redirect_uri=http://localhost:3000
&scope=openid%20profile%20email%20repo
&response_type=code
&response_mode=web_message
&state=xxx
&nonce=xxx
&code_challenge=xxx
&code_challenge_method=S256
&prompt=none
&auth0Client=xxx
```

But the `/token` endpoint never returns with any scope.

```
access_token: "xxx"
id_token: "xxx"
scope: "openid profile email"
expires_in: 86400
token_type: "Bearer"
```

Everything is set up online, and all permissions are granted from the user. Authentication and login works fine. I just can't get the proper scope to access the private GitHub API, despite scopes being granted.

### Environment

```
"@auth0/auth0-spa-js": "^1.3.2",
"react": "^16.9.0",
```

**Comment by stevehobbsdev** [comment]
Hi @taniarascia, thanks for your patience.

Unfortunately the access token you receive from Auth0 is not one that can be used against the GitHub API. You can use the management API to retrieve such a token but you are only able to do that from a confidential client (like a backend web app) and not from a public client like an SPA.

We have some [documentation on calling third-party IDP APIs](https://auth0.com/docs/connections/calling-an-external-idp-api) and some ways you can work around this to get what you need, but unfortunately it's not something that can be done from your SPA at this time.

I'll close this for now but please feel free to continute the conversation if you need anything further.

**Comment by altschuler** [comment]
For anyone else stumbling upon this in search of how to get the *id token*, see https://github.com/auth0/auth0-spa-js/pull/270#issuecomment-549724603
