### ISSUE TITLE
User is logged out when page is refreshed in Safari 13.0.4

### ISSUE THREAD

**Issue by bergdaniel** [auth0/auth0-spa-js#324]
### Description

Running sample project (login) on MacOS 10.15.2, using Safari 13.0.4. When refreshing the page after having successfully logged in the user is logged out.

Works fine on Chrome.

### Reproduction

Download the sample project (login) and run it on Safari 13.0.4 using MacOS 10.15.2. Login, refresh page.

### Environment

Sample project auth0-react-01-login, version 0.1.0. Safari 13.0.4 MacOS 10.15.2.

**Comment by stevehobbsdev** [comment]
Unfortanately you're running into Safari's ITP technology which prevents the transmission of third-party tracking cookies. While Auth0 does not issue tracking cookies, the mechanism that we use to silently log the user in after a page refresh gets caught up in the same net. You can read [more detail on our Community forums](https://community.auth0.com/t/failed-silent-auth-login-required/33165/25).

We are working on some ideas to mitigate this which we will be putting out as a beta shortly. You can also mitigate this by using Auth0's [Custom Domains](https://auth0.com/docs/custom-domains) feature, as in that case your app and the Auth0 login page can run on the same domain. However, I want to point out that this is a paid feature.

**Comment by bergdaniel** [comment]
Awesome, thanks @stevehobbsdev!
