### ISSUE TITLE
Error: Invalid State from Callback on a single device in 1 browser

### ISSUE THREAD

**Issue by dmzza** [auth0/auth0-spa-js#328]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I recently encountered in a bug using only Safari and only on my own computer that completely prevents me from essentially being logged in.

When I login and I get redirected to my app's callback, my app returns this error from Auth0:
`Error: Invalid State`
I checked the url, and it does have `code` and `state` get parameters. 

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

This is nearly impossible to reproduce, because I have only seen it on one computer (my own) in one browser (Safari) in both normal and private modes. 

It had been working fine for a while and then suddenly it stopped, although it works in Safari on any other Mac that I've tried. 

If I try to login again, I get redirected back to the same page because auth0 already thinks I'm logged in. So I have to logout before I can try logging in again.

### Environment

> Please provide the following:

- **Version of this library used:** 1.6.0
- **Version of the platform or framework used, if applicable:** Ember.js 3.15
- **Other relevant versions (language, server software, OS, browser):** Safari 13.0.4, macOS 10.15.2
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Difficult to determine what this is if it's isolated to one machine but is working on the others.

When your app gets the callback, it looks for a cookie on your machine that contains the state in the key, it should start something like: `a0.spajs.txs.<state>`. This is how the SDK is able to retrieve state information after performing the login. Can you confirm that this cookie exists on the broken machine?

**Comment by stevehobbsdev** [comment]
Closing this for now, but if you find out anything else as to what might be causing this, please continue the discussion.
