### ISSUE TITLE
Verification Email triggers handleRedirectCallback

### ISSUE THREAD

**Issue by NerdCowboy** [auth0/auth0-spa-js#335]
### Description
When a user clicks on the email verification link, it will take them to the site with the following url:
https://example.com/?supportSignUp=true&supportForgotPassword=true&email=example%40gmail.com&message=Your%20email%20was%20verified.%20You%20can%20continue%20using%20the%20application.&success=true&code=success#

Using the auth0-spa boilerplate, this will trigger `auth0FromHook.handleRedirectCallback()` and authorization will end up hanging and an `Invalid State` error is shown in the console.

The offending code is this:
```
if (window.location.search.includes('code=')) {
        const { appState } = await auth0FromHook.handleRedirectCallback()
        onRedirectCallback(appState)
      }
```

#### Workaround
If I exclude `code=success` it will work
```
if (
        window.location.search.includes('code=') &&
        !window.location.search.includes('code=success')
      ) {
        const { appState } = await auth0FromHook.handleRedirectCallback()
        onRedirectCallback(appState)
      }
```

### Reproduction

1. Make sure email verification is required in auth0 and use React boilerplate for auth0-spa
2. Sign up for a new account 
3. Click on the "verify email address" link in the verification email
4. Open console and view the `Invalid State` error

### Environment

> Please provide the following:

- **Version of this library used:**  1.6.0
- **Version of the platform or framework used, if applicable:** React/Gatsby
- **Other relevant versions (language, server software, OS, browser):** 
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
@NerdCowboy Thanks for raising this. This will be a fix for the React sample repo rather than this SDK, so I will close this for now and raise a PR on the sample itself.
