### ISSUE TITLE
Using .getTokenSilently() in created - Vue

### ISSUE THREAD

**Issue by Plainnn** [auth0/auth0-spa-js#344]
### Description

When trying to call the getTokenSilently method in the vue js created method an error occurs, but i need to call the method as soon as possible to determine what to show on the page

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

`async created() {
    // Get the access token from the auth wrapper
    const token = await this.$auth.getTokenSilently();
    console.log(token)
}
`
This gives me the error of 
![image](https://user-images.githubusercontent.com/42492521/73469894-f4c96100-437e-11ea-8f99-cbc8666f59a9.png)

### Environment

> Please provide the following:

- Version of this library used: 1.6.2
- Version of the platform or framework used, if applicable: vue 2.6.10
- Other relevant versions (language, server software, OS, browser):  Windows 10, All Browsers

**Comment by NotMyself** [comment]
Hi @Plainnn,

Based on your description and the error you are getting, it seems the auth service has not been initialized when the created method gets called. There is some startup cost for creating that service client-side.

Are you following the [quickstart guidance](https://auth0.com/docs/quickstart/spa/vuejs)?

One technique that I use is to provide default anonymous user information. The page is rendered with this and then when the user becomes available I lean on the vue reactivity model to update the page. Here is an example of one of my user widgets.

```vue
<template>
  <li role="presentation" class="dropdown">
    <a
      class="dropdown-toggle"
      data-toggle="dropdown"
      href="#"
      role="button"
      aria-haspopup="true"
      aria-expanded="false"
    >
      <strong>{{ user.name }}</strong>
      &nbsp;
      <img :src="user.picture" alt="user" class="img-circle" width="36" />
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li role="separator" class="divider"></li>
      <li v-if="!$auth.isAuthenticated && !$auth.loading">
        <a href="#" @click.prevent="login">
          Log In <span class="pull-right glyphicon glyphicon-log-in"></span>
        </a>
      </li>
      <li v-if="$auth.isAuthenticated && !$auth.loading">
        <a href="#" @click.prevent="logout">
          Log Out <span class="pull-right glyphicon glyphicon-log-out"></span>
        </a>
      </li>
    </ul>
  </li>
</template>

<script>
import defaultAvatar from '@/assets/user.png';
export default {
  name: 'UserWidget',
  computed: {
    user() {
      if (this.$auth.user) {
        return this.$auth.user;
      } else {
        return {
          name: 'Anonymous',
          picture: defaultAvatar
        };
      }
    }
  },
  methods: {
    login() {
      this.$auth.loginWithRedirect();
    },
    logout() {
      this.$auth.logout();
      this.$router.push({ path: '/' });
    }
  }
};
</script>
```

**Comment by Plainnn** [comment]
> Hi @Plainnn,
> 
> Based on your description and the error you are getting, it seems the auth service has not been initialized when the created method gets called. There is some startup cost for creating that service client-side.
> 
> Are you following the [quickstart guidance](https://auth0.com/docs/quickstart/spa/vuejs)?
> 
> One technique that I use is to provide default anonymous user information. The page is rendered with this and then when the user becomes available I lean on the vue reactivity model to update the page. Here is an example of one of my user widgets.
> 
> ```
> <template>
>   <li role="presentation" class="dropdown">
>     <a
>       class="dropdown-toggle"
>       data-toggle="dropdown"
>       href="#"
>       role="button"
>       aria-haspopup="true"
>       aria-expanded="false"
>     >
>       <strong>{{ user.name }}</strong>
>       &nbsp;
>       <img :src="user.picture" alt="user" class="img-circle" width="36" />
>       <span class="caret"></span>
>     </a>
>     <ul class="dropdown-menu">
>       <li role="separator" class="divider"></li>
>       <li v-if="!$auth.isAuthenticated && !$auth.loading">
>         <a href="#" @click.prevent="login">
>           Log In <span class="pull-right glyphicon glyphicon-log-in"></span>
>         </a>
>       </li>
>       <li v-if="$auth.isAuthenticated && !$auth.loading">
>         <a href="#" @click.prevent="logout">
>           Log Out <span class="pull-right glyphicon glyphicon-log-out"></span>
>         </a>
>       </li>
>     </ul>
>   </li>
> </template>
> 
> <script>
> import defaultAvatar from '@/assets/user.png';
> export default {
>   name: 'UserWidget',
>   computed: {
>     user() {
>       if (this.$auth.user) {
>         return this.$auth.user;
>       } else {
>         return {
>           name: 'Anonymous',
>           picture: defaultAvatar
>         };
>       }
>     }
>   },
>   methods: {
>     login() {
>       this.$auth.loginWithRedirect();
>     },
>     logout() {
>       this.$auth.logout();
>       this.$router.push({ path: '/' });
>     }
>   }
> };
> </script>
> ```

Hi, thanks for the quick reply.

Is it possible to delay it? This is my code, maybe im doing something wrong

  async created() {

    let token = null;
    if (this.$auth) {
      token = await this.$auth.getTokenSilently();
    } else {
      return false;
    }
    const { data } = await axios.get('https://lol-stat.eu.auth0.com/userinfo', {
      headers: {
        Authorization: `Bearer ${token}` // send the access token through the 'Authorization' header
      }
    });
    //Get Unique ID from auth0
    const uniqueId = data['http://localhost:8080/uuid'];
  
    this.globalId = uniqueId;

    //Check if the Unique ID has been stored in the database, if it has
    //Return the new user
    const postMsg = await axios.post('/api/v1/users/add', {
      uniqueid: uniqueId
    });
    /* eslint-disable no-console */
    console.log(postMsg.data);
    //Check the returned user, and see if the user has already added a friend
    // If he has friends, show the data. If not, show input to add friends.
    if (postMsg.data.users.friendNames.length > 0) {
      this.data = postMsg.data.users.friendNames;
      //Show the dataaa
    } else {
      //Show the input name
    }
  }

**Comment by NotMyself** [comment]
You definitely have an order of operation issue. Have you had a look at the [quickstart guidance](https://auth0.com/docs/quickstart/spa/vuejs)?

**Comment by Plainnn** [comment]
> You definitely have an order of operation issue. Have you had a look at the [quickstart guidance](https://auth0.com/docs/quickstart/spa/vuejs)?

Thanks, i was **really** misunderstanding eh, but i'm still now facing an issue. If i use this code, it works (on auto refresh from vue/nodemon, or by hitting a link to shows the same component that i'm already on) but if i refresh F5 it returns back null, how can i avoid that?

`  if (this.$auth.user) {
      console.log(this.$auth.user['http://localhost:8080/uuid']);
    }`
