### ISSUE TITLE
No error description

### ISSUE THREAD

**Issue by ttiras** [auth0/auth0-spa-js#346]
Hello,
I am on the latest version and my local app crashes with the error of failed silent auth. But on the logs there is no further definition of the error, i only get: "error": {
      "message": "Login required",
      "oauthError": "login_required",
      "type": "oauth-authorization"
    }
i am using localstorage for catchelocation and still not working. 
Is the only option here switching to a custom domain? which means paid subscription.Free tiers are not able to use auth0 any more?

**Comment by stevehobbsdev** [comment]
@ttiras No absolutely not, using custom domains is one option but you should still be able to use silent auth if you are using local storage as the cache location.

Can you let me know which version of the SDK you have installed, and could you show me some code to see how you're configuring the SDK in your app?

**Comment by ttiras** [comment]
Thank you.
i installed 1.7.2 beta and tried also o
with 1.6.3.

auth0_config.json: 

{
  "domain": "dev-.............eu.auth0.com",
  "clientId": "5qTdl................................................",
  "redirect_uri": "https://localhost:8080",
  "audience": "https://........herokuapp.com/v1/............",
  "cacheLocation": "localstorage"
}

**Comment by ttiras** [comment]
and auth0-wrapper.js: 
import React, { useState, useEffect, useContext } from "react";
import createAuth0Client from "@auth0/auth0-spa-js";

const DEFAULT_REDIRECT_CALLBACK = () =>
  window.history.replaceState({}, document.title, window.location.pathname);

export const Auth0Context = React.createContext();
export const useAuth0 = () => useContext(Auth0Context);
export const Auth0Provider = ({
  children,
  onRedirectCallback = DEFAULT_REDIRECT_CALLBACK,
  ...initOptions
}) => {
  const [isAuthenticated, setIsAuthenticated] = useState();
  const [user, setUser] = useState();
  const [auth0Client, setAuth0] = useState();
  const [loading, setLoading] = useState(true);
  const [popupOpen, setPopupOpen] = useState(false);

  useEffect(() => {
    const initAuth0 = async () => {
      const auth0FromHook = await createAuth0Client(initOptions);
      setAuth0(auth0FromHook);

      if (window.location.search.includes("code=")) {
        const { appState } = await auth0FromHook.handleRedirectCallback();
        onRedirectCallback(appState);
      }

      const isAuthenticated = await auth0FromHook.isAuthenticated();

      setIsAuthenticated(isAuthenticated);

      if (isAuthenticated) {
        const user = await auth0FromHook.getUser();
        setUser(user);
      }

      setLoading(false);
    };
    initAuth0();
    // eslint-disable-next-line
  }, []);

  const loginWithPopup = async (params = {}) => {
    setPopupOpen(true);
    try {
      await auth0Client.loginWithPopup(params);
    } catch (error) {
      console.error(error);
    } finally {
      setPopupOpen(false);
    }
    const user = await auth0Client.getUser();
    setUser(user);
    setIsAuthenticated(true);
  };

  const handleRedirectCallback = async () => {
    setLoading(true);
    await auth0Client.handleRedirectCallback();
    const user = await auth0Client.getUser();
    setLoading(false);
    setIsAuthenticated(true);
    setUser(user);
  };
  return (
    <Auth0Context.Provider
      value={{
        isAuthenticated,
        user,
        loading,
        popupOpen,
        loginWithPopup,
        handleRedirectCallback,
        getIdTokenClaims: (...p) => auth0Client.getIdTokenClaims(...p),
        loginWithRedirect: (...p) => auth0Client.loginWithRedirect(...p),
        getTokenSilently: (...p) => auth0Client.getTokenSilently(...p),
        getTokenWithPopup: (...p) => auth0Client.getTokenWithPopup(...p),
        logout: (...p) => auth0Client.logout(...p)
      }}
    >
      {children}
    </Auth0Context.Provider>
  );
};

**Comment by stevehobbsdev** [comment]
@ttiras Yes this will only affect the beta, as the local storage feature isn't available on the stable release yet.

I suspect this is because when you call `createAuth0Client`, it calls `getTokenSilently` setting `ignoreCache: true`. This worked fine when everything was just stored in memory, but now that we have local storage involved, we could change that flag so that it uses the cache if there's one available, so it thinks you don't have an access token.

As a workaround while this is being tested and fixed, can you try manually calling `getTokenSilently` without any arguments after you call `createAuth0Client`? This should get you into the right state.

**Comment by ttiras** [comment]
@stevehobbsdev 
On 1.7.0 beta.2, Auth0Provider component state, cachelocation is still memory. 
i am passing the option for localstorage in auth0_config.json as you can see above.

**Comment by stevehobbsdev** [comment]
I'm about to bring in #352 which may help with this. It'll be released on the beta channel, I'll report here when it's out.

**Comment by ttiras** [comment]
Thank you very much. It is working now with some workarounds. I appreciate your efforts.

**Comment by stevehobbsdev** [comment]
#352 has now been released as `@auth0/auth0-spa-js@1.7.0-beta.3`. Please try working with that version, and feel free to continue the discussion if you uncover any further issues.
