### ISSUE TITLE
AnomalyDetected invalid state from usernamepassword/login endpoint

### ISSUE THREAD

**Issue by tomgranerod** [auth0/auth0-spa-js#350]
### Description

So I've implemented a single sign out solution, somewhat based on this idea: https://github.com/auth0-samples/auth0-single-sign-out-sample
So when the single sign out app calls back to a logout.html file through the iframe I change a localStorage property and listen to a storageEvent across all tab instances of the different applications it calls back to - which in turn calls the auth0-spa-js logout method with a returnTo to the relevant url for the app.

Now I haven't been able to exactly determine a pattern here, but very often when I try to sign in again in one of these tabs I get a 403 forbidden from usernamepassword/login with the following response:

`{
  statusCode: 403
  description: "Invalid state"
  name: "AnomalyDetected"
  code: "access_denied"
}`

I've also tried a websocket approach, where when you sign out from one instance a message would be sent to the server which in turn will emit a message to all relevant clients and call auth0-spa-js' logout method when received. With this approach I also intermittently get the above issue.

So the issue seems to appear when multiple logouts or rather login screens are generated at once.

Looking at the request url sent to the hosted login page, there doesn't seem to be any obvious differences, except the state being unique for each of them of course.

Also Anomaly Detection is NOT enabled in the Auth0 tenant.

Any ideas on how to further investigate this?

### Environment

- **Version of this library used:** 1.4.2
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** Chrome, IE11
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
> Any ideas on how to further investigate this?

I don't, unfortunately. I think distilling this down to something you can reproduce reliably would be key here. If you can share that sample and some repro steps with us, that would allow us to help debug this further.

Closing this for now, but feel free to re-open when you have a sample.
