### ISSUE TITLE
Custom Claims in TypeScript

### ISSUE THREAD

**Issue by picosam** [auth0/auth0-spa-js#351]
In the definition of `IdToken` https://github.com/auth0/auth0-spa-js/blob/4e8663d875a361fa02954b5adc45c98865790f1b/src/global.ts#L255 how do we accommodate for the custom claims sometimes returned in the ID token; for instance, when injected in there by a custom Auth0 Rule?

**Comment by stevehobbsdev** [comment]
@picosam Right now you'll have to cast the thing implementing this interface to `any`, although if you have any ideas around this I would love to hear them.

Closing this but feel free to continue the discussion.

**Comment by picosam** [comment]
@stevehobbsdev I submitted a very simple pull request to remedy this, but it's failing for some reason related to the `email_verified` field being a `boolean` instead of a `string`.
