### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by alexander-daniel** [auth0/auth0-spa-js#36]
Hello! I was using the old quickstart for `auth0-js` until today it seems the docs have swapped over to the new `auth0-spa-js` ones -- no problem.

I was wondering if you had any plans to release an example for the spa module in typescript.

Thanks!

**Comment by luisrudge** [comment]
Do you want a specific SPA sample? Since this library is written with typescript, it should basically just work with all the intellisense etc

**Comment by alexander-daniel** [comment]
Ill give it another go, thanks. Might just be implementation specific issues I'm facing. Thanks for the reply!
