### ISSUE TITLE
Can't retrieve an entire user record using this library.

### ISSUE THREAD

**Issue by Cobalt-Master** [auth0/auth0-spa-js#360]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.
I went through the "migration" instructions to use this library but it turns out it does a fraction of what I need it to do. Is there some reason it doesn't allow me to read and set a user's meta data? What purpose does the SPA SDK serve if it doesn't support the fundamental usefulness of the Auth0 product? When can I expect to have this bug fixed so I can access my user records using the SPA SDK?

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.

**Code example follows description**

After implementing the step by step Quickstart for the SPA SDK I was never able to access all of my user records. Clearly this is a broken implementation since accessing and modifying my user's data is a critical feature of Auth0.

Below is the step in the Quickstart where I should be presented with my user's `metadata` property but I'm left with nothing. Additionally, no documentation exists that allows me to update the `metadata` in anyway.

```
// src/components/Profile.js

import React, { Fragment } from "react";
import { useAuth0 } from "../react-auth0-spa";

const Profile = () => {
  const { loading, user } = useAuth0();

  if (loading || !user) {
    return <div>Loading...</div>;
  }

  return (
    <Fragment>
      <img src={user.picture} alt="Profile" />

      <h2>{user.name}</h2>
      <p>{user.email}</p>
      <code>{JSON.stringify(user, null, 2)}</code>
    </Fragment>
  );
};

export default Profile;
```

### Environment

> Please provide the following:

- **Version of this library used:** v1.6.4
- **Version of the platform or framework used, if applicable:** If you mean the Auth0 dashboard I'm not sure.
- **Other relevant versions (language, server software, OS, browser):** NodeJS 12.x
- **Other modules/plugins/libraries that might be involved:** ReactJS.

**Comment by larsf96** [comment]
> and set a user's meta data?
Are you talking about the user's app_metadata or user_metadata?

As mentioned in the migration guide (https://auth0.com/docs/libraries/auth0-spa-js/migrate-from-auth0js), updating user attributes and metadata is not (yet) supported by this library.
But you can as well read the whole user's profile, including its metadata.

**Comment by stevehobbsdev** [comment]
@Cobalt-Master You should definitely be able to access the properties in your sample without doing any extra work. However, it's true that by default Auth0 only returns a subset of your entire user profile, and that's not a thing that's specific to this SDK. You can use our [Rules engine](https://auth0.com/docs/rules) to extend the user profile object and return whatever metadata you like.

As @larsf96 , you cannot update `metadata` using this library.

**Comment by stevehobbsdev** [comment]
Closing this for now but if you have any further questions or discussion points, please feel free to continue.
