### ISSUE TITLE
Login only, disable sign-up

### ISSUE THREAD

**Issue by nojaf** [auth0/auth0-spa-js#366]
### Describe the problem you'd like to have solved

I don't think this is possible today, so I would like to have a login only functionality.
I'm targeting a limited number of users (which I later grant a role) and my application will be useless unless you have a certain role.
So it is a bit pointless to sign up and I don't want uninvited people to sign up.

### Describe the ideal solution

If the `loginWithRedirect` takes an additional parameter that disables the option to sign up.

## Alternatives and current work-arounds

My workaround now is securing everything with roles and permissions.
This works but there can be a lot of users that shouldn't exist in the first place.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by stevehobbsdev** [comment]
@nojaf This is more of a concern about how you configure the Auth0 login page and not something you would configure in the SDK itself, so I will close this.

However, can you tell me whether you're using the classic login experience or the new one? (Go to your Auth0 Dashboard > Universal Login to find out). Then I can try to route you to the right place to configure it.

**Comment by nojaf** [comment]
Hey @stevehobbsdev, I'm using the classic login page.
I'm guessing I need to change the html to achieve what I want?

**Comment by stevehobbsdev** [comment]
Yes - as you are using Lock, you can choose to customize the template from that same page. There you can change the configuration options for Lock and specify `allowSignup: false` ([this is also documented here](https://auth0.com/docs/libraries/lock/v11/configuration#allowsignup-boolean-)).

**Comment by nojaf** [comment]
Many thanks @stevehobbsdev

**Comment by stevehobbsdev** [comment]
@nojaf No problem! Let me know if you have any more questions

**Comment by hacknaked** [comment]
@stevehobbsdev Any way to do this using the new login (not the classic one)
