### ISSUE TITLE
Auth0Client handleRedirectCallback redirect_uri default to window.location.origin if not set in transaction cookie

### ISSUE THREAD

**Issue by albertlockett** [auth0/auth0-spa-js#373]
### Describe the problem you'd like to have solved

I was wondering about if it would be possible in Auth0Client to have the handleRedirectCallback method use the default value for the redirect_uri if it isn't set in the transaction cookie. 

When the code calls loginWithRedirect(), a cookie gets set for the transaction. In version 1.2.4 the cookie doesn't have the redirct_uri parameter and so when handleRedirectCallback() is eventually called, it doesn't pass redirect_uri to the utils/oathToken method and so the default redirect_uri is used.

In version 1.6.3, the redirect_uri param is read as a value from the transaction cookie.

Compare here (1.2.4 no redirect_uri param)
https://github.com/auth0/auth0-spa-js/blob/prepare/1.2.4/src/Auth0Client.ts#L213 
https://github.com/auth0/auth0-spa-js/blob/prepare/1.2.4/src/Auth0Client.ts#L249
https://github.com/auth0/auth0-spa-js/blob/prepare/1.2.4/src/utils.ts#L173

1.6.3 (with redirect_uri param)
https://github.com/auth0/auth0-spa-js/blob/v1.6.3/src/Auth0Client.ts#L132
https://github.com/auth0/auth0-spa-js/blob/v1.6.3/src/Auth0Client.ts#L289

This can cause a problem in an upgrade scenario. Here is what can what could happen:

- users request the page at http://my-app.com/ and get a cached version, the code calls loginWithRedirect() and the old transaction cookie format (no redirect_uri) is set
- the user logs in at the universal login page, and is redirected back to the application http://my-app.com/callback?code=code&state=state

- if the browser doesn't get the cached version on the callback route, the new sdk will try to use the old transaction cookie, and it will send redirect_uri=undefined into the utils/oauthToken method (which will cause an error):
`Uncaught (in promise) Error: Invalid redirect_uri. Expected type 'string' but found type undefined.`

### Describe the ideal solution

The Auth0Client handleRedirectCallback method could check if the transaction has a redirect_uri, and if it doesn't don't set the parameter, like this:
```javascript
    const tokenOptions = {
      baseUrl: this.domainUrl,
      audience: this.options.audience,
      client_id: this.options.client_id,
      code_verifier: transaction.code_verifier,
      code,
    };
    // some old versions of the SDK might not put this on the transaction
    if (undefined !== transaction.redirect_uri) {
      tokenOptions.redirect_uri = transaction.redirect_uri;
    }

    const authResult = await oauthToken(tokenOptions);
```

## Alternatives and current work-arounds

Applications developers with users who encounter this scenario can instruct their users to remove the query string from their browser, then hit enter, then refresh the page with a hard cache reload.

### Additional context
If the scenario described above is OK, I'd be happy to put together a PR. Also happy to put together an app that can be used to reproduce if this warrants one.

**Comment by stevehobbsdev** [comment]
Thanks for raising this @albertlockett. Yes, please raise your PR where we can discuss further.

**Comment by albertlockett** [comment]
Sounds good will do

**Comment by stevehobbsdev** [comment]
@albertlockett Merged this for you, expect it in a new release this week.
