### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by alkamin** [auth0/auth0-spa-js#381]
### Description

First, I'd like to say that I really appreciated the dev experience when replacing auth0-js with auth0-spa-js. The API is so much more intuitive and other than this error everything has just worked. So, thank you all for your efforts.

We have _no problems_ in development but after a production build we get the following error emitted from the library:

```
Uncaught TypeError: Super expression must either be null or a function
    at auth0-spa-js.production.js:1333
    at auth0-spa-js.production.js:1332
    at auth0-spa-js.production.js:1316
    at auth0-spa-js.production.js:1226
    at Object.<anonymous> (auth0-spa-js.production.js:2)
    at Object.<anonymous> (auth0-spa-js.production.js:2)
    at f (login:1)
    at Module.910 (store.js:30)
    at f (login:1)
    at Object.541 (main.b10f9afe.chunk.js:1)
```

I'm a bit stumped but I also realize we're using the latest beta so I don't know if that is a factor.

We import the library like so:

`import createAuth0Client, { Auth0Client } from "@auth0/auth0-spa-js"`

### Reproduction

This happens on every attempt to boot the app.

`tsconfig.json` in case that is relevant:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "baseUrl": "src",
    "typeRoots": ["src/types", "node_modules/@types"]
  },
  "include": ["src"]
}
```

### Environment

- auth0-spa-js 1.7.0-beta.4
- react 16.8.6 with create-react-app
- typescript 3.5.3
- occurs for different browsers on different OS

**Comment by adamjmcgrath** [comment]
Hi,

Would you mind sharing your `package.json` and webpack, or other build tool, config?

I'm surprised to see that the module is resolving `auth0-spa-js.production.js` (I would expect it to resolve `auth0-spa-js.production.esm.js`)

Doing `import createAuth0Client from "@auth0/auth0-spa-js"` should fix your issue (you probably don't need both the factory and the constructor)

**Comment by adamjmcgrath** [comment]
Ah, sorry - ignore me.

My colleague @stevehobbsdev thinks it might be an issue with an old version of `react-scripts`. Could you upgrade `react-scripts` and give it another go?

**Comment by alkamin** [comment]
Thanks for the prompt response and patience!

I can confirm that the upgrade to `react-scripts` solved the problem for me 🎉

Thanks for your help!

**Comment by adamjmcgrath** [comment]
Great! 😄

**Comment by rparakhiya** [comment]
I'm facing this same error in angular environment.

Angular CLI - 6.0.8
auth0-spa-js - 1.1.1

**Comment by lephuongbg** [comment]
We met the exact same issue when building for production and solved it by disabling uglifyjs's inlining:

```js
new UglifyJsPlugin({
    uglifyOptions: {
        compress: {
            inline: false // <- Set this to false
        }
        //...
    }
}
```
