### ISSUE TITLE
handleRedirectCallback() doesn't remove query / state always undefined in Chrome

### ISSUE THREAD

**Issue by Bastczuak** [auth0/auth0-spa-js#384]
### Description

Calling handleRedirectCallback() after redirect from hosted page doesn't remove the two query parameters `code` and `state` from the url. Also the returned state is always undefined. This results in a `Invalid state` exception and another redirect to the hosted page after page refresh.

### Reproduction

```js
import Vue from 'vue'
import createAuth0Client from '@auth0/auth0-spa-js'
import App from './App.vue'

Vue.config.productionTip = false

createAuth0Client({
  domain: process.env.VUE_APP_AUTH0_DOMAIN,
  client_id: process.env.VUE_APP_AUTH0_CLIENT_ID,
  audience: process.env.VUE_APP_AUTH0_AUDIENCE,
  redirect_uri: window.location.origin,
}).then(async auth0 => {
  try {
    await auth0.handleRedirectCallback()
    new Vue({
      render: h => h(App),
    }).$mount('#app')
  } catch (e) {
    await auth0.loginWithRedirect()
  }
})

new Vue({
  render: h => h(PreApp),
}).$mount('#app')
```
```
## Error: Invalid state
    at eval (auth0-spa-js.production.js:1)
    at eval (auth0-spa-js.production.js:1)
    at Object.eval [as next] (auth0-spa-js.production.js:1)
    at eval (auth0-spa-js.production.js:1)
    at new Promise (<anonymous>)
    at r (auth0-spa-js.production.js:1)
    at e.handleRedirectCallback (auth0-spa-js.production.js:1)
    at _callee$ (main.js:49)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.6.4
- **Version of the platform or framework used, if applicable:** Vue 2.6.11
- **Other relevant versions (language, server software, OS, browser):** Chrome Version 80.0.3987.132 (Official Build) (64-bit)
- **Other modules/plugins/libraries that might be involved:** None I know of.

**Comment by adamjmcgrath** [comment]
Hi @Bastczuak 

You need to remove the query / state from the url yourself, using something like:

```js
await auth0.handleRedirectCallback();
window.history.replaceState({}, document.title, window.location.pathname) // <= THIS
new Vue({
  render: h => h(App),
}).$mount('#app')
```

You're probably getting `Error: Invalid state` when you reload the page while the query params are still there. The auth0Client will try to swap the code and state for a token again and this will fail with `Invalid state` as the state has already been used to get a token.

Have a look at the [Vue quickstart](https://auth0.com/docs/quickstart/spa/vuejs/) for more information on how we recommend implementing `auth0-spa-js` with Vue.

**Comment by Bastczuak** [comment]
Hey @adamjmcgrath,

I realized that after I created this issue. So sorry for that. I somehow miss this in the official [docu](https://auth0.com/docs/libraries/auth0-spa-js) or am I wrong again?

**Comment by adamjmcgrath** [comment]
Yeah, admittedly, this section of the documentation is not great https://auth0.com/docs/libraries/auth0-spa-js#login-and-get-user-info 

I'll raise something internally to see if we can improve it.

In the meantime, the Vue quickstart is the best resource for creating Vue apps with this library. And check this issue if you're using `hash` mode  in your `VueRouter` https://github.com/auth0-samples/auth0-vue-samples/issues/100

Closing this issue, feel free to reopen if you need
