### ISSUE TITLE
Login loop if auth0.com cookie can't be created

### ISSUE THREAD

**Issue by nirvdrum** [auth0/auth0-spa-js#388]
# Description

_auth0-spa-js_ can't really keep track of its login state if it can't use a 3rd party cookie from auth0.com. This is the default configuration when setting up a tenant with Auth0. Unfortunately, we've seen both Brave (out the box) and any browser with the Privacy Badger extension installed won't work with the 3rd party auth0.com cookie.

I understand the solution is probably just to use custom domains, but I think the default experience could be improved. What ends up happening is the login actually completes just fine, but then _auth0-spa-js_ suddenly thinks it's not logged in, and the user is logged out due to a context change. This is very evident when calling `loginWithRedirect` as a guard for apps that require unconditional login (i.e., the user doesn't click a "login" link).

I think the library could continue working even if it couldn't write the cookie, using its own in-memory knowledge of the login state. Failover to local storage might be another option. People are going to continue using ad blockers or privacy add-ons. In the Brave case, it's just what the browser does out of the box. While it may be acceptable to lose analytics for those users in these cases, they still need to be able to log in. I don't think it's very clear that such tools could prevent Auth0 from running at all.

### Reproduction

Set up a new tenant in Auth0 using default settings for cookies. Set up a React app using _auth0-spa-js_ and add something like the following (simplified for brevity):

```js
const { isAuthenticated, loading, loginWithRedirect } = useAuth0()

useEffect(() => {
  if (!loading && !isAuthenticated) {
      loginWithRedirect({})
  }
}, [isAuthenticated, loading, loginWithRedirect])
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.6.5
- **Version of the platform or framework used, if applicable:** React 16.12.0
- **Other relevant versions (language, server software, OS, browser):** Brave, Firefox or Chrome + Privacy Badger

**Comment by stevehobbsdev** [comment]
@nirvdrum Thanks for raising this. This is something we're actively working on to try and make this experience better for our users, including adding an option to make use of local storage as you mention. We have a beta in play right now that allows you to do that (`npm install @auth0/auth0-spa-js@beta`) by setting `cacheLocation: 'localstorage'` when creating the client.

If you try the beta and have some feedback, please raise an issue and let us know!

Using a custom domain is a good way to resolve all these issues but it is a paid feature - hopefully the changes we're making here can help for those who can't use custom domains.
