### ISSUE TITLE
parseQueryResult Invalid state

### ISSUE THREAD

**Issue by Afbcary** [auth0/auth0-spa-js#390]
# Description

I've created an app with react create app and followed the [Quickstart Guide](https://auth0.com/docs/quickstart/spa/react/01-login). I am connecting to an auth server running locally that implements OAuth 2.0 w/ PKCE. 

### Reproduction
- Code available here: [https://github.com/Afbcary/balderdash](https://github.com/Afbcary/balderdash)
- Run the app with `yarn start`. 
- Click login and get redirected to the auth server
- Enter credentials and get redirected back to the react app with state and an authz code like:  `http://localhost:3000/?code=Ij%252F7SxLQVHtGoDVijpEKc28ker5j4Yc5ywkcK%252FqQYMM%253D&state=QTh6flUzRzQzVW5LUHNaMTNZXzZiRWdpR1VKTy5Eb2JBY2hCZmt1THpNWg==`
- The app crashes and shows the error below.
![image](https://user-images.githubusercontent.com/8877911/77470406-9c429d00-6dde-11ea-8c4d-8380257359ba.png)

### Environment

- Run on Ubuntu 18.04.4 LTS
- Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)
- Node v13.11.0
- App dependency versions
"dependencies": {
    "@auth0/auth0-spa-js": "^1.6.5",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.1"
  },

**Comment by stevehobbsdev** [comment]
@Afbcary I can't test this fully as it looks like you're interacting with a third-party IdP that I don't have access to (looking at your [`auth_config.json`](https://github.com/Afbcary/balderdash/blob/master/src/auth_config.json)), but I cloned the app and replaced the config with my own Auth0 config and I can see the app works just fine.

Is it possible that the IdP you're using is not returning the same state value back to you? When the SDK redirects for login, it generates a state value and uses that to write a cookie with some transaction data in it. When control returns to your app, the state param is fetched from the URL and used to look up the transaction cookie. In this case it hasn't managed to marry them up, hence the error.

So either:

* The cookie isn't being written/is being deleted
* The state value you get back from the IdP is not the same one that it received from your app

**Comment by Afbcary** [comment]
Thanks @stevehobbsdev I'll check if the state value is being modified and report back soon.

**Comment by Afbcary** [comment]
My react app 'balderdash' makes a request to my auth server 'kalidasa' with a state.
`Original state: b3lvZzIybllDUGRUdURwZW4wQzBPSGtjWHZrNHNkaEhsVUlueX5QZ1hyLg==`
To ensure that state isn't mangled in the URL, Kalidasa urlencodes it and then decodes when redirecting.
```
Encoded state: b3lvZzIybllDUGRUdURwZW4wQzBPSGtjWHZrNHNkaEhsVUlueX5QZ1hyLg%3D%3D
Decoded, returned state: b3lvZzIybllDUGRUdURwZW4wQzBPSGtjWHZrNHNkaEhsVUlueX5QZ1hyLg==
```
Back in balderdash, the window.location is 
`http://localhost:3000/?code=LrOrsM6gY0QaYPTuva%252BG3PZrJTehWgcp1a%252FVZp0gWXE%253D&state=b3lvZzIybllDUGRUdURwZW4wQzBPSGtjWHZrNHNkaEhsVUlueX5QZ1hyLg==` 

I put in a couple log statements and the transaction manager looks like
```
{"transactions":
 ...
	"b3lvZzIybllDUGRUdURwZW4wQzBPSGtjWHZrNHNkaEhsVUlueX5QZ1hyLg==": {
		"nonce": "ZcYad8r-7dIoo6NObvwVKbnpvTJeMtWrgcv9JL~yFvJ",
		"code_verifier": "AFMGHLQgSe02u~9lzvYVo7Iez0hracHFR21JC-0f_lV",
		"scope": "openid profile email",
		"audience": "default",
		"redirect_uri": "http://localhost:3000"
	}
}
```

I've also logged out state at that point in time, [https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L280](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L280),  the state variable is
`b3lvZzIybllDUGRUdURwZW4wQzBPSGtjWHZrNHNkaEhsVUlueX5QZ1hyLg`

State doesn't include the trailing **==**.

**Comment by Afbcary** [comment]
I was able to modify the source to get further but then ran into problems with the grant via /oauth/token. I'm going to try a different library. Thanks for your timely response.

**Comment by stevehobbsdev** [comment]
@Afbcary No problem, thanks for bringing this to our attention.

I think I can see what's going on. The SDK URI-encodes the state before redirecting to the auth server and it expects it back URI-encoded. It doesn't look like the state is returning to your app URI-encoded, and [this piece of `parseQueryParms`](https://github.com/auth0/auth0-spa-js/blob/master/src/utils.ts#L27) is interfering, because it's effectively cutting off the tail end of the state value.

If you do decide to give this SDK a try, let me know if I can be of any help getting you sorted.
