### ISSUE TITLE
Does the auth0 spa  support rememberLastLogin ?

### ISSUE THREAD

**Issue by SunnyXiao** [auth0/auth0-spa-js#391]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

>Hello, i want know that auth0 spa js whether support the rememberLastLogin like auth.lock.js？ which determines whether or not to show a screen that allows you to quickly log in with the account you used the last time.

**Comment by stevehobbsdev** [comment]
Hi @SunnyXiao,

Can you tell me which login experience you're using - classic or new? This can be determined by looking at the **Universal Login** screen in your [Auth0 Dashboard](https://manage.auth0.com). The reason I'm asking is that the "new" experience does not support such a feature, whereas "classic" does. The default template for Classic will set this property to `true` as long as there is no `prompt` parameter sent.

In short, this SDK doesn't inherently support `rememberLastLogin` as this would be something you would configure as part of your hosted login so long as you're using the "classic" experience.
