### ISSUE TITLE
Detect or synchronize Auth0 state in different tabs.

### ISSUE THREAD

**Issue by Bastczuak** [auth0/auth0-spa-js#392]
### Describe the problem you'd like to have solved

Let's imagine my website is opened in two tabs. If the user logs out in tab one and switches to tab two he is still logged in there. I would love to have a feature which detects that state so that the user get forced logged out also in tab two. Why? Because he can still do some UI interactions and call the backend which then says: 'Ups you are unauthorized'.

### Describe the ideal solution
Here a quick blueprint.

How I would like to use it:
```javascript
const auth0Client = await createAuth0Client(...)
auth0Client.sessionChanged((state) => {
  // something happend, handle it here
})
```

I did handle this in the "old" Webauth Client by using the visibilityState event:
```javascript
let visibilityChange
if (typeof document.hidden !== 'undefined') {
  visibilityChange = 'visibilitychange'
} else if (typeof document.msHidden !== 'undefined') {
  visibilityChange = 'msvisibilitychange'
} else if (typeof document.webkitHidden !== 'undefined') {
  visibilityChange = 'webkitvisibilitychange'
}
document.addEventListener(visibilityChange, () => {
  if (document.visibilityState === 'visible') {
    auth0.checkSession({}, (error) => {
      if (error) {
         auth0.logout()
      }
    })
  }
}, false)
```

I hope you get the Idea.

**Comment by adamjmcgrath** [comment]
Hi @Bastczuak you can do the same thing with this SDK

```js
const auth0Client = await createAuth0Client(...); // <=

let visibilityChange
if (typeof document.hidden !== 'undefined') {
  visibilityChange = 'visibilitychange'
} else if (typeof document.msHidden !== 'undefined') {
  visibilityChange = 'msvisibilitychange'
} else if (typeof document.webkitHidden !== 'undefined') {
  visibilityChange = 'webkitvisibilitychange'
}
document.addEventListener(visibilityChange, () => {
  if (document.visibilityState === 'visible') {
    auth0Client.getTokenSilently().catch(() => auth0Client.logout()); // <=
  }
}, false)
```

**Comment by Bastczuak** [comment]
@adamjmcgrath Thanks for the answer. I already tried this but I have to say that `getTokenSilently()` doesn't fail. I get a valid token back in logged out state.

**Comment by Bastczuak** [comment]
After digging in you code, I found out that I have so set `IngoreCache: true` in `getTokenSilently()`. My 2 cents: Please don't enable cache by default! But why what do I know. I guess you had your reasons.

**Comment by adamjmcgrath** [comment]
Great, thanks @Bastczuak - I'm glad you've got it working. Will take your comment about `ignoreCache` onboard and discuss it with the team

**Comment by Ashishjain608** [comment]
With this approach, multiple calls to fetch tokens will be made even if we switch tabs or minimise the screen. Better way to use a flag in localstorage and listen to localstorage event. This will limit the call to fetch tokens only when a new tab is opened or logout happens in another tab. Below is a working code for react application with atom jotai.

`
// outside the react component
const loggedInAtom = atomWithStorage('isLoggedIn', true);

// react component 
 function Auth0Auth({ children }: { children: ReactNode }) {
  const { getAccessTokenSilently, logout, user, isAuthenticated } = useAuth0();
  const [isLoggedIn, setIsLoggedIn] = useAtom(loggedInAtom);

  useEffect(() => {
    if (!isLoggedIn) {
      getAccessTokenSilently({ ignoreCache: true }).catch(() => {
        logout({ returnTo: window.location.origin });
      });
    }
  }, [getAccessTokenSilently, isLoggedIn, logout]);

  useEffect(() => {
    setIsLoggedIn(isAuthenticated);
  }, [isAuthenticated, setIsLoggedIn]);

  return (
    <AuthUtilsProvider
      authUtils={{
        getAccessToken: getAccessTokenSilently,
        logout,
        profilePic: user?.picture,
      }}
    >
      {children}
    </AuthUtilsProvider>
  );
}`
