### ISSUE TITLE
VueApollo Authorization - Uncaught (in promise) TypeError: Cannot read property 'getTokenSilently' of null

### ISSUE THREAD

**Issue by costas90** [auth0/auth0-spa-js#400]
### Description

I used the Auth0 configuration from https://auth0.com/docs/quickstart/spa/vuejs/01-login

I added VueApollo and after login, when I refresh the page I get the error:
> Uncaught (in promise) TypeError: Cannot read property 'getTokenSilently' of null
>    at Vue.getTokenSilently (index.js?b628:74)
>    at _callee$ (vue-apollo.js?ca94:45)

It seems that this happens because Apollo is loading before the Auth0 instance.

In Apollo, I use the following to get the token, and thus causes the error:
```
getAuth: async () => {
    const token = await getInstance().getTokenSilently();
    console.log('toke', token);
    return token ? `Bearer ${token}` : '';
  }
```

I am not sure how to fix this.

Not sure if related, but when I am logged out I get this error:

>asyncToGenerator.js?1da1:6 Uncaught (in promise) 
{error: "login_required", error_description: "Login required", state: ""}
error: "login_required"
error_description: "Login required"
state: ""
__proto__: Object

### Reproduction

1. Login into the app
2. Refresh app

### Environment

> Please provide the following:

- **Version of this library used:** "@auth0/auth0-spa-js": "^1.6.5"
- **Version of the platform or framework used, if applicable:** "vue": "^2.6.11"
- **Other relevant versions (language, server software, OS, browser):** Chrome Browser, localhost
- **Other modules/plugins/libraries that might be involved:** "vue-apollo": "^3.0.0-beta.11"

**Comment by costas90** [comment]
Sorry the issue was with Vue Apollo. I found how to fix it.

**Comment by stevehobbsdev** [comment]
> It seems that this happens because Apollo is loading before the Auth0 instance.

Yes that sounds like what is happening. The SDK must be initialized first before methods like `getTokenSilently` will work.

Closing this for now as it's not an issue with the SDK, but feel free to continue the discussion.
