### ISSUE TITLE
createAuth0Client throws without returning client instance when silent auth fails with 'consent_required'.

### ISSUE THREAD

**Issue by diegopy** [auth0/auth0-spa-js#402]
### Description

createAuth0Client doesn't handle the 'consent_required' auth failure case and throws without returning a client instance. In general I think the whole code flow should be rethought as this function is doing two seemingly unrelated things: creating the client AND trying to authenticate silently. There's no clear way to indicate failure in one or either of those things failing.
A PR is attached with a proposed solution.

### Reproduction

If you are working locally on localhost on two different projects that use auth0 and one of them sets the auth0.is.authenticated flag to true when it authenticates, the other project may try to silent auth in createAuth0Client but it doesn't have consent yet, so it throws without returning a client.

### Environment

Library version 1.6.5

**Comment by JohnnyTMD** [comment]
save issue here

**Comment by JohnnyTMD** [comment]
This seems to be cause by this cookie `auth0.is.authenticated`
Changing the cookie value in inspector from `true` to `false` seems to fix the issue.

**Comment by derekbekoe** [comment]
Ran into the same issue.
The `createAuth0Client` method is straightforward to can be implemented using `new Auth0Client(options);` to handle the error different:

https://github.com/auth0/auth0-spa-js/blob/0695aaf5df1b7c41f57d01679220a0823e9193eb/src/index.ts#L20-L36

**Comment by stevehobbsdev** [comment]
Thanks @derekbekoe, one of the reasons why we worked to expose the constructor in this way was so that developers could do some custom error handling on startup - the approach you mention is what we recommend 👍
