### ISSUE TITLE
Unable to direct user to either login or signup page in classic lock.

### ISSUE THREAD

**Issue by rpuls** [auth0/auth0-spa-js#404]
Hello, I’m trying to direct my users to the signup form when they are not already registered, but it doesn’t seems to be working.

I’m using the SPA SDK and passing options like this:
onClick: () => props.loginWithRedirect({ mode: 'signUp', login_hint: email }),
I can confirm that the email hint is working but the mode property doesn’t seem to be.

I’m using the classic lock universal login page.

I see in the documentation https://auth0.github.io/auth0-spa-js/interfaces/redirectloginoptions.html
that the mode property doesn't exist, so I suppose that this is a feature request. I was asked to create an issue here when I asked the same question in the community.

Rasmus

**Comment by stevehobbsdev** [comment]
Thanks for raising this @rpuls. Classic Lock won't automatically pick up these properties. You should find that they will appear as querystring parameters on the Authorize call though. In which case the thing to do here is to use a custom login page, where you can pick up these a parameters in the `config.extraParams` object and configure Lock how you wish.

[This community thread](https://community.auth0.com/t/passing-config-to-hosted-login-page/8073) might help a little bit.

Closing as it's not an issue with this SDK per-say, but feel free to continue the conversation if you can't get something working.
