### ISSUE TITLE
Feature request: method to clear the local cache.

### ISSUE THREAD

**Issue by majelbstoat** [auth0/auth0-spa-js#406]
### Describe the problem you'd like to have solved

I'd like to be able to delete a token from the local cache, to facilitate logout without redirect. 

### Describe the ideal solution

The _ideal_ solution would be an async `logoutSilently` method that opens a hidden iframe to the logout endpoint, then deletes the local cache for me. I'm already doing this, but it's not robust to any changes you might make.

The next best thing would be a `cache.delete()` method that clears the cache.

## Alternatives and current work-arounds

At the moment in order to do this, I am writing an immediately expiring token directly into the cache, which is kinda brittle (and which Typescript hates because cache is private):

```ts
client.cache.save({
    scope,
    audience,
    id_token: '',
    access_token: '',
    expires_in: 0,
    decodedToken: {
      claims: {
        __raw: '',
      },
      user: {},
    },
  })
```

**Comment by stevehobbsdev** [comment]
@majelbstoat Thanks for raising this. Could it be considered a duplicate of https://github.com/auth0/auth0-spa-js/issues/308? If so, I can close this one.

**Comment by majelbstoat** [comment]
Ha, I swear I looked before posting. It's funny someone else also thought to call it `logoutSilently` 😂. Yes, you can close, thank you. I'll go upvote that one 😉
