### ISSUE TITLE
When using React Router's HashRouter login redirect loses the route

### ISSUE THREAD

**Issue by UndarkAido** [auth0/auth0-spa-js#407]
### Description

I'm using React Router's HashRouter and setting my `redirect_uri` to `window.location.href` when I call `loginWithRedirect`. After login, it sends me to `http://localhost:3000/?code=<code>#/faq` which routes to the right page but is very quickly stripped down to `http://localhost:3000/` instead of the expected  `http://localhost:3000/#/faq`. This causes an element I have that watches the route to break and if the user reloads it takes them back to the index page.

### Environment
```js
"@auth0/auth0-spa-js": "^1.6.5"
"react": "^16.13.1"
"react-router-dom": "^5.1.2"
```
- Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)
- Windows 10 Version 1909 Build 18363.720

**Comment by lukepearson** [comment]
I had this issue too, just worked around it for now by rewriting the url in index.tsx before the router initializes
```
if (window.location.href.includes('state') && 
    window.location.href.includes('code') && 
    /#\/$/.test(window.location.href)) {
    window.location.href = window.location.href.replace(/\/(\?code=.*)#/, '/#/$1')
  }
```

**Comment by UndarkAido** [comment]
But that will break `auth0-spa-js`

**Comment by UndarkAido** [comment]
Oh I set my onRedirectCallback to this:
```js
appState => {
  history.replace(window.location.hash ? window.location.hash : window.location.pathname);
};
```

Maybe not perfect for the browser router but it works for the hash router
