### ISSUE TITLE
How to use passwordless flow?

### ISSUE THREAD

**Issue by qortex** [auth0/auth0-spa-js#413]
As far as I understand, the correct endpoint to use in `auth0.js` is [this one](https://auth0.github.io/auth0.js/global.html#passwordlessLogin) but I can't see it exposed in `auth0-spa-js`.

Is there something I miss, or is it necessary to use `auth0.js` directly outside of `auth0-spa-js`?

**Comment by stevehobbsdev** [comment]
@qortex You're right in that we don't support this for `auth0-spa-js` at the moment. I've seen this supported by other members of the community by using `auth0.js` specifically for the passwordless part on top of `auth0-spa-js`.

It's not ideal, I agree, but it's where we're at currently. Let me raise an internal discussion about where it is on our roadmap.

**Comment by qortex** [comment]
Quite disappointing I had to spend hours to get it working when it's a commercial promise that it's a breeze to implement (and I made product decisions based on that promise).

Worked out a solution. But still got to do some testing for edge cases, so more hours to spend on that.

But this works ok, adding it to the Auth Service you give as an example in the SPA SDK tutorial.

Posting here to save time for future people.

The idea is to do the flow directly through `auth0.js` instead of the `auth0-spa-js` wrapper, and then simulate the results come from "usual" `handleRedirectCallback`.

To use this snippet, use a different callback url (I use `auth/callback_otp`) and authorize it for your app, and call this specific `handleRedirectCallbackOtp` instead of `handleRedirectCallback` for usual logins with password in the page init.

Need to add `auth0.js` as a direct dependency and do:

```typescript
import { WebAuth } from 'auth0-js';
// ...
  webAuth$ = (of(
    new WebAuth({
      domain: environment.auth0Domain,
      clientID: environment.auth0ClientId,
      redirectUri: `${window.location.origin}/auth/callback_otp`,
      audience: environment.auth0ApiAudience,
      scope: `openid profile email ${AUTH0_API_ALL_SCOPES}`,
      responseType: 'token id_token',
    })
  ) as Observable<WebAuth>).pipe(
    shareReplay(1), // Every subscription receives the same shared value
    catchError(err => throwError(err))
  );

  loginThroughPasswordless(email: string, otp: string): void {
    this.webAuth$.pipe(take(1)).subscribe(webAuth => {
      webAuth.passwordlessLogin(
        {
          email,
          verificationCode: otp,
          connection: 'email',
        },
        err => console.error(err)
      );
    });
  }

  handleAuthCallbackOtp(): void {
    // Call when app reloads after user logs in with Auth0 in OTP mode
    this.webAuth$.pipe(take(1)).subscribe(webAuth => {
      webAuth.parseHash({ hash: window.location.hash }, (err, authResult) => {
        if (err) {
          return console.error('Error in parseHash', err);
        }

        webAuth.client.userInfo(authResult.accessToken, (err, user) => {
          if (err) {
            return console.error('Error in userInfo', err);
          }
          this.userProfileSubject$.next(user);
          this.loggedIn = true;

          this.router.navigate(['/']);
        });
      });
    });
  }
```

**Comment by stevehobbsdev** [comment]
Thanks @qortex!

**Comment by nickrm97** [comment]
Thanks for this solution :) @qortex . Feel like I just went down the same rabbit hole of assuming it's fully supported, then running into lots of unclear errors :(
