### ISSUE TITLE
export type Auth0Client as part of the library interface

### ISSUE THREAD

**Issue by yeiniel** [auth0/auth0-spa-js#416]
### Describe the problem you'd like to have solved

> Some times two imports are required to work with the library on typescript. One of them to import the `createAuth0Client` factory and the other to import the `Auth0Client` type. The latter bleeds details about the package. It looks like this:

```
import createAuth0Client from '@auth0/auth0-spa-js';
import Auth0Client from '@auth0/auth0-spa-js/dist/typings/Auth0Client';
```

### Describe the ideal solution

> The ideal solution will be to export the type as part of the library public interface. With that change applied it will look like this:

```
import createAuth0Client, { Auth0Client } from '@auth0/auth0-spa-js';
```

## Alternatives and current work-arounds

> none right now.

### Additional context

The proposed solution is really simple. Let me know if you guys will like me to contribute a PR for it.

**Comment by stevehobbsdev** [comment]
Thanks @yeiniel  - closing this (see my comment on your attached PR).
