### ISSUE TITLE
Login screen validation message

### ISSUE THREAD

**Issue by LeshikJanz** [auth0/auth0-spa-js#418]
### Description

If you attempt to click "log in" without filling in a username or password, the validation message has lost styling

See attached image

![Screenshot 2020-02-21 at 11 01 01](https://user-images.githubusercontent.com/16132732/79320726-ef59cc80-7f12-11ea-8113-ca11aad96352.png)

### Environment

"@auth0/auth0-spa-js": "^1.6.2"

**Comment by stevehobbsdev** [comment]
@LeshikJanz Can you please raise this on https://github.com/auth0/lock? Please remember to fill out all of the details on the issue template, as these would be most useful to helping you debug this issue.
