### ISSUE TITLE
Bug: Typescript exports incorrect for next.js serverless environment in production build

### ISSUE THREAD

**Issue by hdngr** [auth0/auth0-spa-js#424]
Great work with the v1.7 release!

I've tried approaching this from several directions - super weird for a minor release to break things.

Details on the problem I am running into with [next.js `serverless` build filed in their repo](https://github.com/zeit/next.js/issues/11967).

I believe it is a configuration issue with the new 1.7 release .  Confirmed that rolling back to 1.6.5 works.

Well aware of issues with ssr and my app is properly configured.  Works in development, it is an issue with the production build.

Is there a problem with my tsconfig that may be causing this?

TS Config
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "preserve",
    "lib": ["dom", "es2017"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "preserveConstEnums": true,
    "removeComments": false,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "esnext",
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "baseUrl": ".",
    "paths": {
      "lib": ["lib"]
    },
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true
  },
  "exclude": ["node_modules"],
  "include": ["next-env.d.ts", "lib/**/*.*", "**/*.ts", "**/*.tsx"]
}
```

Next Config
```
/* eslint-disable @typescript-eslint/no-var-requires */
require('dotenv').config()
const withPlugins = require('next-compose-plugins')
const withImages = require('next-images')
const withSass = require('@zeit/next-sass')
const path = require('path')

const nextConfig = {
  target: 'serverless',
  webpack: (config, _options) => {
    config.resolve.modules.push(path.resolve('./'))
    return config
  },
  env: {
    // Will be available on both server and client
    nodeEnv: process.env.NODE_ENV,
    midasApiEndpoint: process.env.MIDAS_API_ENDPOINT,
  },
}

module.exports = withPlugins([[withSass], [withImages]], nextConfig)

```

**Comment by stevehobbsdev** [comment]
@hdngr With 1.7 we introduced the ability to get refresh tokens using a web worker. The rollup plugin that we use depends on Blob being available, but this only works in the browser (which is the only supported target of this SDK).

Questions:

* Is there a Node implementation of `Blob` that can be used during build?
* Can `auth0-spa-js` be skipped during the server build?

**Comment by hdngr** [comment]
@stevehobbsdev just asked @timneutkens to take a look.  Looking to see if auth0 can be skipped in build that is meant for ssr - thanks for getting back to me quickly!   Again great work on 1.7, cleans up a lot of stuff.  Cool implementation with the worker.

**Comment by shicholas** [comment]
@stevehobbsdev Fwiw, this library, https://github.com/Richienb/cross-blob#readme, is like isomorphic-fetch in that it enables `Blob` to work in both Node and Browser environments.

As an analogy, the Apollo GraphQL client allows you to configure isomorphic-fetch upon creating an ApolloClient. Having a similar option for `Blob` could allow users to use this library with SSR libraries like Gatsby & Next

**Comment by stevehobbsdev** [comment]
@shicholas Thanks for pointing that out. cc: @adamjmcgrath 

We've identified that it might be a problem with the rollup plugin we're using to wrap the web worker module, still looking at ideas to fix it.
