### ISSUE TITLE
Incorrectly prefixing `issuer` (URL) with https://

### ISSUE THREAD

**Issue by clehene** [auth0/auth0-spa-js#428]
Per spec, `issuer` is a URL but treated as a domain by the spa client

https://tools.ietf.org/id/draft-ietf-oauth-discovery-08.html#ASMetadata

> issuer
REQUIRED. The authorization server's issuer identifier, which is a URL that uses the https scheme and has no query or fragment components. This is the location where .well-known RFC 5785 resources containing information about the authorization server are published. Using these well-known resources is described in Section 3. The issuer identifier is used to prevent authorization server mix-up attacks, as described in "OAuth 2.0 Mix-Up Mitigation".

https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L107

```typescript
    this.tokenIssuer = this.options.issuer
      ? `https://${this.options.issuer}/`
      : `${this.domainUrl}/`;
```

Hence a user that correctly passes a URL will end up settings `iss` claim to :
`https://https://<ISSUER>//`

**Comment by stevehobbsdev** [comment]
Thanks @clehene for raising. You're correct in that normally `issuer` would be a fully-formed URL containing the scheme. Unfortunately changing this at the moment would require a breaking change. However, let me add to our internal tracker for discussion, and I will raise something to point this out in the option documentation.
