### ISSUE TITLE
Make auth0-spa-js Universal or Split out buildAuthorizeUrl

### ISSUE THREAD

**Issue by dan-barrett** [auth0/auth0-spa-js#432]
### Describe the problem you'd like to have solved

One of the central use cases of the `auth0-spa-js` library is to generate the `/authorize` URL with the necessary parameters. Under normal circumstances, these methods are being executed in the browser, and thus the library leans on the presence of the DOM in many places  to do string manipulation/encoding/decoding. For example: https://github.com/auth0/auth0-spa-js/blob/de3f3d0b400875883e161bbcda7094faf1e50933/src/utils.ts#L212

This means that the library is unable to be used in non-browser javascript environments (ie node). There are a few use cases I can think of off the top of my head, for example in an SSR web application or in a CLI.

Given that a core component of using auth0 is in generating the `/authorize` url, the environment in which we do that should not be limited to the browser.

### Describe the ideal solution

This library should be made "[Universal](https://stackoverflow.com/questions/43862782/whats-universal-javascript)". To accomplish that, you'd need to remove all references to the DOM.

## Alternatives and current work-arounds

If the above proves impossible or difficult because other parts of the library require a reliance on the DOM, the alternative would be to split out the generation of `/authorize` url into a separate node package: the most obvious candidate would be to include it in the `node-auth0` package.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by stevehobbsdev** [comment]
Thanks for raising this @dan-barrett.

The target of this SDK is absolutely the browser and making it more universal is not one of our goals here.

I can understand the need for splitting out `buildAuthorizeUrl` and as you point out, including it in another package like `node-auth0` might be worth considering. Please [raise an issue](https://github.com/auth0/node-auth0) on that repo to discuss possibilities.
