### ISSUE TITLE
Allow the default scope of "openid profile email" to be overridden

### ISSUE THREAD

**Issue by conorcussell** [auth0/auth0-spa-js#433]
### Describe the problem you'd like to have solved

The default scopes of `openid profile email` are always applied. My company's identity team made a decision not to support the scopes of `profile` and `email`, so unfortunately this means I cannot use the library without forking.

I appreciate the fact this module is opinionated and forces the most secure auth flow, but as far as I can tell the Authorisation Code flow with PKCE shouldn't mandate any specific scopes. It would be great to be able to override this default if you really need to.

### Describe the ideal solution

I'd like it to be possible to override the default scope of `openid profile email` which is applied to every request.

## Alternatives and current work-arounds

I've considered using the alternate [Auth0-JS library](https://github.com/auth0/auth0.js). However it seems the only method of extracting the auth response after a successful authentication explicitly does not work with the Authorisation Code flow. See: https://github.com/auth0/auth0.js/blob/540c84af010af730a17d521435ca516d4baf7382/src/web-auth/index.js#L225

Currently I'm going to have to patch or fork the package in order to work with it.

**Comment by stevehobbsdev** [comment]
Thanks for raising. We're currently actively working on #389 which should address this, although you should understand that we would still need to enforce the `openid` scope - otherwise it makes the library kind of useless.

Will close this for now, but please track progress on that PR.

**Comment by conorcussell** [comment]
Thanks @stevehobbsdev - happy to have `openid` be the only default, thats what I need anyway!
