### ISSUE TITLE
Blob is not defined in 1.7.0 when using in Gatsby

### ISSUE THREAD

**Issue by gillkyle** [auth0/auth0-spa-js#437]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

Setting up a new application using the React quick start on a Gatsby site with the latest installation of the SDK results in a pretty obscure webpack error while compiling the `html.js` in Gatsby's build step. 

Reverting to `1.6.5` removes the error which is what makes me think it's an error that would belong here. Here is some of the error output when running `gatsby develop`:

```
 ERROR 

There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html ReferenceError: Blob is not defined


  13 | and limitations under the License.
  14 | ***************************************************************************** */
> 15 | var e=function(t,n){return(e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var n in t)t.hasOwnProperty(n)&&(e[n]=t[n])})(t,n)};function t(t,n){function r(){this.constructor=t}e(t,n),t.prototype=null===n?Object.create(n):(r.prototype=n.prototype,new r)}var n=function(){return(n=Object.assign||function(e){for(var t,n=1,r=arguments.length;
                                                      ^
  16 | //# sourceMappingURL=auth0-spa-js.production.esm.js.map
  17 | 


  WebpackError: ReferenceError: Blob is not defined
  
  - auth0-spa-js.production.esm.js:15 
    node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:15:44578
  
  - auth0-spa-js.production.esm.js:15 Module.<anonymous>
    node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:15:44698
  
  - wrap-root-element.js:1 Module../plugins/gatsby-plugin-auth0/wrap-root-element.js
    plugins/gatsby-plugin-auth0/wrap-root-element.js:1:1
  
  - gatsby-ssr.js:1 Module../plugins/gatsby-plugin-auth0/gatsby-ssr.js
    plugins/gatsby-plugin-auth0/gatsby-ssr.js:1:1
```

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

I have an example Gatsby site here with the code implemented from the Quick Start. `1.6.5` is installed on the `repro` branch: https://github.com/gillkyle/auth0-error-reproduction/tree/repro

You can install dependencies in that project and run the site with `gatsby develop` to see the error.

### Environment

> Please provide the following:

- **Version of this library used:**

`1.7.0`

- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

This is my environment as reported by `gatsby info`:

```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 74.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.35 => 2.20.35
  npmGlobalPackages:
    gatsby-cli: 2.11.22
```

Thanks for any help! In the meantime I've reverted to the older package.

**Comment by pixelbreaker** [comment]
I am also seeing this, rolling back to old version

**Comment by stevehobbsdev** [comment]
We're aware and are taking steps to fix this. The problem lies with a [Rollup plugin](https://github.com/darionco/rollup-plugin-web-worker-loader) that builds our web worker module, and we're actively working with them to fix it.

In the meantime, `auth0-spa-js` can be excluded from the Gatsby server build by configuring webpack and using the Null loader. Something like this:

```js
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    /*
     * During the build step, `auth0-spa-js` will break because it relies on
     * browser-specific APIs. Fortunately, we don't need it during the build.
     * Using Webpack's null loader, we're able to effectively ignore `auth0-spa-js`
     * during the build. (See `src/utils/auth.js` to see how we prevent this
     * from breaking the app.)
     */
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /auth0-spa-js/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
```

However, we expect to be able to release a fix shortly.

**Comment by pixelbreaker** [comment]
It's much easier just to roll back to a working version and await a working release, than add this hack. IMO.

**Comment by stevehobbsdev** [comment]
Agreed, just giving options for others who might feel differently.

**Comment by gillkyle** [comment]
@stevehobbsdev great to hear a fix is already somewhere in the works!

For what it's worth. I have the above code included in my reproduction and still encounter the error. https://github.com/gillkyle/auth0-error-reproduction/blob/repro/plugins/gatsby-plugin-auth0/gatsby-node.js 🤷‍♂️
