### ISSUE TITLE
createAuth0Client(initOptions).cache has undefined values for a social connection log-in after reinit

### ISSUE THREAD

**Issue by farazoman** [auth0/auth0-spa-js#438]
### Description

Log-in with a database vs social connection produces different values in the cache after calling

const auth0FromHook = await createAuth0Client(initOptions)
auth0FromHook.cache is different for database connection (data is there) than a social connection (undefined)

### Reproduction

1. login with callback to auth0 endpoint
2. re-initialize the Auth0Client (note, in my app each page is re-rendered using next.js so every page change I require to get the login info from the client's cache)
3. run const auth0FromHook = await createAuth0Client(initOptions), from import createAuth0Client from '@auth0/auth0-spa-js', in the client creation

**For a Database Connection (see relevant screenshot below):**
const auth0FromHook = await createAuth0Client(initOptions)
In the auth0FromHook.cache object I get data for my current session.

**For a Social Connection:**
When logging in with a social connection, specifically Facebook (other social log-ins weren't tried)
the  auth0FromHook.cache  is undefined.

see below for reference when using a **Database** Connection
![image](https://user-images.githubusercontent.com/2703043/80318394-cf11f380-87d7-11ea-9d98-9d36213fbfed.png)

### Environment

- **Version of this library used:**  "@auth0/auth0-spa-js": "^1.6.5"
- **Version of the platform or framework used, if applicable:** using next.js, "next": "^9.3.4",
- **Other relevant versions (language, server software, OS, browser):** windows, chrome
- **Other modules/plugins/libraries that might be involved:** apollo.js, but unlikely involved . Also using the code from the quick start: https://auth0.com/docs/quickstart/spa/react/01-login#create-a-sample-application

**Comment by stevehobbsdev** [comment]
Please do not access the cache directly in this fashion; that's not the intended use and, being an internal property, could change in the future without warning. You should rely on the [publicly documented API](https://auth0.github.io/auth0-spa-js/classes/auth0client.html) here.

Is there a reason you need to access the cache and can we talk about any missing features you'd like to see from the public API?

I do agree that being an internal property, it should be named differently to distinguish them for our JS users but these are not included in the TypeScript definitions either nor the public API docs.

**Comment by farazoman** [comment]
So I think that I was getting too into the weeds to find something out. My original problem was that I was using the spa sdk yet on the auth0Client re initialization the information for a Social login kept disappearing which was different behaviour from a database connection (email login).

I was wondering is that expected? And secondly, should the auth0Client ever even be reinitialized in the same session?

**Comment by stevehobbsdev** [comment]
> I was wondering is that expected?

That doesn't sound like something that should happen. Whether or not you log in with a social connection or a username/password makes no odds to the SDK, as long as the response to the `/token` endpoint yields an ID token. Do you have any custom Rules in play which might affect what is being returned to your app?

> should the auth0Client ever even be reinitialized in the same session?

Ideally not - it's designed to be set up as a single instance in your application. If you have two instances, they won't share the same in-memory cache but will share cookies and other artefacts. Probably best to just have one instance if you can.

**Comment by farazoman** [comment]
my app is pretty barebones at the moment, i.e no custom rules. One thing I noticed that the auth0.isAuthenticated = true is still set on localhost when I inspect the cookies.

So I think the is the other part of my implementation I might have messed up because I use next.js each page is independently delivered and isn't really a spa. I'll look more into this part and see what alternative solution I can come up with. 

Thanks for following up

**Comment by stevehobbsdev** [comment]
@farazoman Thanks! Always interesting to hear about different use cases :)
