### ISSUE TITLE
Login not possible with redirect in a custom rule

### ISSUE THREAD

**Issue by larsf96** [auth0/auth0-spa-js#439]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Starting from SDK version 1.6.5, it's no longer possible to login users if there is any custom rules in the Auth0 tenant, that is causing a redirect.
Example:
User is logged in, something changes in the background that causes the custom rule to trigger a redirect (i.e. to get updated consent of the user). If the user then refreshes the page, the error "interaction_required" will be thrown. This is expected behaviour, because the user will get a redirect. In our application, the user will then see the welcome page and can hit "Login" again, which triggers loginWithRedirect() of the Auth0Client. But when calling loginWithRedirect(), the exception "interaction_required" is thrown again instead of redirecting the user to the Auth0 tenant to get the redirect, complete the action and get back to the application.
I couldn't figure out if there is any way to suppress this exception in that case or if it's just a bug because loginWithRedirect() should always trigger the redirect to Auth0 I think.

### Reproduction

1. Create a rule that causes a redirect in specific conditions (i.e. some value in the app_metadata exists)
2. Login with a user
3. Change the user's profile so that the custom rule will trigger the redirect
4. Refresh the page and call loginWithRedirect()

### Environment

- **Version of this library used: 1.6.5 and greater**
- **Version of the platform or framework used, if applicable: Angular 8**
- **Other relevant versions (language, server software, OS, browser): Mac OS, Chrome**
- **Other modules/plugins/libraries that might be involved: -**

**Comment by stevehobbsdev** [comment]
Can you see from the browser network traffic if the redirect is happening? It could be seamless SSO getting in the way here. Your app is redirecting to Auth0 but because you already have a session and are logged in, you're getting redirected with an error straight away.

You can force the login prompt to show despite already having a session by using `prompt: 'login'` - would this help? If not, please can you supply the code from the custom rule you're using so that I can have a look.

```js
auth0.loginWithRedirect({
  prompt: 'login'
});
```

**Comment by larsf96** [comment]
> Can you see from the browser network traffic if the redirect is happening
No, there is no redirect or other network traffic being shown

I've tried setting "prompt: login", but still the same behaviour.

You can use the following rule to trigger a redirect:
`function redirectTo(user, context, callback) {
    var flag = user.user_metadata.flag;

    if(flag) {
        context.redirect = {
            url: 'https://github.com'
        };
    }

    callback(null,user,context);
}`

Then you can set the flag property in the user's metadata object to trigger a redirect. 
This is not the rule that we are using, but that one is quite complex and has some business logic, so I've created a simpler one to try out

**Comment by larsf96** [comment]
Is there any update on this?

**Comment by stevehobbsdev** [comment]
@larsf96 Unfortunately not so far; getting time to work on these issues has been extremely challenging the last couple of months. Please let me pick this up again next week, and thanks for your patience here.

**Comment by adamjmcgrath** [comment]
Hey @larsf96 

We've made a change to how `interaction_required` errors are handled in the `createAuth0Client` factory in the latest version of the library which I believe should resolve your problem.

Can you give `1.9.0` a go and let me know how you get on?

**Comment by larsf96** [comment]
Hey @adamjmcgrath 

I can confirm that this is working now, thank you!
