### ISSUE TITLE
require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by nojaf** [auth0/auth0-spa-js#447]
### Description

When upgrading to 1.8.0 my `create-react-app` build is failing:

```
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`

Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

See https://github.com/nojaf/capital-guardian/runs/636017737

### Reproduction

My example project:
https://github.com/nojaf/capital-guardian/blob/master/client/src/App.js
https://github.com/nojaf/capital-guardian/blob/master/client/src/auth0Config.js

### Environment

> Please provide the following:

- **Version of this library used: 1.8.0**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser): create-react-app,  "react-scripts": "3.4.1",**
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Thanks for raising @nojaf - can you confirm if this was also a problem in 1.7?

**Comment by nojaf** [comment]
I checked and it is not a problem with 1.7.

**Comment by dannynpham** [comment]
I'm having the exact same issue after I updated to 1.8.0

**Comment by qortex** [comment]
Same here after updating to 1.8.0.

With Angular, it's a warning and not an error though:

```
WARNING in ./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js 15:49939-49946
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by belachkar** [comment]
The same warning Using **Angular** on **@1.8.0**:
```
[WDS] Warnings while compiling.
./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js 15:49939-49946
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
.

**Comment by sdhwa92** [comment]
With Angular, I'm getting the same warning on @1.8.0:
`WARNING in ./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js 15:49939-49946
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

**Comment by duro** [comment]
I actually had to downgrade all the way down to 1.6.0 to get this to work, but with that, lost all typescript types.

**Comment by belachkar** [comment]
@duro The **1.7.0** works perfectly for me.

**Comment by shorn** [comment]
Working with create-react-app `3.4.1` build environment.
Can confirm warning shows up on version `1.8.0`, but is not present for versions `1.6.5` or `1.7.0`.

Tried changing my import style from
```
import Auth0Client from "@auth0/auth0-spa-js/dist/typings/Auth0Client";
```
to 
```
import createAuth0Client, {Auth0Client} from "@auth0/auth0-spa-js";
```
but that didn't seem to make a difference.

My workaround is to go back to `1.6.5` to avoid "broken window syndrome" around warnings.

Here is a public project that reproduces: [Rabbit](https://bitbucket.org/kopi-cloud/rabbit/src/6f5e2471d267cfd3ddef231f42deb671663907a7/frontend/package.json?at=master)

**Comment by jackall3n** [comment]
I was pulling my hair out last week with this, can clarify that is it certainly working on version `1.7.0` and `1.8.0` is the problem version.

I suspect this might be the issue: https://github.com/auth0/auth0-spa-js/compare/v1.7.0...v1.8.0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R64

**Comment by stevehobbsdev** [comment]
Thanks all, we've identified it as an issue with the latest version of `rollup-plugin-web-worker-loader` and we're [working with them to resolve it](https://github.com/darionco/rollup-plugin-web-worker-loader/pull/21). It looks like they published some extra stuff that they didn't intend to in that release and it's broken other aspects that they didn't intend. As well as that, it's highlighted a gap in our testing and we're working to resolve that too!

**Comment by adamjmcgrath** [comment]
Hi all, we've released [1.8.1](https://github.com/auth0/auth0-spa-js/releases/tag/v1.8.1) which should resolve the issue.

Can you try it out and let us know if you run into any issues?

**Comment by vuhrmeister** [comment]
works!

**Comment by nojaf** [comment]
1.8.1 works for me. Many thanks!
