### ISSUE TITLE
Allow to invalidate user object or refresh user object

### ISSUE THREAD

**Issue by Bastczuak** [auth0/auth0-spa-js#450]
### Describe the problem you'd like to have solved
I provide a flag `mfa` as a namespaced custom claim in the id token to know if MFA is enabled for individual accounts. I wanted to use this flag to represent the state of MFA (on/off) in my frontend. Unfortunately I have not function to refresh the id token or user object so this state is updated because the user object is cached. This results in the fact that my frontend is now out of sync with the MFA state until the user refreshes the browser or logs out and back in.

### Describe the ideal solution
Have the same functionallity like `getTokenSilently()` to provide an option `ignoreCache` which allows to disable the cache and returns a new user object.

## Alternatives and current work-arounds
I have to logout the user manually after he enabled or disabled MFA so I get a new user object after login.

**Comment by stevehobbsdev** [comment]
The way to do this currently is to call `getTokenSilently({ ignoreCache: true })` before using `getUser`. This should refresh your ID token.

Does this help? I agree the naming in this scenario is not the best, but it would unblock you.

**Comment by Bastczuak** [comment]
@stevehobbsdev doing this will throw an error `error: "login_required", error_description: "Multifactor authentication required"`. So I think my "workaround" was instead the right approach.

**Comment by stevehobbsdev** [comment]
I don't think that's possible using the default configuration for the SDK as it will go through the `/authorize` endpoint but in a hidden iframe. Using [refresh tokens](https://auth0.com/docs/libraries/auth0-spa-js#use-rotating-refresh-tokens) may help you here as they are not tied to the user's session, but you would still be able to refresh your ID tokens by calling `getTokenSilently`.

Closing this for now but feel free to continue the discussion if you need some help getting the above set up.
