### ISSUE TITLE
Need to authenticate again every time after a page refresh when logged with Google SSO

### ISSUE THREAD

**Issue by matthieuauger** [auth0/auth0-spa-js#457]
### Description

Hi, this is not a bug on this library side, however I struggled a few hours so I'm creating this issue as least to raise awareness for people who might get the same bug. Also, please tell me if I missed something in the documentation about this.

When creating a brand new React application with Auth0 integration specified here : https://auth0.com/docs/quickstart/spa/react/01-login

And logging in with Google SSO (which is proposed by default).

On page refresh, authentication is lost, you have to go through the whole authentication process again when you hit F5.

To fix it after page refresh, I had to go through the Auth0 documentation about Google integration with Oauth there: https://auth0.com/docs/connections/social/google 

I find it misleading to show a Google Login Button by default in the Universal Login, when in fact you have to do extra steps to have it fully functional. I think most people use this button to test the whole Auth0 setup and think there is an error in their code when it does not work when in fact this is the "normal" behavior.

Some suggestions:
- We could make a visible warning paragraph in the React doc (https://auth0.com/docs/quickstart/spa/react/01-login) to state that OAuth configuration is necessary
- We could remove the Google Button on the default Universal Login

I'd be happy to open a PR if you agree with one of these.

And thanks for your hard work

### Environment

> Please provide the following:

- **Version of this library used:** 1.8.1
- **Version of the platform or framework used, if applicable:** React 16.13
- **Other relevant versions (language, server software, OS, browser):** MacOS, Chrome 81

**Comment by stevehobbsdev** [comment]
Thanks for raising @matthieuauger. The points you've raised here are great points and things we can definitely improve upon, but I think it's a post that's better made on the [Auth0 Community](https://community.auth0.com). There are a few things that could cause your silently login on refresh to not work - using the Google social connection with Auth0's developer keys is just one of them.
