### ISSUE TITLE
nonce inside a0.spajs.txs cookie is blocked by Azure Front Door due to SQL injection threat

### ISSUE THREAD

**Issue by 7opf** [auth0/auth0-spa-js#462]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

When a client browser is redirected to the redirect URL and passes along its cookies to application's http server behind Azure Front Door, the request is blocked. Azure monitor (logging) shows that it was blocked due to a string pattern inside the nonce field of the cookie resembling that of a SQL injection attempt. 
```
942200 Detects MySQL comment-/space-obfuscated injections and backtick termination
```
We worked around it by adding an exclusion to this rule for the cookie name prefix, but it would be good if auth0 could use a less suspicious nonce string.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

Host SPA server behind Azure Front Door.
Commence auth flow using SPA with auth0 spa js, log-in and get redirected back to SPA

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

auth0 spa js 1.0.2

**Comment by stevehobbsdev** [comment]
@7opf is it fair to say that this issue is of wider scope than this SDK? If so, it would be better for you to create an issue on our [Auth0 Community Forums](https://community.auth0.com).

**Comment by 7opf** [comment]
@stevehobbsdev ok no problem, I've posted it here: https://community.auth0.com/t/nonce-inside-a0-spajs-txs-cookie-is-blocked-by-azure-front-door-due-to-sql-injection-threat/43118

**Comment by stevehobbsdev** [comment]
Thanks!
