### ISSUE TITLE
disabling registration of new users in laravel  7

### ISSUE THREAD

**Issue by mons-reys** [auth0/auth0-spa-js#464]
hello, i'm using **laravel** but i can't disable registration 

 Auth::routes([
  'register' => false, // Registration Routes...
  'reset' => false, // Password Reset Routes...
  'verify' => false, // Email Verification Routes...
]); 

this cmd doesn't work with me, someone explain to why ?

**Comment by adamjmcgrath** [comment]
Hi, Could you raise your issue on the Laravel repo https://github.com/auth0/laravel-auth0 ?

And, perhaps add some more details, like why the cmd doesn't work - are you seeing an error? What's the error? etc.
