### ISSUE TITLE
Passing allowedConnections param

### ISSUE THREAD

**Issue by tudorgergely** [auth0/auth0-spa-js#467]
### Description

auth0-spa doesn't seem to allow passing array params (e.g. for allowedConnections). I need to pass the allowedConnections param because we show different login possibilities in some situations.

### Reproduction

Add the allowedConnections param (an array) to Auth0ClientOptions (as an additional key). When you call loginWithRedirect this error will show up inside the auth0 page (which will be blank):

<img width="497" alt="Screenshot 2020-05-18 at 12 16 05" src="https://user-images.githubusercontent.com/7794865/82195925-afb34580-9901-11ea-8b37-3efa3385e424.png">

In the image above, `e` is a string instead of being an immutableJS array (as I saw lock.js expected)

I would expect the parameter works correctly (as it does with auth0-js) or at least the login page shows a relevant error message.

I think this happens because we encode the allowed_connections param differently in auth0-js (uses qs) and auth0-spa-js (uses encodeURIComponent and a custom function) but I don't know enough about the internals of auth0 to be certain of this.

### Environment

> Please provide the following:

- **Version of this library used:** 1.8.1
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** any browser (latest chrome), macOS
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
@tudorgergely thanks for your report

How do you expect the `allowedConnections` array to be serialized in the authorize url? `allowedConnections=foo,bar`, `allowedConnections=foo&allowedConnections=bar` or `allowedConnections[0]=foo&allowedConnections[1]=bar`? And do you have custom logic on your Universal Login Page to handle this?

You're right, currently `Auth0ClientOptions` only [accepts strings as extra parameter values](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html), it doesn't do any special query string serialisation. I'm wondering if there's a way to pass a string as the `allowedConnections` argument that will work for you

**Comment by stevehobbsdev** [comment]
@tudorgergely I'm assuming you're using the Classic Login experience here (Lock). Lock won't automatically pick up that parameter and use it, so you'll need some custom logic here.

In this case you will need to serialize the value yourself in whichever way makes sense to you, then deserialize the value again in your custom Lock template then apply the option to your Lock setup. You should be able to pick up the value from the `config.extraParams` dictionary inside the Lock template.

Hope that helps!
