### ISSUE TITLE
authorize when idle_session_timeout_expired (React)

### ISSUE THREAD

**Issue by ed-sparkes** [auth0/auth0-spa-js#468]
### Description
I am using the React Quick Start guide code and not using refresh tokens. However if i set my idle_session_timeout on my tenant to 5 minutes and then let that 5 minutes expire and then interact with my app (call to `getTokenSilently) i can see an call to `authroize` endpoint with `prompt=none` (presumably form hidden iframe) which returns a 200 response but does not seem to call the `redirect` and leaves my application in a strange state . 
The documentation suggests it should throw a login_required error, but this does not seem to be happening 

snippet from documentation
```
If the fallback mechanism fails, a login_required error will be thrown and could be handled in order to put the user back through the authentication process.
```

How can i tell that the session has timed out such that i can re-direct user to the login screen 

Many thanks, Ed

**Comment by adamjmcgrath** [comment]
Hi Ed,
If you're logged out of auth0 and call `createAuth0Client` it will attempt to log you with an iframe to `/authorize` with `prompt=none`. In your case it will fail with `login_required` and will return you a client, which is not authenticated, and it's your job to call `loginWithRedirect` - usually by presenting the user with a login button or automatically when the user visits a protected route.

**Comment by ed-sparkes** [comment]
Hi, but i call createAuth0Client using react Context when the app is loaded. Once loaded and user goes idle the next interaction is through getTokenSilently  which does seem to call `Authorize` with `prompt=none` but in returns a 200 response but then doesnt seem to get a token, i cant see any login_required failures in the network traffic, just an empty 200 repsonse

**Comment by ed-sparkes** [comment]
ok i worked it out and can now close this. Thanks for the help. 

The issue was that i was not awaiting the getTokenSilently call and not wrapping in try catch. Now i wrap in try catch and call loginWithRedirect if it fails and all is good. 


```typescript
import { useCallback } from 'react'
import { useAsyncTask, useAsyncRun } from 'react-hooks-async'
import { useAuth0 } from '../auth'

export const useGetBearerToken = (): string | undefined => {
  const { getTokenSilently, loginWithRedirect } = useAuth0()
  const getToken = useCallback(async () => 
  {
  try {
  return await getTokenSilently() 
  }catch (e){
    //should i not expect an exception here 
    console.log("Something went wrong ")
    loginWithRedirect({redirect_uri: window.location.origin,
      appState: { targetUrl: window.location.pathname }})
  }
}
, [getTokenSilently])

  const getTokenTask = useAsyncTask(getToken)
  useAsyncRun(getTokenTask)
  return getTokenTask.result ? getTokenTask.result : undefined
}
```
