### ISSUE TITLE
How to generate a passwordless link instead of a code when using loginWithRedirect 

### ISSUE THREAD

**Issue by ngirardin** [auth0/auth0-spa-js#476]
### Description

Hi,

I'd like the `loginWithRedirect` method to generate a passwordless link (https://auth0.com/passwordless) instead of a code.

I skimmed the library code but couldn't find a way to do it.

Thanks for the help.

### Reproduction

I've tried:

```
auth0Client.loginWithRedirect({ appState, passwordlessMethod: "link" });
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.8.1
- **Version of the platform or framework used, if applicable:** web
- **Other relevant versions (language, server software, OS, browser):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Thanks for raising this. This SDK does not support passwordless flows currently. The recommendation is to use [Auth0.js](https://github.com/auth0/auth0.js) instead.

**Comment by ngirardin** [comment]
Thanks @stevehobbsdev !

**Comment by laurentS** [comment]
Is using auth0.js still the current recommendation? I have the exact same question, just 8 months later :)

**Comment by Lonli-Lokli** [comment]
It's not possible to setup `link` option from Universal login page as well as from this library, only `code` available
