### ISSUE TITLE
Multiple auth0 calls on page leading to state mismatch / Scoping silent auth requests

### ISSUE THREAD

**Issue by UlyssesInvictus** [auth0/auth0-spa-js#477]
### Description

Hi,

We're running an app right now that embeds a 3rd party (nav) header. I say 3rd party, because it's loaded remotely, but it's actually developed by the same organization, and authenticates using the same Auth0 domain/audience. This header runs a silent auth (prompt=none) using auth0.js to determine the user's auth state.

We're having an issue where our own app's silent authentication code (using auth0-spa-js, and `getTokenSilently`) seems to be racing with that of the header, and intermittently fails with a `state` mismatch on the auth response.

The silent requests of both the header and our app are succeeding, but the callback code all executes on the same page, and if the header's callback response comes first, it seems as if `auth0-spa-js` inside our app is failing because `state` mismatches.

Is there a way to "scope" our silent token request so that it will only match the request that our app actually sent out, rather than picking up the header's callback response as well? Or to otherwise expose the web message in the response so that we can ignore any missing details we choose?

Other details:

- We are running a Next app, but all of this code only executes in the client (i.e. it has been programmed not to occur server-side).
- We do not have access to the 3rd party code, so it must be assumed that the fix has to be inside our own code.
- As mentioned above, the domain and audience of all requests are the same, but the scopes, client ID, and response type vary (but the header does seem to be using the defaults suggested by auth0.js).

### Environment

- **Version of this library used:** 1.8.1
- **Version of the platform or framework used, if applicable:** Node 12.6.1, React 16.12.0, Next 9.3.6
- **Other relevant versions (language, server software, OS, browser):** Chrome 81.0

**Comment by adamjmcgrath** [comment]
Hi @UlyssesInvictus - we have logic in place that prevents 2 instances of the `auth0-spa-js` client from conflicting with each other. But nothing in place to stop an `Auth0.js` client and an `auth0-spa-js` client from clashing.

I can see that the 2 `message` event handlers that each of the clients put on the `window` could get confused - but I don't think there's much we can do on the `auth0-spa-js` library to prevent this.

You'll need to add some logic to orchestrate how these 2 clients check their session and prevent them from clashing.

**Comment by UlyssesInvictus** [comment]
Thanks @adamjmcgrath for the explainer. It would still be great if there were some way the web message could be configured so that auth0-spa-js will know not to try to respond to that web message except unless it matches a user supplied state (i.e. rather than just erroring out and closing the channel, it stays open and listening for the next message), but I can see how this might be a kind of niche case.

Unfortunately, the code where we manage the auth0-spa-js session has no access to the auth0.js loading code, so (as far as I'm aware), there's absolutely no way to orchestrate the two to run without racing.

For now I've gone with the unhappy hack of just having auth0-spa-js poll for a silent token, so that if it gets back an invalid state error, it will retry (up to a maximum number of times), which solves the problem but is technically not a closed solution.

**Comment by adamjmcgrath** [comment]
>  It would still be great if there were some way the web message could be configured so that auth0-spa-js will know not to try to respond to that web message 
Ultimately it would mean sending extra query params to the authorization server so you can validate what comes back, which unfortunately we'd be reluctant to do for this use case.

If you don't mind sharing some global state between your header and app, you could handle the concurrency between the 2 `/authorize` calls by doing something like:

```js
// in your header
// wait for the app auth to complete if it was kicked off first
window._appPromise && await window._appPromise;
window._headerPromise = auth0.checkSession();
const token = await window._headerPromise;
delete window._headerPromise;

// in your app
// wait for the header auth to complete if it was kicked off first
window._headerPromise && await window._headerPromise;
window._appPromise = auth0spa.getTokenSilently();
const token = await window._appPromise;
delete window._appPromise;
```

This is effectively what we do for concurrent calls to spa js `getTokenSilently` using the `browser-tabs-lock` library.

I'm going to close this issue, feel free to reopen if you want to continue the conversation

**Comment by UlyssesInvictus** [comment]
Thanks for the suggestion! Unfortunately won't work for us because we don't have access to the code in the header, but hopefully it will help someone else (or if we ever do get access to the header, could be useful). Appreciate the feedback and the library!
