### ISSUE TITLE
Build Error: Unexpected token, expected ":"

### ISSUE THREAD

**Issue by 7s4r** [auth0/auth0-spa-js#478]
### Description

After last upgrade of MacOS Catalina to 10.15.4 and yarn upgrade, @auth0/auth0-spa-js package was upgraded from 1.6.5 to 1.8.1, I got this build error on starting parcel.js dev environment: 
`[...]/node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js:15:50071: Unexpected token, expected ":" (15:50071)`

### Reproduction

Just run a build with parcel.js bundler.

### Environment

- **Version of this library used:** 1.8.1
- **Version of the platform or framework used, if applicable:** Node.js v12.2.0
- **Other relevant versions (language, server software, OS, browser):** MacOS Catalina 10.15.4
- **Other modules/plugins/libraries that might be involved:** parcel-bundler@^1.12.4

**Comment by adamjmcgrath** [comment]
Parcel doesn't like our minified binary because of parcel-bundler/parcel#2408

You can try the workarounds in https://github.com/auth0/auth0-spa-js/issues/427#issuecomment-616441410

Also, it doesn't seem to mind our unminified binary, so you could try adding an alias to the cjs one, which is unminified:

```json
// your package.json
  ...
  "alias": {
    "@auth0/auth0-spa-js": "./node_modules/@auth0/auth0-spa-js/dist/lib/auth0-spa-js.cjs.js"
  },
  ...
```

**Comment by jedfoster** [comment]
For anyone else who comes across this, the alias solution above did not work for me. Parcel discourages special characters—specifically `@`—in aliases. 

> Avoid using any special characters in your aliases as some may be used by Parcel and others by 3rd party tools or extensions. For example:
> 
> ~ used by Parcel to resolve tilde paths.
> @ used by npm to resolve npm organizations.

https://parceljs.org/module_resolution.html#aliases 

I ended up importing the CJS file using the full filesystem path.
