### ISSUE TITLE
Question: RBAC rules / auth0Client.getPermissionScopes()

### ISSUE THREAD

**Issue by PaulInglis** [auth0/auth0-spa-js#48]
The examples of this library in conjunction with roles and permissions (via Authorization Extension) utilise a rules file, which involves duplication of data which the extension already exists.
When using `auth-js` there is a method called `getPermissionScopes` which returns the same content as what the rules file contains.
Is there any plans to implement a similar method to get the information required, rather than duplication of the permissions and scopes please?

...or any additional information / best practises on how to implement this would be appreciated

**Comment by luisrudge** [comment]
As of now, there's no plans to add a method to return the RBAC information because decoding the access_token is not recommended. More context here: https://github.com/auth0/auth0-spa-js/issues/23#issuecomment-507794605
