### ISSUE TITLE
Calling getTokenSilently in sequence intermittently makes multiple requests

### ISSUE THREAD

**Issue by JonathanHarvey** [auth0/auth0-spa-js#480]
### Description

When calling getTokenSilently in sequence one would expect the library to initiate an access token request on the first call and (assuming that the access token expiry isn't exceeded) for that same access token to be returned for the subsequent calls. This does not appear to be working correctly. We are seeing that multiple requests are being made to the token endpoint resulting in different access tokens. Furthermore, we suspect that this could be the reason for the significant number of Failed Exchange and Failed Silent Auth log entries, assuming if multiple requests are triggered at once that this opens up the possibility of re-using refresh tokens, and then invalidated tokens. Not only is this an issue for our customers who need to repeatedly re-authenticate but it makes tracking of reused refresh tokens less meaningful, in terms of being aware of possible attacks. This needs validating, of course. 

### Reproduction

This issue has been occurring in two different live codebases and I have now been able to reproduce this issue after making very limited changes to the React Sample Project application:

<img width="793" alt="Screen Shot 2020-05-26 at 1 39 10 pm" src="https://user-images.githubusercontent.com/1634826/82858169-6ba1ef80-9f56-11ea-87b2-c5cf92341677.png">

Note that we are using Rotating Refresh Tokens with a cacheLocation of "localstorage", and a specified audience. 

As you can see in the screenshot below, the sequence of requests initially results in the same access token being returned, and later returning three different access tokens:

<img width="1416" alt="Screen Shot 2020-05-26 at 11 54 29 am" src="https://user-images.githubusercontent.com/1634826/82907122-8a7da180-9fa9-11ea-8f07-5bfe92ad8196.png">

This appears to be an intermittent issue and is not reproducible every time. I have found that leaving the application in a window and returning to it after some time can result in it repeatedly make multiple token requests, and then later returns to expected operation, making only a single request. 

### Environment

- auth0-spa-js library: 1.8.1
- React: 16.8.6
- Chrome: Version 81.0.4044.138 (but seems to occur in at least Safari and Firefox as well)
- mac0S Mojave 10.14.6

**Comment by adamjmcgrath** [comment]
Hi @JonathanHarvey - thanks for your report

I've tried to reproduce your issue using the react sample app here https://github.com/auth0-samples/auth0-react-samples/compare/issue-480

I installed `v1.8.1` of the spa js sdk, set `useRefreshTokens` to `true`, set `cacheLocation` to `localstorage` and set an audience parameter (in my case to `http://localhost`).

I then added the same click handler to `Hero.js` and experimented by clicking the button. Then waiting a couple of minutes for my access tokens to expire, then clicking it again. I got a new token on the second click, and subsequent requests in the second click got that token from the cache. So I'm not able to reproduce the issue you're seeing.

<img width="1791" alt="example" src="https://user-images.githubusercontent.com/1299658/82895924-f8e04680-9f4c-11ea-8d65-f8604577cc9a.png">

Are there any other steps I should do to try and reproduce it? Or do you have a running example somewhere?

**Comment by JonathanHarvey** [comment]
Hi Adam,

As I mentioned this is an intermittent issue. I have, however, been able to force the issue (or at least a similar effect) by setting the access Token Expiration on the API to 59 seconds (or seemingly any value under a minute) once the session is established. But that is certainly not the only scenario in which I have seen this occur. The reason I suggest to change the token expiration after the session is established is that otherwise you will not be able to get isAuthenticated to return true after you have authenticated. Similarly, getIdTokenClaims does not return the token claims. If a value of under a minute is not allowed, I would have expected the UI to reject that config value, but it does not so I assume it is legitimate.

Note, I have now also raised a support ticket for the initial concern and referenced this issue. Through the support ticket I have been asked to provide a HAR file of the requests. The closest I got using the sample application (without changing the token expiration after the session was established) was by triggering a manual request shortly after authentication. I have a HAR file that shows those requests but I don't seem to be able to attach that find of file here.

Thanks,
Jon

**Comment by stevehobbsdev** [comment]
@JonathanHarvey We've identified an issue with the token expiry being under 60 seconds an are working on a fix now. However, in my testing I've been unable to see the multiple request issue you're seeing, but I have seen (and fixed) the issue with `isAuthenticated` not returning true within that 60 window.

**Comment by stevehobbsdev** [comment]
@JonathanHarvey There's an ask for you on the associated PR to test your app with the PR branch to see if that fixes your issue - would that be possible?
