### ISSUE TITLE
Unexpected uncaught "Error: Timeout when executing 'fetch'" promise rejection

### ISSUE THREAD

**Issue by dmin** [auth0/auth0-spa-js#483]
### Description
Even when the `fetchWithTimeout` function (in `src/utils.ts`) resolves successfully (i.e. there is no timeout) it still produces an uncaught promise rejection (`Error: Timeout when executing 'fetch'`). While this has no impact on the application, it does causes Chrome devtools to pause it's debugger (when the "Pause on exceptions" option is enabled). As an application developer, this behavior is unintuitive since everything appears to work as expected, and there are no network requests timing out.

Unless this is intended behavior, I'd be happy to put up a quick PR to resolve the issue.

### Reproduction
- Run sample app with `npm start`
- Load sample app with Chrome and open devtools
- Under "Sources" tab, Ensure "Pause on Exceptions" debugger option is enabled
- Login with popup or redirect/callback
- "Is authenticated" should now be true (i.e. there was not a fetch timeout)
- After 10 seconds the debugger should pause on the uncaught promise rejection "Error: Timeout when executing 'fetch'"
[<img width="1372" alt="Screen Shot 2020-05-27 at 1 36 02 PM" src="https://user-images.githubusercontent.com/371998/83060040-73c66180-a020-11ea-9dff-1e2e0695561b.png">
](url)

### Environment
- auth0-spa-js: 1.8.2
- Chrome: 83.0.4103.61

**Comment by adamjmcgrath** [comment]
Hey @dmin - thanks for reporting this!

You're right - the timeout in https://github.com/auth0/auth0-spa-js/blob/master/src/utils.ts#L250 should be cleared in a `Promise.race([...]).finally(...)`

If you're happy to fix it and write a regression test, great - otherwise we'll take a look at some point.

**Comment by pencilcheck** [comment]
still having this issue on android specifically calling handleRedirectCallback and getUser() right after

**Comment by AlokJoshi** [comment]
I am getting the following error and I think it is related to the above issue

```
Uncaught (in promise) Error: Timeout
    at n [as constructor] (auth0-spa-js.production.js:15:46401)
    at new n (auth0-spa-js.production.js:15:46802)
    at auth0-spa-js.production.js:15:47397
```

Can someone help please?

**Comment by evansims** [comment]
Hi @pencilcheck and @AlokJoshi 👋 This issue is from several years ago. We're happy to assist, but please open new issues on the repo detailing your environment and reproduction steps, so we can better assist you in troubleshooting those.
