### ISSUE TITLE
createAuth0Client throws consent_required on localhost, and documentation is incorrect

### ISSUE THREAD

**Issue by jgbpercy** [auth0/auth0-spa-js#485]
### Description

The [documentation](https://auth0.com/docs/libraries/auth0-spa-js#create-the-client) for `createAuth0Client` states that `createAuth0Client` calls `getTokenSilently` under the hood to refresh the user session, but that all errors except `login_required` are suppressed. Looking at [the code](https://github.com/auth0/auth0-spa-js/blob/e6c3ba188d55576bed4ecf34e7c82d819253f0df/src/index.ts#L33), in fact the opposite is true: `login_required` is suppressed, and all other errors are rethrown.

I believe the library is (almost - see below) correct here, and the docs are just worded incorrectly. It makes sense to me that `login_required` is suppressed (as in that case you want to create the client and let the consuming code use the client to get the user logged in). If another error is thrown then that probably means something unexpected went wrong, and the user will need to deal with it...

However, the related issue we're having is that, on localhost at least, `getTokenSilently` throws a `consent_required` error when called from `createAuth0Client`. This is not suppressed and means that `createAuth0Client` doesn't resolve the promise with a client, so we can't then redirect to show the consent screen using the client.

I'm aware we can work around this using the sync constructor, or by setting up the hosts file to deal with localhost consent skipping, and we'll do one or the other for local dev for now. However, as far as I can tell it makes sense for [this line](https://github.com/auth0/auth0-spa-js/blob/e6c3ba188d55576bed4ecf34e7c82d819253f0df/src/index.ts#L33) to also suppress `consent_required` errors as they're essentially a variation on `login_required` errors, and should be dealt with by resolving the promise with the auth0 client and letting the consuming code call the appropriate redirect.

### Reproduction

I don't think a repro adds much to this issue, but let me know if you need do need an example of anything I've described.

### Environment

auth0-spa-js 1.8.x

**Comment by adamjmcgrath** [comment]
Hi @jgbpercy - thanks for raising this

Yep - you're right on both counts. Because you can recover from the `consent_required` error we should still return you the client so you can prompt the user to login (we should only throw on unrecoverable errors - like configuration issues)

We've raised a PR to resolve this issue https://github.com/auth0/auth0-spa-js/pull/482

And, thanks for reminding me about the Docs, I'll raise a PR to fix those when we next release.

**Comment by jgbpercy** [comment]
Awesome, thank you for the quick response 👍
