### ISSUE TITLE
auth_time and max_age are provided in seconds

### ISSUE THREAD

**Issue by mvakulich** [auth0/auth0-spa-js#489]
https://github.com/auth0/auth0-spa-js/blob/e6c3ba188d55576bed4ecf34e7c82d819253f0df/src/jwt.ts#L167

here is the issue, where `auth_time` and `max_age` as per docs should be a seconds
and division by 1000 breaking token validation

**Comment by stevehobbsdev** [comment]
Thanks for raising @mvakulich - let us look into it!
