### ISSUE TITLE
Refresh token flow doesn't work without custom rule

### ISSUE THREAD

**Issue by Greenbones** [auth0/auth0-spa-js#494]
### Description

I am trying to use the new refresh token support in v1.7 and I am running into some bizarre issues. Specifically, I have the following rule in my Auth0 rules:

```
function (user, context, callback) {
  var permissions = user.permissions || [];
  var requestedScopes = context.request.body.scope || context.request.query.scope;
  var filteredScopes = requestedScopes.split(' ').filter( function(x) {
    return x.indexOf(':') < 0;
  });

  var allScopes = filteredScopes.concat(permissions);
  context.accessToken.scope = allScopes.join(' ');

  callback(null, user, context);
}
```
I found this rule in the following guide: https://auth0.com/docs/architecture-scenarios/spa-api/part-2#create-a-rule-to-validate-token-scopes. I am using it to inject the permissions defined in my Authorization extension config into the scopes on my access token. I had this rule in place and working fine before I started trying to get refresh tokens working. 

Once I turned on the useRefreshToken support in the client and forced a call to get a new token, that rule started causing me problems. Something in the rule is blowing up when it tries to access a 'scope' property on something that's undefined. Based on a scan of the client code, I'm guessing this is because unlike the normal token requests, the request token request does not include a scope property on the request, so my rule code is blowing up. This is fair enough, though it does put me in a position of not knowing how to send back the requested scopes along with my permissions on the access token being returned from the refresh token request.

In the course of trying to debug this issue, I tried turning off my rule. My hope was that I would be able to see what the refresh token request's response looked like to at least give me some clues. What I found however, is that with my rule turned off I don't even get a refresh token back on the initial token request. I narrowed it down to the fact that if my rule doesn't set the offline_access scope on the access token's scopes, no refresh token is returned.

This seems totally bizarre to me however, since I assume not everyone has this random rule in their config. That being said, I can't find any way to get a refresh token back in the first place without this rule, so I thought I'd report the issue.

### Reproduction
As near as I can tell, you simply have to turn on refresh tokens in the auth0 client and attempt to retrieve a new token. Without any custom rules, this appears to fail.

### Environment

> Please provide the following:

- Version of this library used: 1.7.0
- Version of the platform or framework used, if applicable: Angular 9
- Other relevant versions (language, server software, OS, browser): Chrome

**Comment by stevehobbsdev** [comment]
@Greenbones  👋 

In order to use the refresh token feature, you will need to enable [Refresh Token Rotation](https://auth0.com/docs/tokens/guides/configure-refresh-token-rotation) on your Auth0 client application. Otherwise the behaviour is that you won't receive a refresh token for a browser-based app, even if you specify `offline_access`.

Could you check if you have that enabled?

**Comment by Greenbones** [comment]
Hey @stevehobbsdev 

I went through the tutorial on setting up refresh token support and I do have the refresh token rotation turned on yep. I do get refresh tokens properly when the rule I outlined above is turned on, so I'm reasonably sure that things are configured properly. The issue I'm seeing is that when I turn that rule _off_, the refresh tokens stop being sent, seemingly for the reasons I listed above.

**Comment by stevehobbsdev** [comment]
@Greenbones Are there other rules that could be getting in the way here?

As long as the following criteria are met, you should be receiving tokens:

* You're using an SPA
* You have the Rotating Refresh Tokens feature turned on for your client
* You have enabled refresh tokens in the SDK by using `useRefreshTokens: true` in the configuration

As a note, I saw you made reference to "useRefreshToken" in your original post - please ensure you have not mispelled the property in your code (it should be `useRefreshTokens`), in which case your problem would make sense, as enabling this property causes the SDK to start sending the `offline_access` scope.

**Comment by Greenbones** [comment]
We are using an SPA, we have rotation refresh tokens turned on, we have enabled them in the SDK.

As I stated above, we **do** get refresh tokens in the server response as long as the rule I'm describing is turned on, so the configuration has to be correct. It's when we turn the rule off that the refresh token stops being sent.

The only other rules we have in our tenant are the Authorization Extension rule (auth0-authorization-extension) and a rule that dumps some Authorization Extension permissions onto a namespaced claim on the access token. I don't think either of those would be affecting the sending of a refresh token and indeed they aren't since we do get refresh tokens when the rule I described initially is turned on.

**Comment by stevehobbsdev** [comment]
I think at this point, if you can provide the smallest reproducible sample, this would help us triage this issue. Or, try and reproduce what you're seeing with the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground). I can tell you that with the configuration I mention above, this feature works and so I think in your case it could be specific to your setup or scenario.

**Comment by Greenbones** [comment]
I'm sure you're right that's related to our setup in some way. We're not doing anything special in the configuration of the SDK though, it's basically the Angular tutorial verbatim and beyond that we have an SPA application and these rules. There's obviously something going on.

That said, I probably I won't be able to reproduce it outside of our tenant. I wanted to report this in case it was a bug that was going to happen to other people too. If it's not, we can close the issue.

**Comment by stevehobbsdev** [comment]
Ok thanks - if you dig deeper and find anything that could be related to the SDK, please feel free to continue the conversation.
