### ISSUE TITLE
Issue with loginWithPopup method

### ISSUE THREAD

**Issue by demonmovch** [auth0/auth0-spa-js#495]
Hello. I would like to login with popup. I am using loginWithPopup() method to achive this. But when this method is executed, a new small separate window is displayed. But I need this popup to be a modal dialog box embedded within my web site page (like your Lock embeddable login form). Please let me know if this possible and how I can achieve this.

**Comment by stevehobbsdev** [comment]
Unfortunately this is not supported with the methods we expose from the SDK, `loginWithPopup` for example will always use a separate window.
