### ISSUE TITLE
Using auth0-spa-js with apollo-client (and other packages added by ng add apollo-client) and angular breaks auth0 redirect 

### ISSUE THREAD

**Issue by PimS1997** [auth0/auth0-spa-js#496]
### Description

Trying to use auth0 login with apollo-client for graphql backend server and angular.

### Reproduction

1. follow auth0 tutorial for angular: [https://auth0.com/docs/quickstart/spa/angular2/01-login](https://auth0.com/docs/quickstart/spa/angular2/01-login)
2. use `ng add apollo-client`
3. try log in
4. get error:

[https://i.imgur.com/Ol2lY3E.png](https://i.imgur.com/Ol2lY3E.png)

### Environment

> Please provide the following:
Framework: Angular 9

    "typescript": "~3.8.3"
    "apollo-angular": "^1.9.1",
    "apollo-angular-link-http": "^1.10.0",
    "apollo-cache-inmemory": "^1.6.0",
    "apollo-client": "^2.6.0",
    "apollo-link": "^1.2.11",
    "graphql": "^14.6.0",
    "graphql-tag": "^2.10.0",

**Comment by adamjmcgrath** [comment]
Hi @PimS1997 

Do you have a working example I can take a look at? 

I've tried doing `ng add apollo-client` on the Auth0 Angular sample app (https://github.com/auth0-samples/auth0-angular-samples/tree/master/01-Login) - But it gives me:

```bash
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```

**Comment by adamjmcgrath** [comment]
Ah ok, I think you meant to say `ng add apollo-angular`

I've done that on the example app and can't reproduce your issue: https://github.com/auth0-samples/auth0-angular-samples/compare/angular-apollo

The application handles the redirect from the authz server and logs in correctly.

> There are no query params available for parsing 

This error means that you're calling `handleRedirectCallback` when the `code` and `state` query params have already been removed from the callback url. Perhaps it's being called twice?

**Comment by PimS1997** [comment]
I started a new app and followed the guide, I am using the latest packages for each, not the example project from a github page. I am currently unable to share my project as i dont have access to said device at this moment. I will provide the repo once I am able to.

**Comment by PimS1997** [comment]
Hey @adamjmcgrath,
Apologhies, I indeed meant to say `ng add apollo-angular`.

I think I am slowly losing my mind, I have tried reproducing the error in a fresh repository, but somehow the fresh one, tracing all my steps, doesn't have this error? So I must be doing something wrong, I just can't seem to find *what*. Here is my broken repository:
[https://gitlab.com/pims1997/project-air-dnd](https://gitlab.com/pims1997/project-air-dnd)
Let me know if you can acces this. if not I can send a zipped version or try upload on GH

**Comment by PimS1997** [comment]
Okay I found the issue, it's not to do with installing apollo-angular as I initially thought. It's to do with the routing module from angular. I have it set to that all routes to site root (foo.com) will redirect automatically to '/home' (foo.com/home) where my homepage component is. This apparently breaks the auth0 redirect and results in the error.
