### ISSUE TITLE
Typings issue when using typeRoots instead of explict type import

### ISSUE THREAD

**Issue by iongion** [auth0/auth0-spa-js#498]
### Description

> Typescript typing error when trying to set global typings path

```
ERROR in W:\Workspace\nasa-client\tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for '__mocks__'.
Child HtmlWebpackCompiler:
```

### Reproduction

> Adjust tsconfig.json with:

```
{
...
"compilerOptions": {
    "typeRoots": [
      "./src/typings",
      "./node_modules/@auth0/auth0-spa-js/dist/typings",
      "./node_modules/@types"
    ],
    ...
}
...
}
```

### Mitigation

> I currently fix it like this, but I have no idea of what I am doing (Notice the wildcard)

```
{
...
"compilerOptions": {
    "typeRoots": [
      "./src/typings",
      "./node_modules/@auth0/auth0-spa-js/dist/typings/__mocks__/*",
      "./node_modules/@auth0/auth0-spa-js/dist/typings/*",
      "./node_modules/@types"
    ],
    ...
}
...
}
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.9.0
- **Version of the platform or framework used, if applicable:** Vanilla Typescript
- **Other relevant versions (language, server software, OS, browser):** Any
- **Other modules/plugins/libraries that might be involved:** None

**Comment by adamjmcgrath** [comment]
Hi @iongion - thanks for raising this

I've raised a PR to remove `__mocks__` from the typings folder which should resolve the issue for you.

In the meantime, the following should be enough to workaround the issue

```json
{
...
"compilerOptions": {
    "typeRoots": [
      "./src/typings",
      "./node_modules/@auth0/auth0-spa-js/dist/typings/*",
      "./node_modules/@types"
    ],
    ...
}
...
}
```
