### ISSUE TITLE
Methods not available on Auth0Client

### ISSUE THREAD

**Issue by nojaf** [auth0/auth0-spa-js#50]
When the promise resolves and returns me my [Auth0Client ](https://auth0.github.io/auth0-spa-js/classes/auth0client.html)I don't seem to have any methods:

![image](https://user-images.githubusercontent.com/2621499/60625154-4446af00-9de7-11e9-937a-60a5592200c7.png)

![image](https://user-images.githubusercontent.com/2621499/60625197-5cb6c980-9de7-11e9-884e-5a68ce75c55f.png)

I'm following the example from [the docs](https://auth0.com/docs/libraries/auth0-spa-js) using promises (not with async).

**Comment by nojaf** [comment]
My problem is related to passing the client down using React.Context.
Somehow the prototype is reset to Object.
Right after the promise resolves, the object does contain the methods.

**Comment by blakedietz** [comment]
@nojaf did you have a fix for this? I'm following the documentation listed in the react quickstart and am applying it to my app. I'm still seeing this issue by using their example.

**Comment by nojaf** [comment]
So what I had is something like this

```js
const App = ({auth}) => {
   console.log(auth); // here prototype of Object
   <p>my app</p>
}

createAuth0Client({}).then(auth0 =>
   console.log(auth); // here prototype of AuthClient
    const elem = document.getElementById("app")
   ReactDOM.render(elem , <App auth={auth0} />);
)
```

My current workaround was
```js
let auth0 = null;
const App = () => {
   console.log(auth0); // still prototype of AuthClient
   <p>my app</p>
}

createAuth0Client({}).then(auth =>
   console.log(auth); // here prototype of AuthClient
   auth0 = auth;
    const elem = document.getElementById("app")
   ReactDOM.render(elem , <App />);
)
```

I'm not a huge fan of this workaround. Because well a nasty mutable global.

**Comment by stevehobbsdev** [comment]
@nojaf I'm not sure if you've seen this, but we are trialling a React wrapper, which makes an appearance in out [React SDK Quickstart](https://auth0.com/docs/quickstart/spa/react/#install-the-auth0-react-wrapper). Eventually this wrapper will become a library of its own, but right now it provides an `Auth0Provider` component that can wrap your application and provide the Auth0 instance, which uses Context under the hood.

You can see how the component is used on that same doc, or in the [React auth0-spa-js sample app](https://github.com/auth0-samples/auth0-react-samples/blob/master/01-Login/src/index.js).

Does this help you with your issue? If you use the wrapper and have any feedback on it, we'd love to hear it.

**Comment by nojaf** [comment]
Thanks for pointing this out. I really like the hook!
