### ISSUE TITLE
Configurability of token fetch endpoints

### ISSUE THREAD

**Issue by avin45h** [auth0/auth0-spa-js#505]
We have a scenario where we are using different endpoint for fetching token. When I execute 
`handleRedirectCallback` method on auth instance, it fetches the oauth token. However the token end point for fetching this has a hardcoded suffix. Can we add support of configuring these endpoints?

`src/utils.ts:301`
```javascript
export const oauthToken = async (
  { baseUrl, timeout, ...options }: TokenEndpointOptions,
  worker
) =>
  await getJSON(
    `${baseUrl}/oauth/token`,
    timeout,
    {
      method: 'POST',
      body: JSON.stringify({
        redirect_uri: window.location.origin,
        ...options
      }),
      headers: {
        'Content-type': 'application/json'
      }
    },
    worker
  );```

**Comment by adamjmcgrath** [comment]
Hi @avin45h - thanks for raising an issue

`baseUrl` is derived from the `domain` argument, which should be your auth0 account domain https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#domain

Can you tell me more about your use case? Like why you would want to use a different domain for the token endpoint, and why you wouldn't want this to be the same domain as the /authorize endpoint?

**Comment by avin45h** [comment]
Hi @adamjmcgrath 
We have a server for oauth where we fetch meta data from `.well-known/openid-configuration`

I want to keep same domain argument, however we have a token endpoint entry defined which I want to use for fetching token
`token_endpoint : "<baseURL>/connect/token"`

Since the endpoint for token fetch is hardcoded (not the base URL part), I can't use the above endpoint.

**Comment by adamjmcgrath** [comment]
Hi @avin45h - thanks for clarifying

Currently, the scope of this library is only for use with Auth0's authorization server, so we wont be able to accommodate this feature request - apologies.
