### ISSUE TITLE
https改成http

### ISSUE THREAD

**Issue by duzhenyi** [auth0/auth0-spa-js#508]
this.domainUrl = `https://${this.options.domain}`;
这里的https，我想改成http,可是改过后编译的话执行 rollup -m -c ，这个-c是一个配置文件，请问能一起提交嘛？谢谢

**Comment by adamjmcgrath** [comment]
Hi @duzhenyi - thanks for raising this issue. You cannot use this library to call an authorization server over HTTP, it must be over HTTPS to prevent man in the middle attacks.

**Comment by duzhenyi** [comment]
感谢大佬回复，我目前是开发环境，就想用http调试一下，上线的时候才切换成https。谢谢回复！！！

**Comment by adamjmcgrath** [comment]
Hi @duzhenyi - apologies but currently this library is for authenticating against Auth0 only, we don't support other identity providers (even development ones on localhost)
