### ISSUE TITLE
using refreshTokens option throws error when calling getTokenSilently({ ignoreCache: true })

### ISSUE THREAD

**Issue by Bastczuak** [auth0/auth0-spa-js#510]
### Describe the problem

Try to get a fresh token with `getTokenSilently({ignoreCache: true})` and using the `refreshTokens` options will results in an error. To find the error I used the SDK playground. 
```
utils.ts:290 Uncaught (in promise) Error: Cannot read property 'methods' of undefined
    at utils.ts:290
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at fulfilled (tslib.es6.js:70)
```
The problem is somewhere in `utils.ts` in the `getJson()` function. 

I did all the steps needed for using refresh tokens in my application, which means: 
1. Enable rotating refresh tokens.
2. Setup refresh token lifetime and reuse interval
3. Enable refresh token grant type
4. Enable OIDC Conformant setting

### What was the expected behavior?

Calling `getTokenSilently` doesn't fail when using refresh tokens and updates my token or throws an error if a user session is invalid.

### Reproduction

1. Enable refresh tokens in your application following the documentation.
2. Use the SDK playground with `yarn dev`
3. Switch on `Use refresh tokens` in the UI.
4. Be a logged in user.
5. Request a fresh token by clicking on `Get multiple tokens (ignoring cache)`
6. See the error in the dev tools.

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:**
`1.10.0`
- **Which browsers have you tested in?**
`All current versions of Chrome, Safari, Firefox, Edge`
- **Which framework are you using, if applicable (Angular, React, etc):**
`VueJs`
- **Other modules/plugins/libraries that might be involved:**
`None`

**Comment by adamjmcgrath** [comment]
Hi @Bastczuak - thanks for raising this

Am not able to reproduce this - it might be an error from the Network. Can you check if you have a custom rule enabled in your tenant that might be causing the issue?

**Comment by Bastczuak** [comment]
@adamjmcgrath you are right. Of course it's an mistake on my site.  I have a rule which checks the auth method in context.authentication. It looks it doesn't exist there anymore when using `refreshTokens`.

**Comment by adamjmcgrath** [comment]
Good to know - thanks for confirming @Bastczuak

**Comment by Bastczuak** [comment]
@adamjmcgrath  May I ask why `getTokenSilently({ignoreCache: true})` doesn't throw an error when I'm logged out and using refresh tokens? So being logged in 2 tabs -> Log out in tab 1 -> Switch to tab 2 -> getTokenSilently returns a token and doesn't throw an error. I hoped it worked like the legacy flow. What's the best way to check the user session when using refresh tokens?

**Comment by adamjmcgrath** [comment]
@Bastczuak I expect it's because getting the token the first time after being logged out wont use the refresh token grant, you'll do the authorize dance then get your first set of tokens with the code exchange. Subsequent requests will use the refresh token grant which must hit this issue you have with your custom rule

**Comment by Bastczuak** [comment]
@adamjmcgrath oh no, this behavior is with the rule disabled.
