### ISSUE TITLE
Refresh token should survive browser restart

### ISSUE THREAD

**Issue by flundermicha** [auth0/auth0-spa-js#517]
We are considering using `useRefreshTokens: true` and the new feature RTR (Refresh Token Rotation). Unfortunately it looks as if the refresh token is only stored in memory (in the `refreshToken` variable in `token.worker.ts`)

It would be really nice, if there would be a possibility to store the refresh token (which is valid for 30 days!) on the client, so that it survives a browser/computer restart. With this feature users would get a much better SSO experience, because some of our users need to login multiple times a week at the moment.

May be the refresh token could be stored in an HttpOnly cookie (which must be set by the Auth0 server, which answers the request for an refresh token).

**Comment by adamjmcgrath** [comment]
Hi @flundermicha 

If you set `cacheLocation` to `localstorage`, this will store your refresh tokens in the browser's `localStorage` which will persist them between page refreshes / browser restarts

Have a look at https://auth0.com/docs/libraries/auth0-spa-js#change-storage-options for more info

**Comment by flundermicha** [comment]
Thank you.
