### ISSUE TITLE
getUser and getTokenIdClaims are marked as async while no async call is made

### ISSUE THREAD

**Issue by weyert** [auth0/auth0-spa-js#535]
### Describe the problem
The `getUser` and `getIdTokenClaims` methods are worked as `async` in the source code while they aren't doing any `await`.

### What was the expected behavior?
Remove the reference to `async` in the methods when they are synchronous instead of asyncronous

### Reproduction
Please, see the source code, at: 

getTokenIdClaims
https://github.com/auth0/auth0-spa-js/blob/9c50d6def0b3492d62198562eb2c3e175b6faa2b/src/Auth0Client.ts#L407 

getUser
https://github.com/auth0/auth0-spa-js/blob/9c50d6def0b3492d62198562eb2c3e175b6faa2b/src/Auth0Client.ts#L382

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:** master branch of github
- **Which browsers have you tested in?** N/A
- **Which framework are you using, if applicable (Angular, React, etc):** N/A
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by neutiyoo** [comment]
Hi, I've created #537 which makes the following functions synchronous:
- `getUser`
- `getIdTokenClaims`
- `isAuthenticated`

**Comment by weyert** [comment]
Great thank you @neutiyoo

**Comment by stevehobbsdev** [comment]
Thanks for raising this issue. This is absolutely something we'd like to fix, but it will have to happen in a new major version as it changes the method signature. This won't be immediately forthcoming, but I have kept a note internally to fix this.

**Comment by reify-tanner-stirrat** [comment]
I'd argue that it should be async, and that it should wait until the ID token is available and then provide it. I was running into a frustrating issue where if I didn't explicitly wait for `isLoading` to be false on `useAuth0()` before attempting to read the claims, the function would happily return `undefined`, which is useless.

**Comment by frederikprijck** [comment]
They are async still.

We cant wait until there is an id token, as there is a valid situation for the user to not be authenticated, and the user and id token to be undefined.

You should wait until isLoading is false until you start looking at the state.
