### ISSUE TITLE
Timeout presumably due to timeout expiration

### ISSUE THREAD

**Issue by BrianSHenderson** [auth0/auth0-spa-js#541]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I’m receiving the following error message:
![Screenshot 2020-08-04 at 10 02 33](https://user-images.githubusercontent.com/2174330/89313367-5214d680-d670-11ea-83da-e69a7c13be6f.png)
when I go back to a web page that will probably have an expired token. Opening in an Incognito window does not give the error.

### What was the expected behavior?

To either refresh the token or be logged out

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Log in to a site
- The next day check if the timeout error has been produced
- ...

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

I’m using v1.11.0, tested with latest release version of Chrome.

**Comment by stevehobbsdev** [comment]
Thanks for the report - can you let me know if you can see any additional logging in your [Auth0 dashboard logs](https://manage.auth0.com/#/logs)?

**Comment by BrianSHenderson** [comment]
I'm getting a 'Failed Silent Auth' - The specified redirect_uri <domain> does not have a registered origin.

**Comment by BrianSHenderson** [comment]
That appears to have resolved the problem, thanks
