### ISSUE TITLE
Unable to fetch new access token via refresh token rotation in Safari 13.1

### ISSUE THREAD

**Issue by petermatthews** [auth0/auth0-spa-js#543]
### Describe the problem

After a successful login we are unable to fetch a new access token via refresh token rotation in Safari 13.1.1 or Safari 13.1.2 as the "login_required" error is always returned. 

The initial login redirect and subsequent callback does successfully produce a new token. Subsequent login redirects and callbacks also successfully produce a new token but this is disruptive to our user experience given the user may lose unsaved form data due to this redirect.

If you disable "Prevent cross-site tracking" in Safari then the issue is resolved but this is not a practical solution given our user base. Apparently ITP has been "enhanced" in Safari 13.1, it's possible that this issue is related to these changes? https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

### What was the expected behavior?

Ability to fetch a new access token via refresh token rotation without a login redirect being required. This would line up with "You can use Refresh Token Rotation as an alternative that provides a secure method for using refresh tokens in SPAs while providing end-users with seamless access to resources without the disruption in UX caused by browser privacy technology like ITP." from https://auth0.com/docs/api-auth/token-renewal-in-safari .

### Reproduction

Start the v1.11.0 Auth0 SPA JS Playground and visit the local server in Safari 13.1.1 or 13.1.2. Configure the domain, client id, audience appropriately. Set the toggles to the following values:
Use local storage - True
Use refresh tokens - True
Use token cache when fetching new tokens - False
Use Auth0Client constructor - True

Save changes and then click "Login redirect" and enter appropriate credentials to login. On return, click "Login redirect callback" and an access token will be successfully displayed.

Then click "Get access token" and a "login_required" error will be returned. This behavior is consistent.

Note that if you go into Safari preferences and disable "Prevent cross-site tracking" that the problem does not persist. The problem is also not present on Firefox 79.0 or Chrome 84.0.4147.105.

If you enable the token cache the token requests will succeed up until the point the access token expires and then behavior will be as above - a redirect will be required in order to fetch a new token.

The application configuration is set to utilize rotating refresh tokens with a 180 second token expiration for testing purposes. The refresh token lifetime is set to 36000 seconds and the refresh token reuse interval is set to 4 seconds. Happy to share any other pertinent details or logs that might be helpful. (This being related to an application/API configuration issue would be a relief!)

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

Yes, see above.

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:**
v1.11.0
- **Which browsers have you tested in?**
Safari 13.1.1 and 13.1.2
- **Which framework are you using, if applicable (Angular, React, etc):**
N/A - SPA JS Playground.
- **Other modules/plugins/libraries that might be involved:**
N/A - SPA JS Playground.

**Comment by adamjmcgrath** [comment]
Hi @petermatthews - thanks for raising this

Were you using the default `client_id` in the SPA Playground? I just checked and for some reason it was set to non rotating refresh tokens in the management dashboard. I've just fixed this by setting it to  "Rotating" RTs and the playground seems to be working correctly again - can you confirm?

**Comment by petermatthews** [comment]
Hi Adam.

Sincere thanks for the rapid response.

We're using our own domain, client_id, and audience but your response was nonetheless very helpful -- turns out this was similarly related to a misconfiguration on our part. In particular, the Allow Offline Access setting for the relevant API was set to false. Apologies on that front; the shared API is in use by another team's application already using RTR so we hadn't even considered the possibility of a misconfiguration there previously. 

Everything seems fine on Safari after Allow Offline Access was enabled, so overall we're in great shape.

I'm happy to close this issue. Hopefully this record of my misfortune in the issue history proves helpful for someone else who encounters the same problem. It's kind of interesting that the issue was not apparent on Chrome / Firefox or with ITP disabled and thus the issue was masked, I'm guessing it was falling back to third party cookies in that instance?

One note: The need to set "Allow Offline Access" on the API is not a part of the https://auth0.com/docs/tokens/guides/configure-refresh-token-rotation document, this seems like it may be a worthwhile addition.
