### ISSUE TITLE
'@auth0/auth0-spa-js@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by Alexnavi44** [auth0/auth0-spa-js#544]
Hello,

I can not install @auth0/auth0-spa-js with npm, i receive the foloowing error:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@auth0%2fauth0-spa-js - Not found
npm ERR! 404 
npm ERR! 404  '@auth0/auth0-spa-js@latest' is not in the npm registry.

**Comment by tuteng** [comment]
I encountered the same problem.

**Comment by adamjmcgrath** [comment]
Seems to work for me

```
$ npm i @auth0/auth0-spa-js@latest --silent --force --registry=https://registry.npmjs.org/
+ @auth0/auth0-spa-js@1.11.0
```

Looks like there's currently an issue with scoped packages on npmjs.org https://status.npmjs.org/

![image](https://user-images.githubusercontent.com/1299658/89523802-675a4400-d7db-11ea-85ba-bd7600b6aa9e.png)

**Comment by adamjmcgrath** [comment]
https://status.npmjs.org/incidents/cksjqc1w11v5
