### ISSUE TITLE
Unable to reliably retrieve the appState object

### ISSUE THREAD

**Issue by overbyte** [auth0/auth0-spa-js#549]
### Description

I am currently unable to reliably retrieve the appState object from a `handleRedirectCallback()` response after forcing the user to verify their email however I can see that the appState is in the cookie and can reliably get it from `client.transactionManager.transactions`.

### What was the expected behavior?

On a redirect after a verification link is clicked and includes `success=true` in the query, the `client.handleRedirectCallback()` promise should evaluate to include any `appState` supplied to the `client.loginWithRedirect()` method.

### Reproduction

* call `client.loginWithRedirect()` including a `redirect_uri` and an `appState` with a `redirectPath` property.
```
    const client = createAuth0Client(options);

    const login = async redirectPath => {
        const c = await client;
        return c.loginWithRedirect({
            redirect_uri: window.location.origin + '?form=register', // query to set the state of the universal login form
            appState: {
                redirectPath,
            },
        });
    };
```
* register with universal login form
* return to site and redirect to unverified state
```
        const notVerified =
            query.error_description &&
            query.error_description === 'email_unverified';
        // redirect ...
```
* click on verification link in email from auth0 (note: the appState with the redirectPath exists in the cookie (below example)
```
    const handleRedirectCallback = async query => {
        const c = await client;
        const success = query.success === 'true';
        if (query.code && query.state) {
            try {
                const res = await c.handleRedirectCallback();
                const appState = res.appState; // empty response
            } catch (error) {
                console.warn('error handling redirect callback', error);
            }
        }
      ...
    };

// cookie
{
  "nonce": "<removed>",
  "code_verifier": "<removed>",
  "appState": {
    "redirectPath": "/event/myeventid/registration/complete"
  },
  "scope": "<removed>",
  "audience": "https://api.mysite.com/",
  "redirect_uri": "https://mysite.com/"
}
```

* my current fix is to pull the appState from the transaction manager but this is undocument and so makes me nervous
```
    const handleRedirectCallback = async query => {
        const c = await client;
        const success = query.success === 'true';
        if (query.code && query.state) {
            try {
                const res = await c.handleRedirectCallback();
                let appState = res.appState;
                if (!appState.redirectPath) {
                  const transactions = Object.keys(c.transactionManager.transactions).map(
                    key => c.transactionManager.transactions[key]
                  );
                  appState = transactions[0].appState;
                }
            } catch (error) {
                console.warn('error handling redirect callback', error);
            }
        }
      ...
    };
```

### Environment

- **Version of `auth0-spa-js` used:** @auth0/auth0-spa-js@1.11.0
- **Which browsers have you tested in?** 
  * chromium Version 84.0.4147.105 (Official Build) snap (64-bit) (Linux)
  * firefox 79.0 (64-bit) (Linux)
  * firefox 79.0 (64-bit) (MacOS)
  * Safari (iOS 14)
- **Which framework are you using, if applicable (Angular, React, etc):** vue@2.6.11

**Comment by stevehobbsdev** [comment]
Thanks @overbyte. I'd like to pick up on a couple of things to help investigate this:

> return to site and redirect to unverified state

So this is happening on the redirect back to your app from Auth0 after login, and you're reading this from the query string directly?

Do you call `handleRedirectCallback` at this point if your app receives this error?

> click on verification link in email from auth0 (note: the appState with the redirectPath exists in the cookie (below example)

Can you clarify that, aside from not being able to read `appState`, you're able to log in? You're not getting an `invalid state` error or anything else to that effect?

> my current fix is to pull the appState from the transaction manager but this is undocument and so makes me nervous

Yes, this is a private API and so I would not rely on this working in future versions, depending on what changes we make intermally. Let me investigate why you're not able to get access to `appState` the normal way.

**Comment by overbyte** [comment]
Hi @stevehobbsdev 

Apologies, we've moved away from using the verification functionality but I'll respond from memory

> So this is happening on the redirect back to your app from Auth0 after login, and you're reading this from the query string directly?
> Do you call handleRedirectCallback at this point if your app receives this error?

The app will only handleRedirectCallback when it receives a `code` and a `state` in the return query otherwise an error occurs

> Can you clarify that, aside from not being able to read appState, you're able to log in?

The appState is not returned by `await client.handleRedirectCallback()`
```
const res = await c.handleRedirectCallback();
const appState = res.appState; // empty response
```

> You're not getting an invalid state error or anything else to that effect?

apart from the appState object not being returned, the state and code are set (we're not using `handleRedirectCallback` otherwise)

> Yes, this is a private API and so I would not rely on this working in future versions, depending on what changes we make intermally. Let me investigate why you're not able to get access to appState the normal way.

Thankyou

**Comment by stevehobbsdev** [comment]
Thanks for the report. I haven't been able to reproduce a scenario where I can't get access to the app state. I will close this for now but keep it in mind to reference if we do see this again.
