### ISSUE TITLE
Capacitor IOS

### ISSUE THREAD

**Issue by nseb** [auth0/auth0-spa-js#551]
I Use Auth0 in my Capacitor IOS Application with deeplink , I have an error with the silent token : 

Unable to post message to https://www.xxx. Recipient has origin http://195.82.55.55:8081.

**Comment by stevehobbsdev** [comment]
@nseb Please do not clear the issue template when creating bugs as we ask for information on there which can help us to diagnose your issue, including which version of the library you are using.

Do you see an error in your [Auth0 Logs dashboard](https://manage.auth0.com/#/logs) and what is the exact error message you're seeing?

**Comment by stevehobbsdev** [comment]
Closing this for now, but if you have any further information to report, feel free to continue the conversation.
