### ISSUE TITLE
getTokenWithPopup doesn't respect overridden default audience

### ISSUE THREAD

**Issue by zajax** [auth0/auth0-spa-js#554]
### Describe the problem

My workflow is trying to call getTokenSilently() first, and if that fails with an error of "Consent required", try to get the token via getTokenWithPopup(), to allow users to consent. Generally, this works, but getTokenWithPopup will not return the new token due to getting the wrong cache value. It gets the wrong cache value because it doesn't take into account the default Auth0Provider audience, which I have set. The work around is to provide the audience value in the getTokenWithPopup function, but since most other functions work fine under the hood to pull the audience value, I feel getTokenWithPopup should as well.

![image](https://user-images.githubusercontent.com/175696/90566837-2bc65f00-e177-11ea-9701-c066350969a2.png)

### What was the expected behavior?

I expect getTokenWithPopup to not cache miss and thus error on missing field immediately after the consent form is accepted by the user. Additionally I expect the getTokenWithPopup to respect the audience I provided to the Auth0Provider.

### Reproduction

- Have a SPA app that will use an API, but requires consent to use that API.
- Setup the SPA app to use that API as audience
- Call getTokenSilently, and if consent is missing, call getTokenWithPopup
- Provide that token returned by either getTokenSilently or getTokenWithPopup to the next step, in this case, a fetch call to the api.

Example codes:
```
//auth provider. its pretty copy pasted from the auth0 quick start guide
        <Auth0Provider
          domain={this.state.domain}
          client_id={this.state.clientId}
          audience={this.state.audience}
          redirect_uri={window.location.origin + '/'}
          onRedirectCallback={onRedirectCallback}
        >
```

```
// Token retrieval
const { getTokenSilently, getTokenWithPopup } = this.context;
    return getTokenSilently({scope: scopes})
      .catch(err => {
      if(err.message === "Consent required"){
        console.log('Missing Consent, trying to get it.')
        return getTokenWithPopup({scope: scopes, /*audience: '-----'*/})
          .then(token => token)
          .catch(err2 => {
            console.error(err2);
            alert(err2);
          });
      }else{
        throw err;
      }
    })
```

in loginWithPopup(), which is called from getTokenWithPopup(), this._getParams is called and returns the correct audience value.
![image](https://user-images.githubusercontent.com/175696/90567785-b52a6100-e178-11ea-9793-ba9336bce647.png)

but in getTokenWithPopup(), it stays as "default" unless I provided the audience in the actual call of getTokenWithPopup
```
// no where in this function is there a lookup against the provider audience like there is with _getParams in the loginWithPopup call
  public async getTokenWithPopup(
    options: GetTokenWithPopupOptions = {
      audience: this.options.audience,
      scope: this.scope || this.defaultScope
    },
    config: PopupConfigOptions = DEFAULT_POPUP_CONFIG_OPTIONS
  ) {
    options.scope = getUniqueScopes(
      this.defaultScope,
      this.scope,
      options.scope
    );

    await this.loginWithPopup(options, config);

    const cache = this.cache.get({
      scope: options.scope,
      audience: options.audience || 'default',
      client_id: this.options.client_id
    });

    return cache.access_token;
```
![image](https://user-images.githubusercontent.com/175696/90567990-09354580-e179-11ea-9aa6-697d00ac22ee.png)

Which results in cache being null, and thus a error getting access_token property on a null object

```
react_devtools_backend.js:2273 TypeError: Cannot read property 'access_token' of undefined
    at Auth0Client.<anonymous> (Auth0Client.ts:654)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at fulfilled (tslib.es6.js:70)
```

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:** 1.11.0
- **Which browsers have you tested in?** chrome latest on windows
- **Which framework are you using, if applicable (Angular, React, etc):** react 16
- **Other modules/plugins/libraries that might be involved:**

**Comment by zajax** [comment]
Workaround is just to call getTokenSilently one more time

```
    const { getTokenSilently, getTokenWithPopup } = this.context;
    return getTokenSilently({scope: scopes})
      .catch(err => {
      if(err.message === "Consent required"){
        console.log('Missing Consent, trying to get it.')
        return getTokenWithPopup({scope: scopes, /*audience: 'uxua-api'*/})
          .then(token => token)
          .catch(err2 => {
            // temp work around for https://github.com/auth0/auth0-spa-js/issues/554
            return getTokenSilently({scope: scopes});
          });
      }else{
        throw err;
      }
    })
```

**Comment by adamjmcgrath** [comment]
Hi @zajax - thanks for your detailed bug report

Looking at: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L634-L637 

I see that the defaults for `audience` and `scope` are only applied if you don't pass anything to  `getTokenWithPopup`, you're using `getTokenWithPopup({ scope: scopes })`, since an argument is being supplied to `getTokenWithPopup`, it doesn't use the default, so the default audience is not used.

You could also work around this by passing nothing to `getTokenWithPopup` (if `scopes` matches your default scopes), or passing the `audience` to `getTokenWithPopup` in addition to the scopes (`getTokenWithPopup({scope: scopes, audience: 'uxua-api'})`)

We have this behaviour in a couple of other places [getUser](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L383-L386) and [getIdTokenClaims](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L408-L411)  and it should be consistent - let me raise some work to investigate this

**Comment by stevehobbsdev** [comment]
@zajax thanks again for the detailed report - a fix has been merged and will appear in the next release! 🎉
