### ISSUE TITLE
Flicker with loginWithRedirect when appState provided

### ISSUE THREAD

**Issue by ChaudhryAtif** [auth0/auth0-spa-js#555]
### Describe the problem

When specifying the path to redirect to after login (i.e. /callback), `loginWithRedirect` first redirects to `redirect_uri` path, and then to target path (`appState`) -- which causes a flicker, resulting in a bad user experience

### What was the expected behavior?

It should directly/seamlessly redirect to target path instead of first going to `redirect_uri` path and then redirecting to target path

### Reproduction

1. Have a setup similar to auth0 quickstart -- can be login or call-an-api
2. Have a component with a route (i.e. /callback or /welcome)
3. Pass route/path on login: `(click)="auth.login('callback')"`
4. Notice that app goes to `window.location.origin` and then redirects to path (i.e. /callback)

### Environment

- **Version of `auth0-spa-js` used:** 1.11.0
- **Which browsers have you tested in?** Latest Chrome in Windows
- **Which framework are you using, if applicable (Angular, React, etc):** Angular 9.x
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by adamjmcgrath** [comment]
Hi @ChaudhryAtif 

> It should directly/seamlessly redirect to target path instead of first going to redirect_uri path and then redirecting to target path

The authorization server will redirect to whatever path you specify in the `redirect_uri` option. If you want to go directly to your target path, put that url as the value for `redirect_uri` - just be sure to add that uri to "Allowed Callback URLs" in your tenant

**Comment by ChaudhryAtif** [comment]
When a user is not logged in and freshly lands on an authenticated url (i.e. via Bookmark), the `appState` is used to redirect them after login so there's a similar delay there. Adding all those possible paths as Callback URLs and using `redirect_uri ` would not be a good solution.

**Comment by adamjmcgrath** [comment]
Hi @ChaudhryAtif - if you have too many paths to add to "Allowed Callback URLs", then you'll have to redirect to a single callback url.

The authorization server will have to redirect you to this registered redirect url for security reasons.

In this case, this rerouting is unavoidable. It's up to your application to then reroute the user to the path you specified in `appState`, and you should show a loading indicator or something similar to improve the UX

**Comment by stevehobbsdev** [comment]
@ChaudhryAtif  closing this for now as it feels like this is a concern of your application rather than the SDK, but feel free to continue the conversation if you need more clarification.
