### ISSUE TITLE
Error in Auth0Client.d.ts 

### ISSUE THREAD

**Issue by cosmaioan** [auth0/auth0-spa-js#556]
In  Npm package version "@auth0/auth0-spa-js": "1.11.0" the typings contains an error and breaks the ngc aot compiler.

[15:51:44]  typescript: ...3All2/Learn123App/node_modules/@auth0/auth0-spa-js/dist/typings/Auth0Client.d.ts, line: 71
            '>' expected.

      L71:  getIdTokenClaims(options?: GetIdTokenClaimsOptions): Promise<import("./global").IdToken>;

**import("./global").IdToken** Seems to be the problem.

**Comment by adamjmcgrath** [comment]
Hi @cosmaioan - this looks like it could be a TS version issue. 

@auth0/auth0-spa-js v1.11.0 was compiled using typescript v3.8.3 - which version of typescript are you using?

**Comment by adamjmcgrath** [comment]
Looks like you need at least 2.9 for `import("./global")` https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types

**Comment by adamjmcgrath** [comment]
Closing - feel free to reopen if you need more help
