### ISSUE TITLE
option to change /authorize endpoint

### ISSUE THREAD

**Issue by sanyam142mittal** [auth0/auth0-spa-js#557]
This library currently supports only /authorize endpoint. I am using a provider for which endpoint is /authorization/oauth2. There is no way to change the issuer endpoint for getting the code.

**Comment by adamjmcgrath** [comment]
Hey @sanyam142mittal - thanks for raising this. `auth0-spa-js` only supports using auth0.com as your provider, so we can't accommodate this request unfortunately.

**Comment by ehouais** [comment]
> Hey @sanyam142mittal - thanks for raising this. `auth0-spa-js` only supports using auth0.com as your provider, so we can't accommodate this request unfortunately.

While I totally understand your position, OIDC is a standard and your library should be _de facto_ compatible with other OIDC providers, unless you deliberately and artificially prevent this compatibility. A small code change that brings back the 173 forks into using your original library would surely be beneficial, one way or the other...
