### ISSUE TITLE
Support Sending Token Requests with Content-Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by rorydpayne** [auth0/auth0-spa-js#559]
### Describe the problem you'd like to have solved

I'd like to be able to use this library with as many OAuth2 providers as possible. Increasingly, providers support both `application/json` and `application/x-www-form-urlencoded` requests, but many still only accept the latter as per [the spec](https://tools.ietf.org/html/rfc6749#section-4.4.2). 

> 4.4.2.  Access Token Request
> 
> The client makes a request to the token endpoint by adding the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body

### Describe the ideal solution

Ideally, the type of POST body would be configurable to give the best coverage of auth providers. However, it will likely be simpler and more maintainable to send only `application/x-www-form-urlencoded`. Any auth provider adhering to the spec should accept this content-type.

## Alternatives and current work-arounds

Alternatively, some mechanism to intercept requests could be sufficient here. If there is a hard requirement to use `application/x-www-form-urlencoded` then request body and header could be rewritten prior to the connection opening. It's not quite as elegant a solution for this issue, but would generally be a nice extensibility point. In addition to using the correct content-type, such a mechanism would enable clients to add custom logging and measurement, as well as adding any custom headers for correlated logging etc.

**Comment by adamjmcgrath** [comment]
Hi @rorydpayne - thanks for raising this

Currently we have no plans to support other OAuth providers and we have some proprietary features that rely on that content-type, like rules (see: https://github.com/auth0/auth0-spa-js/pull/458#issuecomment-650290623) - so unfortunately we cannot support this request

We do have ongoing internal discussions on this subject though and could plan to support this in the future.

**Comment by rorydpayne** [comment]
> we have some proprietary features that rely on that content-type

So there is no appetite for making this configurable? That way you can support the specification but continue to use json post where it is convenient.
```
createAuth0Client({
  domain: '<AUTH0_DOMAIN>',
  client_id: '<AUTH0_CLIENT_ID>',
  advancedOptions: {
    useFormEncodedPostBody: true // Default = false
  }
});
```
