### ISSUE TITLE
Add API to get authToken expiresAt

### ISSUE THREAD

**Issue by franciscolourenco** [auth0/auth0-spa-js#562]
### Describe the problem you'd like to have solved

I would like to automatically get a new authToken when the cached authToken expires.

### Describe the ideal solution

Ideally the library would get a new token automatically after it expires, and would call a callback provided by me. 

Since that sounds complicated, another solution would be to expose the expiration time of the token, so that I can setup a `setTimout` to call `getTokenSilently`.

## Alternatives and current work-arounds
a) Manually decode token from `getTokenSilently()`
b) Read expiration time from localStorage
c) ...

**Comment by adamjmcgrath** [comment]
Hi @franciscolourenco - thanks for raising this

> Ideally the library would get a new token automatically after it expires, and would call a callback provided by me.

This is exactly what `getTokenSilently` does, if your access token has expired `getTokenSilently` will fetch a new one, either via iframe or refresh token, depending on your configuration settings.

**Comment by franciscolourenco** [comment]
@adamjmcgrath I know what `getTokenSilently` does. I doesn't do it automatically however, `getTokenSilently` needs to be called manually, and there is currently no way to know when the token will expire.

**Comment by adamjmcgrath** [comment]
Hi @franciscolourenco 

You should call `getTokenSilently` everytime you need a token, this will return a token from the cache or get you a new one.

Can you share an example of a situation where this doesn't suit your needs?

**Comment by franciscolourenco** [comment]
Async getAuth is still not fully supported in [vue-cli-plugin-apollo](https://github.com/Akryum/vue-cli-plugin-apollo/pull/365), which means we can't call `getTokenSilently` for every request.

**Comment by adamjmcgrath** [comment]
Hi @franciscolourenco  - thanks for sharing that use case.

Unfortunately it's not something we can accommodate, the library is designed to handle the tokens expiry internally.
