### ISSUE TITLE
getTokenSilently behaves differently when using refresh tokens

### ISSUE THREAD

**Issue by Bastczuak** [auth0/auth0-spa-js#563]
### Describe the problem

Why does `getTokenSilently({ ignoreCache: true })` doesn't throw the error 'login_required` for a current session when the user logged out in other tabs? Is this the desired behavior because it works differently when using cookies and iframe method?

My refresh token setting are `Refresh Token Lifetime: 2592000s` and `Refresh Token Reuse Interval: 4s`. 

### What was the expected behavior?

I expect that when `getTokenSilently` calls the documented `/oauth/token` endpoint that it detects the logged out state.

### Reproduction

- Start the SDK playground in two tabs.
- Enable refresh tokens and disable cache
- Login in both tabs
- Clicking on `Get Token` returns my access token
- Logout in one of the tabs
- Clicking on `Get Token` returns another token and throws not an error.
- Login again in both tabs
- Disable refresh tokens
- Clicking on `Get Token` returns my access token
- Logout in one of the tabs
- Clicking on 'Get token' shows error message `login_required`

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:**1.11.0
- **Which browsers have you tested in?**Newest versions of Chrome, Edge, Firefox and Chrome
- **Which framework are you using, if applicable (Angular, React, etc):**VueJs

**Comment by stevehobbsdev** [comment]
Hey @Bastczuak,

The difference is that refresh tokens are not tied to your user session, so even though you log out, you are still able to use a refresh token to get a new access token. This is why refresh tokens are effective in browsers that block third-party cookies.

If you're not using refresh tokens, we use silent authentication to get you a new access token, which _does_ depend on the user having an active session to work.

Does that answer your question?

**Comment by Bastczuak** [comment]
@stevehobbsdev thank you for the answer. So is it then perfectly acceptable to continue to use the access tokens for api calls when a user is technically logged out?

**Comment by stevehobbsdev** [comment]
Yes, absolutely. As long as the access token itself is valid then it should be considered fine to use.

Closing this for now as I believe the question to be answered, but please feel free to continue the conversation if you have further questions 👍

**Comment by Bastczuak** [comment]
Ok thank you letting me know!

**Comment by Bastczuak** [comment]
If I may add another clarifying question. Silent authentication just works with cookies right? Because disabling third party cookies results in in "Failed Silent Authentication" errors in the Auth0 logs. But to get this to work I just have to use custom domain to receive first party cookies from you, right?

**Comment by stevehobbsdev** [comment]
> But to get this to work I just have to use custom domain to receive first party cookies from you, right?

That's right - if you're using Custom Domains then you should not have problems in browsers that block third-party cookies, but I should point out that custom domains are a paid feature.

**Comment by Bastczuak** [comment]
Its me again.

Could you give an example on how to login now in e2e with cypress? I used this before https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/. But this works just with cookies.

**Comment by stevehobbsdev** [comment]
Unfortunately I don't have such an example to hand, such as a blog post. We do an [E2E test within the SDK itself](https://github.com/auth0/auth0-spa-js/blob/master/cypress/integration/getTokenSilently.js), but we cause the script to do a full login rather than manipulate storage.

I would imagine you could use local storage and replicate the storage in a way that causes the SDK to be logged in; you'd still have to get valid tokens though to populate it with.

**Comment by aexol** [comment]
@Bastczuak 

```ts
  static login = (user: keyof typeof Users, path = "/") => {
    const u = Users[user];
    const options = {
      method: "POST",
      url: Cypress.env("auth_url"),
      body: {
        grant_type: "password",
        username: u.username,
        password: u.password,
        audience: Cypress.env("auth_audience"),
        scope: "openid profile email",
        client_id: Cypress.env("auth_client_id"),
        client_secret: Cypress.env("auth_client_secret"),
      },
    };
    return cy
      .request(options)
      .then((resp) => resp.body)
      .then((body) => {
        const { id_token } = body;
        const newUser = JSON.parse(atob(id_token.split(".")[1]));
        cy.visit(path, {
          onBeforeLoad: (win) => {
            (win as any).auth0Client = {
              getTokenSilently: () => Promise.resolve(id_token),
              getUser: () => Promise.resolve(newUser),
              loginWithRedirect: () => Promise.resolve(),
              logout: () => Promise.resolve(),
            } as any;
          },
        });
        cy.wait(100);
      });
  };
```

Then inside the app
```ts
  const getClient = async (): Promise<Auth0Client> => {
    if (!client) {
      if (process.env.CYPRESS) {
        return (window as any).auth0Client as Auth0Client;
      }
      const _client = await createAuth0Client({
        audience: "https://graphqleditor.com/",
        client_id: process.env.AUTH0_CLIENT_ID!,
        domain: "auth.graphqleditor.com",
        redirect_uri: process.env.HOSTNAME_EDITOR,
        scope: "openid profile email",
        cacheLocation: "localstorage",
        useRefreshTokens: true,
      });
      return _client;
    }
    return client;
  };
```

With this hack you can use auth0 to e2e testing then use it inside `beforeEach`

**Comment by Bastczuak** [comment]
Thanks, but i'll stick with cookies in e2e tests.
