### ISSUE TITLE
Configurable /oauth/token endpoint

### ISSUE THREAD

**Issue by jasondiazg** [auth0/auth0-spa-js#565]
In this line, the library always use ``${baseUrl}/oauth/token`` but I am using the API Manager WSO2 to the authorization flow and the endpoint to obtain the token is ``${baseUrl}/oauth2/token``. There are a way to configure this endpoint? Would be possible to be updated?

Thanks.

Reference:

https://github.com/auth0/auth0-spa-js/blob/3a928909a3bacedd73c78226174f665a77d595f6/src/utils.ts#L320

**Comment by stevehobbsdev** [comment]
Thanks for the report @jasondiazg. This library is very specifically designed to work with Auth0's endpoints and as such this is not a request we will be able to accommodate. Sorry!
