### ISSUE TITLE
Support for running on docker dns as secure origin

### ISSUE THREAD

**Issue by pragmaticivan** [auth0/auth0-spa-js#566]
### Describe the problem you'd like to have solved

> Currently when running a group of services via docker-compose I'm getting `auth0-spa-js must run on secure origin`. It works with localhost because it states in the docs that it's a secure origin. For docker DNS I would like to be able to make a request to http://my-service:3000 as internal DNS so I can easily orchestrate cypress for a large application with multiple services.

### Describe the ideal solution

> Maybe I could set something in the script for local-only usage.

## Alternatives and current work-arounds

> Messages in the forums were not answered. Currently, the only workaround I see is having a proxy with SSL enabled for https.

**Comment by stevehobbsdev** [comment]
Unfortunately we don't plan to support such an option. The reason HTTPS is required is an effect of using the browser's built-in Crypto API, which requires a secure origin. 

The guidance of using an HTTPS proxy is still our recommendation, and something like [Caddy](https://caddyserver.com/docs/quick-starts/reverse-proxy) makes this somewhat easy.

**Comment by 27medkamal** [comment]
There's another solution for this which is to do the following:
1. Expose port 3000 of `my-service` to the host
2. Run the container which makes a request to `http://my-service:3000/` in a `network_mode: host`
3. Instead of calling `http://my-service:3000/`, call `http://localhost:3000/`
