### ISSUE TITLE
Failed to minify the code from this file - on npm build

### ISSUE THREAD

**Issue by benlester** [auth0/auth0-spa-js#57]
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.js:1:12440
```

I'm getting the above error when attempting to run `npm build` on my `create-react-app` created application.

I'm running:
    "@auth0/auth0-spa-js": "^1.0.1",
    "react-scripts": "^2.1.3",

**Comment by luisrudge** [comment]
Is there anything else in this error? We use create-react-app in our Quick Start and it works: https://auth0.com/docs/quickstart/spa/react/01-login#create-a-sample-application

**Comment by benlester** [comment]
```
11 silly lifecycle smart_portal@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle smart_portal@0.1.0~build: Failed to exec build script
13 verbose stack Error: smart_portal@0.1.0 build: `node scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid smart_portal@0.1.0
15 verbose cwd /home/ben/dev/smart.ui
16 verbose Linux 4.4.0-17763-Microsoft
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error smart_portal@0.1.0 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the smart_portal@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Further output. I've tried updating to `react-script` 3 with no luck also. The project I'm working on is ejected which makes updating to the latest CRA scripts troublesome.

**Comment by luisrudge** [comment]
@benlester did you try in a non-ejected project like our Quick Start?

**Comment by benlester** [comment]
Yes I've tried in a non-ejected dummy project and yes it does indeed work. The problem is this project is a behemoth project which was ejected a long time ago - quite difficult to put the genie back in the bottle.

The project works perfectly fine with `npm run start` it just refuses to build a minified version of `auth0-spa-js`

**Comment by luisrudge** [comment]
Maybe it’s trying to process the file again? Make sure you exclude the node_modules or, if you need to process other libs, exclude this specific directory. 

If you put a repro project somewhere, I’ll try to help. For now, I’m closing it because looks like a configuration issue.

**Comment by benlester** [comment]
For what it's worth to anyone who may read this in the future.

I solved this issue by creating a dummy app with CRA, then copying the configs and scripts folders over to the project. And the updating the package.json file against the new dummy app's package.json.
