### ISSUE TITLE
Refetch and update ID token in cache

### ISSUE THREAD

**Issue by ellioseven** [auth0/auth0-spa-js#572]
### Describe the problem you'd like to have solved

Refetch and update ID token in cache. 

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

A user may update their details via an application UI, however there is no way to "refetch" ID token after that mutation has been made. 

> A clear and concise description of what you want to happen.

Ideally, `getUser` would have an option to skip the cache on fetch stage, then update the cache on success.

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

We can rely on the `userinfo` endpoint, however separate storage needs to be implemented by the developer. This creates confusion because there are now two implementations that store user info.

> Add any other context or screenshots about the feature request here.

This is possible to achieve by re-authenticating, but this experience is less than ideal for users, particularly in cases where updating a user information is part of a critical UX workflow.

**Comment by stevehobbsdev** [comment]
Hi @ellioseven,

I appreciate the API is a bit weird in this respect, but if you call `getTokenSilently()` after the user has been updated, this should also cache a new ID token with the updated information, and a subsequent call to `getUser` should give you the right information. Does this work for you?

**Comment by ellioseven** [comment]
@stevehobbsdev If I use `getTokenSilently` I receive a "Login required" error.

**Comment by ellioseven** [comment]
This has been solved. I had to set "Allow Offline Access" in my API under the Auth0 admin UI. `getTokenSilently` followed by `getUser` now fetches the new user data.

**Comment by stevehobbsdev** [comment]
Great! Glad you've managed to solve it 👍
