### ISSUE TITLE
v1.12.0 breaks my app

### ISSUE THREAD

**Issue by qortex** [auth0/auth0-spa-js#573]
With v1.11.0, my app works ok.
With v1.12.0, the login process never ends. It looks like the call to `handleRedirectCallback` never returns. My handling code never gets the promise, and thus my app is stuck.

Downgrading to v1.11.0 solves the issue.

I don't know how to further debug this, I get no output in the console whatsoever. I can see that network requests are properly done and the callback route is properly fired. The call just never returns it seems.

- **Which browsers have you tested in?** Several (latest chrome, firefox, vivaldi)
- **Which framework are you using, if applicable (Angular, React, etc):** Angular
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by stevehobbsdev** [comment]
That sounds... odd.

One of the biggest changes in 1.12.0 was the move from using cookies for transactions, to session storage, but we also did some stuff with caching. Can you see session storage being utilised? Does it not clear it on `handleRedirectCallback` or does it remain in storage?

Are you able to repro in the playground or in a small Angular app using `ng new`?

**Comment by qortex** [comment]
Aw, right. Got it, your comment helped me debug the issue.

Turns out I empty `sessionStorage` at login to start fresh when logging in. Somehow, it has the side effect of preventing `auth0-spa-js` from doing its thing. Does it make sense?

Not emptying sessionStorage at login fixes the issue.

**Comment by qortex** [comment]
Ah, right! I get an `Invalid state` error. It didn't show up because I swallow them, because of the infamous workaround I have to keep for the OTP flow to be available too.

Is the session storage stuff also done in `auth0-js`? It could make my `Invalid state` workaround no longer necessary if I understand correctly.

**Comment by stevehobbsdev** [comment]
Not as part of this work, no. Auth0.js has a `__tryLocalStorageFirst` [experimental flag](https://github.com/auth0/auth0.js/blob/60f26b7fa811603633d11653843d51ce0c5b95b2/src/helper/storage/handler.js#L9) that you can set, which causes the SDK to use local storage for the equivalent functionality instead of cookies, but it's unrelated to this effort and has been there a while.

**Comment by stevehobbsdev** [comment]
I'll close this for now but if you have any further questions, ask away!

**Comment by qortex** [comment]
Alright thanks for the help here.

My takeaway here is that mentioning the use of Session Storage in the doc (with a warning not to interfere with it during the login process) would be a nice addition.
