### ISSUE TITLE
Exposing refresh token expiration date

### ISSUE THREAD

**Issue by iamdof** [auth0/auth0-spa-js#576]
### Describe the problem you'd like to have solved

When using refresh tokens, it seems like it might be helpful for the client to have access to the expiration date of the refresh token so that it could alert the user to the fact when they may be required to leave the site to authenticate again or any number of other things like saving app state etc. This may well be a security problem, but thought I would ask anyway.

### Describe the ideal solution

When using getTokenSilently or other similar functions have the object that is returned contain a field for the refresh token expiration if refresh tokens are being used. Or have a way to request this information on demand by providing a access point to the ICache object.

**Comment by stevehobbsdev** [comment]
Hi @iamdof, that information is not something we get exposed to ourselves through the API, so I'm afraid we cannot expose it even if we wanted to. The only expiry value we get is the expiry time of the access token itself, and its lifetime is purely managed by the SDK internals.
