### ISSUE TITLE
Extending the `auth0.is.authenticated` cookie lifetime

### ISSUE THREAD

**Issue by luisfmsouza** [auth0/auth0-spa-js#584]
### Describe the problem you'd like to have solved

As far as I could research, `auth0.is.authenticated` is boolean cookie that holds the information about the possibility of the user to have a valid session ([here is the reference](https://github.com/auth0/auth0-spa-js/issues/95#issuecomment-513263923)). If this cookie is present in the user's browser, when the auth0 client is instantiated, the SDK is able to perform a `getTokenSilently` call to return or renew the user access token. 

According to the reference, the cookie mechanism is used to improve the user experience. The expiration date of this cookie, is defined as 1 day, then even after 1 day, if the user has a valid session, the website is not capable of identifying it (because the cookie is expired).

Which means the SDK is controlling this aspect of the UX, but not providing a way to the website adjust the cookie lifetime when necessary.

### Describe the ideal solution

My proposal is to add a configuration option to define the lifetime of this cookie. In this option, the website can define for how many days the user is likely to be logged in. 

Something like:

```js
const auth0 = await createAuth0Client({
  daysUntilAuthenticationCookieExpire: 10 // no necessarily with this name
});
```

Then, when the `auth0.is.authenticated` cookie is created, we can do something like:

```js
// https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts
this.cookieStorage.save('auth0.is.authenticated', true, {
  daysUntilExpire: options.daysUntilAuthenticationCookieExpire // we can set the default value to 1
});
```

This way, the website will have control over the desired expiration date for this cookie. I know there might be any security reason behind it, but this also affects the user experience. So I believe by providing such an option, the website will be responsible to determine the right balance between security and UX, removing this limitation/responsibility from the SDK.

## Alternatives and current work-arounds

An alternative, not recommended, is to have this control outside of the SDK. Then the website would need such a mechanism to consider how likely the user is to be logged in and perform the `getTokenSilently`.

For instance, the website can have a `custom.is.authenticated` cookie that will determine when to call the `getTokenSilently` or not.

### Additional context

> nothing to add.

**Comment by stevehobbsdev** [comment]
The other alternative is to use the local storage cache option:

```js
await createAuth0Client({
  cacheLocation: 'localstorage'
});
```

The cookie lifetime you mention is reset every time the client is created from a page refresh and a new access token fetched from the server. Is you app running in some kind of kiosk where it's possible that the page is not refreshed for extended periods of time?

**Comment by luisfmsouza** [comment]
You are right about the reset time of the cookie, that is exactly the way it is working now.
 
The issue we are facing is with the users that access the website more than 24h after the previous access. Those users are not being recognised by the application, because the SDK does not perform a `getTokenSilently()` due to the missing cookie, even though those users have a valid session.

Let me guide through the flow:

Use case 1:
- User access the page
- Make login using email/pass 
- _at this moment the cookie `auth0.is.authenticated` is created_
- App recognises the user and show their name/picture
- User navigates through the page 
- _12 hours later_
- User came back and access the page 
- _at this moment the cookie `auth0.is.authenticated` is renovated_
- App recognises the user and we show their name/picture

Use case 2:
- User access the page
- Make login using email/pass 
- _at this moment the cookie `auth0.is.authenticated` is created_
- App recognises the user and we show their name/picture
- User navigates through the page 
- _48 hours later_
- User came back and access the page 
- _at this moment the cookie `auth0.is.authenticated` does not exist_
- App **does not** recognise the user and **do not** show their name/picture

**Proposal**
What I'm proposing is a way to make this hard coded expiration time extensible. Then the application will decide for how long the cookie should live, which means the period the SDK will renovate in the background.

Do you think that makes sense @stevehobbsdev? I can send a PR covering it.

**About local storage**
[Auth0 does not recommend](https://auth0.com/docs/tokens/token-storage#browser-local-storage-scenarios) it to be used to store tokens. We are trying to achieve a similar behaviour with a safer solution, and I believe its possible.
