### ISSUE TITLE
Broken tests on node < 12

### ISSUE THREAD

**Issue by luisfmsouza** [auth0/auth0-spa-js#587]
### Describe the problem

When I run the unit tests `npm run test` using a node version < 12, I got the following error:

![image](https://user-images.githubusercontent.com/4405147/94243313-8346b000-ff17-11ea-9a7b-b12f15e105e9.png)

### What was the expected behavior?

I expect to see no error when running the unit tests. I can see 2 options to fix it (maybe there is more):

1. Since worker thread is [experimental in node < 12](https://nodejs.org/docs/latest-v10.x/api/worker_threads.html), we can make it explicit by using a flag
1. We can make node >= 12 a requirement to work on this repository

### Reproduction

- Make sure you have node < 12
- Run the unit tests: `npm run tests`
- You'll see the error mentioned above

### Environment

> Please provide the following:

- npm: v6.13.4
- node: v10.19.0

**Comment by adamjmcgrath** [comment]
Thanks for raising this @luisfmsouza - we'll update our development docs
