### ISSUE TITLE
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by flundermicha** [auth0/auth0-spa-js#593]
We are using @auth0/auth0-spa-js 1.12.0 and recently see errors like this one:

```
Error: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
      at Object.get (node_modules/@auth0/auth0-spa-js/dist/../src/storage.ts:88:18)
      at new e2 (node_modules/@auth0/auth0-spa-js/dist/../src/transaction-manager.ts:18:36)
      at new e2 (node_modules/@auth0/auth0-spa-js/dist/../src/Auth0Client.ts:155:30)
      at init6 (packages/lib.web.auth/index.ts:81:20)
      ...
```

Because of this error, it is not possible to create a `Auth0Client` instance and therefore the affected users can not authenticate.

Unfortunately we were not able to reproduce the error yet. All we know is, that the userAgent is always "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.70" indicating an Edge 85 browser running on Windows 10.

**Comment by stevehobbsdev** [comment]
@flundermicha It looks like this might be environmental if you're not seeing this all the time. Perhaps your users have actively blocked third-party cookies and site data: https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

Indeed if I go into my Edge settings (on a Mac) and add `localhost:3000` to the disallowed list for cookies and site data, I see the same error.

I don't get the same error prior to 1.12, but I run into other problems with not being able to read state from the transaction cookie when I have those settings enabled.

**Comment by stevehobbsdev** [comment]
Closing this for now, but feel free to continue the discussion if you have further questions.

**Comment by norbertschuler** [comment]
Just for information: If you have third party cookies disabled in Chrome and include a website using `auth0-spa-js` in an iframe, this error also occurs. Not for the same website if you directly view it in the browser without putting it into an iframe.

**Comment by AK-047** [comment]
It's still not working with an iframe and blocked third-party cookies.
Is there any way to force client initialization to use memory storage or something else to avoid this issue?

**Comment by richardscarrott** [comment]
Hi @AK-047, did you ever figure this out?

It would be nice if we could at least pass Auth0 a custom session storage implementation as it's not even possible to polyfill it because `window.sessionStorage` is readonly.

Additionally, even if passing a custom `cache`, this package blows up as above.

**Comment by dpford** [comment]
FYI I was able to get this to work by adding [useCookiesForTransactions: true](https://auth0.github.io/auth0-spa-js/interfaces/Auth0ClientOptions.html#useCookiesForTransactions) to the options passed in when initializing the auth0 client.

**Comment by charliemeyer** [comment]
Updating here that useCookieForTransactions: true seems to fix the issue (Using auth0-react)

**Comment by robertkibet** [comment]
This seems to not work with [useCookieForTransactions: true](https://auth0.github.io/auth0-spa-js/interfaces/Auth0ClientOptions.html#useCookiesForTransactions) when running the app within the iframe, anyone else facing this issue?

I have this as my config:

```js
        domain: configProd.domain,
        clientId: configProd.clientId,
        useCookiesForTransactions: true,
        authorizationParams: {
          redirect_uri: window.location.origin,
        },
```

this fails with 
> Uncaught (in promise) DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
