### ISSUE TITLE
Can't find variable: AbortController

### ISSUE THREAD

**Issue by Enngage** [auth0/auth0-spa-js#594]
Hey there,

We are seeing increasing amounts of `Can't find variable: AbortController` errors being logged. It seems to happen when logging in with `handleRedirectCallback` method. 

It also seems to happen exclusively to `Safari` users using older versions such as `Safari 10.1.2 macOS desktop`. 

There are some polyfills that solve the issue, but are unnecessary large so I was wondering if you can come up with a custom implementation similar to what you did https://github.com/auth0/auth0-spa-js/pull/336 

Thank you ;)

**Comment by frederikprijck** [comment]
Thanks for reporting this. It looks like we have an issue with our polyfill, as we are supposed to be polyfilling AbortController as part of the SDK itself.

Are you perhaps using RefreshTokens?

Also keep in mind that Safari 10.1.2 is a browser Apple does not support any longer, so upgrading OSX and/or Safari is strongly encouraged.

That said, considering we have a polyfill that is not functioning as expected I agree we should look into this.

**Comment by Enngage** [comment]
Thank you for getting back to me & looking into this.

Yeah, I'm using `RefreshTokens`. I know Safari 10 is not supported anymore, but I can't really all our visitors that ;) From our logs it actually seems to happen to some newer Safari versions. For example `Safari 13.1.1 iOS mobile` is affected too.

**Comment by frederikprijck** [comment]
Hi @Enngage , I managed to reproduce it (and patch it locally) on Safari 10.1.2, but not on Safari 13.1.1 iOS mobile. Are you sure this is the exact same error?

**Comment by Enngage** [comment]
I thought it was, but maybe it's something different if you are unable to reproduce it.. I attempted to solve it with my own polyfill before receiving the error on Safari 13.1.1, so it's possible that something similar, yet different is the cause behind this. It would be strange as it happens on the callback page, but its definitely a possibility.

**Comment by frederikprijck** [comment]
@Enngage Would you be able to provide a stacktrace? I got a fix ready for Safari 10 on macOS, but want to verify if it could be related on iOS before merging it.

**Comment by Enngage** [comment]
@frederikprijck wish I could, but we only ever received this error in prod with unreadable minimized code. I could keep an eye on this and update this thread if it would happen again.

**Comment by frederikprijck** [comment]
Depending on the platform (like this works with Sentry for example), you should be able to upload your sourcemaps to sentry and have the stacktraces make sense without shipping the; to the clients in production.
