### ISSUE TITLE
Provide an API method for clearing the storage location when `auth0CacheLocation=localstorage`

### ISSUE THREAD

**Issue by shorn** [auth0/auth0-spa-js#596]
### Describe the problem you'd like to have solved

I've sped up my local development workflow by enabling `auth0CacheLocation=localstorage` (for local dev builds only).  This works well for normal usage - but I noticed a problem when testing my on-boarding flow for users who need to verify their email address.  My on-boarding flow stops the user until they've verified their email address (as indicated in the JWT via the `email_verified` field).
 I give the user a button to click when they've verified their email, which refreshes the browser causing a new token to be issued with the new value of the `email_verified` attribute.  But that obviously doesn't work when the token is being cached in local storage.  

### Describe the ideal solution

It seems to me that if a mechanism is provided to cache some data, then a complementary mechanism should be provided to clear that cached data.

## Alternatives and current work-arounds

I could write some code to try to clear the auth0 related storage item (looks like `@@auth0spajs@@:...`).  But it doesn't seem like a good idea to be trying to guess what the library is doing and then playing about with what it stores.

I don't want to log the user out - I just want to force the library to skip the cache and refresh the token in this specific on-boarding situation.

**Comment by stevehobbsdev** [comment]
Thanks for raising @shorn.

> It seems to me that if a mechanism is provided to cache some data, then a complementary mechanism should be provided to clear that cached data.

We don't provide a mechanism to cache data to the public - we cache data _anyway_, the developer can only configure where it is stored. The caching mechanism in general is an internal detail.

You are able to call `checkSession({ ignoreCache: true })` in order to cause the SDK to refresh its token cache, and just ignore the return value - does this help you? This will make a call to the token endpoint and store the tokens it receives into the cache, overwriting the existing values.

**Comment by shorn** [comment]
> You are able to call checkSession({ ignoreCache: true }) in order to cause the SDK to refresh its token cache, and just ignore the return value - does this help you?

Definitely! This is significantly better than what I had before.  

I see now that my refresh-browser logic was really just an awkward way of refreshing the token cache that relied on the `auth0CacheLocation=memory` setting being the default.
