### ISSUE TITLE
Typescript fails with auth0-spa-js

### ISSUE THREAD

**Issue by ibraelillo** [auth0/auth0-spa-js#60]
Hello, 

I'm using the same example of the auth0-spa-js quickstart with typescript and it fails all the time. 

this is the code: 

```
import * as React from "react";
import createAuth0Client from '@auth0/auth0-spa-js'
// already tried also
// import * as createAuth0Client from '@auth0/auth0-spa-js'

import {canUseDom} from "../domUtils";


type ProviderProps = Auth0ClientOptions & {
  onRedirectCallback: any,
  ssrUser: any
}

type ContextValueType = {
  isAuthenticated?: boolean,
  user?: any,
  loading?: boolean,
  popupOpen?: boolean,
  loginWithPopup?: (params: any) => void,
  handleRedirectCallback?: () => void,
  getIdTokenClaims?: (...p: any) => any,
  loginWithRedirect?: (...p: any) => any,
  getTokenSilently?: (...p: any) => any,
  getTokenWithPopup?: (...p: any) => any,
  logout?: (...p: any) => any
}

const DEFAULT_REDIRECT_CALLBACK = (appState: any) =>
  // @ts-ignore
  canUseDom() ? window.history.replaceState({}, document.title, window.location.pathname) : null;

export const Auth0Context = React.createContext<ContextValueType>({});
export const useAuth0 = () => React.useContext(Auth0Context);


export const Auth0Provider: React.FC<ProviderProps> = ({
                                children,
                                ssrUser,
                                onRedirectCallback = DEFAULT_REDIRECT_CALLBACK,
                                ...initOptions
                              }) => {
 
  const [isAuthenticated, setIsAuthenticated] = React.useState();
  const [user, setUser] = React.useState();
  const [auth0Client, setAuth0] = React.useState();
  const [loading, setLoading] = React.useState(true);
  const [popupOpen, setPopupOpen] = React.useState(false);

  if(ssrUser){
    setUser(ssrUser)
    setIsAuthenticated(!!ssrUser)
  }

  React.useEffect(() => {

      const initAuth0 = async () => {
       
       // **it breaks here!**
        const auth0FromHook = await createAuth0Client(initOptions);

        setAuth0(auth0FromHook);

        if (canUseDom() && window.location.search.includes("code=")) {
          const {appState} = await auth0FromHook.handleRedirectCallback();
          onRedirectCallback(appState);
        }

        const isAuthenticated = await auth0FromHook.isAuthenticated();

        setIsAuthenticated(isAuthenticated);

        if (isAuthenticated) {
          const user = await auth0FromHook.getUser();
          setUser(user);
        }

        setLoading(false);
      };
      initAuth0();

    // eslint-disable-next-line
  }, []);

  const loginWithPopup = async (params = {}) => {
    setPopupOpen(true);
    try {
      await auth0Client.loginWithPopup(params);
    } catch (error) {
      console.error(error);
    } finally {
      setPopupOpen(false);
    }
    const user = await auth0Client.getUser();
    setUser(user);
    setIsAuthenticated(true);
  };

  const handleRedirectCallback = async () => {
    setLoading(true);
    await auth0Client.handleRedirectCallback();
    const user = await auth0Client.getUser();
    setLoading(false);
    setIsAuthenticated(true);
    setUser(user);
  };


  return (
    <Auth0Context.Provider
      value={{
        isAuthenticated,
        user,
        loading,
        popupOpen,
        loginWithPopup,
        handleRedirectCallback,
        getIdTokenClaims: (...p: any) => auth0Client.getIdTokenClaims(...p),
        loginWithRedirect: (...p: any) => auth0Client.loginWithRedirect(...p),
        getTokenSilently: (...p: any) => auth0Client.getTokenSilently(...p),
        getTokenWithPopup: (...p: any) => auth0Client.getTokenWithPopup(...p),
        logout: (...p: any) => auth0Client.logout(...p)
      }}
    >
      {children}
    </Auth0Context.Provider>
  );
};


```

When I'm trying to use this component then I got the error :

**Unhandled Rejection (TypeError): auth0_spa_js_1.default is not a function**

<img width="789" alt="Captura de pantalla 2019-07-11 a las 11 27 21" src="https://user-images.githubusercontent.com/3011753/61039423-017c6c80-a3cf-11e9-82f6-127fa8e14415.png">

I've been dealing with this issue for days and no solution yet. I'm kinda in a hurry right now. Have anyone of you experienced this? 

kind regards,
Ibrael

**Comment by stevehobbsdev** [comment]
Hi @ibraelillo, another issue was raised with the same error, but in the Angular sample. It looked like it was because of a `tsconfig` problem: https://github.com/auth0/auth0-spa-js/issues/45

Does anything in that issue help you?

**Comment by ibraelillo** [comment]
Hi @stevehobbsdev ,

I've already tried that example, and if I change my tsconfig.json then it breaks the platform. My auth component is part of a library which contains a lot of other components which are working with the current typescript config. The library is also shared between 3 other different apps, so, I have no choice but to find out what's happening. 

As a context, I'm working with :
- nextjs 8.1.0
- next-with-typescript. 

When I do ssr, it works well on the backend because the cjs generated module works fine, but then on the frontend it's raising the error from the auth0-spa-js.production.js file.

**Comment by luisrudge** [comment]
@ibraelillo can you create a simple repo with next+typescript and configs you're using that replicates the problem? I'll clone it and try to find the issue.

**Comment by HIAB-vesteel** [comment]
I´m just noting that i have the same error when running unit test in Karma.
I have the same AuthService as the tutorial right now. 
In my navbar component i have the below code. In the navbar test i avoided/missed to mock the calls to auth0.


```
  async ngOnInit() {
    this.auth0Client = await this.authService.getAuth0Client();
    .....
  }
```

With #45 implemented unit test passes but in "afteall" i  still get this
![image](https://user-images.githubusercontent.com/39406409/61291372-a54e8980-a7ce-11e9-9837-55e1a51f8bc1.png)

Don´t know if this could help you in the correct direction.
I´m still going for the mock approach so this won't be a problem in my case.

**Comment by stevehobbsdev** [comment]
@ibraelillo @HIAB-vesteel I think in order to progress this, a small repro case that you can share would be the most useful thing to help us.

**Comment by HIAB-vesteel** [comment]
I created a completely new and fresh angular cli app.  https://github.com/HIAB-vesteel/auth0-missing-default

Just added auth0 as in  the guide  [Angular: Login](https://auth0.com/docs/quickstart/spa/angular2/01-login) untill the section [showing-profile-information](https://auth0.com/docs/quickstart/spa/angular2/01-login#showing-profile-information).

Pull the solution down. run `npm install` and `ng test`

Only difference is empty object gets error in TS as its not matching type so i cast it with as:
![image](https://user-images.githubusercontent.com/39406409/61295899-53f7c780-a7d9-11e9-8c8d-79ba93d3cddc.png)

If i instead actually try to add redirect url  like below i get a new error:

![image](https://user-images.githubusercontent.com/39406409/61296090-bea90300-a7d9-11e9-87f5-27fc0927eb03.png)
![image](https://user-images.githubusercontent.com/39406409/61296214-fdd75400-a7d9-11e9-81f0-85f2b3485652.png)


Happy hunting

**Comment by stevehobbsdev** [comment]
@HIAB-vesteel Are you missing some commits? I can't see anywhere in that project where Auth0 is used, and all the tests pass.

**Comment by HIAB-vesteel** [comment]
@stevehobbsdev Sorry man, end of the work day and i forgot the commit. Now its updated

**Comment by stevehobbsdev** [comment]
@HIAB-vesteel The app looks fine from the point of view that it works. If I configure it with a valid domain and client ID then I can log in and use the app just fine. So it looks like the error has to do with how it's being tested. The tests are peculiar because it's the Navbar creation test which is failing, yet the error is being thrown by the call to `handleRedirectCallback` from the `CallbackComponent`. I'm not sure how that's happening.

> Only difference is empty object gets error in TS as its not matching type

FYI if you update to `auth0-spa-js@1.1.0`, `loginWithRedirect` now accepts an empty parameter list, which should fix that.

@ibraelillo I'm almost sure that the problems you are having are to do with a misconfiguration somewhere. Could you please check out [this FAQ question](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-does-the-auth0client-object-take-a-long-time-to-initialize) and come back to us once you've done that? Also, a repro app would be _extremely_ helpful at this point.

**Comment by gurneyds** [comment]
I'm seeing the same issue. I create a sample app for React that works fine the first time that the user logs in, but when the page is refreshed the call to createAuth0Client() hangs. This means that the auth client is never set and downstream code chokes. I'm very new to auth0, so I could have something wrong but I can't seem to figure it out.  The code for my sample can be found here: https://github.com/gurneyds/test-auth

**Comment by luisrudge** [comment]
@gurneyds can you see if this helps? https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-does-the-auth0client-object-take-a-long-time-to-initialize

**Comment by gurneyds** [comment]
I'm just trying to run the sample locally, so the values for "Allowed Callback URLs", "Allowed Web Origins", "Allowed Logout URLs" and "Allowed Origins (CORS)
" are all set to "http://localhost:3000/".  The application does login the first time the page is refreshed. Clicking on the "Profile" link also works - UNTIL the page is reloaded, then it hangs on the call to "createAuth0Client".  I've added some console.log statements to the code: 

```
1111111111111111111111 auth wrapper before Auth0Provider
react-auth0-wrapper.js:16 2222222222222222222222 auth wrapper inside Auth0Provider
react-auth0-wrapper.js:25 3333333333333333333333 auth wrapper inside useEffect()
react-auth0-wrapper.js:28 4444444444444444444444 auth wrapper before createAuth0Client()
authorize:1 Failed to load resource: the server responded with a status of 400 ()
```

Clicking on the 'login' link then gives the following errors:

```
1111111111111111111111 auth wrapper before Auth0Provider
react-auth0-wrapper.js:16 2222222222222222222222 auth wrapper inside Auth0Provider
react-auth0-wrapper.js:25 3333333333333333333333 auth wrapper inside useEffect()
react-auth0-wrapper.js:28 4444444444444444444444 auth wrapper before createAuth0Client()
authorize:1 Failed to load resource: the server responded with a status of 400 ()
```

If I clear the cookies, then the login works again. There seems to be something in the processing when there are cookies that causes things to hang.

I really appreciate the help - this seems like a really great product and I can see myself using this for many projects - I just need to learn how it works and what I might be doing wrong.

**Comment by luisrudge** [comment]
@gurneyds Can you inspect your tenant logs? If there's any misconfiguration, it will probably show up there.

**Comment by luisrudge** [comment]
@gurneyds I looked at your client configuration and I believe you have a typo in the ‘Allowed Web Origins’ fields. It should be `http://localhost:3000` and not `http://localhost:3000/`

**Comment by gurneyds2** [comment]
Yes indeed - thank you! The error messages are now gone. I would still expect the authentication to be valid when I refresh the page. After a successful login, the page works fine until I refresh the page. Refreshing the page causes several of the cookies to go away and the page is no longer authenticated. I am forced to authenticate again with each page refresh. Maybe I have another configuration problem?

**Comment by luisrudge** [comment]
@gurneyds If you check your tenant logs again, you'll see a warning about development keys.

**Comment by luisrudge** [comment]
I'll close this in favor of https://github.com/auth0/auth0-spa-js/issues/99 because #99 has a repro project that I can test.
