### ISSUE TITLE
SPA popup setup lock languageDictionary

### ISSUE THREAD

**Issue by Blokh** [auth0/auth0-spa-js#600]
Greetings, 
I've been searching everywhere and Unable to find, 
How do I setup languageDictionary to the auth0's lock popup?

I am willing to show different error than "WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN." ( the error received in the error receive's description.

is it this possible? and if is, how do I initiate the languageDictionary ( handle the error code\description )

Thanks in advance,
Daniel

**Comment by stevehobbsdev** [comment]
@Blokh Just to be clear, is your question about the SPA SDK and using the [Classic Login Experience](https://auth0.com/docs/universal-login/classic-experience), or do you have an app that is using the [Auth0 Lock NPM package](npmjs.com/package/auth0-lock)?

**Comment by Blokh** [comment]
Hello @stevehobbsdev ,
I am using the classic one.
I haven't implemented the auth0 lock package.

**Comment by Blokh** [comment]
Thank you very much! 
everything works. 
Thanks
