### ISSUE TITLE
Get refresh token from Cache

### ISSUE THREAD

**Issue by KaiQTang** [auth0/auth0-spa-js#602]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I need to get the refresh token for automation purpose, but the sdk doesnt provide that function.

### Describe the ideal solution

I've checked the ts code, and looks like refresh token is stored in Cache.ts, is it possible to export a new function so we can get the refresh token from auth0-spa-js?

**Comment by stevehobbsdev** [comment]
Thanks for raising @KaiQTang. It is stored in a couple of places, the cache being one of them.

When we implemented refresh tokens into this library, we made a conscious design and security decision to not expose the refresh token outside of the SDK and instead completely manage the refresh token for you. As such we will not be able to accommodate this request - sorry!
