### ISSUE TITLE
Error when logging in from React app: "invalid_request: Invalid parameter: client_id must be a string"

### ISSUE THREAD

**Issue by jlek** [auth0/auth0-spa-js#604]
### Describe the problem

I tried using this library instead of `@auth0/auth0-react`, because I need access to an `Auth0Client` instance before my React App starts. However, when I click the login button, I see an error page that says:

> Oops!, something went wrong

> invalid_request: Invalid parameter: client_id must be a string

When I check the URL and the Logs, the client ID is in fact a string though.

### What was the expected behavior?

After clicking the login button, I should be directed to the login page.

### Reproduction

I made a small sample application with create-react-app to reproduce the error:

```JavaScript
import React from "react";
import ReactDOM from "react-dom";
import createAuth0Client from "@auth0/auth0-spa-js";

(async () => {
  const client = await createAuth0Client({
    domain: "DOMAIN",
    clientId: "CLIENT_ID",
  });

  ReactDOM.render(
    <React.StrictMode>
      <button onClick={() => client.loginWithRedirect()}>Log in</button>
    </React.StrictMode>,
    document.getElementById("root")
  );
})();
```
**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

I have not tried, but it says the playground is a Vue app, rather than a React app. 

### Environment

- **Version of `auth0-spa-js` used:** 1.12.1
- **Which browsers have you tested in?** Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** -

**Comment by stevehobbsdev** [comment]
This is where the API can come across a bit weird - we know about it and would like to clean it up.

This SDK expects you to pass `client_id` as opposed to `clientId` (which is what the React SDK uses).

```js
const client = await createAuth0Client({
    domain: "DOMAIN",
    client_id: "CLIENT_ID",
  });
```

These options are described in the [API documentation](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html).

Hope that helps!

**Comment by stevehobbsdev** [comment]
> I have not tried, but it says the playground is a Vue app, rather than a React app.

Just wanted to mention as well for the future, the playground is more for testing the SDK from a user point of view, so it does not matter so much which framework it uses. Just in case that allows you to test some scenarios in the future when you raise an issue.

**Comment by jlek** [comment]
Now that you pointed it out, I can't believe I did not spot this. Thanks!

**Comment by stevehobbsdev** [comment]
No worries! Easily missed, and I appreciate that the change is subtle.
