### ISSUE TITLE
Error 'unauthorized' error thrown in Chrome/Firefox, but working in Safari.

### ISSUE THREAD

**Issue by pj** [auth0/auth0-spa-js#610]
# Describe the problem

We're trying to create an auth0 client and getting inconsistent results between Safari and Firefox/Chrome. Safari works as expected, but Firefox and Chrome throw an error when creating the auth0 client:

```typescript

import createAuthClient from '@auth0/auth0-spa-js';
const authClient = await createAuthClient({
      audience: AUTH_API_AUDIENCE,
     domain: AUTH_DOMAIN,
     client_id: clientInfo.id,
     redirect_uri: REDIRECT_URI,
     leeway: 30,
     useRefreshTokens: true,
    cacheLocation: "localstorage"
});
```

Error:
```
Error: You don't have access to this client.
    at new n (auth0-spa-js.production.esm.js:15)
    at Function.n.fromPayload (auth0-spa-js.production.esm.js:15)
    at a (auth0-spa-js.production.esm.js:15)
```

We recently started using refresh tokens, so not sure if that's related.

From checking the network requests for the iframe, it looks like the 'login_required' error is being returned to Safari and the 'unauthorized' error is being returned to Chrome and Firefox?

Firefox iframe response:

```
<!DOCTYPE html>
<html>
<head><title>Authorization Response</title></head>
<body>
<script type="text/javascript">(function (window, document) {
    var targetOrigin = "http://localhost:8080";
    var webMessageRequest = {};
    var authorizationResponse = {type: "authorization_response",
        response: {
            "error": "unauthorized",
            "error_description": "You don't have access to this client.",
            "state": "REDACTED!"
        }
    };
    var mainWin = (window.opener) ? window.opener : window.parent;
    if (webMessageRequest["web_message_uri"] && webMessageRequest["web_message_target"]) {
        window.addEventListener("message", function (evt) {
            if (evt.origin != targetOrigin) return;
            switch (evt.data.type) {
                case "relay_response":
                    var messageTargetWindow = evt.source.frames[webMessageRequest["web_message_target"]];
                    if (messageTargetWindow) {
                        messageTargetWindow.postMessage(authorizationResponse, webMessageRequest["web_message_uri"]);
                        window.close();
                    }
                    break;
            }
        });
        mainWin.postMessage({type: "relay_request"}, targetOrigin);
    } else {
        mainWin.postMessage(authorizationResponse, targetOrigin);
    }
})(this, this.document);</script>
</body>
</html>
```

Safari iframe response:

```
<!DOCTYPE html>
<html>
<head>
    <title>Authorization Response</title>
</head>
<body>
    <script type="text/javascript">
    (function(window, document) {
        var targetOrigin = "http://localhost:8080";
        var webMessageRequest = {};
        var authorizationResponse = {
            type: "authorization_response",
            response: {
                "error": "login_required",
                "error_description": "Login required",
                "state": "Redacted!"
            }
        };
        var mainWin = (window.opener) ? window.opener : window.parent;
        if (webMessageRequest["web_message_uri"] && webMessageRequest["web_message_target"]) {
            window.addEventListener("message", function(evt) {
                if (evt.origin != targetOrigin)
                    return;
                switch (evt.data.type) {
                case "relay_response":
                    var messageTargetWindow = evt.source.frames[webMessageRequest["web_message_target"]];
                    if (messageTargetWindow) {
                        messageTargetWindow.postMessage(authorizationResponse, webMessageRequest["web_message_uri"]);
                        window.close();
                    }
                    break;
                }
            });
            mainWin.postMessage({
                type: "relay_request"
            }, targetOrigin);
        } else {
            mainWin.postMessage(authorizationResponse, targetOrigin);
        }
    })(this, this.document);
    </script>
</body>
</html>
```

### What was the expected behavior?

Behavior should be consistent across browsers.

### Environment

> Please provide the following:

We're using version 1.12.1, I've tested this is Chrome  86.0.4240.111, Firefox 77.0.1 and Safari 14.0 and the frame work we are using is React.

**Comment by stevehobbsdev** [comment]
Thanks for raising @pj.

I can understand why those sets of browsers would return different results; authentication would normally work in Chrome and Firefox as they don't block third-party cookies by default, but Safari does.

In the former case, it looks like you're being authenticated silently but it looks like there's possibly a problem on the Auth0 config site - if you check [the logs in the dashboard](https://manage.auth0.com/#/logs), does that give you any clue as to the problem?

In the latter, Safari is just completely unable to authenticate silently, so it's just giving you a `login_required` error.

In all browsers, if you get `login_required` error when you're using refresh tokens, it generally means that:

* You don't have a refresh token available to use
* You also don't have an active session on the IdP (or your session can't be read, see above)

In this case, the only option you have is to put the user back through an interactive login prompt.

Let me know if you find anything in those logs and we can take it from there.

**Comment by pj** [comment]
I think 'unauthorized' is the correct response in this case, because I'm actually trying to handle the case where someone is unauthorized for a particular client. I think what tripped me up is that login_required is an expected error, while unauthorized throws an exception. I guess without refresh tokens it always returns login_required?

Anyway, I've fixed this by just catching the error since it seems like this is expected behavior.

**Comment by stevehobbsdev** [comment]
> I guess without refresh tokens it always returns login_required?

If you don't have an active session with Auth0, yes.
