### ISSUE TITLE
Undefined response on use complex path

### ISSUE THREAD

**Issue by Arhitector** [auth0/auth0-spa-js#616]
### Describe the problem

on request auth with parametr 'require_url' with at list one letter after base url (Example: base_Url/w) get undefined in response.
<img width="1194" alt="Снимок экрана 2020-10-30 в 09 56 48" src="https://user-images.githubusercontent.com/5256163/97680659-57c76000-1a97-11eb-8657-2cccbb5e7b10.png">
<img width="1174" alt="Снимок экрана 2020-10-30 в 10 05 17" src="https://user-images.githubusercontent.com/5256163/97680714-6e6db700-1a97-11eb-8b34-0ceebd90e98d.png">

- with pure base url works perfect.

### What was the expected behavior?

> Expected auth and redirect to url from 'require_url'.

### Reproduction

init Auth0:
```
const Root = ({ Component, pageProps, router }) => {
    const onRedirectCallback = appState => {
        router.push(appState && appState.targetUrl ? appState.targetUrl : INDEX_ROUTE);
    };
    return (
        <Auth0Provider
            domain={process.env.AUTH0_DOMAIN || ''}
            client_id={process.env.AUTH0_CLIENT_ID || ''}
            redirect_uri={`${process.env.API_BASE_URL}${router.asPath}`}
            onRedirectCallback={onRedirectCallback}
            audience={process.env.AUTH0_AUDIENCE}
            cacheLocation={'localstorage'}
            useRefreshTokens={true}
        >
            <App
                Component={Component}
                pageProps={pageProps}
                router={router}
            />
        </Auth0Provider>
    );
};
export default Root;
```

AuthProvider:

```
export const Auth0Provider = ({
    children,
    onRedirectCallback,
    ...initOptions
}: Auth0ProviderOptions & Auth0ClientOptions) => {
   ...
    useEffect(() => {
        const initAuth0 = async () => {
            const auth0FromHook = await createAuth0Client({
                useRefreshTokens: true,
                ...initOptions,
            });
            setAuth0Client(auth0FromHook);

            if (window.location.search.includes('code=')) {
                let appState: RedirectLoginResult = {};
                try {
                    ({
                        appState,
                    } = await auth0FromHook.handleRedirectCallback());
                } finally {
                    onRedirectCallback(appState);
                }
            }
...
        };

        initAuth0();
    }, []);
...
```

### Environment
 "dependencies": {
        "@apollo/react-hooks": "^3.1.5",
        "@auth0/auth0-spa-js": "^1.8.1",
        "@auth0/nextjs-auth0": "^0.10.0",
        "@emotion/core": "^10.0.14",
        "@emotion/styled": "^10.0.14",
        "@next/bundle-analyzer": "^9.4.2",
        "@types/react-i18next": "^8.1.0",
        "antd": "^4.2.4",
        "apollo-boost": "^0.4.9",
        "express": "^4.17.1",
        "express-jwt": "^5.3.3",
        "firebase": "^7.23.0",
        "firebase-admin": "^8.12.1",
        "graphql": "^14.6.0",
        "i18next": "^19.4.4",
        "i18next-browser-languagedetector": "^5.0.0",
        "i18next-http-middleware": "^3.0.0",
        "next": "^10.0.0",
        "next-with-apollo": "^5.0.1",
        "react": "16.12.0",
        "react-apollo": "^2.5.8",
        "react-dom": "16.12.0",
        "react-hot-loader": "^4.12.21"
    },
    "devDependencies": {
        "@babel/plugin-transform-runtime": "^7.9.6",
        "@types/node": "^13.13.6",
        "@types/react": "^16.9.35",
        "babel-jest": "^25.5.1",
        "babel-loader": "^8.1.0",
        "babel-plugin-module-resolver": "^4.0.0",
        "babel-plugin-transform-class-properties": "^6.24.1",
        "babel-preset-minify": "^0.5.1",
        "nodemon": "^2.0.4",
        "ts-node": "^8.10.2",
        "typescript": "^3.9.2"
    }

**Comment by adamjmcgrath** [comment]
Hi @Arhitector - can you confirm that `http://localhost:8888/certificate` is in your "Allowed Callback Urls" in your tenant settings?

**Comment by Arhitector** [comment]
> Hi @Arhitector - can you confirm that `http://localhost:8888/certificate` is in your "Allowed Callback Urls" in your tenant settings?

yes.

**Comment by stevehobbsdev** [comment]
@Arhitector If I'm understanding you correctly, you're saying that if your `redirect_uri` value as at least one letter after the base URL, the authentication call fails?

Just asking, because the value you send for `redirect_uri` should **exactly** match one of the URIs that you have specified in "Allowed Callback Urls" for your application in the Auth0 Dashboard. If you're trying to send dynamic values based on what's coming out of the router, this probably won't work for you.

**Comment by Arhitector** [comment]
First of all thank you for you response.
I have tried "Allowed Callback Urls" and get undefined. After that i have tested random urls, just for getting more details. And got same results.

**Comment by Arhitector** [comment]
Yes, i am using 'appState' as alternative.

**Comment by stevehobbsdev** [comment]
@Arhitector Is there anything in [the logs](https://auth0.com/#/logs) that can shed any more light?

To reiterate:

* `redirect_uri` must specify a URL back to your application
* The same URI must **exactly** match a URI that appears in your [Allowed Callback Urls list](https://auth0.com/docs/users/redirect-users-after-login#redirect-users-to-callback-urls-on-the-allowlist). This cannot be dynamic

A common pattern here is to do what it sounds like you have now done:

* Set `redirect_uri` to your application root (e.g. `http://localhost:3000`)
* Use `appState` to specify a different URL to show the user after login

In addition, we now have an [Auth0 React SDK](https://github.com/auth0/auth0-react) that may help here, perhaps it's an option to look into.

**Comment by stevehobbsdev** [comment]
Closing this for now but please feel free to raise any further questions you might have.
