### ISSUE TITLE
Add support for confidential clients

### ISSUE THREAD

**Issue by dkaliyev** [auth0/auth0-spa-js#619]
According to https://tools.ietf.org/html/rfc6749#section-3.2.1 confidential clients MUST authenticate themselves as described in https://tools.ietf.org/html/rfc6749#section-2.3,
i.e. when making request to token endpoint client should include Authorization header. This should be done within oauthToken inside Utils.ts

**Comment by stevehobbsdev** [comment]
Hi @dkaliyev, thanks for raising this.

This SDK is intended for SPAs that run in the browser, which are [public clients](https://auth0.com/docs/applications/confidential-and-public-applications#public-applications) as opposed to [confidential clients](https://auth0.com/docs/applications/confidential-and-public-applications#confidential-applications), as they cannot securely store a secret. They do not receive credentials for that reason and thus cannot authenticate themselves.

I'll close this for now, but happy to continue the discussion.
