### ISSUE TITLE
Auth0 Example not working

### ISSUE THREAD

**Issue by ricardonogues** [auth0/auth0-spa-js#62]
Hi,

I've just downloaded the example app from the auth0 page and it seems it's not working. After looking at the URL the login process generates I've noticed this:

error_description=Cannot read property 'persons' of undefined

What am I missing?

**Comment by stevehobbsdev** [comment]
Hi @ricardonogues, a couple of questions:

* Which sample did you download?
* Did you follow the steps in the example app to configure it with your Auth0 details?

**Comment by ricardonogues** [comment]
Hey @stevehobbsdev ,

I've just downloaded the sample provided here:

https://auth0.com/docs/quickstart/spa/react/01-login

The URLs are set up like it's required by this tutorial.

Allowed Callback URLs: http://localhost:3000
Allowed Web Origins: http://localhost:3000
Allowed Logout URLs: http://localhost:3000

**Comment by stevehobbsdev** [comment]
Ok, and you haven't modified the code in any way since downloading it?

Can you tell me if you're connecting to the Default App in Auth0, or have you created a new app for this sample? If you're using Default App, one thing to try is creating a brand new one for this sample and configuring the `auth_config.json` file with those details.

**Comment by ricardonogues** [comment]
I've just downloaded it and ran:

npm install && npm start

I'm using the default app though. I'll try to create a new one and test with that.

**Comment by ricardonogues** [comment]
Hi again,

I've created a new app but no luck. It returns the same error. I've checked it in the tenant logs and the client_id matches the one from the new app. I'm trying to login with Google. Could this be the problem_

**Comment by stevehobbsdev** [comment]
@ricardonogues It's always worth trying to log in with a different method, such as using an email address and password, or a different social provider. Can you try that and let me know how you get on?

**Comment by ricardonogues** [comment]
@stevehobbsdev ,

I've added facebook to the login options. When I try these integrations in the app setup page I always receive this:

{
  "error": "access_denied",
  "error_description": "Cannot read property 'persons' of undefined"
}

Tried with google and facebook, both returned that error. Is it something wrong with my app configuration?

**Comment by stevehobbsdev** [comment]
@ricardonogues Just thought - do you have any custom rules set up in your Auth0 dashboard that may be interfering?

**Comment by ricardonogues** [comment]
@stevehobbsdev ,

That's it. I do have a custom script running as part of the auth process. I was unaware of this as this is an account that was not set up by me. Thank you for your help.

**Comment by stevehobbsdev** [comment]
@ricardonogues No problem! Glad you got it sorted :)
