### ISSUE TITLE
Use library with Resource Owner Auth Flow

### ISSUE THREAD

**Issue by shrumm** [auth0/auth0-spa-js#621]
### Describe the problem you'd like to have solved

I'd like to use the Resource Owner Auth flow (https://auth0.com/docs/api/authentication#client-credentials-flow). So my backend does the login and is able to send the access token + id token back to the SPA. Is it possible to accept an access token and Id token as optional inputs into the constructor?

### Describe the ideal solution

> A clear and concise description of what you want to happen.

To be able to call `createAuth0Client` like so:

```javascript
createAuth0Client({
   access_token: "<access_token>",
   id_token: "<id_token>",
    domain: "mydomain.com",
    client_id: "<client_id>",
    redirect_uri: "<redirect_uri>"
  });
```

## Alternatives and current work-arounds

I'm looking at using localstorage to achieve this. Set localstorage first with the appropriate key and then call createAuth0Client. This isn't a great method though, I'd rather it be part of the API.

**Comment by frederikprijck** [comment]
When implementing Authentication through your backend, there is no need to use Auth0-SPA-JS, as the intention of this SDK is to retrieve tokens in the frontend.

Instead you want to use an SDK for your backend and set an HttpOnly cookie, more on this here https://auth0.com/docs/sessions-and-cookies/spa-authenticate-with-cookies
