### ISSUE TITLE
 issuer is not used on Username & Password authentication

### ISSUE THREAD

**Issue by eugenefrg** [auth0/auth0-spa-js#634]
### Description

 issuer is not used on Username & Password authentication

### What was the expected behavior?

 issuer should be used on Username & Password authentication
Currently, it only works on SSO login. I'm using this library in a project, and the client requires that we use a custom domain to be able to show the end users some consistency by using the same domain name for the auth0 UI.

### Reproduction
 Using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground), I set the configuration of the "clientOptions"
            

> var clientOptions = {
              domain: [custom domain],
              client_id: [application client id],
              issuer: [real domain - ex. domain.auth0.com ],
              cacheLocation: _self.useLocalStorage ? 'localstorage' : 'memory',
              useRefreshTokens: _self.useRefreshTokens,
              audience: _self.audience,
              useCookiesForTransactions: _self.useCookiesForTransactions
            };
- Step 1 - Set the Domain as your custom domain, and set the issuer as the original domain from auth0.
- Step 2 - Login with Popup (To be able to see the error from the console. Login with Redirect does the same)
- Step 3 - Sign in with Username and Password
this would return an error: 
Uncaught (in promise) Error: Issuer (iss) claim mismatch in the ID token; expected "real domain", found "custom domain"
If done using Login with Google, it does not return that error. It actually authenticates

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used: ** ^1.6.5
- **Which browsers have you tested in?** I've tested in Chrome, and Firefox (both OSX)
- **Which framework are you using, if applicable (Angular, React, etc):** React - but the example used ([SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)) is Vue
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
@eugenefrg Thanks for raising. We made [some changes to how the issuer is specified](https://github.com/auth0/auth0-spa-js/commit/3fa28c38c1bd25752f8d7b5ba6c50fdd6fdfdf9b) in v1.11.0 - could you please update to at least this version and verify whether your issue is solved?

Thanks.

**Comment by stevehobbsdev** [comment]
Closing this for now, but if you have further question, please feel free to raise them.
