### ISSUE TITLE
getTokenSilently takes `timeout` options instead of `timeoutInSeconds`

### ISSUE THREAD

**Issue by roman01la** [auth0/auth0-spa-js#636]
Hello! We've bumped into a nasty bug where `timeoutInSeconds` options passed into `getTokenSilently`is ignored and couldn't figure out where the issue is. Upon inspecting library's code we were able to identify that the `timeoutInSeconds` is not used at all in [_getTokenUsingRefreshToken](https://github.com/auth0/auth0-spa-js/blob/5959a2c3f262aec98613964b21975324f440515b/src/Auth0Client.ts#L875) which is called eventually in `getTokenSilently`.

Instead [`customOptions`](https://github.com/auth0/auth0-spa-js/blob/5959a2c3f262aec98613964b21975324f440515b/src/Auth0Client.ts#L883) is passed into [`oauthToken`](https://github.com/auth0/auth0-spa-js/blob/5959a2c3f2/src/utils.ts#L361) as is, which expects `timeout` option.

This is especially confusing since docs doesn't mention `timeout` option at all https://auth0.github.io/auth0-spa-js/interfaces/gettokensilentlyoptions.html

**Comment by stevehobbsdev** [comment]
Thanks for reporting this @roman01la, and that's a good catch. You should be specifying `timeoutInSeconds`, it just looks like we're not translating the value correctly internally to `timeout`.

Let me raise a fix for that 👍
