### ISSUE TITLE
Ability to define custom date/time provider

### ISSUE THREAD

**Issue by dan-j** [auth0/auth0-spa-js#650]
We continually have the problem of customer's clocks not being in sync which results in an error when their time is more than the allowed `leeway`. 

Rather than increase the `leeway` we'd prefer if we could provide a custom implementation to initialise the current time instead of it being hardcoded to `Date.now()`.

### Describe the ideal solution

A new option `Auth0ClientOptions.currentDateProvider` which is an optional function: `() => Promise<Date>`. If not set, it defaults to `() => Promise.resolve(new Date(Date.now()))`.

This option is then used in the `verify()` function within `jwt.ts`.

This allows developers to use a custom implementation of retrieving the current date, i.e by contacting an API to get the current date.

## Alternatives and current work-arounds

I notice this is going to cause `verify()` to become an async function, an alternative is to provide the current date as an argument to `verify()` so that it remains synchronous, and use the above approach further up the call stack.

---

I don't mind providing a PR for this functionality, but would like for some discussion/approval before spending time on an implementation.

**Comment by stevehobbsdev** [comment]
Thanks for raising @dan-j.

My concern is that this would potentially expose a vulnerability in the token validation mechanism that would allow someone to potentially game the validation of the token expiry, so there might be a better way to achieve this.

Let me take this internally to the team and discuss what we can do here.

**Comment by dan-j** [comment]
Hi @stevehobbsdev, is there any update around this?

**Comment by stevehobbsdev** [comment]
@dan-j apologies for the radio silence. We're still discussing internally, I will try to get it to a resolution for you tomorrow and let you know.

**Comment by stevehobbsdev** [comment]
@dan-j To circle back to this, we've discussed this and agree that this could be useful if implemented in a generic way. For example, providing a method that just returns a promise, leaving it open for someone to implement their own logic (to contact a time server, for example). We'd also like to caveat somewhere (probably on the docs for the property/option) that it can potentially compromise the claims validation if used improperly.

Happy for you to go ahead and provide a PR here for us to review 👍
