### ISSUE TITLE
Add option to getTokenSilently to return only the cached access token

### ISSUE THREAD

**Issue by asteed21** [auth0/auth0-spa-js#655]
### Describe the problem you'd like to have solved

I am using the library configured to work with browsers that block third-party cookies (eg with cacheLocation set to 'localstorage' and using the refresh tokens option). I have a requirement for my application to maintain a session timer on the client and prompt the user when their session is about to expire, or log them out if it does expire. This works fine until a user has multiple tabs open which is not uncommon in our application.

I would like to enable my timer to check for the *cached* token in its timeout function so as to check its expiry. As it stands, the getTokenSilently method will automatically revalidate their session if called as a pre-check to logging them out in the case of an invalid session. This is useful for authenticating network requests, but since the user is not on that tab and is working in another tab with a valid token pair already, I just let it log them out on that tab. The main effect is that they will get logged out as soon as a network request fails with a "Login required" message in whichever (valid) tab they are working in.

### Describe the ideal solution

Because the session information is stored in local storage, it seems feasible that if the session is actively maintained via activity in one tab I should be able to confirm it locally in another by getting the current token from local storage and checking it before automatically logging the user out.

It would be great if the getTokenSilently call could have an "ignoreAuthServer" or "cacheOnly" argument in the same vein as "ignoreCache" to specifically return a token from the cache and not attempt a call to auth0 if it fails. That way, I could get the latest cached token (or err or null if empty) to check expiry and confirm if there is in fact a fresh token on hand or not.

Desired result:

Add an option to getTokenSilently call that allows it to check the cache only (vs current behavior of checking cache then going to auth0). 

## Alternatives and current work-arounds

Potentially could set and manage a flag in local storage based on when the token is updated across tabs, but seems somewhat onerous.

I am not currently working around it and users are just logged out of all tabs if any of their tabs' sessions expire.

### Additional context

Happy to understand if this has any downstream implications I have not considered.

**Comment by stevehobbsdev** [comment]
Thanks for raising @asteed21, just had a couple of comments.

> I have a requirement for my application to maintain a session timer on the client and prompt the user when their session is about to expire

From the SDK's standpoint, we don't know when the user's session is about to expire. The access token is not tied to the user's authentication session in anyway. While its expiry value and the expiry of the user's session might equate to similar values, conceptually they are different (a user logging out does not invalidate an access token, for example).

The only thing you can really do with the SDK in that regard is get an indication that the user's session has _already_ expired. In this case, you should receive a `login_required` error when trying to call `getTokenSilently`. But we wouldn't be able to tell _when_ it expired. Or in the case of an active session, when it's _about_ to expire.

It's an interesting case though and I'm going to raise this discussion internally to find out what some common patterns are for handling this, but I have a feeling this will need to be something that's implemented on the application side rather than in the SDK.

**Comment by asteed21** [comment]
Thanks @stevehobbsdev for the feedback. Sorry if the ask wasn't super clear, but just to clarify - I am aware that the SDK does not track (nor should it) if the user's session is about to expire. I have set up logic on the application side to do this based on our own business requirements. The requirement on our side is to track the expiration of the access token (as it is the key to authenticating protected API requests).

My understanding based on updating, parsing and testing token expiries via the Auth0 dashboard, is that the access token provided by the SDK reflects the the access token lifetime specified in the Auth0 dashboard for the API I provide as the audience in the Auth0 Client initialization.

I basically am performing checks on the access token exp property to track session validity within the application (again, outside of the SDK). But to do this, I have to actually get, parse and compare the property of the access token on certain events to the stored threshold on my application. I have successfully implemented this flow; however, there is currently one scenario where I want to check the expiry of the **cached** access token only (not try to refresh/renew it) so as to know if the inactivity is real (eg the cached token has not been replaced) or that the user activity has just switched to another tab (the local storage has been updated from a getTokenSilently call in said other tab and the cached access token is therefor not expired). 

Originally, I had planned to just use the getTokenSilently call when my timer ran out in order to get the cached token and check if it was _actually_ expired. But therein lies the problem - the getTokenSilently call will update the token if it IS expired and the refresh token is still valid. So it will never auto log out the user unless the refresh token is also expired. I have logic to catch a login_required error when the refresh token expires and prompt the user to login. But as that is not the catalyst I am looking to trigger this on, I would like to be able to retrieve the access token (and parse/check its properties however I need to) without the SDK reaching out to Auth0 in this particular instance.

Does that make any more sense? I am absolutely expecting to manage the timeout in my application layer, I just need a way to get the existing cached token without the SDK reaching out to auth0 if it is expired so that I can compare it to my internal application logic.

Also if there is an explicit reason **not** to optionally allow the SDK to return only the cached token, then I am happy to understand that better too.

**Comment by stevehobbsdev** [comment]
Thanks @asteed21, I understand your situation better now.

> I would like to be able to retrieve the access token (and parse/check its properties however I need to) without the SDK reaching out to Auth0 in this particular instance.

One fundamental issue here is that you are checking details of the access token in your client app, whereas in reality the access token is only intended for consumption by the API that you send it to, and forms a contract of sorts between the token issuer and the resource server (the API), not the client. Of course, whether you parse it on your client is up to you but it's really for your API to decide the validity of the access token by checking claims like `exp`. It doesn't really factor into the user's login session.

What you're asking us to implement in the SDK is pretty bespoke - does anything in [this thread](https://github.com/auth0/auth0-spa-js/issues/656) answer any questions you might have regarding inactivity timeout without checking only the cached access token?

**Comment by asteed21** [comment]
@stevehobbsdev thanks. Agreed the checking of the access token properties in the client is not ideal, and we are indeed checking validity on the server side, but the client-check was the only way I felt I could accurately account for resetting the timer based on our current setup. However, between your explanation and the thread in #656, I can see better why the SDK is structured the way it is.

As of now I'll adjust to make it agnostic as to which durations are set on our access token(s) and instead track to refresh token lifetime. That and the described upcoming sliding-refresh-token functionality should account for our use case of actually effecting an auth change on users' persistent inactivity, so should be okay to close this issue.

**Comment by stevehobbsdev** [comment]
Thanks @asteed21! Let us know if you have any further queries
