### ISSUE TITLE
Unable to use custom domain with Auth0 SPA client

### ISSUE THREAD

**Issue by marcoturi** [auth0/auth0-spa-js#663]
### Describe the problem
We are trying to implement custom domain connection to fix problem with same browsers. We are using the Auth0 Spa client library. However we get the error “WE’RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.” after pressing “Login” button. The following api call is returning 404
‘https://auth.DOMAIN.com/usernamepassword/login’

We opened a ticket (00472811) but we got no answer (8 days right now)

### What was the expected behavior?
The api call should correctly login instead of displaying 404

### Environment

- **Version of `auth0-spa-js` used:**
1.13.3
- **Which browsers have you tested in?**
Chrome
- **Which framework are you using, if applicable (Angular, React, etc):**
React
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
@marcoturi Sorry to hear you have had no response, let me find out how I can dig that ticket out internally.

In the meantime, this could be an application configuration issue - is there anything in your [tenant logs](https://manage.auth0.com/#/logs) that might point to the cause of the issue?

**Comment by marcoturi** [comment]
Thank you Steve! The problem was on a missing configuration on universal login (in auth0 dashboard settings).
https://auth0.com/docs/custom-domains/configure-features-to-use-custom-domains#universal-login

**Comment by stevehobbsdev** [comment]
Glad you got it sorted!

**Comment by AndreCAndersen** [comment]
Just to be perfectly clear to anyone else looking for answers.

1) You need actually to login to: https://manage.auth0.com/

2) Navigate to "Universal Login" in the left menu.

3) Select the Login tab in the middle.

4) Then edit the HTML displayed inside the Auth0 dashboard, such that:

    var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
        ...
        configurationBaseUrl: config.clientConfigurationBaseUrl,
        overrides: {
            __tenant: config.auth0Tenant,
            __token_issuer: 'login.example.com'  // replace with your own custom domain
        },

I spent WAY too long looking for a place to update my own Angular application with the `overrides` values.

Then next I configured our `auth0-angular` module (a wrapper around `auth0-spa-js` like this:

    AuthModule.forRoot({
      domain: 'login.example.com',
      clientId: 'somelongclientid',
      responseType: 'token id_token',
      audience: 'https://app.example.com/app',
      scope: 'openid profile email read:user',
    }),

(Note that the above configuration might be in snake-case if you use other libraries that `auth0-angular`.)

I hope that clears things up.
