### ISSUE TITLE
Unable to use Cypress with in memory token storage after changes in version 1.12.0

### ISSUE THREAD

**Issue by HWouters** [auth0/auth0-spa-js#669]
### Describe the problem

In Cypress tests you cannot redirect back and forward to the authorisation server for interactive login. What you do instead is acquire a token with by using password flow and use this token in the application you are testing.

This was all working fine, until version 1.12.0 added [some additional state validation](https://github.com/auth0/auth0-spa-js/pull/560/files). It checks if the nonce matches with the nonce claim in the id token. But since I acquire the token with the password flow, there is no nonce claim in the token. 

It looks like it's not possible to use the combination of Cypress and Auth0 (storing the token in memory) at the moment. See also the discussion [here](https://community.auth0.com/t/nonce-nonce-claim-must-be-a-string-present-in-the-id-token/49740)

### What was the expected behavior?

Using the great products Cypress and Auth0 together.

### Environment

- **Version of `auth0-spa-js` used:** 1.12.0 and higher
- **Which framework are you using, if applicable (Angular, React, etc):** Cypress

**Comment by stevehobbsdev** [comment]
@HWouters Can you review [this working sample](https://github.com/adamjmcgrath/cypress-spa-example) to see if this works for you?

The key bits of configuration are:

* In your test, call the token endpoint using the password grant to programmatically get your tokens
* Configure the SPA SDK with `cacheLocation: 'local storage'`
* Modify the data in local storage and replace the stored tokens with the ones you got from the token endpoint

**Comment by HWouters** [comment]
@stevehobbsdev that will work, but I'm a bit hesitating to change this. Auth0 is always teaching us to not store the token in local storage because many risks and now you are saying to use local storage. This confuses me. 

I was using an approach similar to this https://github.com/dunson062786/login-programmatically-into-auth0-with-cypress, which was working until 1.12. This made it possible to keep the token in memory.

Is this nonce validation really necessary? (There is no rationale in the PR) Could it be made an optional check? Or is there a way to add a nonce claim to a password grant token?

**Comment by stevehobbsdev** [comment]
> Auth0 is always teaching us to not store the token in local storage because many risks and now you are saying to use local storage. This confuses me.

I appreciate that is confusing. With the release of rotating refresh tokens, we made the decision to enable the ability to store your tokens in local storage as a convenience as long as you accept the risks of doing so, but it's not the default setting. As always, you should be aiming to reduce the changes of an XSS attack being successful (whether you're using local storage or not), by limiting the amount of third-party JavaScript you use and using as short an expiry time on your access tokens as is practical.

Here, inside a test, it's a viable solution to your problem. This doesn't mean you also have to enable local storage for your runtime application - but I understand your concerns.

#581 has a more detailed discussion around this, including about the nonce check and it looks like that specific piece was not resolved - let me take that back to the team and find out where that went.

**Comment by weyert** [comment]
The library seems to always use `local storage` even when you say cache location is `in-memory` when calling silently tokens. The problem appears to be that `browser-token-tabs`-module seems to use local storage which breaks everything.

**Comment by stevehobbsdev** [comment]
@HWouters After some discussion with the team, we've decided to remove this check. A PR has been raised and is attached to this issue.

**Comment by stevehobbsdev** [comment]
@weyert I see you've raised another issue, let's chat about it on there.
