### ISSUE TITLE
Expose auth0Client globally

### ISSUE THREAD

**Issue by ricardonogues** [auth0/auth0-spa-js#67]
I've followed the SPA quick start guide and got it working. My problem now is that that guide kinda forces you to manage authentication through your component tree by having the Auth0Context around your entire app. Is there any problem in exposing the auth0Client globally to the app? My issue is regarding API calls. Following the guide, I realized that I need to call getTokenSilently but the way the guide puts it this is only available inside component functions. If I want to have an API module the deals with API calls only how can I access the auth0Client? Am I thinking this wrong?

Thank you!

**Comment by stevehobbsdev** [comment]
Hi @ricardonogues, the SDK itself makes no assumptions about how you will integrate it into your application. You can of course use the client in the way you describe, but it's better discussed in the context of the sample.

Can you raise this issue against the sample you're working from? Additionally, someone has already raised this for discussion in the [Auth0 Community Forums](https://community.auth0.com/t/using-auth0-auth0-spa-js-outside-of-a-react-component/27805) - maybe some ideas can be shared there? I noticed the author posted a Gist of some code modifications which might help you with your particular question.

**Comment by ricardonogues** [comment]
@stevehobbsdev ,

This is exactly my problem!

Again, thank you for your help!
