### ISSUE TITLE
appState is lost when using passwordless login with magic link

### ISSUE THREAD

**Issue by jolleon** [auth0/auth0-spa-js#671]
### Describe the problem

When using passwordless login with magic link, a link is sent via email and this link gets opened in a new tab, with its own session storage. Since auth0Client uses sessionStorage to store the appState, the appState is lost on login. In particular the targetUrl (set on appState) is lost, making redirection of the user to the desired page after login impossible.

Note that this problem doesn't happen when `passwordlessMethod` is set to `'code'`, only when it is set to `'link'`, since using code the code gets entered in the same tab.

### What was the expected behavior?

Restoring appState (and in particular being able to redirect to the proper page after login) should work properly when using  magic link, just like it does with other methods.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Set up universal login with passwordless and `passwordlessMethod='link'`.
- save appState and start login flow with `loginWithRedirect({ appState: { targetUrl: to.fullPath } });`
- click the link in the email
- watch it open in a new tab and fail to find appState and to redirect when `handleRedirectCallback` gets called

And just to be sure:
- get a new magic link
- instead of clicking it, copy the link into the auth0 tab where you entered your email (which is still on the univeral login page)
- watch it succeed because the sessionStorage is still there in that tab

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:**
    "@auth0/auth0-spa-js": "^1.13.1",

- **Which browsers have you tested in?**
chrome

- **Which framework are you using, if applicable (Angular, React, etc):**
Vue

- **Other modules/plugins/libraries that might be involved:**

**Comment by jolleon** [comment]
Update: here is the error raised by the `handleRedirectCallback()` call after clicking a magic link:

```
Error: Invalid state
    at eval (auth0-spa-js.production.esm.js?9767:15)
    at eval (auth0-spa-js.production.esm.js?9767:15)
    at Object.eval [as next] (auth0-spa-js.production.esm.js?9767:15)
    at eval (auth0-spa-js.production.esm.js?9767:15)
    at new Promise (<anonymous>)
    at r (auth0-spa-js.production.esm.js?9767:15)
    at e.handleRedirectCallback (auth0-spa-js.production.esm.js?9767:15)
    at _callee3$ (index.js?b628:86)
    at tryCatch (runtime.js?96cf:45)
    at Generator.invoke [as _invoke] (runtime.js?96cf:274)
```

**Comment by stevehobbsdev** [comment]
Hey @jolleon,

We added an option in [1.13.0](https://github.com/auth0/auth0-spa-js/releases/tag/v1.13.0) where you could elect to store transactional information in a cookie for this exact scenario where you're authenticating across tabs. The default is session storage.

```js
createAuth0Client({
  useCookiesForTransactions: true
})
```

https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#usecookiesfortransactions

Can you give this a try and see if it fixes your issue?

**Comment by jolleon** [comment]
That worked!
You should probably mention that somewhere in the auth0 docs about passwordless because I didn't see it anywhere. And it took me a long time to figure where the issue was coming from because I was assuming the appstate was being passed in the `state` query parameter, not stored in the browser...

**Comment by stevehobbsdev** [comment]
Thanks, glad it worked. I'll keep a note to bolster our docs in this area so that other people can solve this issue more easily.

**Comment by IsabelleLePivain** [comment]
Hi, just flagging that the magic link doc has not been updated of yet. 
Just like jolleon, it took me a long time of testing, then took us to 2 weeks figuring out the issue with your support team.

**Comment by frederikprijck** [comment]
Thanks for reaching out @IsabelleLePivain.

> Hi, just flagging that the magic link doc has not been updated of yet.

Can you elaborate what docs you are referring to?
As it looks like our docs for this SDK explicitly call this out in https://auth0.github.io/auth0-spa-js/interfaces/Auth0ClientOptions.html#useCookiesForTransactions:

> You might want to enable this if you rely on your users being able to authenticate using flows that may end up spanning across multiple tabs (e.g. magic links) or you cannot otherwise rely on session storage being available.

Ofcourse happy to try and understand what we can improve to avoid future issues like this.

**Comment by IsabelleLePivain** [comment]
Hi Frederik,

Sure! I'm referring to Auth0 documentation about [magic links](https://auth0.com/docs/authenticate/passwordless/authentication-methods/email-magic-link.

I understand that using cookies for cross tab transactions might be obvious to someone experienced with authentication. But I would guess many Auth0 users are not, so a note that cookies are required to use magic links would be useful.

I found a couple of tickets after identifying the solution with Auth0 support of other users with the same issue. But I could not google them without the solution.

**Comment by frederikprijck** [comment]
Thanks for that link. That is a link we do not control, and isn't specifically about an SDK., so it might be a bit harder to add SDK specific information in there.

I would say we should add something into our FAQ that explicitly calls out passwordless and the, potential, need for `useCookiesForTransations`.

**Comment by IsabelleLePivain** [comment]
Thank you Frederik. 

I realize this thread might not have been the best place to flag this, as I did not face a problem with the SDK itself.
More so, with the way [Auth0 developer resources](https://developer.auth0.com) and [documentation](https://auth0.com/docs) are organised - apologies if this is not come under your jurisdiction.

I am hopeful the addition to the FAQ will help others though, thank you very much.
