### ISSUE TITLE
Blocking Third party cookies not supported 

### ISSUE THREAD

**Issue by weyert** [auth0/auth0-spa-js#676]
### Describe the problem
I am trying to use this library while the user has third party cookies blocked in their browser. Only this appears not to be possible as it appears to require the use of `localStorage` for the `browser-tab-locks`-package even when the `cacheLocation` is set to `memory`. I also tried to use the refresh tokens which seems to be suggested to still work when third party cookies are blocked.

### What was the expected behavior?
Able to login into the webapplication SPA without the need of using local storage.

### Reproduction
For me disabling the third party cookies throw an `Failed to read the ‘localStorage’ property from ‘Window’` error. 
I am using `loginWithPopup` 

### Environment
- **Version of `auth0-spa-js` used: *latest*
- **Which browsers have you tested in? *Chrome, Edge with third party cookies disabled*
- **Which framework are you using, if applicable (Angular, React, etc): *React*
- **Other modules/plugins/libraries that might be involved: *@auth0-react*

**Comment by frederikprijck** [comment]
When I try running our SDK in Chrome with Third Party Cookies disabled, I am not getting any errors and the application works as expected.
Could you provide a reproduction or try and reproduce it in our playground part of this repository?

**Comment by weyert** [comment]
I will try to make a reproducible case :)

**Comment by stevehobbsdev** [comment]
@weyert You can use the SPA SDK playground if you like. It wasn't clear in your PR whether you had tried this or not (it's something we ask for in the issue template).

Also please let us know the mechanism you are using to block third party cookies - are you using the native browser setting, or a third-party extension?

**Comment by stevehobbsdev** [comment]
@weyert It would be good to understand a solid reproducible case around this, if you have one. I also just wanted to address this:

> Able to login into the webapplication SPA without the need of using local storage.

As mentioned in #682, we're unable to get away from relying on use of local storage in the short term, but reevaluating our usage of it may change later and it's something we plan to look into.

I also would like to clarify our usage here:

> even when the `cacheLocation` is set to `memory`

The `cacheLocation` property controls where tokens are stored - local storage, or memory - but we do use local storage for syncing calls across browser tabs via a dependency.

I'll close this for now, but happy to continue the discussion and of course happy to re-open if you manage to get a repro together and there is some action we can take.
