### ISSUE TITLE
Issues embedding the app and running in Incognito mode

### ISSUE THREAD

**Issue by ilijapuaca** [auth0/auth0-spa-js#682]
### Describe the problem

Embedding an app that uses Auth0 in an iframe and trying to open it in Incognito mode in Chrome results in a crash.

#### First Issue

The following error is thrown :
```
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
```
when the constructor is called:
```
new Auth0Client({
  ...
})
```

The only workaround I found was setting `useCookiesForTransactions` to `true` which presumably has other implications, as I'm seeing a bunch of warnings in the console instead:
`DOMException: An attempt was made to break through the security policy of the user agent.`

I ran into #593 which was closed without an actual solution unless I am missing something. Also #578 seems related?

#### Second Issue 

The following error is thrown:
```
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```
when trying to retrieve a token:
```
auth0Client.getTokenSilently();
```

Didn't find a way to work around this one, other than just catching the error and assuming that fetching a token isn't feasible.

### What was the expected behavior?

Neither `Auth0Client` constructor nor `getTokenSilently` throwing an error due to inability to access session or local storage.

### Reproduction

- Create a very basic app that creates an instance of `Auth0Client` and attempts to call `getTokenSilently`
- Embed the app in an iframe within another page
- Try opening the page in Incognito mode

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

Reproducing using the playground would require embedding it within another page and hosting it, I'm hoping it should be straight-forward to reproduce locally.

### Environment

- **Version of `auth0-spa-js` used:** 1.13.5
- **Which browsers have you tested in?** Chrome 87.0.4280.88
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by frederikprijck** [comment]
Thanks for reporting. 

**Session Storage**
We are using Session Storage to handle transactions when using redirect. I guess you can use `loginWithPopup` instead, as redirecting in the iframe won't work in Safari.

That said, I guess we could have a look at making transaction usage opt-out, but we currently require it to prevent CSRF https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L501 so I am not sure this is possible.

**Local Storage**
We are using a locking mechanism in the browser to prevent duplicate calls to the /token endpoint which is important when using rotating refresh-tokens without a leeway (which is the recommended approach). Not using this locking mechanism might introduce other issues as have been reported several times in GitHub: https://github.com/auth0/auth0-spa-js/issues/553

It looks like our current SPA is not designed to use inside of an iframe and I am not sure it's an easy job to make it do so. @stevehobbsdev @adamjmcgrath what are your toughts on this?

**Comment by ilijapuaca** [comment]
Thanks for a quick response!

> We are using Session Storage to handle transactions when using redirect. I guess you can use loginWithPopup instead, as redirecting in the iframe won't work in Safari. But both approaches are a bit odd when used inside of an iframe.

The error gets thrown in the constructor though regardless of which auth flow the user decides using after the fact. It does sound like something that should be addressed in a more convenient way based on your suggestion?

> Shouldn't it be the responsibility of the main document to handle that (and not the iframe)? Both from a security perspective as for user-experience?

Our app is being embedded and used by a 3rd party, so this is likely not applicable.

> It looks like our current SPA is not designed to use inside of an iframe and I am not sure it's an easy job to make it do so. @stevehobbsdev @adamjmcgrath what are your toughts on this?

Would love to get more input as this is one of the main use-cases for us, and it affects our mid/long-term planning in terms of solution we want to go with.

**Comment by weyert** [comment]
I am having a similar issue in #676. I think postMessage could be used to store the `localStorage` data in the top site. Only problem this is basically async and the `storage`-classes are synchronous.

**Comment by stevehobbsdev** [comment]
Thanks for the report here @ilijapuaca. _Generally speaking_, Auth0 does not really support being using embedded inside an iframe. Whilst there are few more knobs and switches that we could provide from an SDK point of view which _may_ help, at the end of the day your mileage may vary when it comes to the server side and what variant of the login screen you're using.

For example, using the **New** login experience, the `X-Frame-Options` header is **always** set to `deny` and you're unable to change it.

For the Classic login experience, you are able to [disable Click Jacking protection](https://auth0.com/docs/product-lifecycle/deprecations-and-migrations/clickjacking-protection-for-universal-login) which prevents these headers from being set, but it's highly recommended that you keep this enabled; we have provided the option for legacy reasons.

As for use of session and local storage, you are able to do a couple things as you have mentioned (setting `useCookiesForTransactions`, for example) but we are currently unable to get away from using local storage for our browser locking mechanism at this time. So when running in Incognito mode, again your mileage will vary when it comes to browsers actively blocking third party cookies and other site data (read: local storage) from being used.

That said, we already have a reevaluation of our mechanism for how we serialize calls across browser tabs in our roadmap, we're just not quite there yet.

I'll close this for now but we're very happy to continue the discussion around this; if there is any further action we can take in the short term, happy to re-open.

**Comment by mcrawshaw** [comment]
@stevehobbsdev We're in a similar situation. We've tested the removal of the `browser-tabs-lock` functionality from this package and can confirm we're able to embed our product (and Auth0) within an iframe from another domain.

Our setup:
 - We use the new universal login experience and able to avoid clickjacking protection by using `loginWithPopup`. 
 - We use rotating refresh tokens.
 - Iframe setup `sandbox="allow-scripts allow-downloads allow-same-origin allow-forms allow-popups"`
 - We init like this...
```ts
this._auth0 = new Auth0Client({
      domain: config.auth0Url,
      client_id: config.auth0ClientId,
      scope: "openid profile email offline_access",
      audience: config.auth0Audience,
      useRefreshTokens: true,
      cacheLocation: "memory",
      useCookiesForTransactions: true,
      useRefreshTokensFallback: false,
    });
```

I was hoping you could explain the implication of removing the `browser-tabs-lock` package? Is this just functional, or does it have security implications?

Mark.

**Comment by mcrawshaw** [comment]
Thanks, that does help. That makes some sense, though I don't really understand why multiple tabs need to be within the same session (especially with `cacheLocation: "memory"`). I'm sure it's a cookie thing or something that's outside of my understanding.

Regarding browser support... I guess you're referring to the `navigator.locks.*` feature (https://caniuse.com/mdn-api_navigator_locks). Unfortunately, like localStorage, this isn't available within an sandboxed cross-domain iframe. We found the following error in our testing: `Failed to execute 'request' on 'LockManager': Access to the Locks API is denied in this context` (Chrome 103). So this looks to be a dead end.

One possible solution would be to allow the deadlock situation to occur but handle it gracefully. Assuming it was reasonably rare, if we fail to get a token, we could just request a new interactive login. This is our current area of investigation, please let us know if this is completely crazy. :-)

**Comment by mcrawshaw** [comment]
@stevehobbsdev We have resolved this issue and are able to use Auth0 SPA JS within a cross-origin iframe (via `loginWithPopup` and user button click) by gracefully failing when local storage is not available.

```
let lock: {
  acquireLock: (name: string, timeout: number) => Promise<boolean>;
  releaseLock: (name: string) => Promise<void>;
};
try {
  window.localStorage.getItem('test');
  lock = new Lock();
} catch (e) {
  lock = {
    acquireLock: async () => true,
    releaseLock: async () => undefined
  };
}
```
