### ISSUE TITLE
Failed to get token in IE 11 with latest version

### ISSUE THREAD

**Issue by fedeoo** [auth0/auth0-spa-js#686]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

After upgrading to the latest version 1.13.*, we suffered an issue in IE11.  When I'm logging in our platform, I can be redirected to the success page, then I'm checking `isAuthenticated` with  `const isAuthenticated = await auth0Client.isAuthenticated();`    But `isAuthenticated` is always false.
What I can do is to downgrade to the previous version we're using `1.11.0` and the issue was gone.

### What was the expected behavior?

> I expect the latest version support IE 11

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

The playground seems not working in IE 11. I can play with it in Chrome and get `Is authenticated: true` 
However, in IE 11 I am unable to login in with popup and it's stuck there. 

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:**    1.13.5
- **Which browsers have you tested in?** IE 11
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Thanks for reporting. 
I can reproduce this and will look into what's going wrong.

**Comment by fedeoo** [comment]
@frederikprijck  Thanks. You're right. 
I'm trying to reproduce this issue in the SPA Playground.

**Comment by fedeoo** [comment]
In my case, I encounter an error when redirecting back.  Somehow `auth0Client.isAuthenticated()` is returning true.  We reverted the change and the error was gone. 
I failed to reproduce this in SPA Playground.   Thanks anyway.

**Comment by frederikprijck** [comment]
I am closing this issue. If you manage to reproduce this please continue the conversation and we can reopen if needed.
