### ISSUE TITLE
Vue.js wrapper

### ISSUE THREAD

**Issue by alsyia** [auth0/auth0-spa-js#698]
### Describe the problem you'd like to have solved

Hi,

Is there any plan to provide a Vue.js SDK just like the already existing React/Angular SDK? 

The tutorial for Vue currently provides a bunch of code to copy/paste but I had a hard time making it work (this is probably due to me being unfamiliar with the lib too!). Like other people before me, I ran into issues with the asynchronous nature of the code (Client not being ready yet, etc), and I had difficulties finding information on how to use it outside the tutorial. Most of my Vue apps use the old auth0.js lib, but my understanding is that this new SDK includes a more secure flow (PKCE), which is great!

Since Vue.js is quite popular, I'm wondering whether I missed something? If yes, please feel free to correct me!

### Describe the ideal solution

A first-class Vue.js integration would be great! I obviously understand it's a lot of work and might not be prioritized in your roadmap, but I would like to know the status on this.

## Alternatives and current work-arounds

The tutorial provides an example of how to make it work.

**Comment by stevehobbsdev** [comment]
Hi @alsyia and thanks for raising this. We do have a Vue-specific SDK on the roadmap but unfortunately I don't have any time frame to share. It's something we want to do though, as you say it would sit nicely alongside the existing React and Angular SDKs. Keep an eye on our [Auth0 Community](https://community.auth0.com) site and socials for updates on that.

If you're having trouble getting [the sample](https://github.com/auth0-samples/auth0-vue-samples) (which currently only supports Vue 2) to work for you, please feel free to raise an issue on the sample repo and one of the team can try to help.
