### ISSUE TITLE
allow custom authorize url + no scope option

### ISSUE THREAD

**Issue by cjfigueiras** [auth0/auth0-spa-js#699]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> I'm trying the integration with calendly, the problem is that I see the library built the url using https://${domain}/authorize, but calendly use another format https://${domain}/oauth/authorize, so I got => **{"message":"no Route matched with those values"}**

> I resolved the problem passing as domain as "auth.calendly.com/oauth", this works but evidently fails when it try to use the domain for get token by example, the only solution that I found is edit the url manually(eventually it's only to test that there is no another problem)

> The another problem that I have is that calendly doesn't receive any scope, setting defaultScope=null remove scopes "email" and "profile" but not "openid", so I got in any case from calendly **"The requested scope is invalid, unknown, or malformed."**, if again I edited the URL and remove "scopes", then it works but fail getting the token, some error related that it has not the scopes requested

### Describe the ideal solution

> Set custom authorize subpath + Set scopes to null

**Comment by frederikprijck** [comment]
Hi @cjfigueiras ,

Currently, the scope of this library is only for use with Auth0's authorization server, so we wont be able to accommodate this feature request. There are multiple internals in the library that expect to be used with Auth0 that might fail when used elsewhere, which is why we do not support custom URLs.

**Comment by cjfigueiras** [comment]
@frederikprijck Well, calendly works with Auth0 the only difference is that it use /oauth/authorize as suffix url instead of /authorize, if I set my domain as **auth.calendly.com/oauth** instead of just **auth.calendly.com**, it works

**Comment by frederikprijck** [comment]
I am guessing you mean calendly works with OAuth, not Auth0, is that right? This library is for use with **Auth0** only.

**Comment by cjfigueiras** [comment]
> I am guessing you mean calendly works with OAuth, not Auth0, is that right? This library is for use with **Auth0** only.

Ah ok, I understand you now, thanks!
