### ISSUE TITLE
Valid refresh_token from localStorage is not used if auth0.is.authenticated cookie has expired (user seems logged out)

### ISSUE THREAD

**Issue by franciscolourenco** [auth0/auth0-spa-js#704]
### Describe the problem
If certain conditions are met, a valid `refresh_token` from the `localStorage` cache is not used, and the user is considered to be logged out, until he presses the login button and is logged in automatically again.

The following 2 conditions seem to be  necessary for this to happen:
1. `auth0.is.authenticated` + `_legacy_auth0.is.authenticated` have expired, or are not set.
2. The `localStorage` cache has been partially stripped according to the following code: https://github.com/auth0/auth0-spa-js/blob/e770d8938bb45c9417d5d75ea60af8386ba239c0/src/cache.ts#L143-L149

### What was the expected behavior?

A valid `refresh_token` from the `localStorage` cache should be used to retrieve new `access_token`.

### Reproduction
**A) Quick reproduction as a developer:**
1. Delete `auth0.is.authenticated` cookie
2. Delete `_legacy_auth0.is.authenticated` cookie
3. Strip the `localStorage` cache from it's contents except for the `refresh_token` and `expiresAt` properties, according to the following code: https://github.com/auth0/auth0-spa-js/blob/e770d8938bb45c9417d5d75ea60af8386ba239c0/src/cache.ts#L143-L149

**B) Normal reproduction as a user:**
1. Do not reload the app until the `expiresAt` property of the `localStorage` cache has expired, but while still having a valid `refresh_token`.
2. This should mean that the `auth0.is.authenticated` cookies have expired, and that the `localStorage` cache has been stripped automatically.
3. Reload the app

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**
Yes

Same steps as described in Reproduction section. Please find a screen recording bellow:
https://app.birdeatsbug.com/sessions/TkBdfQgaMjC16XcliUFZV

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:** 1.13.6
- **Which browsers have you tested in?** Google Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** Vue.js
- **Other modules/plugins/libraries that might be involved:** N/A

### Possible Workarounds
Using the `sessionCheckExpiryDays` option to extend the lifetime of the `auth0.is.authenticated` cookie, to match the one of the `refresh_tokens` sounds like it could solve this problem. Nevertheless the default lifetime of the cookie is 24h and poses a problem for everyone who is not aware of this behavior.

### Request for Clarification
What exactly is the purpose of the `auth0.is.authenticated` cookie?

### Other
In https://github.com/auth0/auth0-spa-js/issues/584#issuecomment-697260006 @stevehobbsdev says that logged in behavior should not be affected by the lifetime of `auth0.is.authenticated` cookies, if the `localStorage` cache is being used, however this test suggests otherwise.

**Comment by stevehobbsdev** [comment]
Thanks for raising this @franciscolourenco. I believe the behaviour has changed since that comment was made, so it was valid at the time but not valid any longer.

Another workaround here (while we figure out how to progress this) is to call `getTokenSilently`, which will refresh the internal state but does not check that cookie (`checkSession` just wraps this call with the cookie check).

If you're using `createAuth0Client`, you can do this:

```
const client = await createAuth0Client();
await client.getTokenSilently();
```

or you can use the constructor and call it like this:

```
const client = new Auth0Client({.. options ..});
await client.getTokenSilently();
```

> the default lifetime of the cookie is 24h and poses a problem for everyone who is not aware of this behavior.

We unfortunately don't know what the lifetime of the refresh token is on the client, so we have to use a different mechanism. However, some options to configure this or being able to disable that check is perhaps something we can look at. I will raise this internally with the team to see what we can do here.

> What exactly is the purpose of the auth0.is.authenticated cookie?

To prevent us from calling Auth0 endpoints on startup if we think you don't have a session, but as you've discovered, it's not perfect.

**Comment by franciscolourenco** [comment]
Hi @stevehobbsdev thank you for thorough answer, hope Auth0 finds a good long-term solution.

Regarding a work around, would you say that calling `getTokenSilently` explicitly is a more reliable solution than setting a long expire time with the `sessionCheckExpiryDays` option? Doesn't `Auth0Client` call `getTokenSilently` internally if the `auth0.is.authenticated` cookie is set?

Thanks!

**Comment by stevehobbsdev** [comment]
Yes - you can either use `sessionCheckExpiryDays` to increase that cookie expiry or just call `getTokenSilently` if the cookie is set, but `getTokenSilently` itself does not check that cookie, so calling it should work as expected in instances where you have a valid refresh token but not a valid `is.authenticated` cookie. Does that help?

**Comment by franciscolourenco** [comment]
That makes things clear, thanks. Since we are talking about it, maybe you could help clarify a couple more things:

1. Refresh Token expiration - absolute lifetime: Does this mean that refresh_tokens will expire collectively after the absolute lifetime after initial login, or instead that each new refresh_token has a lifetime which would mean that a user could be logged in indefinitely if they exchanged the refresh token frequently enough?
![image](https://user-images.githubusercontent.com/208149/108058730-bb7c9580-7054-11eb-873f-f7d3766b3d6e.png)

2. When does the `auth0.is.authenticated` get set? Every time an `access_token` is retrieved, even by using a `refresh_token`? Or only when retrieving an `access_token` via iframe/session cookie?

**Comment by stevehobbsdev** [comment]
1. Let me ask the owning team about the exact behaviour but I believe the absolute expiration is based on the **first** refresh token that you receive. i.e. from the point of an interactive login, meaning that exchanging the refresh token does not reset the expiry time (otherwise it would be a sliding expiration model). But I will check.
2. The cookie gets set on every interactive login and also when getting new access tokens silently, so on `handleRedirectCallback`, `loginWithPopup` and `getTokenSilently`.

**Comment by stevehobbsdev** [comment]
@franciscolourenco What I described for point 1 is correct - refreshing a token does not change or increase the absolute expiry.

Does this help?

**Comment by stevehobbsdev** [comment]
Closing for now, but happy to continue the conversation if there are further questions.

**Comment by franciscolourenco** [comment]
Hi @stevehobbsdev thank you for the explantion!

Regarding point 1. I must comment that Auth0 has the opportunity to be very clear in this explanatory sentence, but unfortunately I don't find it evident.
![image](https://user-images.githubusercontent.com/208149/109801942-7729f180-7c1f-11eb-9b41-3b64581e5647.png)


Regarding the original issue – has the problem been fixed already?
Shouldn't this be open until the issue has been fixed so that other users can be aware of existing issues?

Thanks!

**Comment by stevehobbsdev** [comment]
In investigating this, the owning team has already taken an action to improve the docs in this area so look forward to those improvements coming in the future!

As for the original issue here, I've taken a low priority action to look at this internally and you should continue to use the method I described above that uses `getTokenSilently`.

**Comment by oneillsp96** [comment]
I think renaming it in the dashboard and the docs to "refresh token _**family**_ absolute lifetime" would be super helpful. Took me a long time to figure out this is how it worked.
