### ISSUE TITLE
Retrieving claims for access token

### ISSUE THREAD

**Issue by weyert** [auth0/auth0-spa-js#705]
### Describe the problem you'd like to have solved
I am trying to extract the claims from the access token but this isn't possible. I am storing a `roles`-claim in the access token. I would  like to check this `roles`-field thats part of the access token.

### Describe the ideal solution

A similar function as the `getIdTokenClaims`-function that's already available but then for the access token.

## Alternatives and current work-arounds

Use `getAccessTokenSilently ` to get the token from the catch or renew the token and then parse the token manually to extract the claims.

### Additional context

I would like to check if the token has a specific role, if not, warn the user, logout, and request the user to login again with the appropriate account.

**Comment by frederikprijck** [comment]
Hey,

An Access Token is expected to be used to access an API, the intention is not to read or parse an Access Token in the client application, more info on the different kind of tokens can be found at https://auth0.com/docs/tokens.

A snippet from the link here:

> In your applications, treat access tokens as opaque strings since they are meant for APIs. Your application should not attempt to decode them or expect to receive tokens in a particular format.

Therefor, this SDK does not allow to parse the access token or provide any way for you to do so.

If you want to know user information in the application, you are supposed to use the ID Token, so you should add the role to the ID Token and retrieve the corresponding claims using `getIdTokenClaims`.
