### ISSUE TITLE
Option to hide missing scopes warning

### ISSUE THREAD

**Issue by someone1** [auth0/auth0-spa-js#709]
### Describe the problem you'd like to have solved

Do not put a console warning message for missing scopes in the returning Access Token.

### Describe the ideal solution

Option to disable, or completely remove, the warning about missing scopes.

## Alternatives and current work-arounds

Ignore the warnings - though we'd rather not have this end up in a production app.

### Additional context

We have several APIs with a myriad of permissions (scopes) each. Our application supports users of multiple roles, and depending on the scopes that user has, we will unlock parts of the application. To achieve this, we request a list of scopes the application knows about and can support and expect some to potentially not be available to the user currently logged in. 

This package always puts a console warning in such scenarios even though this is expected and desired behavior for us.

**Comment by frederikprijck** [comment]
Thanks for reporting. I believe that is a fair request, we put the warning in with a specific reason, but I can totally understand how this could be expected behavior and rather unfortunate to constantly see the warning.

**Comment by someone1** [comment]
@frederikprijck - sounds good, please let me know if I can provide any additional detail. 

Additionally, if there is another approach to accomplish what we're relying on Auth0's RBAC access token behavior to be, please let me know!

**Comment by someone1** [comment]
It would also be nice to expose the [decoded token](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L684) from the call so we don't have to duplicate parse the `accessToken` out ourselves.

**Comment by someone1** [comment]
If it helps any, the PR that introduced the warning - https://github.com/auth0/auth0-spa-js/pull/665

No indication why it was added though.

**Comment by frederikprijck** [comment]
> It would also be nice to expose the TokenEndpointResponse from the call so we don't have to duplicate parse the accessToken out ourselves, though it looks like the returned scope is stomped over by the ones provided in the request params

Could you elaborate what you are trying to do? Your application is not supposed to parse an Access Tokens, an Access Token is supposed to be used only by the Resource Server, see: https://auth0.com/docs/tokens

> In your applications, treat access tokens as opaque strings since they are meant for APIs. Your application should not attempt to decode them or expect to receive tokens in a particular format.

> If it helps any, the PR that introduced the warning - #665
> No indication why it was added though.

This was added to indicate that the requested scopes and the returned scopes differ, because this could introduce unexpected behavior in situations where thess are not expected to differ. However, I think we missed that this could also be expected behavior, resulting in a lot of warnings which isn't great.

**Comment by frederikprijck** [comment]
> though it looks like the returned scope is stomped over by the ones provided in the request params

The reason we are doing that is because if we wouldn't do this you would never use the cache, resulting in a lot of token request.

Imagine the following situation:

- You request a token for Scopes A, B and C.
- You retrieve a token for Scopes A and B.
- We store the token, which has scopes for A and B, using a key that includes Scopes A, B and C.

A few seconds later, you request another token for Scopes A, B and C. However, our SDk sees we already requested a token for this scopes and have one in the cache that is not expired. Even tho this token does not include Scope C, it is the result from request a token for the same scopes as is being requested here.

Not imagine we only include the returned scopes as part of the cache key, in this case it would be Scopes A and B.
If you request another token for Scopes A, B and C, we can not use the cache as we can not tell if Scope C was previously request but not returned, or has never been requested.

**Comment by someone1** [comment]
> Not imagine we only include the returned scopes as part of the cache key, in this case it would be Scopes A and B.
> If you request another token for Scopes A, B and C, we can not use the cache as we can not tell if Scope C was previously request but not returned, or has never been requested.

This totally makes sense, thanks for clarifying! Wouldn't it still be possible not to stomp over the scopes by using the requested scopes directly in the cache key? Update [this line](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L688) to:

```ts
        this.cache.save({ client_id: this.options.client_id, ...authResult, scope: getTokenOptions.scope });
```

Or maybe construct the cache key once and re-use it both when checking existence and again when setting the value? It looks like the popup flow already uses the scopes as requested, not the scopes returned.

This is only meaningful if we get access to returned scopes to begin with:

> Could you elaborate what you are trying to do? Your application is not supposed to parse an Access Tokens, an Access Token is supposed to be used only by the Resource Server, see: https://auth0.com/docs/tokens

Since we are expecting scopes to go missing, the app can activate different paths of the application (e.g. add navigation items) to parts of the app the user has permission to. For example, if we request `read:user update:user` but only `read:user` is returned, I can hide the ability to edit users in my app. But since the current API surface of this library doesn't grant me access to the returned scopes, I am forced to parse it out of the Access Token on the client-side.

I'd be happy to elaborate further as needed!

**Comment by frederikprijck** [comment]
> This totally makes sense, thanks for clarifying! Wouldn't it still be possible not to stomp over the scopes by using the requested scopes directly in the cache key? Update this line to:

I do not believe I see how this would be any different. Could you elaborate on what you mean and why you think this would make any difference?

> Since we are expecting scopes to go missing, the app can activate different paths of the application (e.g. add navigation items) to parts of the app the user has permission to. For example, if we request read:user update:user but only read:user is returned, I can hide the ability to edit users in my app. But since the current API surface of this library doesn't grant me access to the returned scopes, I am forced to parse it out of the Access Token on the client-side.

As explained in the link I shared, clients should not parse Access Tokens, Access Tokens are only for getting access to APIs. Therefore we have no intention to provide any functionalities that allows for you to do that.

Regarding the original issue reported here, I have opened a PR to revert the warning entirely, thanks for reporting.

**Comment by someone1** [comment]
> I do not believe I see how this would be any different. Could you elaborate on what you mean and why you think this would make any difference?

Yes sorry if I wasn't clear - its effectively the same outcome, though the suggestion was made in hopes of the returned scopes being made available to the caller.

> As explained in the link I shared, clients should not parse Access Tokens, Access Tokens are only for getting access to APIs. Therefore we have no intention to provide any functionalities that allows for you to do that.

The response from `/oauth/token` by Auth0 during the exchange process includes the Access Token as well as the list of granted scopes - however the this library does not allow me access to anything but the token. I wouldn't parse the Access Token, as designed, if the underlying data Auth0 provides during the token exchange was made available. Would it help if I open a separate issue to discuss this? I think it's a valid use-case and not something we shouldn't have access to - the data is returned to the client and the app, just hidden by the library (not sure if it was done intentionally).

**Comment by frederikprijck** [comment]
> The response from /oauth/token by Auth0 during the exchange process includes the Access Token as well as the list of granted scopes - however this library does not allow developers access to anything but the token. I wouldn't parse the Access Token, as designed, if the underlying data Auth0 provides during the token exchange was made available.

Sorry, I was misunderstanding what you meant, thanks for elaborating. I understand what you mean and I am happy to discuss this with the rest of the team to see if we could expose this to the users of the SDK.

> Would it help if I open a separate issue to discuss this?

Yes I think that is a good idea, that way we can close the current issue when the warning has been removed.
