### ISSUE TITLE
getTokenWithPopup - update to better match getTokenSilently behavior?

### ISSUE THREAD

**Issue by someone1** [auth0/auth0-spa-js#710]
### Describe the problem you'd like to have solved
 `getTokenWithPopup` behavior doesn't match `getTokenSilently` - resulting in corrupted states and excessive calls.

### Describe the ideal solution

 `getTokenWithPopup` should check cache before running a popup, like `getTokenSilently`, and maybe even the other bits where it throttles request so multiple calls don't corrupt a previous request's state.

## Alternatives and current work-arounds

Try and throttle outside of the library, but we end up looking a lot like what `getTokenSilently` already implements and not as well as it does.

### Additional context

Our app communicates with various APIs with differing audiences/permissions, so we setup API clients for each API and try to make some API calls to bootstrap various parts of the app (e.g. a dashboard). Upon loading, different parts of the app that would typically be unaware of one another start making requests for their respective APIs and stomp on one another's state when using  `getTokenWithPopup`. We haven't seen this behavior with  `getTokenSilently` and we believe aligning the two's process could go a long way in alleviating this.

We use the popup method when developing locally as silent options are not allowed on `localhost` and it'd be cumbersome in our environment to get everyone setup otherwise.

**Comment by frederikprijck** [comment]
> We use the popup method when developing locally as silent options are not allowed on localhost and it'd be cumbersome in our environment to get everyone setup otherwise.

Could you elaborate on this a bit more? [Here is a screen recording](https://www.loom.com/share/58633e429f584710a3af39875325e4da) of this SDK's playground application that runs on localhost and uses `getTokenSilently()` successfully.

> `getTokenWithPopup` should check cache before running a popup, like getTokenSilently

I am curious to understand what we are not checking the cache here. Even though I think, in this case, I would like to understand why you can't use `getTokenSilently` on localhost, as mentioned above. But I will have a chat internally to try and understand what the reasoning is to not check the cache when using `getTokenWithPopup`.

**Comment by someone1** [comment]
`getTokenSilently`  depends on [`prompt: 'none'`](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L836) which, when used with scopes, is explicitly disallowed when running on `localhost` since it's `never a verifiable first-party` ([source](https://auth0.com/docs/authorization/user-consent-and-third-party-applications#skip-consent-for-first-party-applications))

Instead of trying to get admin privileges to my dev team and modify host entries, it's easier just to switch to pop-ups for local dev.

**Comment by someone1** [comment]
Looks like https://github.com/auth0/auth0-spa-js/pull/664 added the more robust caching and locking mechanisms to `getTokenSilently`, but the intent of the PR, as it's described/reads, probably should have included the popup flow as well?

**Comment by frederikprijck** [comment]
> getTokenSilently depends on prompt: 'none' which, when used with scopes, is explicitly disallowed when running on localhost since it's never a verifiable first-party (source)

`getTokenSilently` is not disallowed on localhost, skipping consent is.

The idea is to first use `loginWithRedirect` or `loginWithPopup` to prompt for consent, including all scopes that your application needs. Once you have done that, `getTokenSilently` can be used safely with a combination of any of the scopes the user has given consent for. 

e.g. If your application needs 20 scopes, you should ensure these scopes are passed to the `logigWithRedirect` or `loginWithPopup` call:

```
loginWithRedirect({ scope: 'scope1 scope2 scope3 ...' });
```

Next, you can get tokens using all of these combinations, without the need for a prompt for consent, so using `prompt=none` should work fine:
```
getTokenSilently();
getTokenSilently({ scope: 'scope1 scope2' });
getTokenSilently({ scope: 'scope1 scope3' });
getTokenSilently({ scope: 'scope2 scope3' });
getTokenSilently({ scope: 'scope1 scope2 scope3' });
```

Here is yet another screen capture of this using our playground: https://www.loom.com/share/24699865ed424fe0a2cfb531d4262c84

> Looks like #664 added the more robust caching and locking mechanisms to getTokenSilently, but the intent of the PR, as it's described/reads, probably should have included the popup flow as well?

I don't think that PR relates to the conversation here. `getTokenWithPopup` doesn't suffer from the same problems `getTokenSilently` did, which is improved in that PR.

**Comment by someone1** [comment]
Thanks for the tip and I really appreciate you taking the time to create the screen recordings!

We use multiple audiences so when we login we don't do anything with audiences/scopes until further down the bootstrap process:

E.g.: Load Page -> Login with ID Token ONLY -> Bootstrap App -> Init API Clients / get Access Tokens

Your suggested flow would require multiple `loginWithRedirect` (or popup?) calls with the varying audiences/scope combinations up front - we could see how we'd have to modify our bootstrap process to try things this way. Preferably it'd only affect localhost development and it seems like a bigger hammer than the approach we are trying now (e.g. switch to the popup flow for Access Token retrieval on localhost).

I still think the popup flow could benefit from better use of the cache and locking as the silent flow uses - it looks like `getTokenWithPopup` calls `loginWithPopup` and then takes the token from the cache - so checking before the call could be a small (but welcome) optimization. Locking would help with concurrent calls to `getTokenWithPopup` to prevent state corruption.

**Comment by frederikprijck** [comment]
> We use multiple audiences so when we login we don't do anything with audiences/scopes until further down the bootstrap process:

Thats a fair point, thanks for mentioning that. Have you considered using `127.0.0.1` or any custom hosts entry to be able to skip consent locally while not needing to add extra code to support that? Consent is not skippable for localhost, but it is for `127.0.0.1` or any other host entry that maps to localhost, see https://auth0.com/docs/authorization/user-consent-and-third-party-applications#skip-consent-for-first-party-applications.

> I still think the popup flow could benefit from better use of the cache and locking as the silent flow uses - it looks like getTokenWithPopup calls loginWithPopup and then takes the token from the cache - so checking before the call could be a small (but welcome) optimization. Locking would help with concurrent calls to getTokenWithPopup to prevent state corruption.

I believe as well that it's worth looking into the reasoning why this differs.

**Comment by someone1** [comment]
I hadn't considered using `127.0.0.1` as I assumed that'd be prohibited for the same reason `localhost` is - I'll give it a try, thanks for the idea! Modifying host files could be possible, but then I'd be getting IT involved and possibly having devs modify settings that require admin privileges - if a solution that works with no additional config could be provided, that'd be preferred.

Might be worth mentioning here as we discuss aligning behavior between the functions - one advantage `getTokenWithPopup` has that `getTokenSilently` doesn't is a better typed return value:

```ts
// Auth0Client.d.ts

getTokenSilently(options?: GetTokenSilentlyOptions): Promise<any>;

getTokenWithPopup(options?: GetTokenWithPopupOptions, config?: PopupConfigOptions): Promise<string>;
```

I think from my (brief) review of `getTokenSilently` it should always return a `Promise<string>` but perhaps the inference in TypeScript cannot determine that, adding an explicit return type should fix it.
