### ISSUE TITLE
Implement retry logic when state mismatch error

### ISSUE THREAD

**Issue by scottfirestone** [auth0/auth0-spa-js#711]
### Describe the problem you'd like to have solved

Users are reporting issues with our auth0 implementation whereby state mismatch errors occur and auth cannot be completed.

### Describe the ideal solution

Ideally, auth0-spa-js would handle mismatch errors with a retry. [This post](https://community.auth0.com/t/invalid-state-on-reload-auth0-callback-url-using-auth0-spa-js-and-angular-8/36469/10) describes some possible workarounds - `1` describes the desired improvement to this library.

### Additional context

This issue has been reported across OS and browsers, impacting 3%-9% of our daily users.

**Comment by frederikprijck** [comment]
Hi @scottfirestone ,

Thanks for reporting this. This issue isn't supposed to happen in normal situations, so I think it is worth investigating what your users are doing that makes this error occur, as explained in the community post you linked.

This is a situation that I feel like applications should solve themselves when the corresponding error occurs.
If our SDK detects an Invalid State, I do not believe it is up to the SDK to ignore those and just retry. Our SDK informs you about the error and you are free to decide how you react to it, as not every application has the same requirements on that end (some want to retry login, others maybe want to show an error page, some want to involve server-side error logging to track all these errors ...).

In case you want to retry login automatically, you should be able to use something like this:

```
auth0Client.handleRedirectCallback().catch(err => {
  if(err.message === 'Invalid state') {
    auth0Client.loginWithRedirect();
  }
});
```
Or in case you are using loginWithPopup:
```
auth0Client.loginWithPopup().catch(err => {
  if(err.message === 'Invalid state') {
    auth0Client.loginWithPopup();
  }
});
```

Closing this for now, but feel free to continue the conversation.
