### ISSUE TITLE
Return scope detail during access token retrieval

### ISSUE THREAD

**Issue by someone1** [auth0/auth0-spa-js#715]
### Describe the problem you'd like to have solved

Continuing discussion from #709 - currently there's no way to obtain the list of scopes returned during a `/oauth/token` exchange with Auth0 in either `getTokenSilently` or `getTokenWithPopup`

### Describe the ideal solution

Might be an overstep, but [all information](https://github.com/auth0/auth0-spa-js/blob/master/src/api.ts#L6) from the exchange could be returned to the user (e.g. expiration time may be valuable in situations where API clients cannot be setup to retrieve the Access Token via a `Promise` based function and instead needs to be periodically cached outside the library).

## Alternatives and current work-arounds

Parse the info from the returned access token itself, which is [discouraged behavior](https://auth0.com/docs/tokens).

### Additional context

Some discussion/context can be found in #709.

**Comment by stevehobbsdev** [comment]
Thanks for the feedback and the feature suggestion. Ideally what we'd do is return the full detail directly out of `getTokenSilently`, but it's a breaking change and not one we can make just at the moment.

Alternatives I can think of:

* Some sort of eventing system that returns the full detail when an event is raised
* Some other method that allows you to retrieve the full item out of the cache

Neither of which are ideal IMO as they bloat the API. Happy to hear alternatives.

We have an ongoing ideas board internally to capture things to explore for a new major version, and I've added this for discussion. Closing the issue but happy to continue the discussion.

**Comment by someone1** [comment]
Thanks for the update! Glad to hear this is acknowledged as a shortcoming of the current package and on the radar for improvement - though could you maybe entertain the following ideas, or give some sort of ETA/timeline when introducing a fix for this can be reasonably expected?

* Introduce `*WithResponse` versions of each call - I think reasonable people can disagree that adding a fix for a known shortcoming of the package would be considered API bloat - I guess I sit in the camp of it wouldn't be in this situation. I've seen this solution used many times over in many other places trying to avoid breaking changes (e.g. the `context` package adoption even made such changes to the Go standard library). The non `WithResponse` versions of each call could then just call the `WithResponse` versions and return the `accessToken` - so it'd be minimal code changes for this package.
* A tricky but non-breaking change: add an option to the existing call options to change the return type of the function, maybe using [conditional types](https://stackoverflow.com/a/54166010/700188)? Make `*OptionsWithResponse` versions of each options parameter for each call that the function conditionally accepts to deduce its return value? This shouldn't be a breaking change and work for plugging this gap.

**Comment by stevehobbsdev** [comment]
Thanks for the suggestions, we'll take them on board. In the meantime, I'm interested in diving more into the use case here. From #709:

> exposing the list of returned scopes would help the client determine if the Access Token was valid or not

Can you elaborate on why checking the return scopes would validate the access token? Also, generally speaking, it is not for the client to determine whether an access token is valid as it is not the consumer of said access token, but it's up to the resource server to determine whether the token it has been given is valid.

> a shortcoming of the current package

One could argue it's a shortcoming, but in reality we just haven't yet seen a strong use case for enabling this.

> all information from the exchange could be returned to the user

We cannot return all the information from the exchange. For example, we would not return the refresh token for security reasons. By default we already strip this off and hold it internally.

**Comment by someone1** [comment]
> Can you elaborate on why checking the return scopes would validate the access token?

I don't actually need this, this was just suggested since #709 removed the scopes warning and if this was important to the user (it's unknown why this was added), then they could detect this themselves.

> it is not for the client to determine whether an access token is valid

Agreed - that's not what we're talking about here though. Happy to treat the Access Token as opaque, just need some small details around it. I understand it's impossible to enumerate all possibilities of what developers may need, but exposing some of the details from the exchange helps. We have a use case where we couldn't use the a Promise-based approach to retrieving Access Tokens since the OpenAPI typescript-fetch generator [only accepts strings or non-async functions](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/typescript-fetch/builds/es6-target/src/runtime.ts#L138). Knowing when the token expires could allow an event to be timed to call `getTokenSilently` prior to the expiration and update the client accordingly.

The other use-case around the returned scopes is less about security and more of a UX thing - if my app is aware of scopes an API it interacts with has, and can offer various functionality based on what the currently logged in user has permissions for (using Auth0's RBAC features), we could optimize the UX by hiding functionality the user is not permissioned for. Auth0 specifically returns a list of granted scopes vs requested scopes ([doc](https://auth0.com/docs/scopes#requested-scopes-versus-granted-scopes) and [doc](https://auth0.com/docs/scopes/api-scopes#example-an-api-called-by-a-first-party-application)).

I think this exact use-case is described in the [SPA+API](https://auth0.com/docs/architecture-scenarios/spa-api/part-3#display-ui-elements-conditionally-based-on-scope) example.

> One could argue it's a shortcoming, but in reality we just haven't yet seen a strong use case for enabling this.

Fair Point.

> For example, we would not return the refresh token for security reasons.

10,000% agree with this, hence why I cautioned that it may be an overstep. I personally disable the use of Refresh Tokens for all my SPAs. Maybe everything minus the Refresh Token then?

**Comment by someone1** [comment]
@stevehobbsdev - would you be willing to reopen this issue? Given this library doesn't support an [example Auth0 use-case](https://auth0.com/docs/architecture-scenarios/spa-api/part-3#display-ui-elements-conditionally-based-on-scope) and the possibility of introducing support in a [non-breaking way](https://stackoverflow.com/questions/54165536/typescript-function-return-type-based-on-input-parameter/54166010#54166010), this issue can be reopened and addressed sooner rather than later!

**Comment by stevehobbsdev** [comment]
@someone1 Yes I can reopen, seems fair. I'm out the rest of the week, but I can put some deep thought into this next week and come back to you.

**Comment by fivepapertigers** [comment]
Just wanted to chime in here, but I'm having a similar issue.

I have a known set of scopes that is required to access the full functionality of a specific page, and I include those when requesting an access token. The token that is returned, however, may or may not have those scopes depending on their permission set in Auth0. But there's no way for me to programatically understand that (in order to conditionally render an "access denined" screen without doing either of the following:

1. Manually parsing the access token and reading the returned scopes
2. Attempting to connect to the backend and handling the corresponding 403

Neither of these is ideal. FWIW, my context is a React app.
