### ISSUE TITLE
Obtain auth_time even without max_age

### ISSUE THREAD

**Issue by mitar** [auth0/auth0-spa-js#719]
### Describe the problem you'd like to have solved

For logging purposes, I would like that the ID tokens always contain `auth_time`. It seems that auth0 currently provides it only when `max_age` is set. The [spec](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) says that I could request it as an essential claim, but I do not see a way to do that using this library.

### Describe the ideal solution

A way to specify essential claims when requesting ID tokens.

**Comment by frederikprijck** [comment]
Thanks for reaching out,

I think it's important to understand what `Essential Claims` means first:

> It means that WHEN the `claims` parameter is supported on an Authorization Server declaring it as `essential: true` means it MUST be part of the `ID Token`.

However, according to the spec, you can decide if you want to support this claims parameter or not in your implementation, see https://openid.net/specs/openid-connect-discovery-1_0.html and look for `claims_parameter_supported`:

> claims_parameter_supported
OPTIONAL. Boolean value specifying whether the OP supports use of the claims parameter, with true indicating support. If omitted, the default value is false.

As you can see in your OIDC Configuration, which you can find at `https://[tenant name].auth0.com/.well-known/openid-configuration`, you will notice that we ommit the `claims_parameter_supported` property, meaning it defaults to false which means Auth0 does not support the concept of `Essential Claims`.

This means the only way to get the `auth_time` claim is by specifying the `max_age` parameter as you had already mentioned.

The above shows this isn't a limitation of our SDK, but a design decision with Auth0 when implementing the OIDC Specification.
