### ISSUE TITLE
loginWithPopup is blocked by firefox since version 1.6.5

### ISSUE THREAD

**Issue by napter** [auth0/auth0-spa-js#726]
### Describe the problem
Using loginWithPopup in firefox in an onclick works in 1.6.4. However, in 1.6.5 the same code now triggers firefox pop blocker. 

I have done some preliminary investigation and I believe the issue was introduced in [this commit](https://github.com/auth0/auth0-spa-js/pull/368/commits/6665dc071e7e27d480ef2b7d91673741fe571d5e).

Prior to this, the code would call window.open during the asynchronous part of the function call - then later, it would asynchronously set the URL of the pop up. This is the correct way to handle this. However, after the refactor the popup was moved to the asynchronous code - this causes Firefox to block it with its popup blocker. In Girefox if you try to open a window asynchronously it will [no longer be treated as a user action ](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions). 

### What was the expected behavior?

The window should open without being blocked by the popup blocker.

### Reproduction

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

If so, provide steps:

Run the playground, click login with popup in firefox. Get a banner showing "firefox prevented this site from opening a pop up window". Console shows "Uncaught (in promise) Error: Could not open popup"

### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:**
- Listed above - any version after 1.6.4 has this issue
- 
- **Which browsers have you tested in?**
- Issue occurs in firefox
- 
- **Which framework are you using, if applicable (Angular, React, etc):**
- Vue
- 
- **Other modules/plugins/libraries that might be involved:**
None

**Comment by stevehobbsdev** [comment]
Thanks for raising this - let me do my own investigation into this and get back to you, although it will likely be next week.

**Comment by stevehobbsdev** [comment]
I was able to reproduce the issue. Something like this works, tested in with the latest Firefox based on the latest version of the SDK: https://github.com/auth0/auth0-spa-js/compare/fix/firefox-popup. Are you able to test this branch to confirm?

**Comment by napter** [comment]
@stevehobbsdev I will try - but in the meantime I am getting [this issue](https://github.com/auth0/auth0-spa-js/issues/726). My primary goal is to get safari to work with refresh tokens and localstorage, in testing that I also tested firefox with third party cookies disabled and came across this popup bug.

**Comment by weyert** [comment]
I ended up using `oidc-client-js` instead of this library since I switched I don't have any issues with popup blockers in Safari and Firefox.

**Comment by stevehobbsdev** [comment]
> My primary goal is to get safari to work with refresh tokens and localstorage

Thanks, that helps. I can confirm on my end that the branch I put up fixes the same issue in Safari with the popup not opening, and I replied to the other issue as well.

**Comment by stevehobbsdev** [comment]
I've raised #732 which should fix this as well as #728, if you would like to try it out.
