### ISSUE TITLE
Cannot login if cookies are blocked using refresh tokens and local cache storage

### ISSUE THREAD

**Issue by napter** [auth0/auth0-spa-js#728]
Using the latest version 1.14.0. When I run loginwithpop up using social login (google), refresh tokens and cache set to localstorage. The login fails ,on second attempt I get this error in Safari:

[Error] TypeError: null is not an object (evaluating 't.organization')

	_callee$ (app.js:16429)
	l (chunk-vendors.js:27481:5863)
	(anonymous function) (chunk-vendors.js:27481:5648)
	asyncGeneratorStep (chunk-vendors.js:131)
	_throw (chunk-vendors.js:157)
	promiseReactionJob

In Firefox, if I set it to block all third party cookies it shows as:

TypeError: t is null
    node_modules auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js/</Vo</t.prototype.loginWithPopup/</<@http://localhost:8080/js/chunk-vendors.js:32
    s http://localhost:8080/js/chunk-vendors.js:32
    s http://localhost:8080/js/chunk-vendors.js:32
    c http://localhost:8080/js/chunk-vendors.js:32
    promise callback*a http://localhost:8080/js/chunk-vendors.js:32
    c http://localhost:8080/js/chunk-vendors.js:32
    promise callback*a http://localhost:8080/js/chunk-vendors.js:32
    c http://localhost:8080/js/chunk-vendors.js:32
    promise callback*a http://localhost:8080/js/chunk-vendors.js:32
    r http://localhost:8080/js/chunk-vendors.js:32
    r http://localhost:8080/js/chunk-vendors.js:32
    node_modules auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js/</Vo</t.prototype.loginWithPopup@http://localhost:8080/js/chunk-vendors.js:32
    _callee$ http://localhost:8080/js/app.js:17333
    l http://localhost:8080/js/chunk-vendors.js:36663
    _invoke http://localhost:8080/js/chunk-vendors.js:36663
    t http://localhost:8080/js/chunk-vendors.js:36663
    asyncGeneratorStep http://localhost:8080/js/chunk-vendors.js:131
    _next http://localhost:8080/js/chunk-vendors.js:153
    _asyncToGenerator http://localhost:8080/js/chunk-vendors.js:160
    _asyncToGenerator http://localhost:8080/js/chunk-vendors.js:149
    loginWithPopup http://localhost:8080/js/app.js:17364
    _callee$ http://localhost:8080/js/app.js:1220
    l http://localhost:8080/js/chunk-vendors.js:36663
    _invoke http://localhost:8080/js/chunk-vendors.js:36663
    t http://localhost:8080/js/chunk-vendors.js:36663
    asyncGeneratorStep http://localhost:8080/js/chunk-vendors.js:131
    _next http://localhost:8080/js/chunk-vendors.js:153
    _asyncToGenerator http://localhost:8080/js/chunk-vendors.js:160
    _asyncToGenerator http://localhost:8080/js/chunk-vendors.js:149
    loginClick http://localhost:8080/js/app.js:1231
    click http://localhost:8080/js/app.js:7562
    invokeWithErrorHandling http://localhost:8080/js/chunk-vendors.js:38806
    invoker http://localhost:8080/js/chunk-vendors.js:39131
    invokeWithErrorHandling http://localhost:8080/js/chunk-vendors.js:38806
    $emit http://localhost:8080/js/chunk-vendors.js:40835
    click http://localhost:8080/js/chunk-vendors.js:47527
    invokeWithErrorHandling http://localhost:8080/js/chunk-vendors.js:38806
    invoker http://localhost:8080/js/chunk-vendors.js:39131
    _wrapper http://localhost:8080/js/chunk-vendors.js:43860

How can I troubleshoot this? Am I doing something wrong? 

My main goal is to allow logins using safari. All the posts on this issue says to use refresh tokens  and set cache to localstorage, however that doesn't seem to be working with Google OAuth login.

**Comment by napter** [comment]
Additional info: When logging in using google social login, if I go to storage I can see that ___.auth0.com created a cookie (despite refresh tokens and localstorage being set). Meanwhile there is no data in localstorage. However if I log in with a username and password, the above error does not occur - I do get logged in, and a key "@@auth0spajs@@______" is added to localstorage.

**Comment by stevehobbsdev** [comment]
> null is not an object (evaluating 't.organization')

This looks like a bug on our end, which I will fix in [this branch](https://github.com/auth0/auth0-spa-js/tree/fix/firefox-popup). Out of interest are you passing `null` to `loginWithPopup`?

> My main goal is to allow logins using safari. All the posts on this issue says to use refresh tokens and set cache to localstorage, however that doesn't seem to be working with Google OAuth login.

This is a use case that should definitely work so I'm sorry that you're having trouble. Whether you use username & password, or social login, should not matter to the SDK as this all happens on the Auth0 server. Either way, your app should receive the necessary `code` and `state` params and the SDK will process them all the same.

If I run through your scenario in Safari using the SDK playground, enabling the "Use local storage" and "Use refresh tokens" switches, and turning off "Use token cache when fetching new tokens", I am able to log in just fine.

**Comment by napter** [comment]
@stevehobbsdev I was passing null. I switched to passing {} - which seems to have fixed it on firefox but I still get [Error] TypeError: null is not an object (evaluating 't.organization') on Safari. 

I am trying to use the latest master with your changes to see if that helps but I am having a hell of a time figuring out how to do that. Previously, I just used npm install. I tried to git clone the master to a subdirectory of my project and then npm install from the directory but when I do that and try to vue build or serve I just get an error:

This dependency was not found:
* @auth0/auth0-spa-js in ./src/auth/index.js

I tried installing straight from github (although it would be nice to mess with it locally) using:  npm install _npm install _https://github.com/auth0/auth0-spa-js_ but that first threw errors about missing rimraf, Installed that, then Cannot find module 'rollup-plugin-node-resolve', I tried installing that then I get "ES-Check: Did not find any files to check for 'dist/auth0-spa-js.production.js'". Same thing if I try to npm run build in a local clone.

What steps can I take to use and (possibly deploy) the code from github instead of the published npm versions?

Thanks for any help you can offer!

**Comment by stevehobbsdev** [comment]
@napter The way I normally do this is by using [`npm pack`](https://docs.npmjs.com/cli/v7/commands/npm-pack):

* Clone `auth0-spa-js` to a folder locally
* Check out the branch you want to test (or leave on the master branch)
* Install dependencies: `npm install`
* Pack: `npm pack` - this will build and pack the project, and output a `.tgz` file to your current directory
* Move to the project that you want to install `auth0-spa-js` _into_
* Install the package by referring to the `.tgz` file that was created by `npm pack` in the step above: `npm install <path to .tgz file>`

Hope that helps
