### ISSUE TITLE
HTTP Interceptor should not require auth token

### ISSUE THREAD

**Issue by schmidt-daniel** [auth0/auth0-spa-js#736]
### Describe the problem you'd like to have solved
(also see https://community.auth0.com/t/auth0-angular-http-interceptor-error-when-user-is-not-logged-in/50866)

I want to send a request to my API from an Angular application. Depending on whether the user is logged in or not, I want the API to return different levels of detail information.
Unfortunately, the integrated HTTP Interceptor does not send requests to the API at all if there is no token present, instead it throws an error "Login required".

### Describe the ideal solution
In my opinion, the HTTP Interceptor should just make the API call, even if there is no token present (by omitting the Authentication header). If a token is really required, the backend should take care of it and return an error, not the frontend.

## Alternatives and current work-arounds
Option 1: Implement own HTTP interceptor that behaves differently based on the route (as proposed by Edward in the forum post), but that does not work for my use case.

**Comment by frederikprijck** [comment]
Hi,

This the wrong repository. you want https://github.com/auth0/auth0-angular/.

That said, we added the ability for this here https://github.com/auth0/auth0-angular/pull/145 and it should be available in `1.4.1`

If that doesn't work, please open an issue in the repository for the Angular SDK.
