### ISSUE TITLE
Bug introduced by #732 - "Invalid Scheme"

### ISSUE THREAD

**Issue by yinzara** [auth0/auth0-spa-js#745]
The method used to fix #732 has caused an "invalid scheme" error when using this library inside of Cordova because it calls "window.open" with an empty string before setting the "location.href" of the popup which Cordova doesn't seem to like.

I know that Cordova should allow for "window.open" with an empty string, but it doesn't and getting them to fix that issue will be a very major change.

This fix could have been made much simpler. I will submit a PR that simplifies the fix and prevents the error from occurring in Cordova.

**Comment by stevehobbsdev** [comment]
Let's close this for now and keep any discussion on the PR.
