### ISSUE TITLE
Is the state parameter really checked?

### ISSUE THREAD

**Issue by Equanox** [auth0/auth0-spa-js#747]
I took a look into the library and was wondering if the state parameters is checked to mitigate CSRF attacks, see https://auth0.com/docs/protocols/state-parameters#csrf-attacks

https://github.com/auth0/auth0-spa-js/blob/1da10cb344892b72471e5d709e32b68f26269a2e/src/Auth0Client.ts#L525

Maybe i missed it but it seems to me that this check is not done inside the library?

**Comment by heidemn-faro** [comment]
To add a bit more context, we're talking about this API function:

```js   
  /** 
   * ...
   * Performs a redirect to `/authorize` using the parameters
   * provided as arguments. Random and secure `state` and `nonce`
   * parameters will be auto-generated.
   *
   * @param options
   */
  public async loginWithRedirect(options: RedirectLoginOptions = {}) {
```

Great that a random `state` is generated, but we were wondering where it is then actually checked.

**Comment by frederikprijck** [comment]
Thanks for reaching out.

This SDK is using the PKCE flow, and as mentioned here https://tools.ietf.org/id/draft-ietf-oauth-security-topics-13.html#rfc.section.3.1, when using `PKCE`, checking `State` is not required to prevent `CSRF`.

> Clients MUST prevent CSRF. One-time use CSRF tokens carried in the state parameter, which are securely bound to the user agent, SHOULD be used for that purpose. If PKCE [RFC7636] is used by the client and the authorization server supports PKCE, clients MAY opt to not use state for CSRF protection, as such protection is provided by PKCE. In this case, state MAY be used again for its original purpose, namely transporting data about the application state of the client (see Section 4.7.1).

In this case, this SDK is protecting against CSRF by using PKCE but uses State to transport data.

The wording of `Random and secure `state` and `nonce` parameters will be auto-generated.` can be a bit confusing as the `secure` part might indicate it is used for CSRF as well, but it is not.

**Comment by heidemn-faro** [comment]
Thanks Frederik for your quick reply.
So is the following correct?

`loginWithRedirect()` is already secure by default, and we don't have to put any special security measures on top of it to avoid e.g. that tokens are intercepted by another app?
So it is **not** required that we generate a random number in the app, store it in localStorage and compare it later when Auth0 redirects back to the app?

**Comment by frederikprijck** [comment]
Closing this, feel free to continue conversation.
