### ISSUE TITLE
Better insulate calls to other IDP's when using loginWithRedirect() when 3rd party cookies are not allowed

### ISSUE THREAD

**Issue by joberdick** [auth0/auth0-spa-js#753]
### Describe the problem you'd like to have solved

When logging in an app, we don't want to be subject to downtime(like Azure) or added latency of an enterprise connection. In many cases we also specify the connection name in the auth0 config to avoid being prompted by the auth0 universal login page. This works well in a browser that supports 3rd party cookies. When loginWithRedirect() is called on app start up it automatically attempts a silent auth request via iframe. If that succeeds, the user is logged in without ever going back to the enterprise connection IDP. The problem occurs if in a browser that blocks 3rd party cookies and we specifiy the enterprise connection in the auth0 client config. The silent auth will never succeed because of the cookies being blocked. This then leads to login to the enterprise connection IDP and then back to Auth0 **even if the auth0 session is already valid**.  This extra hop then create more latency and subject the login to the uptime of the enterprise IDP when it didnt need it.

### Describe the ideal solution

We would like an option that does not use silent login at all in loginWithRedirect(), but instead an attempted login with setting prompt=none in the main url. Then fallback to regular login if that fails. This would give us protection from IDP outages and better performance when 3rd party cookies are not enabled. We are finding this to more common now given the state of browsers on cookies. 

## Alternatives and current work-arounds

It could be argued that silent auth in general should stop trying to use iframes all together when the rotating refresh token is enabled. So the scope of iframes being in question could be expanded.

We could create our own wrapper of this SDK, but we want to give our devs the easiest way to get best practices. It makes more sense to us to try to fix it in the SDK itself though.
### Additional context

If this was updated, we would want to use it in the other SDK's that leverage this one. IE https://github.com/auth0/auth0-angular

**Comment by stevehobbsdev** [comment]
@joberdick There are a few things to unpack here, so let me go through it. I can understand the trepidation when it comes to outages.

> Better insulate calls to other IDP's

Just to clarify, I wasn't sure or not if you're using this library with IDPs other than Auth0, but this is not generally supported as this is an Auth0-specific SDK rather than a generic OIDC client.

> When loginWithRedirect() is called on app start up it automatically attempts a silent auth request via iframe

It might help to see the order of operations in your app here and what calls you're making. Regardless of whether you do `loginWithRedirect`, we do try to log you in silently on startup if we think you might have a session (we check the presence of a `auth0.is.authenticated` cookie). When calling `loginWithRedirect`, it simply builds a URL and performs a redirect and does nothing with silent auth.

When you are redirected back to your app, calling `handleRedirectCallback` will retrieve a token directly from the token endpoint without using an iframe.

I just want to ensure we're on the same page here, as "We would like an option that does not use silent login at all in loginWithRedirect()" doesn't make sense given the above. We'd like to see some code, ideally if you have a small repro sample we can look at.

> It could be argued that silent auth in general should stop trying to use iframes all together when the rotating refresh token is enabled

This is something that has been discussed before without too much of a resolution, as we do fall back to using an iframe if either you don't have a refresh token, or using it fails. As third-party cookies become more and more restricted, that behaviour becomes less and less relevant.

**Comment by joberdick** [comment]
@stevehobbsdev  we are only using the SDK with Auth0. The IDP's I am referring to are the ones you can setup under connections:

![image](https://user-images.githubusercontent.com/33881653/121359673-b7290080-c901-11eb-8702-7ba1db98f8be.png)


I can easily reproduce this using this sample app: https://github.com/auth0-samples/auth0-angular-samples

Let me walk through that...

1. Setup an enterprise connection. In my case, Azure.
2. Setup a SPA client in Auth0 and enable that connection on the app.
3. Clone down the angular sample app and setup the config for your SPA app
4. Add the connection name of enterprise connection to the auth_config.json
``` "connection": "your-connection-name" ```
5. ng serve up the page locally
6. Open http://localhost:4200/ in regular chrome(I am on  91.0.4472.77)
7. Click login button and sign into your enterprise connection(Note that you didn't see the universal login screen since you have the connection in your client config)
8. After successful login to the app, refresh the page. You should see that the sign-in worked without redirecting to the enterprise connection:
![image](https://user-images.githubusercontent.com/33881653/121362612-37506580-c904-11eb-9705-b26400b7895c.png)
This is because silent auth was called and worked.
9. Open a chrome incognito tab and ensure that 3rd party cookies are blocked:
![image](https://user-images.githubusercontent.com/33881653/121363087-9e6e1a00-c904-11eb-9cf3-2460e1614350.png)
10. Open  http://localhost:4200/ and login again
11. After successful login, refresh the page. Note that sign in did not occur. This looks like because silent auth failed: 
![image](https://user-images.githubusercontent.com/33881653/121365233-7aabd380-c906-11eb-9a2e-d204046dae23.png)

11. Now click login. Observe that your browser went to auth0 and the enterprise connection even though your auth0 session is still valid: 
![image](https://user-images.githubusercontent.com/33881653/121364388-bd20e080-c905-11eb-9dad-d9a229dba75a.png)

This seems to be because silent auth fails from iframe with 3rd party cookies blocked. Since silent auth failed, Auth0 will always redirect the user to the enterprise connection when the connection name is specified in the authorization request.

**Comment by stevehobbsdev** [comment]
Thanks for the detailed repro steps @joberdick.

Regarding the use of `prompt=none` when third-party cookies are blocked, you're able to do this today with the SDK as-is:

* Use the constructor to initialise the SDK, as opposed to using `createAuth0Client` (see [creating the client](https://auth0.github.io/auth0-spa-js/#creating-the-client). This will mean that the automatic call to `checkSession` (and thus silent login) will not happen on SDK start-up and you can manage this yourself.
* Use `loginWithRedirect({ prompt: 'none' })`. The `prompt` parameter will be sent to Auth0 and will not show the login screen if the user has a session
* If the user does _not_ have a session, a `login_required` error will be thrown, and you can handle this to log the user in normally

If that's an acceptable solution for you, we can look at how we can enable this scenario in `auth0-angular` (as well as `auth0-react`) as right now you can't disable the initial call to `checkSession` (or it could just be ignored), but you can specify `prompt=none` when logging in.

I also wanted to note that our official solution for auth when third-party cookies are blocked is to use rotating refresh tokens. I can see you're using them here, but without some kind of storage that persists them across page refreshes. The SDK allows you to [store both in memory (the default) and local storage](https://auth0.com/docs/libraries/auth0-single-page-app-sdk#change-storage-options). Plus we have [a PR in flight](https://github.com/auth0/auth0-spa-js/pull/743) that would allow you to build your own cache storage if you have a secure place to send and store refresh tokens. I was just curious as the reason you're not (or can't) use local storage in this scenario, which would mean you're only ever interacting with Auth0's token endpoint in the same login session as long as the refresh token is valid. It would also remove the additional latency you get with interacting with a third-party connection or even just silent auth using iframes.

**Comment by joberdick** [comment]
@stevehobbsdev I was able to create a working example with prompt=none. I am waiting to hear back from others internally on how viable that would be to use as our standard. Its not clear to me on what we might lose out on by going this direction. It's a bit clunky, but might be acceptable. I will let you know soon if we think it's worth adding that to ```auth0-angular``` and a```uth0-react```. 

Using local storage is something we have not been comfortable with. The reuse detection on refresh tokens helps but access tokens are still subject to attack as far as I know. Using our own cache is interesting, but I am not aware of a use case for SPA's where that would practical?

I assume there is not much room for improvement in the SDK to be able to automatically handle trying prompt=none with loginWithRedirect() since it's on the reload of the page where the app needs to handle the error and retry login without the prompt=none? We are ideally looking for a solution that doesn't require very specific implementation guidance to all of our dev teams. Which makes me wonder if we should also put in a feature request to have API support login to an enterprise connection for an optional parameter that would allow existing session to be honored when specifying a connection at login. We really just want to skip the universal login screen when its not needed without causing unneeded latency or reduced reliability.

**Comment by stevehobbsdev** [comment]
> Using our own cache is interesting, but I am not aware of a use case for SPA's where that would practical?

We're implementing it for those users who wish to use this SDK inside a hybrid framework like Ionic + Capacitor, and want to use a more secure storage option.

Let me know if you've managed to come to a workable solution within your own environment or if you need further guidance from us.

**Comment by joberdick** [comment]
@stevehobbsdev  thanks for the follow up. We have decided to change our strategy and rely more on login_hint, which does not have the same issue with re-authing to other IDP's unnecessarily. We have put in a feature request at the API level to assist in our goals in reducing prompt of UL. I will come back if we need to pick this back up. Thanks for your input.
