### ISSUE TITLE
Documentation of interaction between refresh token inactivity timeout, access token expiration time, and tenant level settings (inactivity timeout and require login after)

### ISSUE THREAD

**Issue by oneillsp96** [auth0/auth0-spa-js#754]
Mentioned this briefly in a previous issue, but my largest struggle while implementing rotating refresh tokens has been trying to understand how the various expiration times and inactivity settings interact with one another.  One question especially is how and when the tenant level settings come into play.

Here are a few of the things I'm trying to get straight in my head.

Do the tenant level settings "require login after" and "inactivity timeout" have any bearing on whether the oauth/token endpoint will issue a new access/refresh token pair (when getTokenSilently is called)?

Or do the tenant level settings "require login after" and "inactivity timeout" only affect the cookie?

What happens when refresh token family has absolutely expired, but the tenant level "require login after" and "inactivity timeout" have not been surpassed, and then you call getTokenSilently?

Conversely, what happens when the the tenant level "require login after" and "inactivity timeout" have been surpassed, but the refresh token family has not expired yet, and then you call getTokenSilently? 

If the refresh token absolute lifetime is expired, does the library error with "invalid grant" or "login required"? Or does it fallback to using an iframe?  Reading the code, it looks like the fallback to iframe only happens when the refresh token is completely absent...can you confirm?

It seems that "login_required" error correlates with a tenant level session being timed out, which correlates to the iframe technique of getTokenSilently failing, while the "invalid grant" error correlates to a refresh token family hitting absolute expiration, which correlates with the useRefreshTokens technique of getTokenSilently failing. Is that more or less accurate?

Is it a best practice to set the refresh token lifetime as a certain multiple of the access token lifetime? Is there a formula most users should follow, ie my access token lifetime is x minutes, refresh token lifetime should be y minutes?

**Comment by frederikprijck** [comment]
> Do the tenant level settings "require login after" and "inactivity timeout" have any bearing on whether the oauth/token endpoint will issue a new access/refresh token pair (when getTokenSilently is called)?

Purely looking at it from the `/token` endpoint, no. But that's only when using Refresh Tokens. 
When not using Refresh Tokens, `getTokenSilently` uses an iFrame in which it actually just navigates to the same page as `loginWithRedirect` does (but with a few different settings). In this case it relies on the fact that we still have an active session with auth0. This session is controlled by that tenant setting for as far as I know. So imagine the following:

- I open your application and log in, a session is stored on auth0.com to remember that I am authenticated
- In the tenant settings we set `require login after` to 60 minutes
- After 61 minutes, assuming my cached access token is expired and I use `getTokenSilently` from your application.

Now there are two scenarios:

**When not using Refresh Tokens**
- I wont get a new access token and Auth0 will tell me that a login is required (It cares about the session on auth0.com).

**When using Refresh Tokens:**
- I get a new access token (it doesnt care about the session on auth0.com).

If you want to ensure that after 60 minutes, I also cant get an access token when using refresh tokens, you need to use the refresh token setting to ensure it expires after 60 minutes (whether or not you use the absolute expiration here or not depends on the use case).

> Or do the tenant level settings "require login after" and "inactivity timeout" only affect the cookie?

Well it impacts the cookie/session on Auth0.com, but it also impacts whether or not u can keep retrieving new access tokens without entering credentials when u do not use Refresh Tokens.

> What happens when refresh token family has absolutely expired, but the tenant level "require login after" and "inactivity timeout" have not been surpassed, and then you call getTokenSilently?

When using Refresh Tokens, `getTokenSilently` will do two things:

- It first tries to get a new Access Token using the refresh token, which will fail
- It then fallback to the iframe approach, this will not fail so you will still get an access token. (**see the note about 3rd party cookies below**)

Subsequent calls will continue to work and you will be able to keep refreshing your Access Token until the tenant settings have surpassed.

> Conversely, what happens when the the tenant level "require login after" and "inactivity timeout" have been surpassed, but the refresh token family has not expired yet, and then you call getTokenSilently?

When using Refresh Tokens, `getTokenSilently` will do one thing now (same as above, but step 1 wont fail). 

- It first tries to get a new Access Token using the refresh token, which will succeed

So it doesnt care about the require login after or activity timeout setting in this case.

> If the refresh token absolute lifetime is expired, does the library error with "invalid grant" or "login required"? Or does it fallback to using an iframe? Reading the code, it looks like the fallback to iframe only happens when the refresh token is completely absent...can you confirm?

- This is the fallback when the refresh token is absent: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L934
- This is the fallback when it was no longer valid: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L980-L986

> It seems that "login_required" error correlates with a tenant level session being timed out, which correlates to the iframe technique of getTokenSilently failing, while the "invalid grant" error correlates to a refresh token family hitting absolute expiration, which correlates with the useRefreshTokens technique of getTokenSilently failing. Is that more or less accurate?

yes, `login_required` means the user needs to log in again. Which is controlled by the tenant level settings mentioned here (well it can also show up when using a browser that blocks 3rd party cookies, see the bottom of this post).

> Is it a best practice to set the refresh token lifetime as a certain multiple of the access token lifetime? Is there a formula most users should follow, ie my access token lifetime is x minutes, refresh token lifetime should be y minutes?

I believe the decision here is a combination of security and user experience.
Let us say we set Access Token to expire in 10 minutes, and Refresh Token to expire in 30 minutes (Let's assume absolute is set to a few days, to make it irrelevant here)...

I can successfully keep using the application for hours (assuming we refresh the token regularly, but that is an application concern of course).
However, once I close your application for 30 minutes, my refresh token is invalid. This is where the tenant level setting comes into play. If the session with Auth0 still exists, I can successfully get a new token without having to re-enter my username and password. However, if that session was also configured to only last for 30 minutes, I would need to re-enter my credentials when I only left your application for 30 minutes.

This behavior could be acceptable in your application, while other applications wont like that approach (e.g. when was the last time u had to enter your facebook credentials? assuming u use facebook ofcourse).

So now you need to decide what combination of these values work in your case:

- Refresh Token expiration > Require Login After: As long as the user does not go away from the application for the duration of the Refresh Token expiration, they will be able to continue using the application untill the Absolute refresh token expiration is surpassed
- Require Login After > Refresh Token Expiration: As long as the user does not go away from the application for the duration of the Refresh Token expiration, they will be able to continue using the application untill the Absolute refresh token expiration is surpassed. If the user goes away longer than the configured Refresh Token Expiration, they can rely again on the session with Auth0 and get an access token and new Refresh Token from using that approach.
- Require Login After === Refresh Token Expiration: As long as the user does not go away from the application for the duration of the Refresh Token expiration, they will be able to continue using the application untill the Absolute refresh token expiration is surpassed. If the user goes away longer than the configured Refresh Token Expiration, they need to reenter their credentials.

**3rd party cookies**
One important thing to add here... As mentioned above, `getTokenSilently` falls back to using an iframe if the refresh token is expired. However, the iframe approach does not work on browsers that block 3rd party cookies (e.g. Safari, and soon Firefox and Chrome). What will happen then is, even tho we still have a session with Auth0, `getTokenSilently` will throw `Login required`... It is then up to the application to catch that error and call our SDK's `loginWithRedirect`. If the user still has an active session with Auth0, they will not be prompted for their credentials and get redirected back to your application instantly, with a new set of tokens that you can start using.

Note: The above explanation for the different settings is not unique to this SDK, same goes for things like Mobile and Desktop applications. 

Hopefully this is helpful.

**Comment by oneillsp96** [comment]
Very helpful, thank you.

**Comment by oneillsp96** [comment]
@frederikprijck one last question and I'll leave you alone...can you confirm that during a refresh token rotation event, the id_token exp field is also renewed? This is what my experiments show.

**Comment by frederikprijck** [comment]
Using the refresh token results in a new access token, id token and refresh token. All of these should have a new iat claim and as well have a different expiration.
