### ISSUE TITLE
Make '/authorize' endpoint configurable

### ISSUE THREAD

**Issue by knuff3l** [auth0/auth0-spa-js#767]
### Describe the problem you'd like to have solved

You always use the `/authorize` endpoint of the Authentication API to authenticate the user.
Our identity provider uses the endpoint `/auth`.
So we can't use your library.

### Describe the ideal solution

I think it would be easy to configure the authentication endpoint by some kind of options.

One step further:
If I'm right, every identity provider following the openid connect specs implements a `/.well-known/` route.
This route exposes some details of the provider, like the `authorization_endpoint`, which points to the route you'll have to authenticate to.

## Alternatives and current work-arounds

Currently no work-arounds.

**Comment by stevehobbsdev** [comment]
HI @knuff3l, thanks for raising this. As this SDK is designed to give the best experience for Auth0 and is not a generic OIDC client, we align with Auth0's endpoint locations and do not offer the ability to customize it. We also do not integrate with our `.well-known` discovery document currently, although this occassionally gets discussed internally as an improvement we might make in the future - but it's not without its downsides and challenges.

Therefore, unfortunatley we're unable to accomodate your request at this time.

**Comment by knuff3l** [comment]
I understand. 
Thank you very much for your answer.
