### ISSUE TITLE
Different scopes for multiple APIs

### ISSUE THREAD

**Issue by erlendp** [auth0/auth0-spa-js#776]
### Describe the problem you'd like to have solved

According to the official API documentation [Authentication API Explorer](https://auth0.com/docs/api/authentication?javascript&_ga=2.24713146.1275084142.1628640630-732235340.1628640630&_gl=1*5uhurx*rollup_ga*NzMyMjM1MzQwLjE2Mjg2NDA2MzA.*rollup_ga_F1G3E656YZ*MTYyODY3NDE3OS40LjEuMTYyODY3NDE4NS41NA..#refresh-token), we should be able to authorise with a set of scopes, and then use the returned refresh token to retrieve an access token with a sub-set of those scopes.

Experimentation with the library suggests it does not support this use-case (when using the `useRefreshTokens` option, anyway). If I pass a set of scopes in when I create the `Auth0Client`, then supply a restricted set of scopes in the call to `getAccessTokenSilently`, the token returned is the same for all sub-sets of scopes.

I suspect the scopes passed to `Auth0Client` are acting as global scopes, which is not what I want, given the Principle of Least Privilege.

### Describe the ideal solution

Ideally, this library would support the use-case described in the API documentation, and allow access tokens to be generated with different scopes when using the `useRefreshTokens` option.

### Alternatives and current work-arounds

If you avoid using the `useRefreshTokens` option, and don’t provide the scopes to the client, then things work as expected in browsers that support third party cookies. Unfortunately, as browsers tighten up their security with respect to third party cookies, this problem is only going to get worse, and I'm not sure if the custom domain workaround will work in all use-cases.

**Comment by stevehobbsdev** [comment]
Thanks for raising this @erlendp. While this is supported in the `/oauth/token` endpoint as mentioned, it's not a scenario that's currently supported with the SDK; as you rightly point out, we're treating the scopes here as global and as a result you're not able to request a subset of scopes right at this moment.

We're currently evaluating feature requests across all our SDKs, and I will add this to the list for evaluation.

**Comment by erlendp** [comment]
Thanks for your quick response. I may consider opening a PR for this at some stage, assuming you're open to accepting PR's from the public?

**Comment by stevehobbsdev** [comment]
Generally we do accept PRs from the public. However, for this particular issue we may prefer to implement this ourselves. It's something we've discussed off and on before and there are many caveats and edge cases to consider, particularly around caching.

We'll have a discussion internally and come back to you on it. If you need this in the meantime, feel free to fork and implement.

**Comment by stevehobbsdev** [comment]
Hi @erlendp,

We've had a discussion about this internally and decided that we will go ahead and implement this. I don't have a timescale for you at the moment but it's been moved to our internal backlog for action.

I'll close this for now but feel free to catch up with us about this here. I'll also make sure to tag the issue in the resulting PR for visibility.

**Comment by erlendp** [comment]
Hi there,

Just a quick follow-up to see if any progress has been made on this issue. Our company has begun development work to migrate our existing authentication + authorisation over to Auth0, so any update you can give would be helpful for planning our work stream. Cheers.
