### ISSUE TITLE
Get token without popup?

### ISSUE THREAD

**Issue by erlendp** [auth0/auth0-spa-js#777]
### Describe the problem you'd like to have solved

Authorizing via a popup is problematic, because many browsers will block popups that aren't user initiated. Additionally, popups are not particularly in-keeping with a modern SPA design, and can lead to a jarring experience.

### Describe the ideal solution

Ideally this library would support a way of doing interactive authorization without using a popup (i.e. `getTokenWithIFrame` or similar)

## Alternatives and current work-arounds

The current workaround is to call `getTokenWithPopup` from a user event handler, which may not be practical if there are multiple audiences that need to be authorized.

**Comment by frederikprijck** [comment]
Thanks for reaching out. This actually is supported in our SDK.

I believe what you are looking for is `getTokenSilently`, which uses an iframe depending on your configuration. See https://auth0.github.io/auth0-spa-js/classes/auth0client.html#gettokensilently

**Comment by erlendp** [comment]
My understanding was that getTokenSilently requires third party cookie access in the case of falling back to an iframe. The problem with this is that we need to support browsers where this access is disabled (I.e. Safari).

**Comment by frederikprijck** [comment]
> Is there any fundamental reason that this interactive flow couldn't be supported via an embedded iframe / overlay of some kind?

I am not sure what difference such an iframe would make in terms of third-party cookies as opposed to the iframe we currently have. An overlay is supported by using the popup implementation.

If you want to support Safari (as well as any browser that in the future blocks third-party cookies), you basically can either use custom domains or ensure to use Rotating Refresh Tokens, as explained in the FAQ: https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md.

**Comment by erlendp** [comment]
The coca for getTokenSilently state:
```
If an `audience` value is given to this function, the SDK always falls back to using an iframe to make the token exchange.

Note that in all cases, falling back to an iframe requires access to the `auth0` cookie.
```
If this is correct, it implies that when specifying an audience, the cookie will be used, regardless of whether refresh token rotation is used.

Having tested `refreshTokenWithPopup` with an audience, it appears to work in Safari, so I can only conclude that this function doesn't depend on the cookie.

If `refreshTokenWithPopup` can work with an overlay that will address my needs, and this ticket can be closed. Are there any examples of such an approach? I'm guessing one would need to pass an iframe element in as the popup parameter?

**Comment by frederikprijck** [comment]
I think the important part of the `getTokenSilently` documentation is this:

> If refresh tokens are used, the token endpoint is called directly with the 'refresh_token' grant. If no refresh token is available to make this call, the SDK falls back to using an iframe to the '/authorize' URL.

So if you use Refresh Tokens and Local Storage, and there is a valid Refresh Token in Local Storage, we will not be using an IFrame.

Code wise you can look at it here: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L745

If you are using Refresh Tokens but have no Refresh Token, you can see the fallback to the IFrame here: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L993

If something goes wrong with using the Refresh Token, you can see the fallback to the IFrame here: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L1039

> Having tested refreshTokenWithPopup with an audience, it appears to work in Safari, so I can only conclude that this function doesn't depend on the cookie.

It does depend on the cookie. But it is not using an IFrame so third party cookies are not being blocked.

> If refreshTokenWithPopup can work with an overlay, rather than a new window, that will address my needs, and this ticket can be closed. 

I am still not sure I understand what the need for an overlay is. I also believe there are some security implications to take into considerations with such an overal. In general we recommend to ensure **users do not enter their credentials inside your application**, so either using a redirect or a popup that opens a new window to guarantee the users credentials never hit your own application.

**Comment by frederikprijck** [comment]
I want to add onething more:

> If this is correct, it implies that when specifying an audience, the cookie will be used, regardless of whether refresh token rotation is used.

I believe that is inaccurate. It depends. If an audience is used that can not result in finding a corresponding Refresh Token, an IFrame will be used.

If you have the use case to use multiple audiences, I believe using Custom Domains is what you want for supporting Safari when using `getTokenSilently`.

**Comment by stevehobbsdev** [comment]
Closing as this looks to be answered. @erlendp feel free to continue the conversation if we can help further.
