### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by DShep68** [auth0/auth0-spa-js#780]
using both installation commands i am unable to install this package. using npm version 6.7.0 or yarn version 1.15.0

COMMAND
npm install  @auth0/auth0-spa-js
yarn add @auth0/auth0-spa-js

Error message 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://artifactory.psdops.com/api/npm/npm/@auth0%2fauth0-spa-js - not_found
npm ERR! 404 
npm ERR! 404  '@auth0/auth0-spa-js@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deionshepherd/.npm/_logs/2021-08-19T15_50_59_921Z-debug.log

**Comment by adamjmcgrath** [comment]
Hi @DShep68 

`npm i @auth0/auth0-spa-js --registry=https://artifactory.psdops.com/api/npm/npm` works for me.

Are you able to access `artifactory.psdops.com` from your terminal?

```shell
$ curl -I https://artifactory.psdops.com/api/npm/npm/@auth0%2fauth0-spa-js
HTTP/1.1 200 OK
```

**Comment by stevehobbsdev** [comment]
@DShep68 This looks to be a local environment issue rather than anything to do with the SDK, so I will close this for now. However, please feel free to continue the conversation if you need further help.
