### ISSUE TITLE
getTokenWithPopup Failure: TypeError: Cannot read property 'access_token' of undefined

### ISSUE THREAD

**Issue by holub008** [auth0/auth0-spa-js#784]
### Describe the problem
When calling `Auth0Client`'s `getTokenWithPopup` method, we are encountering the following error infrequently across users but consistently within users:

`TypeError: Cannot read property 'access_token' of undefined`

Logs on Auth0 show that the user was successfully logged in, but on the browser, it's a failed login, and I believe we have no recourse.

### What was the expected behavior?
`getTokenWithPopup` should produce an access token.

### Reproduction
This is impacting a small number of end users, and none of our development team can reproduce. We're working with our users who have limited technical skills to debug. The clues we have:

- Our app uses both Google and Auth0 u/p authentication, and this bug reproduces on both.
- The bug reproduces on the same computer (across browsers), and does not appear to be strictly linked to user accounts (a user with a failure on one device can still log in on another)
- The bug reproduces after clearing cookies & storage and in the browser's private mode   

I can supply a HAR for a failed popup login. It appears unremarkable, and the last `resume` call includes an embedded `response` object with `state` and `code` fields. The popup's console shows no output for these failures.
  
**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**
Not by our development team.

### Environment

- **Version of `auth0-spa-js` used:** 1.16.1
- **Which browsers have you tested in?** For impacted end users, bug was reproduced in Chrome, FF, Edge
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

I understand this is just about impossible to resolve with the given information. I was wondering if anyone had suggestions for where to look next.

**Comment by holub008** [comment]
Upon forking this repository and adding a lot of logging, we've discovered that the access token was expired on arrival at the client. This was due to a client with a wandering system clock (off by 45 seconds or so). We resolved by increasing the ID Token expiry setting (and asking the user to sync their clock).

I'm not sure how common this scenario is, but hopefully this issue helps someone in the future!

In case it's helpful, I wanted to comment on my experience. The lack of debug capabilities for this library is frustrating. Coupled with uninformative error messages (e.g. "Invalid State", or the above TypeError), diagnosing any type of login failure is painful. I had to fork `auth0-spa-js`, add console logging, deploy to production, and then coordinate with nontechnical users who generously gave their time reproducing the bug and sending network request & console logs. In theory, a well placed debug statement, e.g. "ID Token expired, attaching refresh token", would have saved us days.

Some of this complexity is unavoidable with client app development, and you can't anticipate every failure mode. But, if maintainers can give constructive guidance on features (e.g. adding some form of debug logging, adding a system clock synchronization check, etc.), my team would be happy to work on PRs.

**Comment by stevehobbsdev** [comment]
Thanks for the feedback @holub008, we'd like to look into how to improve the debug experience. Some of it is tricky as we tend to forward the responses we get from the server. A good debug tool to use is the [Auth0 Logs](https://manage.auth0.com/#/logs) tool in the dashboard which can often provide insight into what's going on. And you're right, trying to cater to the myriad of problems we might encounter is challenging.

I've taken it on board to figure out how we can improve in this area - again, thanks for the feedback!
