### ISSUE TITLE
Missing flow to take the user directly to the sign up page.

### ISSUE THREAD

**Issue by abrahamgnz** [auth0/auth0-spa-js#79]
Seems like there is nos straight forward way of taking a user to the sign up page.

Maybe loginWithRedirect could take an option to take the user directly to the sign up page.

**Comment by abrahamgnz** [comment]
Found on the documentation that this is a now issue for the universal login.
- It's not possible to link to the Signup page or default to it. Users will land in the login page, and can navigate to Signup from there.

**Comment by brendanator** [comment]
I think this issue should be reopened, this is definitely missing functionality. 

If not, is there an issue somewhere else that can be tracked?

**Comment by stevehobbsdev** [comment]
@brendanator As mentioned, it's a characteristic of the Universal Login page and nothing to do with this SDK. Your question might be better posed on our [community site](http://community.auth0.com). Can you make a post over there?
