### ISSUE TITLE
Linking Account Help

### ISSUE THREAD

**Issue by 814k31** [auth0/auth0-spa-js#80]
Good work so far on this package!

I'm looking at how to authenticate an account using this package without affecting the currently logged in account such that I can trigger the accounts to be linked.

Example:
I have account `A` logged in using email/password and they want to click a button to authenticate a social network account `B` but does not want the app to be logged into that social network account.

Am I correct thinking that:
```jsx
import createAuth0Client from '@auth/auth0-spa-js';

const accountAAuth0 = await createAuth0Client({ domain: 'xxx', client_id: 'yyy' });
await accountAAuth0.loginWithPopup();
const accountAUser = await accountAAuth0.getUser();

const accountBAuth0 = await createAuth0Client({ domain: 'xxx', client_id: 'yyy' });
await accountBAuth0.loginWithPopup();
const accountBUser = await accountBAuth0.getUser();

const accountAUserCopy = await accountAAuth0.getUser();

const worked = (
    accountAUserCopy.sub === accountAUser.sub
    && accountAUserCopy.sub !== accountBUser.sub
);
```

Is there a way to do this using redirect logins as well?

**Comment by 814k31** [comment]
It seems that the above code works, however when the original in overridden in storage so refreshing the page or adding the following code to the end of the above snippet will break:

Options like `rememberLastLogin` || `remember_last_login` did not work

```jsx
const accountCAuth0 = await createAuth0Client({ domain: 'xxx', client_id: 'yyy' });
const accountCUser = await accountAAuth0.getUser();

const stillWorked = (
const worked = (
    accountCUser.sub === accountAUser.sub
    && accountCUser.sub !== accountBUser.sub
);
```

**Comment by luisrudge** [comment]
You should only have a single `auth0Client` per page. We don't currently support account linking with this SDK because we don't expose the raw id_token. For now, you can use Auth0.js (https://auth0.com/docs/migrations/guides/account-linking#link-current-user-accounts-with-auth0-js) or a rule (https://auth0.com/docs/link-accounts#automatic-account-linking). I'll add this to our backlog as a feature request. Thanks for the feedback!

**Comment by 814k31** [comment]
@luisrudge all good thanks for responding so quickly

**Comment by afreix** [comment]
@luisrudge any updates on the status of this feature request? I'd also be interested in having this feature

**Comment by 814k31** [comment]
@afreix I ended up doing

```jsx
localStorage.set('accessToken', this.accessToken);

// You can actually dont need to create a new one, though I left it here for clarity
const accountBAuth0 = await createAuth0Client({ domain: 'xxx', client_id: 'yyy' });
await accountBAuth0.loginWithPopup();
const accountBUser = await accountBAuth0.getUser();
```

and in my constructor
```jsx
this.accessToken = localStorage.get('accessToken');
```

And before the checkSession
```jsx
getSession() {
    if (this.accessToken) {
        return;
    }

    accountAAuth0.checkSession();
}

The issue for me was that the checkSession method I used before getting the profile got the wrong access token so that was my work around

hope that helps
