### ISSUE TITLE
handleRedirectCallback still requires nonce

### ISSUE THREAD

**Issue by hle-skillz** [auth0/auth0-spa-js#807]
### Describe the problem
#678 attempts to make the `nonce` optional as it is possibly redundant when a PKCE `code_verififer` is present.  However, the nonce is still checked if it's present in the TransactionManager:
https://github.com/auth0/auth0-spa-js/blob/4c0c755c51781ed8da7cd43b0f33da1c9166b963/src/Auth0Client.ts#L658-L662

and the authorize flow unconditionally generates the PKCE *AND* the nonce:
https://github.com/auth0/auth0-spa-js/blob/4c0c755c51781ed8da7cd43b0f33da1c9166b963/src/Auth0Client.ts#L378-L385
https://github.com/auth0/auth0-spa-js/blob/4c0c755c51781ed8da7cd43b0f33da1c9166b963/src/Auth0Client.ts#L401-L402

This prevents operability with a [PKCE-compliant](https://doorkeeper.gitbook.io/guides/ruby-on-rails/pkce-flow) issuer like Doorkeeper without also bringing in [OpenID Connect](https://github.com/doorkeeper-gem/doorkeeper/pull/897).

### Reproduction
Use any issuer that does not provide OpenID Connect.

### Environment
- **Version of `auth0-spa-js` used:** 1.18.0
- **Which browsers have you tested in?** Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** [Doorkeeper](https://github.com/doorkeeper-gem/doorkeeper)

**Comment by stevehobbsdev** [comment]
Hi @hle-skillz,

The SDK makes no claim to work with just any authentication provider and as the name suggests, is mostly designed to work with Auth0. Also, #678 is not an attempt to make `nonce` optional, it was just removing a check that was not necessary and causing issues in some circumstances. As you say, the SDK continues to always generate a nonce, and is validated when it returns in the ID token.

Right now we don't have plans to remove the check as we expect Auth0 as the IdP but we also enforce the OpenID Connect flow. Even if we removed the `nonce` check, there are a few other things here that may prevent another IDP from being used successfully, such as our non-standard logout endpoint.

Will close for now but happy to discuss further.

**Comment by hle-skillz** [comment]
@stevehobbsdev any chance we could get a backwards-compatible prop / option `useNonce=true` that can be overridden for use with a non-Auth0 IdP?

**Comment by stevehobbsdev** [comment]
As long as the primary use case is to support another IdP, it's highly unlikely to be prioritised. As it is at the moment, it's causing no issues for Auth0 users and at best is a potentially redundant but innocuous check.

As I said though, even without this check you may run into issues depending on the IdP being used, and we'd likely need to add other affordances to work better with other IdPs.
