### ISSUE TITLE
Incorrect typing for getTokenSilently method

### ISSUE THREAD

**Issue by mcummings-evive** [auth0/auth0-spa-js#817]
The typing is incorrect for the getTokenSilently method in \src\Auth0Client.ts line 753

The type should be `Promise<any>` (or something else, definitely not string) not `Promise<string>`

Current typing

```
  /**
   * Fetches a new access token and returns the response from the /oauth/token endpoint, omitting the refresh token.
   *
   * @param options
   */
  public async getTokenSilently(
    options: GetTokenSilentlyOptions & { detailedResponse: true }
  ): Promise<GetTokenSilentlyVerboseResponse>;

  /**
   * Fetches a new access token and returns it.
   *
   * @param options
   */
  public async getTokenSilently(
    options?: GetTokenSilentlyOptions
  ): Promise<string>;
```

Correct typing
```
  /**
   * Fetches a new access token and returns the response from the /oauth/token endpoint, omitting the refresh token.
   *
   * @param options
   */
  public async getTokenSilently(
    options: GetTokenSilentlyOptions & { detailedResponse: true }
  ): Promise<GetTokenSilentlyVerboseResponse>;

  /**
   * Fetches a new access token and returns it.
   *
   * @param options
   */
  public async getTokenSilently(
    options?: GetTokenSilentlyOptions
  ): Promise<any>;
```

**Comment by bfricka** [comment]
Seems correct to me. If you don't ignore cache it'll return the entry if it finds one in the cache and it'll either be string or details based on options. If it doesn't find a cache entry it'll try to get a token using refresh token or iframe, depending on options. And it'll return either the auth token `string`, or `GetTokenSilentlyVerboseResponse`. That's all it can return as far as I can see. Obviously it can throw, but that has nothing to do w/ the return type.

**Comment by frederikprijck** [comment]
Thanks for reaching out.
I think `any` is never something to be considered as correct.

However, as pointed out by @bfricka , the typings look correct to me.

The method has always only resolved with a **string** only. As of v1.19.0 it can also resolve using `GetTokenSilentlyVerboseResponse`, as indicated by the types.

```
public async getTokenSilently(
    options: GetTokenSilentlyOptions & { detailedResponse: true }
  ): Promise<GetTokenSilentlyVerboseResponse>;
```

Closing this, but feel free to continue the conversation if you believe we are missing something here.
