### ISSUE TITLE
Session lost on page reload in "private browsing" mode

### ISSUE THREAD

**Issue by ranjan-purbey** [auth0/auth0-spa-js#819]
### Describe the problem

`Auth0Client` currently depends on `isAuthenticatedCookieName` cookie to maintain sessions. This cookie is set by `handleRedirectCallback` or `loginWithPopup` methods and is used by `checkSession` to determine whether a user is already authenticated. Only if this cookie is set to `true`, a token request is sent to Auth0 servers. Note that this cookie is set by JavaScript using the `es-cookie` package and is NOT related to 3rd-party cookie blocking.

Now according to [RFC 6265 - Section 7.2](https://datatracker.ietf.org/doc/html/rfc6265#section-7.2)
> Some user agents provide users the option of preventing persistent
   storage of cookies across sessions.  When configured thusly, user
   agents MUST treat all received cookies as if the persistent-flag were
   set to false.  Some popular user agents expose this functionality via
   "private browsing" mode

Both Chrome & Firefox, discard all JS cookies on page reload. I am not sure if that's what is meant by "persistence" in the RFC. Nonetheless, this means that `isAuthenticatedCookieName` cookie is lost when the user refreshes the page (or opens the app in a new private tab). This behavior is contrary to how most auth providers work.

### What was the expected behavior?
The user's session should be maintained as long as the private window is open

### Reproduction

- Step 1: Follow Auth0 React [quickstart](https://auth0.com/docs/quickstart/spa/react/01-login)
- Step 2: Open the app in a private window and login
- Step 3: Reload the browser page. Note that the user is logged out

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**
Yes

### Environment

- **Version of `auth0-spa-js` used:** 1.19.1
- **Which browsers have you tested in?** Chrome 94, Firefox 93
- **Which framework are you using, if applicable (Angular, React, etc):** React, Vanilla JS
- **Other modules/plugins/libraries that might be involved:** -n/a-

IMO, since this cookie doesn't store any sensitive information, why not use `localStorage` to store `isAuthenticated` state? That will allow maintaining sessions in private windows as well.

**Comment by ranjan-purbey** [comment]
Thanks @stevehobbsdev! You're right, we can directly call `getTokenSilently` to fetch session info from Auth0 servers. However, I think if someone follows the docs it might come as a surprise to them when `checkSession` doesn't work in private browsing mode. Probably we can add this caveat as a note in the docs?

**Comment by stevehobbsdev** [comment]
Sure, let me take a look at what we have now and see if we can make this clearer 👍🏻
