### ISSUE TITLE
auth0-spa-js only works in secure origin

### ISSUE THREAD

**Issue by Jorgevillada** [auth0/auth0-spa-js#82]
Hi,
window.crypto only  works in secure origin https://github.com/w3c/webcrypto/issues/28

https://github.com/auth0/auth0-spa-js/blob/b9ae10f9f7029c566abe7ee0bc4594e4914cb439/src/utils.ts#L92

error:
![image](https://user-images.githubusercontent.com/8599697/61375656-0b85eb80-a865-11e9-9936-8e08b30836eb.png)

![image](https://user-images.githubusercontent.com/8599697/61375687-1e002500-a865-11e9-964a-5207af8997c7.png)

![image](https://user-images.githubusercontent.com/8599697/61375703-26f0f680-a865-11e9-8d7d-a7752697c454.png)

Is the behavior expected? 
is it possible to use crypto-js?

**Comment by stevehobbsdev** [comment]
@Jorgevillada that is correct; the SDK only supports running in a secure origin.

However, we appreciate that the error message isn't exactly helpful, and already have it on our backlog to fix.
