### ISSUE TITLE
getTokenSilently return type

### ISSUE THREAD

**Issue by camden-brown** [auth0/auth0-spa-js#829]
### Describe the problem

With the recent version updates `getTokenSilently` is typed to return `GetTokenSilentlyVerboseResponse`. However, it can return `string` or `GetTokenSilentlyVerboseResponse`. It only returns `GetTokenSilentlyVerboseResponse` when `{ detailedResponse: true }` is passed to  `getTokenSilently`.

### What was the expected behavior?
For the return type of `getTokenSilently` to be refactored to only return a specific type or to accommodate both `string` and `GetTokenSilentlyVerboseResponse`.

### Environment

- **Version of `auth0-spa-js` used:*1.19.2*
- **Which browsers have you tested in? N/A
- **Which framework are you using, if applicable (Angular, React, etc): N/A
- **Other modules/plugins/libraries that might be involved: N/A

**Comment by stevehobbsdev** [comment]
Thanks for raising @camden-brown. Are you reporting an actual issue here?

The API isn't ideal and I would be looking to refactor this out when we do a new major version of the library. This was a compromise to satisfy a feature request whilst also providing backwards compatibility.

**Comment by camden-brown** [comment]
I just wanted to bring it to the team's attention. When updating to recent versions I just had to do some debugging to figure out how it was really suppose to work.

Low priority

**Comment by stevehobbsdev** [comment]
Thanks @camden-brown - it's on our list to improve :)
