### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by based64-eth** [auth0/auth0-spa-js#834]
### Describe the problem

Getting this error when doing `yarn install @auth0/auth0-spa-js` and the package fails to install:
![Screenshot](https://user-images.githubusercontent.com/90023181/140631921-6e561039-4d62-4e62-a943-75d1d9e47bd0.jpg)

### What was the expected behavior?

Package should install successfully.

### Reproduction

- Run `yarn add @auth0/auth0-spa-js`

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

No

### Environment

- **Version of `auth0-spa-js` used:** Latest
- **Which browsers have you tested in?** N/A
- **Which framework are you using, if applicable (Angular, React, etc):** N/A
- **Other modules/plugins/libraries that might be involved:** yarn

**Comment by frederikprijck** [comment]
Hi,

I tried installing our SDK using yarn and it works fine for me:

![image](https://user-images.githubusercontent.com/2146903/140707229-d1718cb5-08b7-40a0-b067-cb3de33e9e02.png)

Could it be the case that something else is causing this?
Could you try installing the SDK in a new folder?

Thanks.

**Comment by stevehobbsdev** [comment]
This doesn't appear to be a dependency of ours, running `yarn why Asaps` returns no results. The package is also not available [on NPM](https://npmjs.org/package/Asaps).

This looks to be something else within your app. Closing for now, but happy to continue the conversation if that turns out not to be the case.
