### ISSUE TITLE
If providing a nowProvider during client creation, the value/function is being encoded in calls to the /authorize endpoint

### ISSUE THREAD

**Issue by demvin** [auth0/auth0-spa-js#836]
### Describe the problem

The recently added nowProvider parameter to Auth0ClientOptions is wrongly being encoded and sent as a url query parameter to the /authorize endpoint.  If an Auth0 tenant is fronted by Akamai, then Akamai rejects/403s the request (possible attack detection).

The culprit seems to be the utils.ts::createQueryParams function receiving the nowProvider parameter from upstream and not filtering it out while building the /authorize url parameters.

### What was the expected behavior?

The value passed to nowProvider should not be sent as a url query parameter to the /authorize endpoint.

- **Version of `auth0-spa-js` used:**
- 1.19.2
- 
- **Which browsers have you tested in?**
- Edge, Chrome
- 
- **Which framework are you using, if applicable (Angular, React, etc):**
- SPA SDK
-

**Comment by stevehobbsdev** [comment]
Thanks for raising. Indeed, this should be filtered out. I'll raise a PR 👍
