### ISSUE TITLE
Configurable logout endpoint URL

### ISSUE THREAD

**Issue by yk-eukarya** [auth0/auth0-spa-js#845]
### Describe the problem you'd like to have solved

We are using this lib with another auth provider rather than the auth0, everything is is ok except the logout functionality, the problem is the logout endpoint URL `/v2/logout` is hard coded and we need to change it.

### Describe the ideal solution

Make the logout endpoint URL configurable instead of [hard coded one](https://github.com/auth0/auth0-spa-js/blob/5f4d2805523124c1dfe4cd85d5d65f9bcb1777e2/src/Auth0Client.ts#L976).

**Comment by stevehobbsdev** [comment]
@yk-eukarya can you let us know your use case? Not sure if it's intended but you have not left any information on this issue for us to work with or comment on.

We do not currently allow the logout URL to be configured as the library is designed to work with Auth0's endpoints, but curious to hear the reason as to why you raised this issue.

**Comment by yk-eukarya** [comment]
Our auth service provider provides the logout endpoint as `/api/logout` but the log out in this lib is `/v2/logout` so I could not make the logout functionality work. 
if the library provides a configurable logout endpoint that will be great

**Comment by stevehobbsdev** [comment]
Thanks for that context @yk-eukarya. As mentioned, we only support Auth0's endpoints with this library and so unfortunately we are unable to accommodate this request.
