### ISSUE TITLE
Add an option to return use id_token instead of access token

### ISSUE THREAD

**Issue by garfunkelvila** [auth0/auth0-spa-js#848]
https://github.com/auth0/auth0-spa-js/blob/0c6166c0f1dd7c8405b7231d0074c1eb0d8a164f/src/Auth0Client.ts#L884

I am a newbie with auth0 and I am not to sure where to report it. Because I am using angular and @auth0/auth0-angular. But, server do not like the value of `authResult.access_token` and it responded with `Could not verify JWT: JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 5)`. 

However the server likes the value of `authResult.id_token`

I am thinking of adding an option flag to use the id_token instead of the `access_token`

Currently I am using a custom http_interceptor instead of the AuthHttpInterceptor from `@auth0/auth0-angular`

But with that I can't use the AuthModule.forRoot > httpInterceptor.allowedList.uri. exposed by `@auth0/auth0-angular`

Or I am missing a thing in the documentations

**Comment by frederikprijck** [comment]
Hey,

Typically you shouldn't need to send the ID Token to any API, the ID Token is supposed to be used by the application (Angular in your case) only.

However, if u do need the ID Token, it is available as part of the `__raw ` claim, which u can retrieve by calling `getIdTokenClaims()` or use the `idTokenClaims$` observable in Angular.

That is the only way we are exposing the ID Token, as we believe it shouldn't be a common requirement we have no plans expose the ID Token in any other way.

Closing this, but happy to discuss further if you have any additional questions.
