### ISSUE TITLE
State check causes failing Cypress tests

### ISSUE THREAD

**Issue by Okyne** [auth0/auth0-spa-js#849]
### Describe the problem
I'm using auth0-spa for authentication purpose and I'm testing my application using Cypress. Until the last release `1.19.3` everything was fine, no issue concerning the login. I was running the `1.19.2` version. But since we upgraded to the latest version, all my automated tests are failing. The auth0-spa plugin does not handle redirect anymore. It seems to be an issue with the recently added state check.
Do you have any recommendations to bypass this check and get back my automated tests ?

### What was the expected behavior?
I use a password grant_type request to retrieve tokens and then I mock the response on /oauth/token. I visit the url : "mysite.com/?code=test-code&state=any-state" and I expect the handleRedirectCallback method to let me use the app as I have a valid token.

### Reproduction
The code I use is there.

```
   cy.request({
    method: 'POST',
    url,
    body: {
      grant_type: 'password',
      username,
      password,
      audience,
      scope,
      client_id,
      client_secret,
    },
  }).then(({ body }) => {
    const { access_token, expires_in, id_token, token_type } = body;
    const expireDate = Math.floor(Date.now() / 1000) + expires_in;

    cy.window().then((win) => {
      win.sessionStorage.setItem(
        `a0.spajs.txs.${client_id}`,
        JSON.stringify({
          code_verifier: 'any-code',
          appState,
          scope,
          audience,
          redirect_uri: baseUrl,
        })
      );
      win.sessionStorage.setItem(
        `a0.spajs.txs`,
        JSON.stringify({
          code_verifier: 'any-code',
          appState,
          scope,
          audience,
          redirect_uri: baseUrl,
        })
      );
      win.localStorage.setItem(
        `@@auth0spajs@@::${client_id}::${audience}::${scope}`, // Could also be ::default:: instead of ::${audience}::
        JSON.stringify({
          body: {
            client_id,
            access_token,
            id_token,
            scope,
            expires_in,
            token_type,
            decodedToken: { user: JSON.parse(Buffer.from(id_token.split('.')[1], 'base64').toString('ascii')) },
            audience,
          },
          expiresAt: expireDate,
        })
      );

      cy.intercept('POST', '/oauth/token', {
        body: {
          access_token,
          id_token,
          scope,
          expires_in,
          token_type,
        },
      });
    });

    cy.visit(`${visitUrl}/?code=test-code&state=any-state`);
  });
```

### Environment
- **Version of `auth0-spa-js` used:**
  - @auth0/auth0-spa-js: 1.19.3

- **Which browsers have you tested in?**
- **Which framework are you using, if applicable (Angular, React, etc):**
  - React
- **Other modules/plugins/libraries that might be involved:**
   - cypress: 8.7.0

**Comment by stevehobbsdev** [comment]
You just need to store the state value inside your transaction data in a `state` property, as this is what is compared when handling the redirect.

Can you try this and let me know how you get on?

Having said that, the code is supposed to be resilient to the fact that there might not be any state in the transaction (for backwards compatibility), so I'm curious as to why this is breaking.

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you need further support.
