### ISSUE TITLE
Wrong getTokenSilently return type depending on cache state

### ISSUE THREAD

**Issue by yeiniel** [auth0/auth0-spa-js#857]
### Describe the problem

if Auth0Client.getTokenSilently() is called with { detailedResponse: true } first and later called without argument at that time an object is returned instead of a string. This is a bug according with the definition of the method in typescript. This is due to the fact that the cached value for the token depends on the argument of the function the first time is called.

### What was the expected behavior?

Auth0Client.getTokenSilently() return a string or an object based on the request argument for that call and not the argument of the first call made after the user authenticate is complete.

### Reproduction

- Create an instance of Auth0Client
- Authenticate user
- call auth0Client.getTokenSilently({ detailedResponse: true });
- call auth0Client.getTokenSilently() without arguments, expected response should be string but actually is of type object

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

Not sure, never programmed using Vue before

### Environment

- **Version of `auth0-spa-js` used:** 1.19.2, but from what i can see in master in the repo it appears the bug is in there yet https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L829
- **Which browsers have you tested in?** Google Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** Angular
- **Other modules/plugins/libraries that might be involved:** @auth0/auth0-angular

**Comment by yeiniel** [comment]
@auth0/auth0-angular is impacted by this bug at this line https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.interceptor.ts#L97 . If https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.service.ts#L200 is called before a protected API endpoint is requested.

**Comment by stevehobbsdev** [comment]
👋🏻  Thanks for your patience here.

I'm unable to reproduce what you're seeing using the steps provided, are you able to provide a small repro that shows the issue?

Can you let me know what type of cache you're using (the in-memory default, or local storage)?

To show how I repro'd this, please checkout the [test/857 branch](https://github.com/auth0/auth0-spa-js/tree/test/857). I [added a test](https://github.com/auth0/auth0-spa-js/blob/013bd7a01bd1c93d72d76fe48f7e5a31d45a8534/__tests__/Auth0Client/getTokenSilently.test.ts#L1803-L1835), which passes. I also added a button into the playround that you can test yourself by following these steps:

* Clone this repo locally
* Run `npm install` then `npm start`
* Open a browser at `http://localhost:3000`
* Click "Login with Redirect", and log in using some credentials, or sign up
* When you're back at the playground, click "Login Redirect Callback" at the top
* Then, open your developer tools console and press "Get Access Token (test)", which then [calls `getTokenSilently` twice](https://github.com/auth0/auth0-spa-js/blob/013bd7a01bd1c93d72d76fe48f7e5a31d45a8534/static/index.html#L740-L748) - first to get the detailed response, then again to get a string value. You should see those being output in the console.

Please let me know if you're seeing anything different.

**Comment by yeiniel** [comment]
thank you for taking the time to look into this. i will check the playground and test case and come back to you once i have an answer

**Comment by yeiniel** [comment]
Well this is embarrassing. I downloaded the playground but was unable to reproduce the bug there. Additionally i created a project from scratch with minimal dependencies and i can't reproduce the bug there either. But i still can reproduce the bug on another repository with a lot of dependencies. So, weird. Feel free to close this issue. I will continue researching my problem, but probably is not related to the `getTokenSilently` method.

**Comment by stevehobbsdev** [comment]
Let us know if you find anything further that we need to look into.

**Comment by rrjohnson85** [comment]
@stevehobbsdev  FWIW, I'm able to see the same behavior using the Angular library when multiple calls to `getTokenSilently` happen at roughly the same time but with different arguments.  Could this be due to the `singlePromise` key not taking the detailedResponse argument into consideration?

**Comment by ryanashcraft** [comment]
> @stevehobbsdev FWIW, I'm able to see the same behavior using the Angular library when multiple calls to `getTokenSilently` happen at roughly the same time but with different arguments. Could this be due to the `singlePromise` key not taking the detailedResponse argument into consideration?
> 
> EDIT: I see the same behavior with the AuthService and Auth0Client exported from the Angular library. I'm using Angular v1.8.2 and SPA v1.19.3.

I also have observed this behavior and have had to implement a nasty workaround as a temporary fix (retry with polling).

I agree the [singlePromise key in getTokenSilently](https://github.com/auth0/auth0-spa-js/blob/842e132bec718867026c99c76a27f810083258d6/src/Auth0Client.ts#L860-L866) looks suspicious. Shouldn't `this.options.detailedResponse` be a part of that key on line 866? cc @stevehobbsdev

**Comment by frederikprijck** [comment]
Any chance you can provide something for us to reproduce this? 

For the key, i am not sure i see why it should be part of it. Can you elaborate on why you think so ?

**Comment by frederikprijck** [comment]
Actually, having looked at it some more I think I see what you mean. I don't think it should be part of the key, but I think I can see how it can use the wrong return type.

Re-opening this while I look into this.

**Comment by frederikprijck** [comment]
Thanks for reporting this, I added a PR to address this. Would appreciate if you could take a look and see if you think it would work for you as well.

**Comment by ryanashcraft** [comment]
@frederikprijck Thank you for investigating and submitting a patch!
