### ISSUE TITLE
Bundle size of auth0-spa-js is large

### ISSUE THREAD

**Issue by LucasLemanowicz** [auth0/auth0-spa-js#859]
### Describe the problem

I am using the auth0-react library, and it is by far the largest package in my front end JS bundle (sitting at 100kb / 31kb gzipped):

<img width="554" alt="Screen Shot 2022-01-09 at 5 03 45 PM" src="https://user-images.githubusercontent.com/361348/148830920-660123bb-3d43-4350-87a0-fe31e2c7c82f.png">

I filed a ticket there which was closed (https://github.com/auth0/auth0-react/issues/316) and explained that 80% of the size comes from auth0-spa-js. It seems like there's also been several tickets here over the last couple of years asking similar things with promises that a fix was eventually coming:

- https://github.com/auth0/auth0-spa-js/issues/627
- https://github.com/auth0/auth0-spa-js/issues/608

Has there been any updates on this since last year, or at least estimates (days? weeks? months? years?) on when this will be addressed?

Thanks,

### What was the expected behavior?

It would be nice to have a smaller bundle size

### Reproduction

1. Import the auth0-spa-js library into your project
2. Run your favorite bundle analyzer

### Environment

- **Version of `auth0-spa-js` used:** `"@auth0/auth0-react": "^1.8.0"` (`"@auth0/auth0-spa-js" "^1.18.0"`)
- **Which browsers have you tested in?** browser agnostic
- **Which framework are you using, if applicable (Angular, React, etc):** NextJS 12, React 17, Typescript 4.3
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Thanks for raising @LucasLemanowicz. You're right, it is large and we still have it on the roadmap to improve. In November I had [put some effort towards being able to put a slimmer, more modern build together](https://github.com/auth0/auth0-spa-js/tree/feat/modern-build) that didn't include all the polyfills and whatnot but it unfortunately succumbed to other priorities. However, I will reignite these efforts and work towards a resolution. I can't give an exact estimate but at this point I would say hopefully in the realm of weeks, pending further investigation.

Please stay tuned on the PRs coming through and I will endeavour to report back here once we've made progress.

**Comment by divmgl** [comment]
I removed the polyfills and the bundle size decreased by about 50kb. There's probably more that can be done.

https://github.com/auth0/auth0-spa-js/issues/627#issuecomment-1093621867
