### ISSUE TITLE
Logout request being cancelled by browser

### ISSUE THREAD

**Issue by muralimaddu** [auth0/auth0-spa-js#866]
I'm testing a scenario my application needs that is when auth server throws unauthorized error redirect to unauthorized page.

I added below snippet in app.component.ts constructor in my Angular app, I'm able to capture the error thrown by auth server and logout is being triggered but observed that logout request is being cancelled by browser,

```ts
this.auth.error$.subscribe((err) => {
      if (err instanceof GenericError) {
        if (err.error === 'login_required') {
          this.auth.getAccessTokenSilently({
            redirect_uri: location.origin + '/authentication',
          });
        } else if (err.error === this.unauthorized) {
          this.auth.logout({
            returnTo: location.origin + '/' + this.unauthorized,
          });
        }
      }
    });
  }
 ```
![image](https://user-images.githubusercontent.com/95929070/150323118-8474af59-4c4f-424f-8999-a012bc952e62.png)

Could anyone tell me why this is happening?

**Comment by frederikprijck** [comment]
Could you expand the screenshot a bit so that it shows what is happening after the logout request is getting cancelled?

Thanks

**Comment by muralimaddu** [comment]
ok, I'll raise it there.

Thanks.
