### ISSUE TITLE
Allow timeout in handleRedirectCallback to be configurable

### ISSUE THREAD

**Issue by henrymunro** [auth0/auth0-spa-js#871]
### Describe the problem you'd like to have solved

We are using the `@auth0/auth0-react` package and are seeing quite a few `Timeout when executing 'fetch'` errors when the `handleRedirectCallback` is being called. We operate in some areas in Kenya and Ghana where network connectivity can be very patchy, it's not unheard of our users being degraded to slow 2G for periods of time.

In the `handleRedirectCallback` call to [oauthToken](https://github.com/auth0/auth0-spa-js/blob/d21736f10ba79f354e9aec52e0d5c6562a3ef049/src/Auth0Client.ts#L689) I think were hitting the [default 10s timeout](https://github.com/auth0/auth0-spa-js/blob/4641135d0eb06ef5d96d10d38672dbe4477d98f1/src/http.ts#L77
). As far as I can tell we have no way to configure the timeout to extent it.

This is especially annoying because the user isn't able to refresh to try again, because the [state has been removed](https://github.com/auth0/auth0-spa-js/blob/d21736f10ba79f354e9aec52e0d5c6562a3ef049/src/Auth0Client.ts#L653) meaning they are hit with a [Invalid State error](https://github.com/auth0/auth0-spa-js/blob/d21736f10ba79f354e9aec52e0d5c6562a3ef049/src/Auth0Client.ts#L669) if they do. 

When our users hit this error we have to direct them back to our hosted auth0 login screen and get them to input their details again.

### Describe the ideal solution

Ideally we'd be able to pass a timeout to the [oauthToken](https://github.com/auth0/auth0-spa-js/blob/d21736f10ba79f354e9aec52e0d5c6562a3ef049/src/Auth0Client.ts#L689) call in `handleRedirectCallback` so we can set it to a value longer than 10s.

I don't know if it would be problematic but It might also be useful if the state wasn't removed until after the `oauthToken` call had successfully run.

## Alternatives and current work-arounds

We're a bit stuck really, best I can see is get the users to log back in and hope their network is better.

**Comment by stevehobbsdev** [comment]
Thanks for this @henrymunro, I think it's a fair request. I've added it to our internal backlog, where we have a number of feature requests to go through and will be triaging these shortly. Will keep you posted.
