### ISSUE TITLE
iFrame to refresh token is blocked by cross-origin isolated policy

### ISSUE THREAD

**Issue by duvet86** [auth0/auth0-spa-js#872]
### Describe the problem you'd like to have solved
Currently the `_getTokenFromIFrame ` method uses an iFrame to refresh the token. The iFrame is blocked by cross-origin isolated policy.
Update the iFrame to support cross-origin isolated policy.
See: https://web.dev/coop-coep/

### Describe the ideal solution
Ideal solution is to handle cross-origin isolated policy.

## Alternatives and current work-arounds
Workaround is to change the cache location to localStorage.

### Additional context
![image](https://user-images.githubusercontent.com/5604548/151728992-8d80f13b-0c9f-400f-91d0-4cd6e7c2c4a3.png)

![image](https://user-images.githubusercontent.com/5604548/151727217-f390b409-a087-49eb-8d0d-eae6c67c7cc9.png)

**Comment by duvet86** [comment]
Please disregard. I had updated helmet js to the latest version and it now enforces cors isoled policy.
Reverting helmet to the previous version fixed the issue.

**Comment by dabernathy89** [comment]
Can we re-open this ticket? This feature is essentially required to use wasm packages that use SharedArrayBuffer while maintaining a seamless login experience.
