### ISSUE TITLE
Make raw id_token available for consumers

### ISSUE THREAD

**Issue by Lonli-Lokli** [auth0/auth0-spa-js#878]
### Describe the problem you'd like to have solved

I need to get access to raw id_token, in order to send it as Bearer token to API. Right now its not possible as it's store as private field in CacheManager which is not exported either as type or as accessable property.

### Describe the ideal solution

Have an ability to get raw id_token

**Comment by Lonli-Lokli** [comment]
@frederikprijck Let me explain scenario when IdToken is required.

Assume we have role based auth on API, eg we assume that different users has different groups on IdP side, which are mapped internally on API side to different role inside API. So with IdToken we can extract their roles from IdToken and also validate token itself with IdP.

This scenario can be changed with access token itself via call to Introspect endpoint but - surprise - Auth0 do not expose such endpoint for no reason.

Thanks for your hint, anyway

**Comment by frederikprijck** [comment]
@Lonli-Lokli With Auth0 you can use a custom Action to set the roles in the access token by copying them from the id token. Something along the lines of:

```
exports.onExecutePostLogin = async (event, api) => {
  const claimName = 'roles';
  if (event.authorization) {
    const roles = event.authorization.roles;
    api.accessToken.setCustomClaim(`${claimName}`, roles);
  }
};
```
The above should give you an idea, but is probably not exactly what you need as I haven't tried it out.

Some more info regarding this:
- https://auth0.com/docs/customize/actions
- https://auth0.com/docs/customize/actions/flows-and-triggers/login-flow
- https://auth0.com/docs/get-started/apis/scopes/sample-use-cases-scopes-and-claims#add-custom-claims-to-a-token

**Comment by Lonli-Lokli** [comment]
@frederikprijck thanks I am aware of this, just don't think it's a good idea put business logic into auth provider
