### ISSUE TITLE
Cache gets called with undefined key

### ISSUE THREAD

**Issue by ntziolis** [auth0/auth0-spa-js#879]
We have implemented the `ICache` interface based on the local storage version. The issue we ran into was that:
- At some point during the initialization the library makes a call to `cache.get` with `undefined` as a key value
- While the local storage handles this gracefully
- Our backing store threw an exception

It took us quite a while to track this down, while the eventual fix was easy. To prevent others from falling into this we propose to either:
- Ensure that `cache.get` does not get called with `undefined` as a key
- Or that the `ICache.get` interface is updated to be more explicit `get<T = Cacheable>(key: string | undefined): MaybePromise<T | null>; `  
Instead of:
https://github.com/auth0/auth0-spa-js/blob/4641135d0eb06ef5d96d10d38672dbe4477d98f1/src/cache/shared.ts#L89

**Comment by stevehobbsdev** [comment]
Thanks, I will take a look. I don't believe sending a key of `undefined` is the correct behaviour.

> while the eventual fix was easy

Was this a fix within your own app or did you identify a fix within the SDK? Did you happen to notice in your debugging how a key of `undefined` could have been sent?

**Comment by ntziolis** [comment]
The fix was input implementation of the interface. We simply did the following in the get method:
```
if(!key) return;
```

We did not spend too much time figuring out why undefined was being sent.

But it does happen after `allkeys` is called. And when all keys returns `[]`.

We know this because:
- Initially we thought all keys might need to return undefined when there are no keys
- This in fact fix the issue and get was not called with undefined as key at all
- But we felt Ensuring that they get method would not fail was a more stable approach

**Comment by stevehobbsdev** [comment]
Looks like we can solve this by guarding the `cache.get` call here: https://github.com/auth0/auth0-spa-js/blob/451956f5615bdd7e8fe3c313dbe30d1e31b855f1/src/cache/cache-manager.ts#L36

It just doesn't take into account that the key might be undefined. I'll raise a PR 👍🏻 

Thanks for bringing this to our attention!
