### ISSUE TITLE
Option to override cookie domain

### ISSUE THREAD

**Issue by Soviut** [auth0/auth0-spa-js#884]
Originally posted here on the `auth0-vue` project.  https://github.com/auth0/auth0-vue/issues/90

### Describe the problem you'd like to have solved

We have multiple apps, each on their own subdomain. We want users to be able to sign in on any of these subdomains and remain signed in when visiting the other subdomains.

Currently, a cookie is created with a domain that includes the subdomain. This is too specific;  the cookie will only exist on that subdomain and none of the others. In order for the cookie to span multiple subdomains it must be written as `domain=.site.com`.

### Describe the ideal solution

Ideally, I would be able to set a `cookieDomain` as part of the `createAuth0` client options. This could be passed as [`ClientStorageOption`](https://github.com/auth0/auth0-spa-js/blob/50159871db2dd27329ef7df6d87ca31a85d048d3/src/storage.ts#L3) to the [`CookieStorage.save()`](https://github.com/auth0/auth0-spa-js/blob/50159871db2dd27329ef7df6d87ca31a85d048d3/src/storage.ts#L30) method.  There the domain can be added to the `cookieAttributes` when the cookie is created.

This would allow a top level domain cookie to be created with all the correct attributes, including the correct expiry date, that is accessible across multiple subdomains.

## Alternatives and current work-arounds

Currently, I use a hacky work around that involves performing the `handleRedirectCallback()` manually on my callback page. I then create a cookie with the same name but the desired top level domain.

```
auth0.<clientid>.is.authenticated=true;domain=.site.com;path=/;expires=${date};
```

This leaves me with 3 cookies; the real auth0 cookie, the legacy auth0 cookie and my top level domain cookie.

When I visit another subdomain where I haven't explicitly logged in, the top level domain cookie is present and the auth0 SDK recognizes it, assumes its logged in, and performs a `checkSession`, creating the auth0 and auth0 legacy cookies in the process.

On log out I have to remember to remove the top level cookie before calling `auth0.logout()`.

Having to manually keep track of extra cookies when logging in and out is not ideal. I have to manually set the expiry date based on what's set in the Auth0 tenant configurations.

**Comment by stevehobbsdev** [comment]
Thanks for raising this PR. In general I think it's a useful feature, I will review this week and provide feedback 👍🏻

**Comment by Dannnir** [comment]
@Soviut Thank you for this one!!!
Can you please check why the domain doesn’t take effect for the organization_hint cookie?

**Comment by Soviut** [comment]
@Dannnir You should probably open a new issue for that. I haven't worked with organizations in auth0.
