### ISSUE TITLE
Unable to login through loginWithRedirect

### ISSUE THREAD

**Issue by tiwarivijay123** [auth0/auth0-spa-js#887]
### Problem

I have some issues in this SDK https://auth0.com/docs/libraries/auth0-single-page-app-sdk , when trying to use loginWithRedirect it is not staying user logged in , it is taking user back to onboard page.

while loginWithPopup works well.

**Comment by jlaasonen** [comment]
Is your browser blocking cross-site cookies? I have noticed that blocking them causes issues with Auth0.

**Comment by tiwarivijay123** [comment]
```
import { Auth0Client } from '@auth0/auth0-spa-js';
let auth0Client: Auth0Client | null = null;

 useEffect(() => {
    const initialize = async () => {
      try {
        auth0Client = new Auth0Client({
          client_id: '',
          domain: '',
          redirect_uri: window.location.origin,
          audience: '',
        });

        await auth0Client.checkSession();

        const isAuthenticated = await auth0Client.isAuthenticated();

        if (isAuthenticated) {
          const user = await auth0Client.getUser();       
        } else {
          dispatch({
            type: Types.init,
            payload: { isAuthenticated, user: null },
          });
        }
      } catch (err) {
        console.error(err, 'erorr');
        dispatch({
          type: Types.init,
          payload: { isAuthenticated: false, user: null },
        });
      }
    };
    initialize();
  }, []);
  const login = async () => {
try {
      await auth0Client?.loginWithRedirect();
    } catch (error) {
    }
      const isAuthenticated = await auth0Client?.isAuthenticated();
      const user = await auth0Client.getUser();
      console.log(user, isAuthenticated, 'auth response');
      if (isAuthenticated) {
        const user = await auth0Client?.getUser();
        const accessToken = await auth0Client.getTokenSilently();
        const userInfo = await getUserInfo(user, isAuthenticated);
        dispatch({ type: Types.login, payload: { user: user || null } });
      } 
}
```
Basically my code structure is like this , in this code if I'm using loginWithPopUp works well instead of loginWithRedirect please have a look into this and let me know where I'm wrong.

thank you.

**Comment by frederikprijck** [comment]
Can you please elaborate on what isn't working here? Sharing code without elaborating on what is or isn't working makes debugging less ideal from our side.

**Comment by tiwarivijay123** [comment]
Hey @frederikprijck I visited to this side https://github.com/auth0/auth0-react but my project is in next not in react that's why I'm using this one https://github.com/auth0/auth0-spa-js. this SDK works well only I have issues with loginWithRedirect loginWithPopup works well.

**Comment by frederikprijck** [comment]
For next, we have https://github.com/auth0/nextjs-auth0. You can even combine that one with auth0-react if needed in a Next application.

**Comment by tiwarivijay123** [comment]
https://github.com/auth0/auth0-spa-js this one is not ok to use  ?

**Comment by frederikprijck** [comment]
That isn't an SDK we recommend for next applications no. In next we try and stick with cookies, while this isn't what SPA-JS does (neither what Auth0-React does).

I would advise looking into our SDK for next applications and take it from there. Using SPA-JS is pretty low-level and complicates things when we have an SDK available tailored specifically for Next or React.

Our SDK for React is built on top of SPA-JS, so it makes little sense to use SPA-JS in favor of https://github.com/auth0/auth0-react.
However, for next I really recommend using https://github.com/auth0/nextjs-auth0 instead.

**Comment by stevehobbsdev** [comment]
Closing for now as this has been answered, feel free to continue the discussion though @tiwarivijay123 if you need further support.
