### ISSUE TITLE
Make authorize & oauth/token url configurable

### ISSUE THREAD

**Issue by nkashyap** [auth0/auth0-spa-js#890]
### Describe the problem you'd like to have solved

Currently `/authorize` and `oauth/token` are hard coded, It would be nice to make it configurable to work with alternative.

### Describe the ideal solution

Add new config options `authorizationUrl`, `tokenUrl`

**Comment by frederikprijck** [comment]
It's important to know that our SDK is only supposed to be used with Auth0. 
Apart from the URLs being mentioned, there are other things internally to the SDK that make it probably not a good idea to use with anything other than Auth0.

Therefore, we aren't really considering making these endpoints configurable, as they are not expected to change when using Auth0.
