### ISSUE TITLE
handleRedirectCallback strips `=` from returned base64 state.

### ISSUE THREAD

**Issue by jrmoretti** [auth0/auth0-spa-js#892]
When using [handleRedirectCallback](https://auth0.github.io/auth0-spa-js/classes/auth0client.html#handleredirectcallback) to validate the `code_verifier` and `state`, the `parseQueryResult` maps query strings to the their respective key/value pair, but because it splits on `=`, a `state` that is base64 encoded fails to validate against the state retrieved by the `transactionManager`, resulting in an `invalid state` error.

### What was the expected behavior?

`handleRedirectCallback` should be able to match base64 encoded states.

### Reproduction

```
const client = new Auth0Client({
      "audience": "default",
       "client_id": "<REMOVED>",
       "domain": "<REMOVED>",
       "redirect_uri": "http://localhost:3000"
});


if(isRedirect){
   client.loginWithRedirect().catch((e) => {console.log(e);});
} else {
   await client.handleRedirectCallback();
}
```
Redirect result: `/?code=z5e4uzqa5iui1bx225gde5rc&state=ZVF6QXdLWkJZbGhBd095VFR3dDFtSllQWFVWU2xwTDM0SDJ4SDFzZmtKbA==`

Stored state: 
```
{
    "nonce": "NXpHZ2NXd2U4UklYY19KUVpDV19wRW5LSS04SUlzUXpwcmJ1ZzRKTzR1UQ==",
    "code_verifier": "Ngsv9K-XoqQiJ3gSJ7R~Mer68b4SNMc-kX2OF03Y35_",
    "scope": "openid profile email offline_access",
    "audience": "default",
    "redirect_uri": "http://localhost:3000",
    "state": "ZVF6QXdLWkJZbGhBd095VFR3dDFtSllQWFVWU2xwTDM0SDJ4SDFzZmtKbA=="
}
```

State from query string:
![image](https://user-images.githubusercontent.com/330917/161298675-da15a9af-a4b6-447b-85fa-d9198cfdd2fa.png)

Actual code:
https://gist.github.com/jrmoretti/0abb0f923237d50f739ac6b12246120b

### Environment
"@auth0/auth0-spa-js": "^1.20.1",
Chrome,
No Frameworks.
No other modules/plugins involved

**Comment by adamjmcgrath** [comment]
Hi @jrmoretti - thanks for raising this

This SDK expects the state to be url encoded per https://openid.net/specs/openid-connect-core-1_0.html#AuthResponse

Do you know how are you arriving at your callback url with unencoded state parameters?

**Comment by jrmoretti** [comment]
@adamjmcgrath thanks for the quick reply. 
The resulting url is the result of an Okta PKCE flow.

**Comment by adamjmcgrath** [comment]
np @jrmoretti 

This SDK is only compatible with Auth0 I'm afraid. There's a bunch of things that wont work if you try and point it to other Identity Providers.

Have a look at https://developer.okta.com/code/javascript/ for tools to get your SPA setup with Okta

**Comment by jrmoretti** [comment]
@adamjmcgrath I would use the Okta lib if it worked with this. 
It's controlled by a 3rd party vendor and they have their own auth0 compatible flow. 
This code base I landed on is using a forked version of auth0-spa-js and I'm trying to remove that insecure dependency. 

The fix for this would be as simple as this:
https://jsbin.com/woyelizedi/edit?js,console 
( I can make that PR if you're ok with that)

**Comment by adamjmcgrath** [comment]
ok @jrmoretti - unfortunately we can't support this use case

I suggest you either fork the current version of this repo or get your auth0 compatible Identity Provider to encode the parameters in the auth response

**Comment by jrmoretti** [comment]
@adamjmcgrath thanks!
