### ISSUE TITLE
Question: refresh token call and custom rules

### ISSUE THREAD

**Issue by emanuellarini** [auth0/auth0-spa-js#896]
From what I read in the code (and correct if i'm wrong here), while refreshing tokens I saw that the oauth call doesn't send the `scopes` and `audience`.

is it intended to not send these values while refreshing a token?

I have a situation where I have custom rules set in auth0 and not sending these values break the rule.

What should I do in this case? 

Thank you.

**Comment by stevehobbsdev** [comment]
Thanks for your patience here. Today the SDK does not send those values when sending a `refresh_token` grant. From an OAuth perspective, the only reason you would send `scope` in particular is when you want to **descope** an access token. This is a use case that the SDK does not support today but are looking into for future improvement.

For your scenario, where you want access to these values in a Rule to run your own custom logic, you're better just putting these values into a custom parameter that you can then pick up inside a rule. That way they don't interfere with the OAuth flow while still being able to participate in your own custom logic. You can do this just by specifying your custom props to `getTokenSilently`:

```js
await client.getTokenSilently({
  customProp1: 'hello',
  customProp2: 'world'
});
```

Let me know if that helps!

**Comment by emanuellarini** [comment]
But what should I do with the custom rules? My rules kind of expect the scopes to be sent because we're adding some information to the token

**Comment by emanuellarini** [comment]
I see. That can help for now. I could help you and make a PR allowing to pass both audience and scope in refresh calls if you need. I'm very interested in this feature.

Btw, if I send something like:

```
await client.getTokenSilently({
  myAppScopes: 'app:X app:Y app:Z domain:XXX',
});
```

I'm also worried about the audience as well. Is there any way to get help for my case? I can't share here the rules I have but I'd love to get a closer help on this if you can.

Thank you!

**Comment by stevehobbsdev** [comment]
@emanuellarini Do you already have paid support with Auth0? As I am getting requests internally to look into this, but normally if that's the case this would go through our dedicated support team where you would be able to get a deeper look into your case.

> if I send something like this and use the myAppScopes instead of scope, would it be fine?

Yes - as it's a custom property, you're able to retrieve that in a rule and do as you wish.

> I could help you and make a PR allowing to pass both audience and scope in refresh calls if you need

This is something we're already looking into internally as it will require some careful looking at how the cache is managed, as both the scope and audience are a factor in how our data is cached. It's not something to be taken lightly.

However, as long as the use case is simply passing scopes to a rule, I'm afraid that's not something we're looking at supporting when we talk about passing scopes to the token endpoint. The only way we'd do this is to support the use case of descoping an access token.

**Comment by emanuellarini** [comment]
If i use a second property to get scopes, won't it break the caching of tokens?

I'm thinking if it won't cause unwanted side effects.

Tbh I'd rather fork your repo and add the scopes and audience to token refresh calls. it doesn't seem to be difficult. 

What are the possible side effects of passing the scopes and audience to refresh calls? 

Also, how does the auth0 works when refreshing and generating a new access token if it doesn't have the scopes sent?? Does it creates an empty scoped token? I mean, after refresh it looses all added scopes? Kinda weird, no?

**Comment by stevehobbsdev** [comment]
> I do have paid subscription plan. Been using auth0 for 2-3 years.

Great! I think that would come with some support time so I would reach out to the person who is handling your account if you require a deeper look at your specific case. They've already been in touch internally.

> If i use a second property to get scopes, won't it break the caching of tokens?

No, if it's a custom property then the SDK won't assume anything about it or use it to cache tokens. It mainly uses `clientId`, `scope` and `audience` to do this. If you had another property called something like `myScopes` then that won't affect the token caching.

> Tbh I'd rather fork your repo and add the scopes and audience to token refresh calls. it doesn't seem to be difficult.

All good, you just might run into issues with cache retrieval and getting the right access token given your scope and audience, these are edge cases that we've yet to take a deep look into.

> What are the possible side effects of passing the scopes and audience to refresh calls? Also, how does the auth0 works when refreshing and generating a new access token if it doesn't have the scopes sent??

I touched on this earlier but the only reason to send the `scope` parameter to the token refresh endpoint is if you want to __descope__ the access token (i.e. remove scopes from it). The [refresh token is bound to the scope and audience](https://datatracker.ietf.org/doc/html/rfc6749#section-1.5) that were supplied on the initial `/authorize` call, so you cannot add new scopes (they will just be ignored and will not appear in the resulting access token), and sending the same scopes will have no effect. In fact, sending additional scopes not originally requested on the `/authorize` endpoint when the user logs in is [explicitly prohibited by the specification](https://datatracker.ietf.org/doc/html/rfc6749#page-47); in our case, we ignore them.

However, the scopes you send _may_ be accessible in a rule, but I haven't tried this myself. This is where you might see some undesirable side effects - your primary intention here is to send scopes to a rule but you might inadvertently affect the access token if you send a subset of the scopes it already has, as then the access token will become descoped. Hence using a custom property here is best as you are separating those two cases.

So if you don't send _any_ scopes (this is what the SDK does today) then the access token will contain the same scopes and audience as when the user first logged in and got an access token.

If you want to completely change scopes and/or audience, the user must log in again.

Does that help?

**Comment by stevehobbsdev** [comment]
I'll close this for now as I don't think there's anything actionable here for the SDK, but more than happy to continue the conversation.

**Comment by rwbarber2** [comment]
@stevehobbsdev For reference, there is a support ticket (00746381) on this and it *is* directly related to refresh tokens and rules.  When a rule is executed for a refresh token the rule does not get passed the original scopes (nor audience) and that is the root of our problem.  Our rule adds both authorizations (scopes)and claims to the token which are dependent upon the scopes passed in among other things.

It does not seem like refresh tokens and rules work together so we will get together internally to discuss.

Thank you!
