### ISSUE TITLE
How to customize logout url

### ISSUE THREAD

**Issue by superbull** [auth0/auth0-spa-js#897]
Our company uses a combination of Auth0 & Azure AD for our SSO.
In order to logout completely from main-tenant and sub-tenant, we need to call a **special logout URL**.

I found the logout URL is built from this method, it seems not easy to hook into this and replace it with our special URL.
https://github.com/auth0/auth0-spa-js/blob/0ae6078c02d3a4184147e788adfceae4db78db65/src/Auth0Client.ts#L1045

Do you have some advice how to do that?
We use [auth0-react](https://github.com/auth0/auth0-react) in our project.

**Comment by frederikprijck** [comment]
Thanks, our SDK is made to be used only with Auth0. As our logout URL on the server-side is fixed, our SDK does not allow for this to be configurable.

APart from the logout URL, there are other internals that may or may not work with other providers, so we don't recommend doing this.

**Comment by stevehobbsdev** [comment]
While this isn't really a supported use case, you could achieve what you want by disabling the logout redirect using `localOnly`:

```js
client.logout({ localOnly: true });

// perform your own redirect here or use:
const logoutUrl = client.buildLogoutUrl();
window.location.href = logoutUrl;
```

`localOnly` clears out internal state but doesn't perform the redirect to the logout endpoint in the browser, so you're able to handle that as you wish.
