### ISSUE TITLE
Seperate hostname and endpoint path for token endpoint

### ISSUE THREAD

**Issue by TobiSW** [auth0/auth0-spa-js#904]
### Describe the problem you'd like to have solved

In order to access the authorization endpoint of my oauth server i need to set the domain options to something like that: 
> Given the following authorization endpoint: https://{host}/oauth/authorize
> The token endpoint is located here: https://{host}/oauth/token
```
const auth0 = await createAuth0Client({
  domain: 'https://{host}/oauth',
  client_id: 'YOUR_CLIENT_ID'
});
```
After i trigger the loginWithRedirect method everything is working fine so far until it tries to call the token endpoint. It seems that it is a hardcoded concatenated string which is created out of the domain options:
```
'${baseUrl}/oauth/token'
```
My problem now is that it is trying to access the token endpoint like this
```
https://{host}/oauth/oauth/token
```
### Describe the ideal solution

Handle hostname and a endpoint path seperateley. Maybe add additional options?
```
const auth0 = await createAuth0Client({
  domain: 'https://{host}',
  token_endpoint_path: '/oauth/token'
  client_id: 'YOUR_CLIENT_ID'
  ...
});
```

### Additional context

- Version: 1.21.1
- Which browsers have you tested in: Chromium Version 101.0.4951.54 
- Other modules/plugins/libraries that might be involved: auth0/auth0-vue 1.0.1

**Comment by frederikprijck** [comment]
Thanks for reaching out!

Can you elaborate what you are trying to achieve? Our SDK is designed to work with Auth0, not with other Identity Providers, so making the URL configurable like you are trying shouldn't be needed to integrate Auth0.

Are you perhaps trying to use a different Identity Provider here ?

**Comment by TobiSW** [comment]
Thank you for your reply! Okay understood, yes i tried to use it with an different identity provider.

**Comment by stevehobbsdev** [comment]
Thanks for raising this @TobiSW . We cannot accommodate this request, so I'll close this issue for now.
