### ISSUE TITLE
In-memory (default) storage cannot be used with reasonably strict CSP

### ISSUE THREAD

**Issue by robbytx** [auth0/auth0-spa-js#915]
### Describe the problem

Using the default configuration (where `cacheLocation` defaults to `memory`), the Auth0Client attempts to load a Web Worker using a Blob URI constructed with a static payload.  

However, if the application is served from a domain with a reasonably strict CSP (i.e. where `script-src` contains `'self'`, other trusted origins (`localhost:4200`), and possibly some `'sha256-...'` hashes), then the attempt to load the Web Worker will yield a CSP violation such as:
> Refused to create a worker from `'blob:http://localhost:4200/751ba39b-d811-48d1-9e11-6155af130329'` because it violates the following Content Security Policy directive: `"script-src 'self' 'sha256-...' localhost:4200"`. Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

Unless the policy was served via `Content-Security-Policy-Report-Only`, then this will also throw the following exception from the Auth0Client constructor:
> Uncaught DOMException: Failed to construct 'Worker': Access to the script at 'blob:http://localhost:4200/751ba39b-d811-48d1-9e11-6155af130329' is denied by the document's Content Security Policy.

Ideally one would be able to update the CSP to allow the worker to load, as can be done using `sha256-...` for static inline scripts.  However, this is apparently not possible for Blob URIs -- the only recourse is to allow `blob:` in `script-src` or `worker-src`, which allows blobs of any provenance and is effectively the equivalent of `unsafe-inline`, thereby **defeating the purpose of CSP** in the first place.

### What was the expected behavior?

The SDK should provide some affordance for loading the Web Worker from a static URL, ideally served from the application's domain so that its source can be safely blessed in the CSP.  I suppose this would necessitate making the worker source available as a separately distributed source file, and then providing a parameter in the constructor that can accept the URL where the source file is hosted.

### Reproduction

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**  Yes

1. Add reasonable CSP policy to server: https://github.com/auth0/auth0-spa-js/commit/9cb4d310239d52d1756be5afb782f167d547d01e
2. Apply `npm start`
3. Open http://localhost:3000 and confirm no unexpected errors in console.
4. Click "Use Refresh Tokens" toggle
5. Observe the following CSP violation and constructor errors are logged:
```
> Refused to create a worker from 'blob:http://localhost:3000/a74af990-51e2-49f1-b05f-9ed5fa600e0e' because it violates the following Content Security Policy directive: "script-src 'self' http://localhost:35729 https://cdn.jsdelivr.net 'sha256-J//UXYk+juFDMC3Sigv2AtNlcUYV4ePFk7I2Sa+nJac=' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
> [Vue warn]: Error in callback for watcher "useRefreshTokens": "SecurityError: Failed to construct 'Worker': Access to the script at 'blob:http://localhost:3000/a74af990-51e2-49f1-b05f-9ed5fa600e0e' is denied by the document's Content Security Policy."
> DOMException: Failed to construct 'Worker': Access to the script at 'blob:http://localhost:3000/a74af990-51e2-49f1-b05f-9ed5fa600e0e' is denied by the document's Content Security Policy.
    at new WorkerFactory (http://localhost:3000/auth0-spa-js.development.js:5540:20)
    at new Auth0Client (http://localhost:3000/auth0-spa-js.development.js:6111:31)
    at Vue.initializeClient (http://localhost:3000/:549:21)
    at Vue.useRefreshTokens (http://localhost:3000/:471:18)
    at invokeWithErrorHandling (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:1872:28)
    at Watcher.run (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:4583:11)
    at flushSchedulerQueue (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:4327:15)
    at Array.<anonymous> (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:1998:14)
    at flushCallbacks (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:1924:16)
```

### Environment

- **Version of `auth0-spa-js` used:** 1.22.0
- **Which browsers have you tested in?**  Chrome 101.0.4951.64 on macOS 12.3.1
- **Which framework are you using, if applicable (Angular, React, etc):** Ember.JS
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by robbytx** [comment]
Thanks, yes, I'm using my own `cache` storage, which leverages `sessionStorage` to encapsulate the tokens a bit better than the `localStorage` option, and even give our users the ability to maintain separate logins in individual tabs.

I understand the concern about making the SDK too complex to use out of the box, but users leveraging CSP clearly care about security and so providing a slightly more complex option to leverage the worker code maintained in the SDK would be valuable.  The only alternatives are for us to write our own worker (no small feat itself) or utilize browser storage, which is explcitly discouraged in this SDK's README:
> **Important:** This feature will allow the caching of data **such as ID and access tokens** to be stored in local storage. Exercising this option changes the security characteristics of your application and **should not be used lightly**. Extra care should be taken to mitigate against XSS attacks and minimize the risk of tokens being stolen from local storage.

FWIW implementing CSP securely on the site is likely to sufficient "extra care" "to mitigate against XSS attacks", so I believe the latter option is reasonably secure.  Still, being able to utilize the pre-built worker to maintain tokens in memory would further improve the security posture, by hiding tokens from malicious browser extensions or other code on the computer that is able to read browser storage.

I'm thinking that a simple solution could be to include an additional "bundle" in the Rollup config that compiles [token.worker.ts](https://github.com/auth0/auth0-spa-js/blob/master/src/worker/token.worker.ts) to its own output file, which SDK consumers could host on their server, and provide the URL to in the Auth0Client constructor options.

**Comment by adamjmcgrath** [comment]
> Thanks, yes, I'm using my own cache storage, which leverages sessionStorage to encapsulate the tokens a bit better than the localStorage option, and even give our users the ability to maintain separate logins in individual tabs.

If you're using your own cache, the SDK wont create a Web Worker, so you shouldn't get that CSP issue

> The only alternatives are for us to write our own worker (no small feat itself) or utilize browser storage, which is explcitly discouraged in this SDK's README:

The alternative if you don't want to use browser storage is to create your own in memory storage which I've suggested here https://github.com/auth0/auth0-spa-js/issues/915#issuecomment-1148928670

**Comment by stevehobbsdev** [comment]
Closing as this looks to have been answered. Of course, we're happy to continue the discussion if we can help further.

**Comment by azjgard** [comment]
We ran into this same issue, and solved it by implementing a custom in-memory cache as specified. However, implicit in this solution is accepting the loss of the benefits furnished by fetching tokens via worker.

As @robbytx has already stated, it would be great if there was an option for us to take advantage of the built-in worker support using the built-in memory cache without having to nuke our CSP.
