### ISSUE TITLE
buildAuthorizeUrl miss ?

### ISSUE THREAD

**Issue by nseb** [auth0/auth0-spa-js#922]
Hello , I use buildAuthorizeUrl , with redirect_uri defined. I just saw that the ? had disappeared, and this poses a problem in hybrid mode with Apple, because it refuses the deeplink.
Before it worked

**Comment by stevehobbsdev** [comment]
@nseb If you can provide a small repro app I'd be happy to take a long. Or at least share some code here on the issue?

Nothing has changed recently regarding `buildAuthorizeUrl`, if you're able to pinpoint a version of the SDK where it stopped working, I can look into it.
