### ISSUE TITLE
`RedirectLoginOptions` has no default

### ISSUE THREAD

**Issue by danillouz** [auth0/auth0-spa-js#93]
Hi there,

I've experimenting with the new library and it looks like the default value of `{ }` is not set for the `RedirectLoginOptions` in the `loginWithRedirect` method.

When I call the method like this:
```js
client.loginWithRedirect();
```

I get the error:
```
TypeError: r is undefined
```

But if I call it with an empty Object, everything works fine:
```js
client.loginWithRedirect({});
```

I'm not familiar with TypeScript, but when I look at the code, a default value is set:
https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L194

However, when I check the compiled file `auth0-spa-js.production.js:834`, it's missing:
```js
loginWithRedirect(r) { // no default value is set
  return t(this, void 0, void 0, function* () {
    const t = r.redirect_uri,
          o = r.appState,
          n = e(r, ["redirect_uri", "appState"]),
          i = A(k()),
          a = k(),
          s = k(),
          c = yield N(s),
          l = F(c),
          d = this._getParams(n, i, a, l, t),
          u = this._authorizeUrl(d);

    this.transactionManager.create(i, {
      nonce: a,
      code_verifier: s,
      appState: o,
      scope: d.scope,
      audience: d.audience || "default"
    }), window.location.assign(u);
  });
}
```

Any idea why this is happening? I'm happy to send a PR with a fix if needed.

On a side note, the link to the _Auth0's contribution guidelines_ in `CONTRIBUTING.md` seems to be broken. It links to `GENERAL-CONTRIBUTING.md`, but it looks like that file is not present in this repo:
https://github.com/auth0/auth0-spa-js/blob/master/GENERAL-CONTRIBUTING.md

**Comment by luisrudge** [comment]
@danillouz what version are you using? The default param was added in 1.1.0 and I can see it in the bundled file: 
![image](https://user-images.githubusercontent.com/941075/61463500-e10e5e00-a94a-11e9-8d04-8e3ac12e1ba6.png)

**Comment by danillouz** [comment]
@luisrudge I was using `1.0.2`, just tested with `1.1.0` and it works as expected.
My mistake, I should have checked the release logs more carefully.
Thanks for your help.
