### ISSUE TITLE
Issue with loginWithRedirect google social login connection

### ISSUE THREAD

**Issue by omrisavra** [auth0/auth0-spa-js#936]
### Describe the problem

This is a bug report or a question I have. 
I am trying to implement a button outside of my auth0-supported application, using this lib.

Using this button I want to redirect the users to google social login and skip my auth0 universal login, then redirect them to my application.

When running this code, it doesn't redirect them to the google-oauth2 it just bring them to my auth0 universal login.

I expected when running this code users will go straight ahead to the google login and skip the auth0 universal login 

I run this code and expected that the connection variable will work as I read and don't know if connection works like this

The main function:
`
function redirectLogin() {
let auth0Client = new Auth0Client({
domain: "<app-domain>",
client_id:  "<my-client-id>",
redirect_uri: "<redirect_uri>"
});
auth0Client.loginWithRedirect({connection: "google-oauth2"});
}
`

`
The index.html code:
<html>
  <body>
    <script src="https://cdn.auth0.com/js/auth0-spa-js/1.22/auth0-spa-js.production.js"></script>
    <script type="module">
      function redirectLogin() {
        let auth0Client = new Auth0Client({
          domain: "<app-domain>",
          client_id:
            "<my-client-id>",
            redirect_uri: "<redirect_uri>"
        });
        auth0Client.loginWithRedirect({connection: "google-oauth2"});
      }
      document
        .getElementById("signInBtn")
        .addEventListener("click", redirectLogin);
    </script>
    <button id="signInBtn">sign in to google</button>
  </body>
</html>
`
I open this code in chrome and expected it to work.

**Comment by stevehobbsdev** [comment]
👋🏻 Using what you describe works for me:

```
auth0Client.loginWithRedirect({ connection: 'google-oauth2' });
```

I get directed straight to the Google sign-in page as long as my Google connection is enabled on my Auth0 client:

https://user-images.githubusercontent.com/766403/183122470-06a798ce-0a1d-4d96-8553-7667a86283d0.mov

Are you using your own Google account keys, or Auth0's developer keys? I'm not sure what happens when you're using the Auth0-provided keys, as the intention is that you replace those with your own.

**Comment by frederikprijck** [comment]
Closing this, if this would still be an issue we can always reopen.
