### ISSUE TITLE
Deploying to http environment causes error on `loginWithRedirect`

### ISSUE THREAD

**Issue by PaulInglis** [auth0/auth0-spa-js#96]
We have an environment deployed on Azure which is used for test automation.  Currently, as it is limited by ip address, we don't have https set up on this environment.

When we do a build of our code with this library incorporated, I get and error when I hit the login button, which is in turn calling `loginWithRedirect`.  We use a slightly modified version of the [Auth0 React wrapper](https://auth0.com/docs/quickstart/spa/react/01-login#install-the-auth0-react-wrapper) from the examples, but is verbatim of the example for the `loginWithRedirect` function.

The error I get (which could be clearer or mitigated against possibly) is: 
```
Uncaught (in promise) TypeError: Cannot read property 'digest' of undefined
    at q (auth0-spa-js.production.js:570)
    at t.<anonymous> (auth0-spa-js.production.js:1052)
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.e.<computed> [as next] (runtime.js:98)
    at auth0-spa-js.production.js:66
    at new Promise (<anonymous>)
    at n (auth0-spa-js.production.js:43)
    at t.value (auth0-spa-js.production.js:1037)
    at loginWithRedirect (Auth.tsx:151)
```

which points to line 570 of auth0-spa-js.production.js, which on mine reads:
```
569      N = function N(e) {
570    return window.crypto.subtle.digest({
571      name: "SHA-256"
572    }, new TextEncoder().encode(e));
```

If this library is not intended to be ran in http in a prod environment, then I think that needs to be made clear.  If it should "cope", then some checking and handling needs to be done here too.

**Comment by stevehobbsdev** [comment]
Hi @PaulInglis,

Running in non-secure environment is not supported by the library as it relies on the native Crypto APIs being available in the browser. 

This is covered in [the FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md)

**Comment by PaulInglis** [comment]
Thanks Steve, however I do not see that FAQ which you refer to in that link.

**Comment by stevehobbsdev** [comment]
@PaulInglis No I know, I raised that comment in error, apologies for that.

To answer your question, yes the SDK must be run on a secure origin as it relies on the crypto APIs being available in the browser to function.

We fully intend to handle this better and surface better messaging from the library when the scenario you've encountered occurs, and it's in our internal backlog to fix.

**Comment by davidgeary** [comment]
@stevehobbsdev It may also be worth noting that while `localhost` is considered a secure origin, locally-defined domains (i.e. entries added to your local `hosts` file) are not.

So if, for example, you're testing a multi-tenanted app by adding dummy client-specific subdomains to your `hosts` file - _alice.my-app.local_, _bob.my-app.local_ and so on - you'll need to run under HTTPS, even if they just point to 127.0.0.1.
