### ISSUE TITLE
`core-js` is a deprecated dependency

### ISSUE THREAD

**Issue by EvHaus** [auth0/auth0-spa-js#961]
### Describe the problem

When installing `@auth0/auth0-spa-js` via `npm`, there's a warning shown:

```
core-js@npm:3.22.8 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
```

This is happening because `core-js` is a dependency of `@auth0/auth0-spa-js`. Is there any way to remove this dependency from `@auth0/auth0-spa-js`? Not only is it deprecated, but it's also a very large dependency at over 200kb.

At a minimum, it would be good to version it up to 3.23.3+ to remove the warning.

### What was the expected behavior?

No deprecation warning after installing the library.

### Reproduction

1. `npm install @auth0/auth0-spa-js` inside any node project

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

Yes

### Environment

- **Version of `auth0-spa-js` used:** 1.22.0
- **Which browsers have you tested in?** N/A
- **Which framework are you using, if applicable (Angular, React, etc):** N/A
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by frederikprijck** [comment]
Thanks, We already dropped core-js in https://github.com/auth0/auth0-spa-js/pull/951, which will be released in our next major version.
