### ISSUE TITLE
Is it possible to mock window.crypto in unit tests?

### ISSUE THREAD

**Issue by mraible** [auth0/auth0-spa-js#963]
### Describe the problem

I'm trying to create a quick example that uses Auth0 React and includes unit tests to verify everything works. 

I get an error when running unit tests:

```
  ● renders learn react link

    For security reasons, `window.crypto` is required to run `auth0-spa-js`.
```

### What was the expected behavior?

`npm test` passes.

### Reproduction

```
git clone https://github.com/mraible/auth0-react-example.git
cd auth0-react-example
npm i
npm test
```

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

Not that I know of.

### Environment

- **Version of `auth0-spa-js` used:** 1.22.2
- **Which browsers have you tested in?** jsdom
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
You can mock crypto as follows:

```
global.crypto = {
  subtle: {
    digest: () => ''
  }
};
```

Doing so makes your test succeed:
![image](https://user-images.githubusercontent.com/2146903/186089775-ff0c5d33-5b84-4683-ae51-c9a898ac00cc.png)

Closing, but feel free to let me know if that doesn't help.

**Comment by mraible** [comment]
That worked. Thank you!
