### ISSUE TITLE
isAuthenticated, getUser and getIdTokenClaims does not check cookie 

### ISSUE THREAD

**Issue by missing1984** [auth0/auth0-spa-js#968]
### Describe the problem

When `isAuthenticated ` cookie is removed `isAuthenticated` and `getUser` api can still return value if local cache is still valid. 

This may happen when managing login status  across multiple subdomains using `cookieDomain` option -- user may log out and have `isAuthenticated` cookie clear from one subdomain such as `account.foo.com`.  When this happen we need to make sure `app.foo.com` is logout as well.

### What was the expected behavior?

When cookie is removed, isAuthenticated and getUser should return negative result regardless cache status.

```ts
  public async getUser<TUser extends User>(
    options: GetUserOptions = {}
  ): Promise<TUser | undefined> {
    // return undefined if authenticated cookie does not exists
    if (!this.cookieStorage.get(this.isAuthenticatedCookieName)) {
      return;
    }
    const audience = options.audience || this.options.audience || 'default';
    const scope = getUniqueScopes(this.defaultScope, this.scope, options.scope);

    const cache = await this.cacheManager.get(
      new CacheKey({
        client_id: this.options.client_id,
        audience,
        scope
      })
    );

    return cache && cache.decodedToken && (cache.decodedToken.user as TUser);
  }
```
### Reproduction

1. Login with localStorage cache.
2. delete authenticated cookie and refresh the page.
3. user still login -- while i expected user be log out.

**Can the behavior be reproduced using the [SPA SDK Playground](https://github.com/auth0/auth0-spa-js/blob/master/DEVELOPMENT.md#the-sdk-playground)?**

### Environment

- **Version of `auth0-spa-js` used:**
- latest
- **Which browsers have you tested in?**
- chrome, safari
- **Which framework are you using, if applicable (Angular, React, etc):**
- React
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Hello,

Thank you for raising this and sorry for the late reply.

The cookie you mention was introduced as a hint for our SDK to avoid doing unnecessary calls to Auth0 when loading the page and calling our SDK's `checkSession` method. The naming of that cookie is unfortunate, but it was never intended to be introduced to drive the internal state of the SDK, if you are using local storage and have data in the local storage, it will be used regardless of the existence of the cookie.

This brings up the question as to why you are using local storage? Would you be using refresh tokens? From the information you provided, I would assume you are not using refresh tokens. 

Before continuing, I want to add that refresh tokens provide a way to enable **offline access**, which basically tells Auth0 that your user can keep using the tokens, even if there is no more session with Auth0 (so offline compared to the IDP). Imagine having a session duration of 60 minutes on Auth0, but you use Refresh Tokens, you might be able to use your application for hours, days, even weeks without ever having an active session with Auth0 again.

If you aren't using refresh tokens, you most likely want the Auth0 session to drive the Application session, meaning that if the user is logged out from Auth0, they should be logged out from your application.

With the above, refreshing the page would log the user out if there is no active session with Auth0. **Unless** you use local storage, if you do you are basically extending the duration of the Auth0 session by keeping an access token around which can still be usable even if the session with Auth0 does not exist anymore. 

To avoid this, you can avoid using local storage and rely on calling `checkSession` on page load.




- Frontchannel logout: The IDP would call your applications in an iframe and allows you to clear the cookies, but Auth0 does not support this.
- Online access:

**Comment by frederikprijck** [comment]
Closing this, as I believe there isn't much our SDK. Happy to continue the conversation, and can always reopen if needed.
