### ISSUE TITLE
Ability to configure client with customizable auth endpoints

### ISSUE THREAD

**Issue by ericofusco** [auth0/auth0-spa-js#976]
### Describe the problem you'd like to have solved

Use auth0-spa-js with other identity providers like Okta but because paths are hard-coded in the library it's not possible

### Describe the ideal solution

I'm not sure if that would be all, but the identity providers like Auth0 and Okta follow the oauth2 standards, but there is no standardization for the URIs. (Examples: Auth0 with `/authorize` and `/oauth/token` and Okta with `/oauth2/v1/authorize` and `/oauth2/v1/token`

If we could do something like this (I'm using through auth0-react).

```
<Auth0Provider
  domain={'test.myprovider.com'}
  clientId={'client_id'}
  redirectUri={'http://localhost:3000'}
  authorizeUrl={'/oauth2/v1/authorize'},
  tokenUrl={'/oauth2/v1/token'}>
  <Component {...pageProps} />
</Auth0Provider>
 ```

## Alternatives and current work-arounds

- Fork auth0-spa-js and customize to work with multiple identity providers.
- Use okta library but I couldn't find a good way to do client-side auth for nextjs apps, auth0-react and auth0-spa-js are simpler and easier to use and it doesn't use local storage as default.

**Comment by frederikprijck** [comment]
Thanks for opening this request, our SDK is tailored specifically for Auth0 and we do not provide support for other providers.
Even though some parts might work, others may not work as expected.

> but the identity providers like Auth0 and Okta follow the oauth2 standards

There are things specific to Auth0 inside our SDK that are not OAuth2 standards (e.g. first-class support for certain custom properties an IDP can accept, which are specific to Auth0).

Even though supporting multiple IDP's would be a nice thing for our SDK, it's currently not the case and, therefore, we have no intention to make these endpoints configurable.

**Comment by johnnymetz** [comment]
I also need this ability. Would be great if to implement because seems like a lot of ppl use this library for other providers.
