### ISSUE TITLE
Sometime got `request error` with custom domain (don't know related to custom domain maybe...)

### ISSUE THREAD

**Issue by kntmrkm** [auth0/auth0-spa-js#983]
### Describe the problem

- Sometimes we can log in.
- But, Sometimes got `request error` see below attached image.

![CleanShot 2022-09-13 at 21 58 23@2x](https://user-images.githubusercontent.com/2703486/189907290-ac707703-03d8-4f20-88a1-5e4e7f6d8142.png)

### What was the expected behavior?

- Always authenticate correctly.

### Reproduction

- Nothing. Depend on our env. maybe.

### Environment

- auth0-spa-js v1.13.6
- auth0-react 1.3.0
- auth0-js 9.14.2

thanks.

**Comment by kntmrkm** [comment]
Sentry shows a Timeout error.

```
../node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js in call at line 2677:15

  name: "auth0-spa-js",
  version: "1.13.6"
},
    wr = function (e) {
  function n(t, i) {
    var r = e.call(this, i) || this;
    return r.error = t, r.error_description = i, Object.setPrototypeOf(r, n.prototype), r;
  }
  return t(n, e), n.fromPayload = function (e) {
    return new n(e.error, e.error_description);
```

![CleanShot 2022-09-13 at 22 02 16@2x](https://user-images.githubusercontent.com/2703486/189908101-a0aee7db-3d49-454e-b390-ca508caf88d9.png)

**Comment by kntmrkm** [comment]
Auth0 setting is ok

![CleanShot 2022-09-13 at 22 04 25@2x](https://user-images.githubusercontent.com/2703486/189908649-98d1323f-d7b6-47a8-875a-885782329f7c.png)

**Comment by stevehobbsdev** [comment]
@kntmrkm I'm not sure that this is an SDK error, it's just surfacing what you're getting from the server.

Can you inspect [your tenant logs](https://manage.auth0.com/#/logs) in your dashboard when you get an error and see if there's anything in there that tells you anything?

**Comment by kntmrkm** [comment]
Thanks. @stevehobbsdev 

I realized that I should contact Auth0 support and I will close it.
My apologies.
