### ISSUE TITLE
Custom token endpoint

### ISSUE THREAD

**Issue by Djay77** [auth0/auth0-spa-js#995]
### Describe the problem you'd like to have solved

It's impossible to override the token endpoint. It is hardcoded with '/oauth/token` ?

### Describe the ideal solution

Accept some parameters to specify custom base url (global or specific for token endpoint)

## Alternatives and current work-arounds

No work-arronds seem possible

**Comment by frederikprijck** [comment]
This SDK is intended to be used with Auth0, not with any other Identity Provider. Therefore these URLs are not configurable.

Apart from the URLs, there are more things internally to the SDK that are specifically for Auth0 that might not work as expected when used with any other Identity Provider.
