### ISSUE TITLE
When following the SPA example using LoginWIthRedirect does not properly login the user while LoginWithPopup does

### ISSUE THREAD

**Issue by mhamrah** [auth0/auth0-spa-js#996]
### Describe the problem

I'm creating a new SPA app with Svelte (just a vanilla SPA) following the instructions here: https://auth0.com/docs/libraries/auth0-single-page-app-sdk#login-and-get-user-info

The example provided, when clicking an html button to call `loginWithRedirect() `does not properly initialize the login state whereas changing this code to `loginWithPopup()` works fine. 

It seems the promise for `loginWithRedirect()` resolves immediately and then redirects, so that when the code ` const user = await auth0.getUser();` gets called you get back an undefined result. When the redirect returns to the app, and a subsequent call to getUser or isAuthenticated is made, it does not return true or have a valid user object so you must login again. However, when using loginWithPopup(), you can successfully return to the app, logged in, with no other changes. 

### What was the expected behavior?

I expect loginWithRedirect and loginWithPopup to be used interchangeably, but this does not appear to be the case.  I am also setting     `cacheLocation: "localstorage"` so true thinking that this is a state management problem

### Reproduction

Create an SPA, paste the code in, login using loginWithRedirect, then login with loginWithPopup. This repo has the svelte code: https://github.com/mhamrah/hamrah.com/blob/main/src/components/Login.svelte#L22 and you can replace this line with the redirect to mimic.

### Environment

- **Version of `auth0-spa-js` used:**
- **Which browsers have you tested in?**
- **Which framework are you using, if applicable (Angular, React, etc):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Hello,

Looking at the project, it looks like you are not calling `handleRedirectCallback`. It's important to know that, using `loginWithRedirect` requires a two-step process:

- Call `loginWithRedirect`, it will bring you to Auth0 and end up back in your app, including a `code` and `state` (or `error`) query parameter.
- Call `handleRedirectCallback` when the page loads AND it has the above mentioned queryparams.

For more info see: https://auth0.com/docs/quickstart/spa/vanillajs/#log-in-to-the-application
